MariaDB/server

libmysqld/CMakeLists.txt, mysql-test/suite/perfschema/r/pfs_functions.result, mysql-test/suite/perfschema/t/pfs_functions.test, sql/CMakeLists.txt, sql/item.h, sql/item_create.cc, sql/item_pfsfunc.cc, sql/item_pfsfunc.h
This PR is for backporting `FORMAT_BYTES` and `FORMAT_PICO_TIME` from MySQL to MariaDB as needed in Jira Issue. 
The source of MySQL I backported from is [item_pfs_func.h](https://github.com/mysql/mysql-server/blob/8.0/sql/item_pfs_func.h) and [item_pfs_func.cc](https://github.com/mysql/mysql-server/blob/8.0/sql/item_pfs_func.cc)
There is still `pfs_thread_id` and `pfs_current_thread_id` needs to be backported, I have worked on them, but they need more work because some PSI functions (`get_thread_by_id` & `get_thread_internal_id`) are still not existing in MariaDB, so I will backport and push all of this as a separate PR so it's easy to review.
I have used used MySQL tests too, and it passed the tests successfully too.
=> [MDEV-19629] Backport FORMAT_PICO_TIME from MySQL to MariaDB

.gitlab-ci.yml, tests/code_quality/cppcheck_ignorelist.txt, tests/code_quality/flawfinder_ignorelist.json
Include cppcheck and FlawFinder for SAST scanning.
Both have ignorelists so only new regressions will 
trigger failures in GitLab CI.
The pipeline for these changes successfully complete and a [public pipeline](https://salsa.debian.org/robinnewhouse/mariadb-server-mirror/-/commits/11.0-gitlab-ci) is available.
BSD-new license. I am contributing on behalf of my employer
Amazon Web Services, Inc.
=> Add SAST scanning to Gitlab CI

mysql-test/main/func_str.result, mysql-test/main/func_str.test, sql/item_strfunc.cc
crash in `Item_func_left::val_str`
The test is appended to `func_str`
=> MDEV-30351 crash in Item_func_left::val_str

.gitignore
This reverts commit 158a58245813b1959d6ee912d77734620c7cf3ba.
In 10.11 the generation of mysql-log-rotate was removed in commit fd0dcad676e7b8665f5363d97849a20cbb712933
There's no need to ignore files that aren't generated.
By doing out of tree builds and not leaving build artefact littered in tree builds as some basis of what is generated.
- [ X ] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.
=> Revert "Added mysql-log-rotate to .gitignore"

mysys/my_addr_resolve.c
MariaDB server prints the stack information if a crash happens.
It traverses the stack frames in function `print_with_addr_resolve`.
For *EACH* frame, it tries to parse the file name and line number of the
frame using `addr2line`, or prints `backtrace_symbols_fd` if `addr2line`
fails.
1. Logic in `addr_resolve` function uses addr2line to get the file name
and line numbers. It has a timeout of 500ms to wait for the response
from addr2line. However, that's not enough on small instances
especially if the debug information is in a separate file or
compressed.
Increase the timeout to 5 seconds to support some edge cases, as
experiments showed addr2line may take 2-3 seconds on some frames.
2. While parsing a frame inside of a shared library using `addr2line`,
the file name and line numbers …
=> Handle meaningless addr2line results and increase timeout

client/mysqltest.cc, mysql-test/suite/innodb/r/innodb-wl5522.result, mysql-test/suite/innodb/t/import_tablespace_race.test, mysql-test/suite/innodb/t/innodb-wl5522.test, mysql-test/suite/innodb/t/restart.test
The tests innodb.import_tablespace_race, innodn.restart, and innodb.innodb-wl5522 move the tablespace file between the data directory and the tmp directory specified by global environment variables. The code looks like: `--move_file $tmpdir/file $datadir/file`
However this is risky because it's not unusual that the set tmp directory (often under /tmp) is mounted on another disk partition or device, and 'move_file' command may fail with "Errcode: 18 'Invalid cross-device link'".
A screenshot of the error:
> CURRENT_TEST: innodb.import_tablespace_race
> /local/.../client//mariadb-test: Error on rename of '/tmp/1TzsNV4ZrR/7/t.cfg' to '/local/.../mysql-test/var/7/mysqld.1/data//test/t.cfg' (Errcode: 18 "Invalid cross-device link")
> mysqltest: At line 50: command "move_file" failed with …
=> Make 'move_file' command more reliable in mysqltest

mysql-test/suite/encryption/r/innodb-bad-key-change.result, mysql-test/suite/encryption/t/innodb-bad-key-change.test
A suppression was needed for encryption.innodb-bad-key-change due to the path change.
fix on #2392
=> MDEV-30205: /usr/share/mysql-test -> mariadb-test (fix)

include/my_alloca.h
Two corrections for 1e58b8afc086da755cf9209ed17fc36351da5563.
* forward port from #2326
* AIX compile fix
Minor cleanup - remove always true HAVE_ALLOCA
AIX is in CI should hopefully compile now. Will also fix encryption based plugins that need an alloca.h include.
=> my alloca fixes

storage/rocksdb/build_rocksdb.cmake
The glibc headers declare fallocate only if _GNU_SOURCE is defined. Without this change, the probe fails with C compilers which do not support implicit function declarations even if the system does in fact support the fallocate function.
Upstream rocksdb does not need this because the probe is run with the C++ compiler, and current g++ versions define _GNU_SOURCE automatically.
Related to:
* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC
=> rocksdb: Define _GNU_SOURCE during fallocate CMake probe

mysql-test/mariadb-test-run.pl
As found by @LinuxJedi the use of globals here was subject to race conditions.
Replace previous fix by a solution that just tests if there are not tests and exit quickly.
Per original MDEV with `-DPLUGIN_MROONGA=NO`:
```
$ mysql-test/mtr --suite=mroonga
Logging: /home/dan/repos/mariadb-server-10.6/mysql-test/mariadb-test-run.pl  --suite=mroonga
VS config: 
vardir: /home/dan/repos/build-mariadb-server-10.6/mysql-test/var
Creating var directory '/home/dan/repos/build-mariadb-server-10.6/mysql-test/var'...
MariaDB Version 10.6.13-MariaDB
Using suites: mroonga
Collecting tests...
No tests to run...
```
For reference, 10.5 behaves as such:
```
$ mysql-test/mtr --suite=mroonga …
```
=> MDEV-30186 unintialized value where there are no test cases

storage/connect/reldef.cpp, storage/connect/tabbson.cpp, storage/connect/tabdos.cpp, storage/connect/tabext.cpp, storage/connect/tabfmt.cpp, storage/connect/tabjdbc.cpp, storage/connect/tabjson.cpp
This submission continues work started in 567b681 where `safe_strcat()` and `safe_strcpy()` functions were introduced.
The MariaDB code base uses `strcat()` and `strcpy()` in several places. These are known to have memory safety issues and their usage is discouraged. Common security scanners like Flawfinder flags them. In MariaDB we should start using modern and safer variants on these functions.
We changed old unsafe functions with the new safe ones and also use `snprintf()` in the places where series of `strcpy()/strcat()` were used – this also make code safe and fix more clear.
We would like to provide 2-3 smaller size changes to make code review and
merge easier. Next part will follow.
All build stages pass for these commits.
The changes are fully backward compatible.
All new code of …
=> Minimize unsafe C functions usage - replace str…() and strn…() functions with custom safe_strcat() and safe_strcpy() functions - part 2

storage/connect/catalog.h, storage/connect/ha_connect.cc, storage/connect/tabext.cpp, storage/connect/value.cpp, storage/connect/value.h
fp->field_length was unsigned and therefore the negative condition around it.
Backport of cc182aca9352 fixes it, however to correct the consistent use of types pcf->Length needs to be unsigned too.
At one point pcf->Precision is assigned from pcf->Length so that's also unsigned.
GetTypeSize is assigned to length and has a length argument. A -1 default value seemed dangerious to case, so at least 0 should assert if every hit.
Existing test suite. Look at warnings generated.
Hoping the -1 -> 0 change in GetType doesn't cascade to a meaningful change.
- [ X ] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/11.0/CODING_STANDARDS.md) file and my …
=> MDEV-30713 field length handling for CONNECT engine

mysql-test/suite/rpl/r/rpl_xa_prepare_gtid_fail.result, mysql-test/suite/rpl/t/rpl_xa_prepare_gtid_fail.test, sql/handler.cc, sql/log_event.h, sql/log_event_server.cc
If a replica failed to update the GTID slave state when committing
an XA PREPARE, the replica would retry the transaction and get an
out-of-order GTID error. This is because the commit phase of an XA
PREPARE is bifurcated. That is, first, the prepare is handled by the
relevant storage engines. Then second, the GTID slave state is
updated as a separate autocommit transaction. If the second phase
fails, and the transaction is retried, then the same transaction is
attempted to be committed again, resulting in a GTID out-of-order
error.
This patch fixes this error by immediately stopping the slave and
reporting the appropriate error. That is, there was logic to bypass
the error when updating the GTID slave state table if the underlying
error is allowed for retry on a parallel slave. This …
=> MDEV-31038: Parallel Replication Breaks if XA PREPARE Fails Updating Slave GTID State

mysql-test/main/events_embedded.test, mysql-test/main/events_skip_grant_tables-master.opt, mysql-test/main/events_skip_grant_tables.result, mysql-test/main/events_skip_grant_tables.test, mysql-test/main/mysql_upgrade-6984.result, mysql-test/main/mysql_upgrade-6984.test, mysql-test/main/skip_grants.result, mysql-test/main/skip_grants.test, sql/events.cc, sql/share/errmsg-utf8.txt
When the server is started with `--event-scheduler=ON` and with `--skip-grant-tables`, the event scheduler *appears* to be enabled (`SELECT @@global.event_scheduler` returns `'ON'`), but attempting to manipulate it in any way returns a misleading error message:
"Cannot proceed, because event scheduler is disabled"
Possible solutions:
1. Fast-fail: fail immediately on startup if `EVENT_SCHEDULER` is set to
any value other than `DISABLED` when starting up without grant
tables, then prevent `SET GLOBAL event_scheduler` while running.
Problem: there are existing setup scripts and code which start with
this combination and assume it will not fail.
2. Warn and change value: if `EVENT_SCHEDULER` is set to any value
other than `DISABLED` when starting, print a warning and change it
immediately to …
=> [MDEV-29827] Clear and specific error when --event-scheduler=ON is combined with skip-grant-tables

mysql-test/main/func_sformat.result, mysql-test/main/func_sformat.test, sql/item_strfunc.cc
The problem is that sformat does not assign the enough space for the result string. The result string is allocated with the max_length of argument, but the correst max_length should be based on the format string.
The patch fixes the problem by calculating the max_length of the result string based on the format string.
=> MDEV-29646: sformat('Num [{:20}]', 42) gives incorrect result in view

debian/mariadb-common.postinst, debian/mariadb-common.postrm, debian/mariadb-server-10.6.postinst, debian/mariadb-server-10.6.postrm, debian/mariadb-server-10.6.preinst, debian/mariadb-server-10.6.prerm
Debian pre- and postinst script have been getting slightly out of `ShellCheck` and they are not indented correctly or same way always. These commits fix most of the issues.  
Run `ShellCheck debian/*.pre* debian/*.post*` and check if there is indentation which seems not to be correct.
Should not be affected
=> MDEV-30952: Fix and correctly indent Debian scripts

debian/mariadb-server-10.6.postinst
Command lsof can fail on Debian install. Revert logic more like old one to make sure that there is no failing and still does don't boundce on shellcheck.
Salsa-CI run before indent and this patch: https://salsa.debian.org/illuusio/mariadb-server/-/pipelines/526135
Salsa-CI with indent merge and this fix: https://salsa.debian.org/illuusio/mariadb-server/-/pipelines/526215
Build package and try to install package mariadb-server and please check BB builds and Salsa-CI run.
This fix makes sure Backward compatibility is ensured
=> MDEV-31216: Make sure that lsof does not fail on install

support-files/rpm/server.cnf
Update rpm file server.cnf to bump major version to 10.11 group.
For example, adding some options for enabling SSL (ssl_key, ssl_cert, ssl_ca, ssl_cipher)
=> server.cnf: adjust major version to 10.11

debian/additions/innotop/innotop
- Add Modern Perl headers. Perl 5.16 is still fairly old from 2012.
- Enable UTF-8, warnings and make script 'strict'
- Small fixes for perlcritic reported problems and some crashes
```
I/O layer ":utf8" used at line 268, column 16.  Use ":encoding(UTF-8)" to get strict validation.  (Severity: 5)
"return" statement with explicit "undef" at line 806, column 4.  See page 199 of PBP.  (Severity: 5)
"return" statement with explicit "undef" at line 6844, column 4.  See page 199 of PBP.  (Severity: 5)
"return" statement with explicit "undef" at line 7524, column 4.  See page 199 of PBP.  (Severity: 5)
"return" statement with explicit "undef" at line 7527, column 4.  See page 199 of PBP.  (Severity: 5)
"return" statement with explicit "undef" at line 7599, column 4.  See page 199 of PBP. …
```
=> MDEV-30951: Fix small perlcritic and enable modern Perl

storage/connect/bson.cpp, storage/connect/bsonudf.cpp, storage/connect/cmgoconn.cpp, storage/connect/filamgz.cpp, storage/connect/filamtxt.cpp, storage/connect/filamvct.cpp, storage/connect/filamzip.cpp, storage/connect/filter.cpp, storage/connect/fmdlex.c, storage/connect/ha_connect.cc, storage/connect/javaconn.cpp, storage/connect/jdbconn.cpp, storage/connect/jmgoconn.cpp, storage/connect/json.cpp, storage/connect/jsonudf.cpp, storage/connect/macutil.cpp, storage/connect/odbconn.cpp, storage/connect/osutil.c, storage/connect/plgdbutl.cpp, storage/connect/plugutil.cpp, storage/connect/tabjmg.cpp, storage/connect/tabmysql.cpp, storage/connect/tabpivot.cpp, storage/connect/tabsys.cpp, storage/connect/tabwmi.cpp, storage/connect/tabxml.cpp, storage/connect/value.cpp, storage/connect/xindex.cpp
Old style C functions `strcpy()`, `strcat()` and `sprintf()` are vulnerable to
security issues due to lacking memory boundary checks. Replace these in the
Connect storage engine with safe new and/or custom functions such as
`snprintf()` `safe_strcpy()` and `safe_strcat()`.
With this change FlawFinder and other static security analyzers report 287 fewer
findings.
The FlawFinder log before changes:
```
$ cat flawfinder-all-vulnerabilities.html | grep "Hits ="
Hits = 14955
```
After the changes:
```
$ cat flawfinder-all-vulnerabilities.html | grep "Hits ="
Hits = 14668
```
Additionally all CI passes for this change.
The changes are fully backward compatible.
=> Fix insecure use of strcpy, strcat and sprintf in Connect

.github/CODEOWNERS
The CODEOWNERS was added almost 3 years ago but never saw any adoption. Only one person used it (me) to mark what files I maintain and for which I wish to review commits. No other maintainers or code paths were added, so clean it away for clarity.
=> Remove CODEOWNERS as obsolete

.gitlab-ci.yml
Add .gitlab-ci.yml file to earliest supported branch to enable
automated building and testing for all MariaDB major branches.
Note to mergers:
GitLab CI is available for branches >= 10.6. This commit includes a
GitLab CI file identical to that in branches >= 10.6, except for the
MARIADB_MAJOR_VERSION variable which should reflect the branch version.
A modified CI will be included in branches 10.4 with PR !2418.
Also changed is the `allow_failure: true` for the MSAN build,
which should be merged up to later branches.
The pipeline for these changes successfully completes and a [public pipeline](https://salsa.debian.org/robinnewhouse/mariadb-server-mirror/-/commits/10.5-backport-CI) is available.
that are either new files …
=> Backport GitLab CI to 10.5

debian/mariadb-server-10.6.preinst
There is unwanted cut'n'paste variable name in Debian pre-inst script which causes:
df: '': No such file or directory
/var/lib/dpkg/tmp.ci/preinst: line 215: [: : integer expression expected
Rename variable to correct one and make check that that directory or symlink really exists. If it does not then fail with error and message.
This is little bit bumpy to test one needs Debian 11 (container or real) and configure it with this one: https://mariadb.org/download/?t=repo-config&d=Debian+11+%22Bullseye%22&v=10.6&r_m=xtom_tal
after that one downloads: https://salsa.debian.org/illuusio/mariadb-server/-/jobs/4260007/artifacts/browse/debian/output/
and installs them over the installed MariaDB 10.6.13 images with
```
w3m  https://salsa.debian.org/illuusio/mariadb-server/-/jobs/4260007/artifacts/do …
```
=> MDEV-31331: Fix cut'n'paste variable name in Debian pre-inst script

README.md, SECURITY.md
Please look at the Jira ticket: https://jira.mariadb.org/browse/MDEV-31364
This PR only carries changes on documentation.
=> MDEV-31364: Adding a Github Security Policy file

cmake/aws_sdk.cmake
Typo: complatible > compatible
Proposed fix (fixed typo, improved grammar):
Seen during 11.0 build:
```
-- Can't build aws_key_management - AWS SDK not available (AWS SDK has Apache 2.0 License which is not complatible with 
GPLv2. Set -DNOT_FOR_DISTRIBUTION=ON if you need it)
```
Code location:
```
SKIP_AWS_SDK("AWS SDK has Apache 2.0 License which is not complatible with GPLv2. Set -DNOT_FOR_DISTRIBUTION=ON if you need it")
```
file in the …
=> MDEV-31205 Typo: complatible > compatible

debian/mariadb-common.postinst, debian/mariadb-common.postrm, debian/mariadb-plugin-mroonga.postinst, debian/mariadb-plugin-mroonga.prerm, debian/mariadb-server.preinst, debian/mariadb-server.prerm
Make sure that every Debian post and prescript are using bash and have set -e in next to shebang. Commands set -e makes sure that if script fails in one command it will fail whole script.
As Salsa-CI on 11.2 in currently broken and this has to be tested by hand:
```
debian/autobake-debs.sh
dpkg -i ../*.deb
```
If everything goes well it should be ok as most of the people had sh either zsh or bash. Now we just want to use Bash as it makes testing easier.
=> MDEV-31242: Make sure every Debian post/pre script is using bash

mysql-test/suite/rpl/r/rpl_row_trigger_multi_db.result, mysql-test/suite/rpl/t/rpl_row_trigger_multi_db.test, sql/log_event.h, sql/log_event_server.cc
When opening and locking tables, if triggers will be invoked in a
separate database, thd->set_db() is invoked, thus frees the memory
and headers which thd->db had previously pointed to. In row based
replication, the event execution logic initializes thd->db to point
to the database which the event targets, which is owned by the
corresponding table share. The problem then, is that during the
table opening and locking process for a row event, memory which
belongs to the table share would be freed, which is not valid.
This patch replaces the thd->reset_db() calls to thd->set_db(),
which copies-by-value, rather than by reference. Then when the
memory is freed, our copy of memory is freed, rather than memory
which belongs to a table share.
Additionally, the function backup_current_db_name() …
=> MDEV-29894: Calling a function from a different database in a slave side trigger crashes

cmake/cpack_rpm.cmake
fix conflict
file /usr/lib64/libmariadb.so.3 from install of MariaDB-shared-10.11.3-1.fc38.x86_64 conflicts with file from package mariadb-connector-c-3.3.5-1.fc38.x86_64
- [ X ] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/11.0/CODING_STANDARDS.md) file and my PR …
=> MDEV-31268 Fedora MariaDB-shared replaces mariadb-connector-c

debian/mariadb-server-core.install, debian/po/sw.po, mysql-test/main/locale.result, mysql-test/main/locale.test, mysql-test/main/variables.result, mysql-test/main/variables.test, mysql-test/suite/plugins/r/locales.result, mysql-test/suite/sys_vars/r/lc_time_names_basic.result, mysql-test/suite/sys_vars/t/lc_time_names_basic.test, sql/share/CMakeLists.txt, sql/share/errmsg-utf8.txt, sql/sql_locale.cc
Kenyan Swahili is enabled for error messages as well as datetime.
The following MTR tests have been updated to test for Swahili and have all passed successfully:
- locale.test
- locales.test
- lc_time_names_basic.test
- variables.test
=> MDEV-31530 Localizations for Swahili language

.gitlab-ci.yml, tests/upgrade_from/test_upgrade.sh
Performs an upgrade of mariadb from an earlier version to the rpms built
in CI. Then checks whether log contains evidence of upgrade in the form
of "Needs upgrade" or "Table rebuild required". Designed to check minor
version upgrades which should not trigger rebuilds.
The test is written in bash script so it can be executed from other CI
systems.
```
$ test_upgrade.sh source_version target_version
$ test_upgrade.sh source_version # defaults to rpm/
$ test_upgrade.sh source_version --rpm-dir <directory>
```
Binaries must be created with performance schema enabled, or
mysql_upgrade complains about missing tables.
Upgrade testing is parallelized with a "matrix" of source versions.
Others can be introduced later.
This was partially designed to catch issues like that seen in …
=> Implement mysql_upgrade upgrade testing in CI

CODING_STANDARDS.md
Adds minor section about preprocessor indentation to coding standards.
Against 11.0 since that is where the first version of the coding standards document lives.
=> Add preprocessor whitespace to CODING_STANDARDS.md

sql/sql_parse.cc
The pointer was used deep in the call path.
Resolve this by setting the pointer to NULL at the end of the function.
Tested with gcc-13.3.1 (fc38)
The warning disable 38fe266ea953 can be reverted in 10.6+ on merge.
Compiler with gcc-13.3.1+ and run mtr.
- [ X ] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.
=> MDEV-31545 GCC 13 -Wdangling-pointer in execute_show_status()

sql/session_tracker.cc
Concatenation error leads to typo in the warning message
`set session_track_system_variables='foo';`
- [ X ] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.
=> MDEV-23133 session tracker - warning message typo

mysql-test/suite/rpl/r/rpl_parallel_sbm.result, mysql-test/suite/rpl/r/rpl_seconds_behind_master_spike.result, mysql-test/suite/rpl/t/rpl_delayed_parallel_slave_sbm-slave.opt, mysql-test/suite/rpl/t/rpl_parallel_sbm-slave.opt, mysql-test/suite/rpl/t/rpl_parallel_sbm.test, mysql-test/suite/rpl/t/rpl_seconds_behind_master_spike.test, sql/slave.cc
If the workers of a parallel replica are busy (potentially with long
queues), but the SQL thread has no events left to distribute (so it
goes idle), then the next event that comes from the primary will
update mi->last_master_timestamp with its timestamp, even if the
workers have not yet finished.
This patch changes the parallel replica logic which updates
last_master_timestamp after idling from using sql_thread_caught_up
(added in MDEV-29639) to using rli queued/dequeued event counters.
That is, if the queued count is equal to the dequeued count, it
means all events have been processed and the replica is idle.
Notes:
* MDEV-29639 changed when sql_thread_caught_up was updated so it
could be used to set last_master_timestamp. This patch additionally
reverts those changes.
* Renamed …
=> MDEV-30619: Parallel Slave SQL Thread Can Update Seconds_Behind_Master with Active Workers

scripts/CMakeLists.txt, scripts/galera_new_cluster.sh, support-files/CMakeLists.txt, support-files/mariadb.service.in
We used to run `systemctl set-environment` to pass
_WSREP_START_POSITION. This is bad because:
* it clutter systemd's environment (yes, pid 1)
* it requires root privileges
Let's just create an environment file in ExecStartPre=, that is read
before ExecStart= kicks in. We have _WSREP_START_POSITION around for the
main process without any downsides.
=> MDEV-19210: use environment file in systemd units for _WSREP_*

mysql-test/main/information_schema_temp_table.result, mysql-test/main/information_schema_temp_table.test, sql/sql_parse.cc, sql/sql_show.cc, storage/myisammrg/myrg_info.c
[x] *The Jira issue number for this PR is: MDEV-31618*
=> MDEV-31618: Server crashes in process_i_s_table_temporary_tables/get_all_tables

mysql-test/main/distinct.result, mysql-test/main/distinct.test, sql/filesort.cc, sql/sql_select.cc
…ndler_string_result::sort_length
After MDEV-21580 the truncation of SORT_FIELD::length
set_if_smaller(sortorder->length, thd->variables.max_sort_length)
became conditional:
if (is_variable_sized())
set_if_smaller(length, thd->variables.max_sort_length)
To provide correct functioning of is_variable_sized() SORT_FIELD::type must be set properly. This commit adds the necessary initialization of SORT_FIELD::type to JOIN_TAB::remove_duplicates() as it is done in filesort's sortlength() function.
DBUG_ASSERT is added to sortlength() just in case to prevent a possible uint32 overflow
Consult the documentation on ["Writing good test …
=> MDEV-31743 Server crash in store_length, assertion failure in Type_handler_string_result::sort_length

debian/autobake-deb.sh
Avoid autobake failing when it sees trixie as the codename.
Build on a trixie image.
=> deb autobake - add trixie

cmake/libfmt.cmake, sql/item_strfunc.cc
As described in [MDEV-31963](https://jira.mariadb.org/browse/MDEV-31963), MariaDB fails to build with libfmt 10.1.0 because `fmt::detail::make_arg` no longer accepts temporaries. (See also: https://github.com/fmtlib/fmt/issues/3596#issuecomment-1679244746.) This PR fixes the code snippet that checks the system libfmt, and also the `SFORMAT` code that makes use of libfmt.
I do not think addition or modification to test cases is necessary; [`func_sformat.test`](https://github.com/MariaDB/server/blob/11.3/mysql-test/main/func_sformat.test) should continue to pass.
To verify the fix, one could install libfmt 10.1.0 locally and build MariaDB 10.7 or later against that. I applied the changes to MariaDB 11.0.3 and 10.9.8 and can confirm that it fixes the build. For the examples in the [`SFORMAT` …
=> MDEV-31963 Fix libfmt usage

sql/mysqld.cc
Create test for for case insensitive gives a basic warning on creating a test file and the next thing a user might see is an abort.
ProtectHome and other systemd setting protect system services from accessing user data. Unfortunately some of our users do put things on /home due space or other reasons.
Rather than enumerate the systemd options in a very clunkly fragile way we put an error associated with the "Can't create test file" and hope the user can work it out from there.
As RO file systems can't be done in mtr.
ProtectHome in systemd is a read only mount so:
```
mkdir /tmp/d /tmp/e
sudo mount --bind /tmp/d /tmp/e -o ro
$ scripts/mariadb-install-db --no-defaults --srcdir=$OLDPWD --builddir=$PWD --datadir=/tmp/e --verbose  
Installing MariaDB/MySQL system tables in '/tmp/e' ... …
```
=> MDEV-25177 Better indication of refusing to start because of ProtectHome

tests/mysql_client_test.c
Port the test case from MySQL to MariaDB:
MySQL fix Bug#33813951, Change-Id: I2448e3f2f36925fe70d882ae5681a6234f0d5a98.
Function test_simple_temporal() from MySQL ported from C++ to pure C.
This includes one change:
-  DIE_UNLESS(field->type == MYSQL_TYPE_DATETIME);
+  DIE_UNLESS(field->type == MYSQL_TYPE_TIMESTAMP);
The bound param of SELECT ? is TIMESTAMP in this code. MySQL returns it back as DATETIME. MariaDB preserves TIMESTAMP.
If the changes are not amenable to automated testing, please explain why not and carefully describe …
=> MDEV-32130 Port MySQL test on protocol bug #106352 to MariaDB

storage/oqgraph/graphcore.cc, storage/oqgraph/oqgraph_judy.h, storage/oqgraph/oqgraph_shim.h
-Wdeprecated-copy-with-user-provided-copy was causing a few errors on things that where defined in a way that was implicit. By removing code it now compiles without warnings.
tested with fc38 / clang-16
=> oqgraph: remove clang warnings

mysql-test/main/ssl_cipher.result, mysql-test/main/ssl_cipher.test, mysql-test/main/tls_version.result, mysql-test/main/tls_version.test, mysql-test/main/tls_version1.result, mysql-test/main/tls_version1.test, sql/mysqld.cc, sql/sys_vars.cc
Remove TLSv1.1 from the default tls_version system variable.
Output a warning if TLSv1.0 or TLSv1.1 are selected.
Thanks Tingyao Nian for the feature request.
Covered by existing tests.
- [ X ] *This is a new feature and the PR is based against the latest MariaDB development branch.*
- [ X ] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.
=> MDEV-31369 Disable TLS v1.0 and 1.1 for MariaDB

client/mysqltest.cc, mysql-test/main/mysqltest-break.result, mysql-test/main/mysqltest-break.test
I've added `break` statement to `mysqltest.cc ` to improve flexibility of test framework.
=> MDEV-12130: Add break statement in mysqltest

mysql-test/suite/rpl/my.cnf
- `default_client` is included already in `rpl_1slave_base.cnf`, so remove it from `my.cnf`
- Remove option group for `mysqld` server as and add comment how to override specific settings for specific server
- Reviewer: <brandon.nesterenko@mariadb.com>
- Dependency graph (red component in the diagram is related to the PR):
=> Remove duplicated default client include from replication my.cnf

mysql-test/include/rpl_change_topology.inc, mysql-test/include/rpl_connect.inc, mysql-test/include/rpl_end.inc, mysql-test/include/rpl_for_each_slave.inc, mysql-test/include/rpl_init.inc, mysql-test/include/rpl_reconnect.inc, mysql-test/include/rpl_start_slaves.inc, mysql-test/include/wait_for_slave_io_to_start.inc, mysql-test/include/wait_for_slave_sql_to_start.inc, mysql-test/include/wait_for_slave_to_start.inc
* Make `rpl_check_server_ids` argument work again.
* Remove extra connections namely `server_[1,2,..]_1`, that were created during initalization in `rpl_init.inc`, recreated in `rpl_reconnect.inc` and removed in `rpl_end.inc`.
They are dead connections, not used anywhere in `rpl` suite.
* Cosmetic fixes
* Fix errors in `rpl_init.inc` regarding the comments
* sed 's/.cfg/.cnf/'
* Verifying server_id is not by default but with using `rpl_check_server_ids` parameter.
* Add comment why extra connections `server_[i,..,N]_1` are needed, since there is no usage of env variables `[MASTER,SLAVE]_PORT1` except in `rpl_show_slave_hosts.test`.
* Other cleanup
* More debug messages,
* Missing arguments
* Spaces.
* `rpl_init.inc` flow chart
=> MDEV-32004: Parse error in mtr tests when using rpl_check_server_ids

debian/mariadb-test.install, debian/not-installed
File is built, but was missing from packaging, so add it.
Test however fail currently. Filed as MDEV-22243.
Attempted to disable test until it is fixed, but test runs despite being listed in unstable-tests.
=> Deb: Include type_test.so in mariadb-test package

extra/mariabackup/xtrabackup.cc, mysql-test/suite/mariabackup/data_directory.result, mysql-test/suite/mariabackup/data_directory.test, storage/innobase/fil/fil0fil.cc, storage/innobase/include/log0log.h, storage/innobase/include/log0recv.h, storage/innobase/log/log0log.cc, storage/innobase/log/log0recv.cc
There are many filesystem related errors that can occur with MariaBackup. These already outputed to stderr with a good description of the error. Many of these are permission or resource (file descriptor) limits where the assertion and resulting core crash doesn't offer developers anything more than the log message. To the user, assertions and core crashes come across as poor error handling.
As such we return an error and handle this all the way up the stack.
mtr test included. Leaving tests versioned as 10.4 as #2281 merge up will be in the same spot(?).
=> MDEV-18200 MariaBackup full backup failed with InnoDB: Failing assertion: success (10.5)

scripts/mysql_install_db.sh
The problem shows up if you compile MariaDB without PAM.
The fix is trivial. Before doing chown, the script should check if directory exists.
Inside the file **./scripts/mysql_install_db.sh** 
change line 496 from
```shell
if test -z "$srcdir" -a "$in_rpm" -eq 0
```
to
```shell
if test -z "$srcdir" -a "$in_rpm" -eq 0 -a -d "$pamtooldir/auth_pam_tool_dir"
```
Affected Versions:
1. 10.4
2. 10.5
3. 10.6
4. 10.10
5. 10.11
6. 11.0
If the changes are not amenable to automated testing, please explain why not and carefully describe how to …
=> MDEV-32142 mariadb-install-db shows warning on missing directory $pamtooldir/auth_pam_tool_dir

debian/additions/mariadb.conf.d/50-server.cnf
utf8mb4_general_ci has been outdated for a while. Lets use our modern standard.
my_print_defaults --mysqld on install in debian
- [] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced.*
=> MDEV-32336 deb default config - use collation-server = utf8mb4_uca1400_ai_ci

mysql-test/suite/innodb/r/foreign_key.result, mysql-test/suite/innodb/t/foreign_key.test, sql/sql_table.cc
In MDEV-31086, SET FOREIGN_KEY_CHECKS=0 cannot bypass checks that make column types of foreign keys incompatible. An unfortunate consequence is that adding an AUTO_INCREMENT is considered incompatible in Field_{num,decimal}::is_equal and for the purpose of FK checks this isn't relevant.
The reason for the auto_increment check in is_equal seems to resolve mysql bug #14573 which still affects Aria and MyISAM storage engines but not InnoDB.
mtr test included.
- [*] *This is a feature addition for a limited set of functionality that was removed in a bug fix and hence cased a regression for @horrockss.
- [*] I checked the …
=> MDEV-32018 Allow the setting of Auto_increment on FK referenced columns

mysql-test/main/mysql_upgrade.result, mysql-test/main/mysql_upgrade.test, scripts/mysql_system_tables_fix.sql
Tested multiple major version upgrades with sql_safe_updates enabled, and confirmed the issue is resolved.
Some applications run with MariaDB `sql_safe_updates = on`, to ensure updates and deletes always reference keys.
When upgrading major versions however, having this value left in your my.cnf file can lead to a mariadb-upgrade failure with errors:
```
Phase 4/7: Running 'mysql_fix_privilege_tables'
--
ERROR 1175 (HY000) at line 316: You are using safe update mode and you tried to update a table without a WHERE that uses a KEY column
ERROR 1175 (HY000) at line 328: You are using safe update mode and you tried to update a table without a WHERE that uses a KEY column
ERROR 1175 (HY000) at line 340: You are using safe update mode and you tried to update a table without a WHERE that uses a …
```
=> MDEV-29914: Fix maridab-upgrade when sql_safe_updates = on is set in my.cnf

mysql-test/suite/rpl/r/rpl_parallel_sbm.result, mysql-test/suite/rpl/t/rpl_parallel_sbm.test, sql/slave.cc
MDEV-32265: seconds_behind_master is inaccurate for Delayed replication
If a replica is actively delaying a transaction when restarted (STOP
SLAVE/START SLAVE), when the sql thread is back up,
Seconds_Behind_Master will present as 0 until the configured
MASTER_DELAY has passed. That is, before the restart,
last_master_timestamp is updated to the timestamp of the delayed
event. Then after the restart, the negation of sql_thread_caught_up
is skipped because the timestamp of the event has already been used
for the last_master_timestamp, and their update is grouped together
in the same conditional block.
This patch fixes this by separating the negation of
sql_thread_caught_up out of the timestamp-dependent block, so it is
called any time an idle parallel slave queues an event to a worker. …
=> MDEV-32265: Seconds_Behind_Master is inaccurate for Delayed replication

mysql-test/include/delete_anonymous_users.inc, mysql-test/suite/roles/set_default_role_for.result, mysql-test/suite/roles/set_default_role_invalid.result, mysql-test/suite/roles/set_default_role_invalid.test, mysql-test/suite/roles/set_default_role_invalid_skip_name_resolve-master.opt, mysql-test/suite/roles/set_default_role_invalid_skip_name_resolve.result, mysql-test/suite/roles/set_default_role_invalid_skip_name_resolve.test, sql/sql_acl.cc
- Regression introduced in https://github.com/MariaDB/server/commit/957cb7b7ba355184aebf0f5dc91b7f2aa620c0e0
- Patch https://github.com/MariaDB/server/commit/4abb8216a054e14afbeb81e8529e02bab6fa14ac change `mysql.user` to `mysql.global_priv` for
`add_anonymous.inc`, update `delete_anonymous.inc`.
- Added test case with `--skip-name-resolve`
- Add test case with anonymous user
- Disable this test for windows, assignes current user to anonymous
user.
Reviewed by: <serg@mariadb.com>
=> MDEV-26875: Wrong user in SET DEFAULT ROLE error

sql/rpl_mi.h, sql/sys_vars.cc, sql/sys_vars.inl
Updates to specific replication system variables need to target the active primary connection to support multi-source replication. These variables use the Sys_var_multi_source_ulonglong type. This class uses offsets of the Master_info C++ class to generalize access to its member variables.
The problem is that the Master_info class is not of standard layout, and neither are many of its member variables, e.g. rli and rli->relay_log. Because the class is not of standard layout, using offsets to access member variables invokes undefined behavior.
The proposed patch changes how Sys_var_multi_source_ulonglong accesses the member variables of Master_info from using parameterized memory offsets to accessor function pointers.
Note that an alternative approach would have been to refactor …
=> MDEV-26272: The macro MASTER_INFO_VAR invokes undefined behaviour

mysql-test/suite/federated/federatedx_create_handlers.result, mysql-test/suite/federated/federatedx_create_handlers.test, sql/select_handler.cc, sql/select_handler.h, sql/sql_select.cc, storage/federatedx/federatedx_pushdown.cc, storage/federatedx/federatedx_pushdown.h
Pushing down statements to FederatedX engine is implemented by printing either SELECT_LEX or SELECT_LEX_UNIT into a string and sending that string to the engine. In the case of pushing down a single SELECT having a CTE (WITH clause) there was a problem, because normally single SELECT's were printed using SELECT_LEX::print(). But CTE's are stored in the upper unit of the SELECT_LEX - SELECT_LEX_UNIT, so they were not unfolded in the string produced.
The solution is to invoke SELECT_LEX_UNIT::print() when pushing down single SELECT statements (but not those which are parts of units), so the possible CTE's are unfolded and printed
FederatedX error on pushdown of statements having CTE
Appropriate test cases are added to the FederatedX test suite.
- [ x] I checked the …
=> MDEV-32382 FederatedX error on pushdown of statements having CTE

mysql-test/main/order_by_innodb.result, mysql-test/main/order_by_innodb.test, sql/sql_select.cc
Verify that a pointer is set before dereferencing it.  Adds automated test that will crash without this fix.
=> MDEV-31116 SIGSEGV in test_if_skip_sort_order|JOIN::optimize_stage2

debian/autobake-deb.sh
Commit Removed Ubuntu Bionic from debian/autobake-debs.sh as it's not used anymore to build official MariaDB images.
Please see #2828 for 10.6 and up version
**REMINDER TO MERGER: This commit should not be merged up to 10.6 or forward**
This is just downgraded #2828 which is merged
=> MDEV-32689: Remove Ubuntu Bionic from 10.5

support-files/mariadb.service.in, support-files/mariadb@.service.in
Originally requested to be infinity, but rolled back to 99% to allow for a remote ssh connection or the odd needed system job. This is up from 15% which is the effective default of DefaultTasksMax.
Thanks Rick Pizzi for the bug report.
```
$ systemctl show -all | grep TasksMax
DefaultTasksMax=38170
$ systemctl show mariadb.service | grep TasksMax
TasksMax=38170
$ sudo systemctl edit mariadb.service
(add TasksMax=99%
Successfully installed edited file '/etc/systemd/system/mariadb.service.d/override.conf'.
$ systemctl show mariadb.service | grep TasksMax
TasksMax=251925
```
=> MDEV-30236 set TaskMax=99% in the MariaDB systemd unit

sql/wsrep_high_priority_service.cc
After b8f9f796 Format_description_log_event constructor requires binlog checksum algorithm or BINLOG_CHECKSUM_ALG_OFF for Galera also.
Thanks to Kristian Nielsen <knielsen@knielsen-hq.org> for pointing a fix.
- [ x] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced.*
- [ x] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/11.0/ …
=> MDEV-31273: Precompute binlog checksums

storage/innobase/buf/buf0buf.cc, storage/innobase/buf/buf0flu.cc, storage/innobase/buf/buf0lru.cc, storage/innobase/include/buf0buf.h, storage/innobase/include/buf0flu.h, storage/innobase/include/ut0new.h
This is a backport of [MDEV-26055](https://jira.mariadb.org/browse/MDEV-26055) from 10.6 
9593cccf285ee348fc9a2743c1ed7d24c768439b and d4265fbde587bd79b6fe3793225d3f4798ee955e into 10.5. This fixes a performance regression of I/O bound workloads where pages need to be evicted from the buffer pool. [MDEV-32681](https://jira.mariadb.org/browse/MDEV-32681) was filed because a regression test easily fails due to this performance regression.
This also includes the changes of #2830.
```bash
./mtr --parallel=auto --repeat=100 innodb.undo_truncate_recover{,,,,,}
```
Without this fix, the test would frequently fail, because the buffer pool page replacement would be extremely slow. As a result, the server would end up being killed by the test harness before the undo tablespace truncation is …
=> 10.5 MDEV-26055: Improve adaptive flushing

mysql-test/suite/innodb/r/row_format_redundant.result, mysql-test/suite/innodb/r/table_flags.result, mysql-test/suite/innodb/t/row_format_redundant.opt, mysql-test/suite/innodb/t/table_flags.opt, mysql-test/suite/innodb/t/table_flags.test, mysql-test/suite/innodb_zip/r/restart.result, mysql-test/suite/innodb_zip/t/restart.opt, storage/innobase/btr/btr0cur.cc, storage/innobase/buf/buf0dump.cc, storage/innobase/dict/dict0load.cc, storage/innobase/fil/fil0fil.cc, storage/innobase/include/dict0load.h, storage/innobase/srv/srv0start.cc
Back when InnoDB was not crash safe with respect to DDL operations, the purpose of the function `dict_check_tablespaces_and_store_max_id()` was to hopefully catch and report some corruption. In MariaDB Server 10.6, all we really need is to ensure that no tablespace ID is assigned twice.
In case there are entries in the change buffer, or an encryption plugin is loaded and some `fil_crypt_thread` might be started later, we will open each tablespace file as usual.
When loading a buffer pool dump, we will attempt to open the data files for all tablespaces that are mentioned in the buffer pool dump file but were not yet loaded into `fil_system`.
Run the regression test suite. In particular, the following would fail:
```sh
./mtr --mysqld=--innodb-buffer-pool-dump-at-shutdown=0 …
```
=> MDEV-32027 Opening all .ibd files on InnoDB startup can be slow

sql/sql_lex.cc, sql/sql_lex.h
Lex_ident_sys had no new operator and was used incorrectly in save_item_list_names(), so leaked memory.
=> MDEV-31995 Fix2 allocate memory in mem_root properly.

mysql-test/suite/innodb/r/mem_pressure.result, mysql-test/suite/innodb/t/mem_pressure.test, storage/innobase/buf/buf0buf.cc, storage/innobase/include/buf0buf.h
The madvice(FREE) added in 10.11 cased performance regressions. To trigger it less often the memory pressure mechanism of Linux was used.
Manually like in MDEV-25341.
```
2023-10-27 19:37:44 0 [Note] InnoDB: Loading buffer pool(s) from /tmp/build-mariadb-server-10.11-datadir/ib_buffer_pool
2023-10-27 19:37:44 0 [Note] Plugin 'FEEDBACK' is disabled.
2023-10-27 19:37:44 0 [Note] sql/mariadbd: ready for connections.
Version: '10.11.6-MariaDB'  socket: '/tmp/build-mariadb-server-10.11.sock'  port: 0  Source distribution
2023-10-27 19:37:45 0 [Note] InnoDB: Buffer pool(s) load completed at 231027 19:37:45
2023-10-27 19:37:54 0 [Note] Memory pressure event freed 5314 pages
```
+ mtr case
=> MDEV-31953 madvise(..., MADV_FREE) is causing a performance regression / MDEV-24670 avoid OOM by linux kernel co-operative memory management

storage/innobase/trx/trx0purge.cc
`trx_purge_free_segment()`: If `fseg_free_step_not_header()` needs to be called multiple times, acquire an exclusive latch on the rollback segment header page after restarting the mini-transaction so that the rest of this function cannot execute concurrently with `trx_undo_create()` on the same rollback segment.
This fixes a regression that was introduced in commit c14a39431b211017e6809bb79c4079b38ffc3dff (MDEV-30753).
The normal regression test suite should exercise this. The bug was found via a one-time failure of the test `encryption.create_or_replace` in 23651e27c672aa57d0dfba1251a4fc0abc6c95d6 (which uses `innodb_undo_tablespaces=3` by default). I think that the bug should be repeatable with any setting of `innodb_undo_tablespaces=0`, but it is a very rare finding (only one …
=> MDEV-32820 Race condition between trx_purge_free_segment() and trx_undo_create()

storage/innobase/btr/btr0bulk.cc, storage/innobase/buf/buf0flu.cc, storage/innobase/fil/fil0fil.cc, storage/innobase/handler/ha_innodb.cc, storage/innobase/handler/handler0alter.cc, storage/innobase/include/fil0fil.h, storage/innobase/include/log0log.h, storage/innobase/include/mtr0mtr.h, storage/innobase/include/srw_lock.h, storage/innobase/log/log0log.cc, storage/innobase/mtr/mtr0mtr.cc, storage/innobase/row/row0merge.cc, storage/innobase/sync/srw_lock.cc
The `log_sys.lsn_lock` that was introduced in commit a635c40648519fd6c3729c9657872a16a0a20821 had better be located in the same cache line with `log_sys.latch` so that `log_t::append_prepare()` needs to modify only two first cache lines where `log_sys` is stored.
`log_t::lsn_lock`: On Linux, change the type from `pthread_mutex_t` to something that may be as small as 32 bits, to pack more data members in the same cache line. On Microsoft Windows, `CRITICAL_SECTION` works better.
`log_t::check_flush_or_checkpoint_`: Renamed to `need_checkpoint`. There is no need to pause all writer threads in `log_free_check()` when we only need to write `log_sys.buf` to `ib_logfile0`. That will be done in `mtr_t::commit()`.
`log_t::append_prepare_wait()`: Make the member function non-static to simplify the …
=> MDEV-32374 log_sys.lsn_lock is a performance hog

scripts/mysql_setpermission.sh
```sql
MariaDB [(none)]> create user test@localhost identified by 'pass1';
MariaDB [(none)]> grant select,update on mysql.* to test@localhost;
Query OK, 0 rows affected (0.001 sec)
MariaDB [(none)]> show grants for test@localhost;
+-------------------------------------------------------------------------------------------------------------+
| Grants for test@localhost                                                                                   |
+-------------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO `test`@`localhost` IDENTIFIED BY PASSWORD '*FB6E1F205D675BC29B052DB14CCEFE7759C5FF7E' |
| GRANT SELECT, UPDATE ON `mysql`.* TO `test`@`localhost`                                                     | …
```
=> MDEV-31611: mariadb-setpermission - Can't use string as an ARRAY ref while strict refs in use

mysql-test/suite/perfschema/r/sxlock_func,debug.rdiff, mysql-test/suite/perfschema/t/sxlock_func.test, storage/innobase/dict/dict0dict.cc, storage/innobase/handler/ha_innodb.cc, storage/innobase/handler/handler0alter.cc, storage/innobase/include/dict0dict.h, storage/innobase/include/lock0lock.h, storage/innobase/lock/lock0lock.cc
`lock_table_children()`: A new function to lock all child tables of a table. We will only hold `dict_sys.latch` while traversing `dict_table_t::referenced_set`. To prevent a race condition with `std::set::erase()` we will copy the pointers to the child tables to a local vector. Once we have acquired references to all child tables, we can safely release `dict_sys.latch`, wait for the locks, and finally release the references.
This fixes up commit 2ca112346438611ab7800b70bea6af1fd1169308 (MDEV-26217) and commit c3c53926c467c95386ae98d61ada87294bd61478 (MDEV-26554).
RQG stress testing, preferrably after #2868 has been merged.
TODO: Add an `mtr` test case.
TODO: Add a debug option to change the type of `dict_sys.latch` to `index_lock` so that we can add debug assertions to prove that the …
=> MDEV-32899 InnoDB is holding shared dict_sys.latch while waiting for FOREIGN KEY child table lock on DDL

mysql-test/suite/innodb/r/foreign_key.result, mysql-test/suite/innodb/t/foreign_key.test, storage/innobase/row/row0upd.cc
`row_upd_clust_rec_by_insert()`: If we are resuming from a lock wait, reset the `disowned` flag of the BLOB pointers in `entry` that we copied from `rec` on which we had invoked `btr_cur_disown_inherited_fields()` before the lock wait started. In this way, the inserted record with the updated `PRIMARY KEY` value will have the BLOB ownership associated with itself, like it is supposed to be.
Note: If the lock wait had been aborted, then rollback would have invoked `btr_cur_unmark_extern_fields()` and no corruption would be possible.
The test `innodb.foreign_key` was extended. It would be good to additionally test this with RQG with a broader selection of input. I do not think that it should make any difference if there is 1 or multiple BLOBs attached to the record.
The patch can be …
=> MDEV-31441 BLOB corruption on UPDATE of PRIMARY KEY with FOREIGN KEY

mysql-test/main/subselect.result, mysql-test/main/subselect.test, mysql-test/main/subselect_no_exists_to_in.result, mysql-test/main/subselect_no_mat.result, mysql-test/main/subselect_no_opts.result, mysql-test/main/subselect_no_scache.result, mysql-test/main/subselect_no_semijoin.result
Using mysql.slow_log was a test table would generate more than one row if there was more than one row in the table.
Some by implicitly enforcing an aggregation in the subquery.
its a test.
=> main.subselect* often fails on CI with ER_SUBQUERY_NO_1_ROW

storage/innobase/mtr/mtr0mtr.cc
`mtr_t::commit()`: If `IMPORT TABLESPACE` is first-time-dirtying blocks, acquire both `log_sys.mutex` and `log_sys.flush_order_mutex` to assign a valid `m_commit_lsn` so that the block will be inserted into the correct position of `buf_pool.flush_list`.
This fixes occasional debug assertion failures when running the regression test suite.
=> MDEV-32269 InnoDB after ALTER TABLE…IMPORT TABLESPACE may not be crash safe

storage/innobase/buf/buf0buf.cc
`buf_page_get_zip()`: Do not wait for the page latch while holding `hash_lock`. If the latch is not available, ensure that any concurrent `buf_pool_t::corrupted_evict()` will be able to acquire the `hash_lock`, and then retry the lookup. If the page was corrupted and evicted, we will finally `goto must_read_page`, retry the read once more, and then report an error.
I think that this is best tested together with [MDEV-31817](https://jira.mariadb.org/browse/MDEV-31817) #2865, which is included for the purpose of testing. The workload must use `ROW_FORMAT=COMPRESSED` tables, and we might want to use `CMAKE_BUILD_TYPE=RelWithDebInfo`.
=> MDEV-32371 Deadlock between buf_page_get_zip() and buf_pool_t::corrupted_evict()

sql/filesort.h, sql/sql_delete.cc
Statements affected by this bug are delete statements that have all these conditions
1) single table delete syntax
2) an in (sub-query) predicate
3) semi-join optimization enabled
4) an order by clause.
Semijoin optimization on an innocent looking query, such as
DELETE FROM t1 WHERE c1 IN (select c2 from t2) ORDER BY c1;
turns it from a single table delete to a multi-table delete.
During multi_delete::initialize_tables for the top level join object, a table is initialized missing a keep_current_rowid flag, needed to position a handler for removal of the correct row after the filesort structure has been built.
Fix provided by Monty (monty@mariadb.com)
Pushed into 10.5 at Monty's request.
Applicable to 10.6, 10.11, 11.0.
OK'd by Monty in slack:#askmonty 2023-12-01
TODO: fill description …
=> MDEV-32212 DELETE with ORDER BY and semijoin optimization causing crash

mysql-test/main/rpl_mysqldump_slave.result, mysql-test/main/rpl_mysqldump_slave.test
This patch is for updating the testcase in `rpl_myslqdump_slave.test` for missing mysqldump `delete-master-logs` option
by executing `mysql-test-run.pl rpl_mysqldump_slave.test` desire output can be obtained.
an additional note: I added this test at the very end, because adding it in the middle at it's correct place. it changes pre existing result, so i didn't. on suggestion i can do it.
=> MDEV-32611: Test suite is missing dump option `delete-master-logs`

storage/innobase/btr/btr0btr.cc, storage/innobase/btr/btr0cur.cc, storage/innobase/btr/btr0pcur.cc, storage/innobase/btr/btr0sea.cc, storage/innobase/buf/buf0buf.cc, storage/innobase/buf/buf0lru.cc, storage/innobase/dict/dict0boot.cc, storage/innobase/gis/gis0sea.cc, storage/innobase/ibuf/ibuf0ibuf.cc, storage/innobase/include/btr0btr.h, storage/innobase/include/buf0buf.h, storage/innobase/include/buf0lru.h, storage/innobase/row/row0merge.cc, storage/innobase/row/row0purge.cc, storage/innobase/row/row0sel.cc, storage/innobase/row/row0undo.cc, storage/innobase/trx/trx0rec.cc, storage/innobase/trx/trx0rseg.cc, storage/innobase/trx/trx0trx.cc, storage/innobase/trx/trx0undo.cc
The linear read-ahead (enabled by nonzero `innodb_read_ahead_threshold`) works best if index leaf pages or undo log pages have been allocated on adjacent page numbers. The read-ahead is assumed not to be helpful in other types of page accesses, such as non-leaf index pages.
We will make the callers of `buf_page_get_low()` responsible for invoking one or both of `buf_page_make_young_if_needed()` and `buf_read_ahead_linear()`. We will invoke them in those callers of `buf_page_get_gen()` or `buf_page_get()` where it makes sense: the access is not one-time-on-startup and the page and not going to be freed soon.
We will not invoke linear read-ahead in functions that would essentially allocate or free pages. Freshly allocated pages are expected to be initialized by `buf_page_create()` and not …
=> MDEV-32068 Some calls to buf_read_ahead_linear() seem to be useless

mysql-test/suite/binlog/t/flashback.test
The binlog.flashback test tries to run using the stmt and mix binlog_format combinations (because it includes have_log_bin.inc), yet are meaningless tests because the server starts with the --flashback option, forcing binlog_format=row.
This patch optimizes test time by removing the stmt and mix format combinations from running.
=> MDEV-32933: Skip statement and mix mode for binlog.flashback

mysql-test/suite/innodb/r/innodb_force_recovery.result, mysql-test/suite/innodb/t/innodb_force_recovery.test, storage/innobase/srv/srv0srv.cc
srv_export_innodb_status(): Update
export_vars.innodb_buffer_pool_read_requests
with buf_pool.stat.n_page_gets.
Attached the innodb.buf_pool_read_requests in innodb suite.
=> MDEV-32920  innodb_buffer_pool_read_requests always 0

storage/innobase/btr/btr0btr.cc, storage/innobase/buf/buf0buf.cc, storage/innobase/buf/buf0lru.cc, storage/innobase/dict/dict0boot.cc, storage/innobase/ibuf/ibuf0ibuf.cc, storage/innobase/include/buf0buf.h, storage/innobase/include/log0recv.h, storage/innobase/log/log0recv.cc, storage/innobase/row/row0import.cc, storage/innobase/srv/srv0start.cc
The fix of bug [MDEV-21572](https://jira.mariadb.org/browse/MDEV-21572) introduced a rarely holding condition in a commonly executed function `buf_page_get_gen()`, which is only needed while crash recovery is in progress.
We will refactor the InnoDB startup so that `buf_page_get_gen()` can assume that any recovery on the page has already been performed. Dictionary tables and undo log records will be loaded only after all log has been applied.
This is adequately covered by the regression test suite. The tests `innodb.group_commit_binlog_pos_no_optimize_thread`, `innodb.group_commit_binlog_pos`, and `mariabackup.binlog` cover the changed logic around the call to `trx_sys_print_mysql_binlog_offset()`.
Some additional stress testing will be useful to ensure that this will not introduce any …
=> MDEV-32042 Simplify buf_page_get_gen()

mysql-test/suite/innodb/r/doublewrite.result, mysql-test/suite/innodb/r/doublewrite_debug.result, mysql-test/suite/innodb/t/doublewrite.test, mysql-test/suite/innodb/t/doublewrite_debug.combinations, mysql-test/suite/innodb/t/doublewrite_debug.test, storage/innobase/handler/ha_innodb.cc
- Rewrote the doublewrite test case and removes the usage of innodb_buf_flush_list variable, added search pattern to make sure that InnoDB uses doublewrite buffer. Replaced all kill_mysqld.inc with shutdown_mysqld.inc and zero shutdown timeout
Run innodb.doublewrite test case in mtr
=> MDEV-32242	innodb.doublewrite test case always gets skipped

storage/innobase/buf/buf0flu.cc
`buf_flush_page_cleaner()`: Pass `pct_lwm=srv_max_dirty_pages_pct_lwm` (`innodb_max_dirty_pages_pct_lwm`) to
`page_cleaner_flush_pages_recommendation()` unless the dirty page ratio of the buffer pool is below that. Starting with
commit d4265fbde587bd79b6fe3793225d3f4798ee955e we used to always pass `pct_lwm=0.0`, which was not intended.
I tested this with a Sysbench `oltp_update_index` workload and some diagnostic that would emit additional output once per second:
```diff
diff --git a/storage/innobase/buf/buf0flu.cc b/storage/innobase/buf/buf0flu.cc
index c0c743ede57..91b7b04819c 100644
--- a/storage/innobase/buf/buf0flu.cc
+++ b/storage/innobase/buf/buf0flu.cc
@@ -2433,6 +2433,10 @@ static os_thread_ret_t DECLARE_THREAD(buf_flush_page_cleaner)(void*)
mysql_mutex_lock(&buf_pool.mutex); …
```
=> MDEV-31939 Adaptive flush recommendation ignores dirty ratio and checkpoint age

mysql-test/suite/rpl/r/rpl_deadlock_show_slave_status.result, mysql-test/suite/rpl/t/rpl_deadlock_show_slave_status.test, sql/rpl_parallel.cc, sql/rpl_parallel.h, sql/rpl_rli.h, sql/slave.cc
A replication parallel worker thread can deadlock with another
connection running SHOW SLAVE STATUS. That is, if the replication
worker thread is in do_gco_wait() and is killed, it will already
hold the LOCK_parallel_entry, and during error reporting, try to
grab the err_lock. SHOW SLAVE STATUS, however, grabs these locks in
reverse order. It will initially grab the err_lock, and then try to
grab LOCK_parallel_entry. This leads to a deadlock when both threads
have grabbed their first lock without the second.
This patch implements the MDEV-31894 proposed fix to optimize the
workers_idle() check to compare the last in-use relay log’s
queued_count==dequeued_count for idleness. This removes the need for
workers_idle() to grab LOCK_parallel_entry, as these values are
atomically updated.
This …
=> MDEV-10653: SHOW SLAVE STATUS Can Deadlock an Errored Slave

debian/libmariadb3.symbols
Add missing symbols and their introduced C/C version.
@ottok  see you added this in #2778. Some of our version number differ. I didn't look down to 3.1 so your introduced version of this is likely more accurate.
Is it a FYI field in the debian packaging?
deb-autobake tests (check output, won't fail I think)
=> MDEV-30482 libmariadb3 - debian/libmariadb3.symbols not updated

mysql-test/suite/innodb/r/alter_table.result, mysql-test/suite/innodb/t/alter_table.test, storage/innobase/handler/handler0alter.cc
`ha_innobase::check_if_supported_inplace_alter()`: On `ALTER_OPTIONS`, if `innodb_file_per_table=1` and the table resides in the system tablespace, require that the table be rebuilt (and moved to an `.ibd` file).
The regression test suite was extended with a test case.
=> MDEV-31000 Assertion failed on ALTER TABLE...page_compressed=1

plugin/disks/mysql-test/disks/disks.result, plugin/disks/mysql-test/disks/disks.test, plugin/disks/mysql-test/disks/disks_notembedded.result, plugin/disks/mysql-test/disks/disks_notembedded.test
Thanks Otto Kekäläinen for the bug report.
Allow for a CI system to be almost out of space, or having so little use, that the Total space is the same as available or used.
its a mtr test.
=> MDEV-21587: disk.disk test result

mysql-test/suite/innodb/r/instant_alter_bugs.result, mysql-test/suite/innodb/t/instant_alter_bugs.test, storage/innobase/handler/handler0alter.cc, storage/innobase/row/row0ins.cc
`innobase_instant_try()`: Invoke `btr_set_instant()` in the same mini-transaction that has successfully inserted the metadata record. In this way, if inserting the metadata record fails before any undo log record was written for it, the index root page will remain consistent.
The regression test was extended with a test case for reproducing this bug.
=> MDEV-18322 Assertion "wrong page type" on instant ALTER TABLE

extra/mariabackup/xtrabackup.cc, mysql-test/suite/mariabackup/backup_grants.result, mysql-test/suite/mariabackup/backup_grants.test
opt_kill_long_query_type being an enum could be 0 corresponding to ALL. When ALL is specified, the CONNECTION ADMIN is still required.
fixed test cases associated with REPLICA MONITOR.
Noticed thanks to bug report by Tim van Dijen.
Fixes: 79b58f1ca893b8affc5075d0a548563d376cd481
mtr included
=> MDEV-33006 Missing required privilege CONNECTION ADMIN

storage/innobase/fil/fil0fil.cc, storage/innobase/log/log0recv.cc, storage/innobase/os/os0file.cc
During `mariadb-backup --backup`, a table could be renamed, created and dropped. We could have both `oldname.ibd` and `oldname.new`, and one of the files would be deleted before the InnoDB recovery starts. The desired end result would be that we will recover both `oldname.ibd` and `newname.ibd`.
During normal crash recovery, at most one file operation (create, rename, delete) may require to be replayed from the write-ahead log before the DDL recovery starts.
`deferred_spaces.create()`: In `mariadb-backup --prepare`, try to create the file in case it does not exist.
`fil_name_process()`: Display a message about not found files not only if `innodb_force_recovery` is set, but also in `mariadb-backup --prepare`.
It should be possible to write a test case for this using debug injection points. …
=> MDEV-32939 If tables are frequently created, renamed, dropped, a backup cannot be restored

.github/pull_request_template.md, CODING_STANDARDS.md
When making commits, the branches to target are not clearly defined in
public documentation, and frequently change. As the development branch
and the earliest maintained branches progress, it should be reflected in
CODING_STANDARDS.md.
BSD-new license. I am contributing on behalf of my employer Amazon Web
Services.
Documentation change, no testing necessary.
that are either new files or modified ones, are contributed under the 
BSD-new license. I am contributing on behalf of my employer Amazon Web 
Services.
=> Explicitly recommend target branches in CODING_STANDARDS

mysql-test/suite/innodb/t/import_update_stats.test, storage/innobase/dict/dict0stats.cc, storage/innobase/handler/ha_innodb.cc, storage/innobase/include/dict0stats.h
- InnoDB should write all zeros into a table and its indexes statistics members when table is unreadable.
./mtr innodb.import_update_stats
=> MDEV-32725 innodb.import_update_stats accesses uninitialized ib_table->stat_n_rows

storage/innobase/trx/trx0purge.cc
`trx_purge_truncate_history()`: When we need to wait for a page latch, acquire and release `buf_pool.mutex` to ensure that any thread that may be holding `buf_pool.mutex` and waiting for `buf_pool.flush_list_mutex` will be able to proceed.
This fixes up commit a0f02f743848fb6ef6d2a51960f77e1e38da1682 (MDEV-32757).
This is best tested by @hgxl64 in the Ubuntu 18.04 environment where the original anomaly was observed. The existing regression tests `innodb.undo_truncate` and `innodb.undo_truncate_recover` does cover this code.
=> MDEV-33009 Server hangs for a long time with innodb_undo_log_truncate=ON

storage/innobase/buf/buf0rea.cc
A MemorySanitizer error use-of-uninitialized-value may be issued for `buf_read_ahead_linear()`, which indeed is performing unsafe reads of the page header fields `FIL_PAGE_PREV` and `FIL_PAGE_NEXT`. The impact of comparing invalid data is minor; we might trigger a read-ahead when we should not, or skip it when we should perform it.
The error is very rare and nondeterministic. On buildbot, it was observed only once in a 10.6 based branch when running the test `innodb_fts.bug_32831765`.
MemorySanitizer is only usable (and enabled in our CI systems) starting with 10.5. A corresponding error could theoretically occur also in Valgrind builds on 10.4, but I do not remember any occurrence there, and the code in 10.5 has been heavily refactored over earlier versions.
=> MDEV-33052 MSAN use-of-uninitialized-value in buf_read_ahead_linear()

client/mysql_upgrade.c, mysql-test/main/mysql_upgrade_file_leak.result, mysql-test/main/mysql_upgrade_file_leak.test
This patch addresses a file leak issue identified in `mysql_upgrade` with the `--check-if-upgrade-is-needed` option. Previously, the execution of `mysql_upgrade` with this flag would leave temporary files in the system's temp directory. This patch ensures that any temporary files created during the `mysql_upgrade `process are properly cleaned up, thus maintaining a cleaner system environment.
The patch includes an updated test case that verifies the absence of temporary files after running `mysql_upgrade` with the `--check-if-upgrade-is-needed` option. This test should pass without any temporary files being left behind in the temp directory.
=> MDEV-31925 mysqld_upgrade --check-if-upgrade-is-needed leaks files

storage/innobase/buf/buf0buf.cc
mariadb-backup wasn't meant to have memory pressure sensors so restrict the operation to SRV_OPERATIONAL_NORMAL mode.
mtr --suite=mariabackup
=> MDEV-24670 memory pressure - mariadb-backup postfix

storage/innobase/buf/buf0buf.cc
Silence a few more un-actionable warnings.
Use ignoring result on write to make sure compilers don't complain. Use empty if statement as a warning suppressant for other compilers.
=> MDEV-24670 memory pressure - warnings/notes

mysql-test/suite/innodb/r/doublewrite_debug.result, mysql-test/suite/innodb/t/doublewrite_debug.test
- innodb.doublewrite_debug should avoid the checkpoint before killing the server. So used debug sync and innodb_flush_sync to avoid the checkpoint completely.
./mtr innodb.doublewrite_debug
=> MDEV-33098 The test innodb.doublewrite_debug occasionally fails to start up InnoDB

sql/mysqld.cc, sql/sql_acl.cc, sql/table_cache.cc, sql/table_cache.h, sql/threadpool.h, storage/sphinx/ha_sphinx.cc, storage/sphinx/ha_sphinx.h, storage/spider/spd_param.cc
In commit b4ff64568c88ab3ce559e7bd39853d9cbf86704a the signature of mysql_show_var_func was changed, but not all functions of that type were adjusted.
When the server is configured with `cmake -DWITH_ASAN=ON` and compiled with clang, runtime errors would be flagged for invoking functions through an incompatible function pointer.
This is covered by the regression test suite. I noticed the problem by running `./mtr --suite=perfschema` and searching the logs. I had applied the following patch in order to ignore all other errors that `clang -fsanitize=undefined` would catch:
```diff
diff --git a/mysql-test/mysql-test-run.pl b/mysql-test/mysql-test-run.pl
index cdd8f0bf6cd..2ad0651afb6 100755
--- a/mysql-test/mysql-test-run.pl
+++ b/mysql-test/mysql-test-run.pl
@@ -4370,8 +4370,7 @@ sub …
```
=> MDEV-33160 show_status_array() calls various functions via incompatible pointer

storage/connect/tabvct.cpp
Unneeded definition prototype that conflicted with the Solaris defination.
See if it compiles.
=> MDEV-8941 Compile on Solaris (SPARC) fails with errors in filamvct.cpp

storage/innobase/trx/trx0purge.cc
`trx_purge_free_segment()`, `trx_purge_truncate_rseg_history()`: Do not claim that the blocks will be modified in the mini-transaction, because that will not always be the case. Whenever there is a modification, `mtr_t::set_modified()` will flag it.
The debug assertion that failed in recovery is checking that all changes to data pages are covered by log records. Due to these incorrect calls, we would unnecessarily write unmodified data pages, which is something that commit 05fa4558e0e82302ece981deabce764491464eb2 aims to avoid.
The incorrect calls had originally been added in commit de31ca6a212118bd29876f964497050e446bda02 (MDEV-32820) and commit 86767bcc0f121db3ad83a74647a642754a0ce57f (MDEV-29593).
This was tested by @elenst on the 10.11 and 11.2 branches by repeatedly killing and …
=> MDEV-33137: Assertion end_lsn == page_lsn failed in recv_recover_page

storage/innobase/buf/buf0flu.cc, storage/innobase/fil/fil0fil.cc, storage/innobase/fsp/fsp0fsp.cc, storage/innobase/handler/ha_innodb.cc, storage/innobase/include/fil0fil.h, storage/innobase/include/mtr0mtr.h, storage/innobase/include/srv0srv.h, storage/innobase/mtr/mtr0mtr.cc, storage/innobase/srv/srv0srv.cc, storage/innobase/trx/trx0purge.cc
When `innodb_undo_log_truncate=ON` causes an InnoDB undo tablespace to be truncated, we must guarantee that the undo tablespace will be rebuilt atomically: After `mtr_t::commit_shrink()` has durably written the mini-transaction that rebuilds the undo tablespace, we must not write any old pages to the tablespace.
To guarantee this, in `trx_purge_truncate_history()` we used to traverse the entire `buf_pool.flush_list` in order to acquire exclusive latches on all pages for the undo tablespace that reside in the buffer pool, so that those pages cannot be written and will be evicted during `mtr_t::commit_shrink()`. But, this traversal may interfere with the page writing activity of `buf_flush_page_cleaner()`. It would be better to lazily discard the old pages of the truncated undo tablespace. …
=> MDEV-33112 innodb_undo_log_truncate=ON is blocking page write

mysql-test/main/mysql_json_table_recreate.result, mysql-test/main/mysql_json_table_recreate.test, plugin/type_mysql_json/type.cc
- [x ] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced.*
- [x ] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/11.0/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [ x] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.
=> MDEV-32790: Output result in show create table for mysql_json type should be longtext

mysql-test/main/mysql_json_table_recreate.result, mysql-test/main/mysql_json_table_recreate.test, sql/sql_table.cc
- [x ] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced.*
- [x ] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/11.0/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [ x] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.
=> MDEV-32235: mysql_json cannot be used on newly created table

mysql-test/main/subselect_nulls_innodb.result, mysql-test/main/subselect_nulls_innodb.test
This ticket is fixed by MDEV-32555 and this test captures a different use case.
=> MDEV-32090 Test for null-safe equals in join

scripts/mysqlhotcopy.sh
This PR consists of 3 PR:
- I tried to allow DBI for mariadb-hotcopy the same as for other scripts.
<details closed>
<summary>Check driver compatibility</summary>
<br>
Install DB and run server locally :heavy_check_mark: 
<pre>
$ ./scripts/mysql_install_db --srcdir=../../src/10.11 --defaults-file=~/.my1011-hs.cnf
Installing MariaDB/MySQL system tables in '/tmp/10.11' ...
OK
$ ./sql/mysqld --defaults-file=~/.my1011-hs.cnf
</pre>
1. User not allowed to connect through socket :heavy_check_mark: 
<pre>
$ ./scripts/mysqlhotcopy  "--regex=.*" ./tmp 
DBI connect(';host=;port=;mariadb_read_default_group=mysqlhotcopy','',...) failed: Access denied for user 'anel'@'localhost' (using password: NO) at ./scripts/mysqlhotcopy line 222.
</pre>
2. User cannot connect through socket :heavy_check_mark: …
=> MDEV-30259 & MDEV-33187: mariadb-hotcopy fails for performance_schema/sys

mysql-test/suite/innodb/r/doublewrite.result, mysql-test/suite/innodb/r/log_file_name.result, mysql-test/suite/innodb/t/doublewrite.test, mysql-test/suite/innodb/t/doublewrite_debug.test, mysql-test/suite/innodb/t/log_file_name.test, storage/innobase/buf/buf0dblwr.cc, storage/innobase/fsp/fsp0file.cc, storage/innobase/fsp/fsp0sysspace.cc, storage/innobase/include/buf0dblwr.h, storage/innobase/include/log0recv.h, storage/innobase/log/log0recv.cc, storage/innobase/srv/srv0start.cc
InnoDB fails to find the space id from the page0 of
the tablespace. In that case, InnoDB can use
doublewrite buffer to recover the page0 and write
into the file.    
buf_dblwr_t::init_or_load_pages(): Loads only the pages
which are valid.(page lsn >= checkpoint). To do that,
InnoDB has to open the redo log before system
tablespace, read the latest checkpoint information.
recv_dblwr_t::find_first_page():
1) Iterate the doublewrite buffer pages and find the 0th page
2) Read the tablespace flags, space id from the 0th page.
3) Read the 1st, 2nd and 3rd page from tablespace file and
compare the space id with the space id which is stored
in doublewrite buffer.
4) If it matches then we can write into the file.
5) Return space which matches the pages from the file. …
=> MDEV-32968  InnoDB fails to restore tablespace first page from doublewrite buffer when page is empty

mysql-test/suite/binlog/r/flashback.result, mysql-test/suite/binlog/t/flashback.combinations, mysql-test/suite/binlog/t/flashback.test, sql/log_event.h, sql/log_event_client.cc
Summary
=======
With FULL_NODUP mode, before image inclues all columns and after image inclues only the changed columns. flashback will swap the value of changed columns from after image to before image. For example:
BI: c1, c2, c3_old, c4_old
AI: c3_new, c4_new
flashback will reconstruct the before and after images to
BI: c1, c2, c3_new, c4_new
AI: c3_old, c4_old
Implementation
==============
When parsing the before and after image, position and length of the fields are collected into ai_fields and bi_fields, if it is an Update_rows_event and the after image doesn't includes all columns.
The changed fields are swapped between bi_fields and ai_fields. Then it recreates the before image and after image by using bi_fields and ai_fields. nullbit will be set to 1 if the field is NULL, …
=> MDEV-32894: mysqlbinlog flashback support binlog_row_image FULL_NODUP mode

storage/innobase/os/os0file.cc
```
2024-01-16 18:42:29 0 [Note] InnoDB: IO Error: 5during write of 16384 bytes, for file ./ibdata1(12), returned 0
```
Isn't very readable.
Hammer storage until it doesn't work and run MariaDB. Look at error. Then buy new storage.
=> innodb: IO Error message missing space

storage/innobase/buf/buf0flu.cc, storage/innobase/buf/buf0lru.cc, storage/innobase/include/buf0buf.h
When using `innodb_buffer_pool_size=2000g` and `innodb_log_file_size=128g` it could happen that InnoDB will be stalled for less than a second while the buffer pool is running out of free pages. Setting a smaller `innodb_max_dirty_pages_pct` or (nonzero) `innodb_max_dirty_pages_pct_lwm` will not necessarily keep the `buf_flush_page_cleaner()` thread busy.
`buf_pool_t::page_cleaner_wakeup()`: Change the parameter `bool for_LRU` to an integer, to distinguish immediate wakeup and a "soft" wakeup (no need to interrupt a 1-second sleep).
`buf_LRU_get_free_block()`: After `buf_LRU_get_free_only()` succeeded, invoke `buf_pool_t::page_cleaner_wakeup()` if the number of free blocks is below `innodb_lru_scan_depth`. If it is below half that, wake up the page cleaner immediately, not letting it wait …
=> MDEV-33053 InnoDB LRU flushing does not run before running out of buffer pool

storage/federatedx/federatedx_io_mysql.cc
The FederatedX storage engine in MariaDB was identified to have a performance issue where it repeatedly sets the time_zone for each individual query executed against a federated table. 
Instead of setting the` time_zone` with every query, the time zone is now set to `'+00:00' (UTC)` only upon establishing a new connection. 
=> MDEV-32990 federatedx time_zone round trips

mysql-test/suite/rpl/r/rpl_domain_id_filter_master_crash.result, mysql-test/suite/rpl/t/rpl_domain_id_filter_master_crash.test
While a replica may be reading events from the
primary, the primary is killed. Left to its own
devices, the IO thread may or may not stop in
error, depending on what it is doing when its
connection to the primary is killed (e.g. a
failed read results in an error, whereas if the
IO thread is idly waiting for events when the
connection dies, it will enter into a reconnect
loop and reconnect). MDEV-32168 changed the test
to always wait for the reconnect, thus breaking
the error case, as the IO thread would be stopped
at a time of expecting it to be running.
The fix is to manually stop/start the IO thread
to ensure it is in a consistent state.
Note that rpl_domain_id_filter_master_crash.test
will need additional changes after fixing MDEV-33268
=> MDEV-32168: Postpush fix for rpl_domain_id_filter_master_crash

sql/log_event_server.cc
An existing binlog checksum can be overridden to 0 if writing a NULL payload when using Zlib for the computation. That is, calling into Zlib's crc32 with empty data initializes an incremental CRC computation to 0.
This patch changes the Log_event_writer::write_data() to exit immediately if there is nothing to write, thereby bypassing the checksum computation. This follows the pattern of
Log_event_writer::encrypt_and_write(), which also exits immediately if there is no data to write.
See that this fixes the failing `rpl.rpl_sp_effects` test on [s390x](https://buildbot.mariadb.org/#/builders/476/builds/16004)
=> MDEV-33283: Binlog Checksum is Zeroed by Zlib if Part of Event Data is Empty

storage/columnstore/CMakeLists.txt
MCOL-5611 supporting with Boost-1.80, the version "next_prime" disappears from https://github.com/boostorg/unordered/blob/boost-1.79.0/include/boost/unordered/detail/implementation.hpp makes it the currenly highest supported versions.
Lets check this version.
While CMake-3.19+ supports version ranges in package determinations this isn't supported for Boost in Cmake-3.28. So we check for the 1.80 and don't compile ColumnStore.
Check fc39 builder works.
=> MDEV-33290: Disable ColumnStore based on boost version

debian/mariadb-server-10.6.mariadb.init
Noted by Eric X. Confirmed by shellcheck.
Note this is a part fix of the MDEV. Rest in progress on #2300.
Eric X confirmed it.
=> MDEV-28640: Debian typo in init script

mysql-test/suite/innodb/r/undo_space_dblwr.result, mysql-test/suite/innodb/t/undo_space_dblwr.test, mysql-test/suite/sys_vars/r/innodb_fil_make_page_dirty_debug_basic.result, mysql-test/suite/sys_vars/t/innodb_fil_make_page_dirty_debug_basic.test, storage/innobase/handler/ha_innodb.cc
Reason:
======
undo_space_dblwr test case fails if the first page of undo tablespace is not flushed before restart the server. While restarting the server, InnoDB fails to detect the first page of undo tablespace from doublewrite buffer.
Fix:
===
Use "ib_log_checkpoint_avoid_hard" debug sync point to avoid checkpoint and make sure to flush the
dirtied page before killing the server.
innodb_make_page_dirty(): Fails to set srv_fil_make_page_dirty_debug variable.
./mtr innodb.undo_space_dblwr
=> MDEV-33341 innodb.undo_space_dblwr test case fails with Unknown Storage Engine InnoDB

extra/mariabackup/xtrabackup.cc
Postfix for a6290a5bc5f3cba096854595c354d19d9267743d, in 10.11 where OS_DATA_FILE_NO_O_DIRECT gets used. Same #ifdef conditions as other uses of OS_DATA_FILE_NO_O_DIRECT.
Noticed on aarch64-macos builder.
=> MDEV-33095 MariaDB-backup - no OS_DATA_FILE_NO_O_DIRECT on some platforms

storage/innobase/log/log0log.cc
Without an OS error it could one of the many errors from write.
Hardware errors with hammer while running mariadb.
- [] *This is a new feature and the PR is based against the latest MariaDB development branch.*
=> MDEV-33397: Innodb include OS error information when failing to write  to iblogfileX

plugin/cracklib_password_check/CMakeLists.txt
As was done in dc77111 for `support-files/CMakeLists.txt`
Do not rely on existence of `CMakeFiles/${target}.dir` directory existence
It is not there for custom targets in Ninja build.
This regression was introduced in #1131 which likely copied the pattern from e79e840 before that regression was addressed in dc77111.
A passing build can be seen at https://salsa.debian.org/robinnewhouse/mariadb-server-mirror/-/pipelines/630860.
BSD-new license. I am contributing on behalf of my employer Amazon Web
Services.
=> Fix ninja build for cracklib_password_check

mysql-test/suite/encryption/r/innodb-redo-nokeys.result, mysql-test/suite/encryption/t/innodb-redo-nokeys.test, mysql-test/suite/innodb/include/no_checkpoint_start.inc, storage/innobase/log/log0recv.cc
If we fail to open a tablespace while looking for FILE_CHECKPOINT, we set the corruption flag. Specifically, if encryption key is missing, we would not be able to open an encrypted tablespace and the flag could be set. We miss checking for this flag and report "Missing FILE_CHECKPOINT".
./mtr encryption.innodb-redo-nokeys
Please check the MDEV for temporary changes suggested in test to for faster reproduction.
=> MDEV-33274 The test encryption.innodb-redo-nokeys often fails

client/mysqldump.c, mysql-test/main/rpl_mysqldump_slave.result, mysql-test/main/rpl_mysqldump_slave.test
Recording both is useful on a replication relay.
If a =2, commented is selected, allow the alternate option to exist.
This still disables --dump-slave=1 --master-data=1 as having the a CHANGE MASTER TO and START SLAVE on different positions would be confusing and dangerious to the data.
Based of code from Elena Stepanova.
- [ X ] *This is a bug fix and the PR is based against the earliest maintained branch in …
=> MDEV-4827 mysqldump --dump-slave=2 --master-data=2 doesn't record both

mysql-test/main/distinct_notembedded.result, mysql-test/main/distinct_notembedded.test, mysql-test/main/opt_trace.result, sql/item_sum.h, sql/sql_select.cc, sql/sql_select.h
When executing a statement of the form
SELECT AGGR_FN(DISTINCT c1, c2,..,cn) FROM t1,
where AGGR_FN is an aggregate function such as COUNT(), AVG() or SUM(), and a unique index exists on table t1 covering some or all of the columns (c1, c2,..,cn), the retrieved values are inherently unique. Consequently, the need for de-duplication imposed by the DISTINCT clause can be eliminated, leading to optimization of aggregation operations.
This optimization applies under the following conditions:
- only one table involved in the join (not counting const tables)
- some arguments of the aggregate function are fields (not functions/subqueries)
This optimization extends to queries of the form
SELECT AGGR_FN(c1, c2,..,cn) GROUP BY cx,..cy
when a unique index covers some or all of the columns (c1, …
=> MDEV-30660 Aggregation functions fail to leverage uniqueness property

include/my_rdtsc.h
Starting with Linux 6.6 [1], RDCYCLE is a privileged instruction on RISC-V and can't be used directly from userland. There is a sysctl option to change that as a transition period, but it will eventually disappear.
Use RDTIME instead, which while less accurate has the advantage of being synchronized between CPU (and thus monotonic) and of constant frequency.
[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=cc4c07c89aada16229084eeb93895c95b7eabaa3
Running MariaDB on a riscv64 host running Linux 6.6+ without this change (or even just the testsuite) fails with a SIGILL. After applying this patch, the testsuite passes fully.
=> [MDEV-33435] RISC-V: use RDTIME instead of RDCYCLE

scripts/wsrep_sst_mariabackup.sh
Also fix the usage of timeout(1) on NetBSD, OpenBSD and DragonFly.
Issues were found via trying to utilize the script on OpenBSD and things not working due to differences in command operation.
=> Fix timeout(1) usage in wsrep_sst_mariabackup on *BSD

man/my_print_defaults.1
The `--mariadbd` option was added in 10.11.3, this commit adds the option
to the man page as well.
=> Update my_print_defaults man page with mariadbd option

debian/autobake-deb.sh
While a -f debian/mariadb-plugin-columnstore.install idempotent check
existed, the tying of the install file to the control file has some
weaknesses.
Used sed as an alternative to replace the debian/control
mariadb-plugin-columnstore package defination and replace it with the
one from the columnstore submodule.
in the expected behavior can't …
=> MDEV-28419 subsequent runs of debian/autobake-deb.sh are not idempotent

storage/connect/libdoc.cpp
libxml2 2.12.0 made `xmlGetLastError()` return `const` pointer:
https://gitlab.gnome.org/GNOME/libxml2/-/commit/61034116d0a3c8b295c6137956adc3ae55720711
Clang 16 does not like this:
error: assigning to 'xmlErrorPtr' (aka '_xmlError *') from 'const xmlError *' (aka 'const _xmlError *') discards qualifiers
error: cannot initialize a variable of type 'xmlErrorPtr' (aka '_xmlError *') with an rvalue of type 'const xmlError *' (aka 'const _xmlError *')
Let’s update the variables to `const`. For older versions, it will be automatically converted.
But then `xmlResetError(xmlError*)` will not like the `const` pointer:
error: no matching function for call to 'xmlResetError'
note: candidate function not viable: 1st argument ('const xmlError *' (aka 'const _xmlError *')) would lose const qualifier …
=> [MDEV-33439] Fix build with libxml2 2.12

debian/mariadb-server-10.5.install, man/CMakeLists.txt, man/wsrep_sst_backup.1
The script wsrep_sst_backup was introduced on MariaDB 10.3 in commit
9b2fa2a. The new script was automatically included in RPM packages but not
in Debian packages (which started to fail on waring about stray file).
Include wsrep_sst_backup in the mariadb-server-10.{3..8} package, and
also include a stub man page so that packaging of a new script is complete.
Build packages and compare file listings before and after. Also see Buildbot Debian builders and Salsa-CI which cover this change.
I would refrain from introducing new stuff on very old releases, but since 9b2fa2a already happened on 10.3, also this commit should be made to make the introduction of a new script complete.
=> Properly introduce wsrep_sst_backup script in project packaging

debian/control, debian/mariadb-plugin-spider.install, debian/mariadb-server.install
Instead of having a separate plugin, simply include Spider in the main
MariaDB Server package and let users manually enable on server installs
where they want to run it.
***
Created on request by @vuvova in https://jira.mariadb.org/browse/MDEV-13033?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel&focusedCommentId=157462#comment-157462
This is pending on ColumnStore to be fixed on 10.5 trunk first so that I can run all the QA tools to verify this does not regress and all upgrades work.
=> Deb: Stop shipping mariadb-plugin-spider separately, include in server

mysql-test/main/join.result, mysql-test/main/join.test, sql/sql_derived.cc
For queries with derived tables populated having some side-effect, we will fill such a derived table more than once, but without clearing its rows. Consequently it will have duplicate rows. An example query exhibiting the problem is
SELECT STRAIGHT_JOIN c1 FROM t1 JOIN (SELECT @A := 0) x;
Since mysql_derived_fill will, for UNCACHEABLE_DEPENDENT tables, drop all rows and repopulate, we relax the condition within mysql_derived_fill: rather than assume all uncacheable values prevent an early return, we now allow an early return for uncacheable values other than UNCACHEABLE_DEPENDENT. In general, we only populate derived tables once unless they're dependent tables.
=> MDEV-30975 Wrong result with cross Join given join order

cmake/cpack_rpm.cmake, debian/mariadb-server-core-10.5.postinst, support-files/policy/apparmor/usr.sbin.mysqld, support-files/policy/selinux/mariadb-server.te
CapabilityBoundingSet included CAP_IPC_LOCK in MDEV-9095, however it requires that the executable has the capability marked in extended attributes also.
The alternate to this is raising the RLIMIT_MEMLOCK for the service/ process to be able to complete the mlockall system call. This needs to be adjusted to whatever the MariaDB server was going to allocate. Rather than leave the non-obvious mapping of settings and tuning, add the capability so its easier for the user.
We set the capability, if possible, but may never be used depending on user settings. As such in the Debian postinst script, don't complain if this fails.
The CAP_IPC_LOCK also facilitates the mmaping of huge memory pages. (see man mmap).
enable --memlock and a innodb_buffer_pool or similar larger than the default memlock …
=> MDEV-33301 memlock with systemd still not working

mysql-test/suite/innodb/r/undo_truncate.result, mysql-test/suite/innodb/t/undo_truncate.test, storage/innobase/trx/trx0purge.cc
`purge_sys_t::truncating_tablespace()`: Clamp the
`innodb_max_undo_log_size` to the maximum number of pages before converting the result into a 32-bit unsigned integer.
This fixes up commit f8c88d905b44bffe161158309e9acc25ad3691aa (MDEV-33213).
In later major versions, we would use 32-bit unsigned integer here due to commit ca501ffb04246dcaa1f1d433d916d8436e30602e and the code would crash also on 64-bit processors.
https://mariadb.com/kb/en/innodb-purge/ seems to be covering this area. I am not sure if this bug deserves to be mentioned there.
For 10.11 and later: Setting innodb_max_undo_log_size to something larger than innodb_page_size*4294967295 would 
cause unexpected behavior or crashes when setting innodb_undo_log_truncate=ON and using innodb_undo_tablespaces>1.
For 10.6: The …
=> MDEV-33464 Crash when innodb_max_undo_log_size is set to innodb_page_size*4294967296

mysql-test/suite/innodb/r/lock_insert_into_empty.result, mysql-test/suite/innodb/t/lock_insert_into_empty.test
Problem:
=======
- innodb.log_file_name fails if it executes after innodb.lock_insert_into_empty in few cases.
innodb.lock_insert_into_empty test case failed to
cleanup the table t2. Rollback of create..select fails to remove the table when it fails to acquire the
innodb statistics table. This leads to rename table in log_file_name test case fails.
Solution:
========
- Cleanup the table t2 explictly after resetting innodb_lock_wait_timeout variable in
innodb.lock_insert_into_empty test case.
./mtr innodb.log_insert_into_empty innodb.log_file_name
=> MDEV-14193 innodb.log_file_name failed in buildbot with exception

mysql-test/suite/innodb/r/instant_alter_crash.result, mysql-test/suite/innodb/r/instant_alter_debug,dynamic.rdiff, mysql-test/suite/innodb/r/instant_alter_debug.result, mysql-test/suite/innodb/t/instant_alter_crash.test, mysql-test/suite/innodb/t/instant_alter_debug.test, storage/innobase/rem/rem0rec.cc
=> MDEV-19044  Alter table corrupts while applying the modification log

storage/innobase/buf/buf0flu.cc
`buf_flush_page_cleaner()`: Remove a loop that had originally been added in commit 9d1466522ea92963ac6ca16b597392714280c9f1 (MDEV-32029) and made redundant by commit 5b53342a6a59ae1141b2a46467954fc3836f8e80 (MDEV-32588).
Starting with commit d34479dc664d4cbd4e9dad6b0f92d7c8e55595d1 (MDEV-33053) this loop would cause a significant performance regression in workloads where `buf_pool.need_LRU_eviction()` constantly holds in `buf_flush_page_cleaner()`.
Thanks to @sm-shaw for noticing this. (Actually, also @mariadb-DebarunBanerjee had pointed out this code in the #2949 review.)
Some stress tests of …
=> MDEV-33508 Performance regression due to frequent scan of buf_pool.flush_list

mysql-test/main/mysqld_option_err.result, mysql-test/main/mysqld_option_err.test, mysys/my_getopt.c
This change makes the effort to reduce the number of server restarts required due to passing invalid options.
Previously, the behavior was to error out on the first invalid option encountered. With this change, a best effort approach is made so that all invalid options processed will be printed before exiting.
There is a caveat. The options are processed many times at varying stages of server startup because the server is not aware of all valid options immediately (e.g. plugins have to be loaded first before the server knows what are the available plugin options). So, there are some options that the server can determine are invalid "early" on, and there are some options that the server cannot determine are invalid until "later" on. For example, the server can determine an option such as …
=> MDEV-26923 Check all invalid config options

mysql-test/suite/encryption/t/encrypt_and_grep.test
- Adjust the test case to check whether all tablespaces are encrypted by comparing it with existing table count.
./mtr encryption.encrypt_and_grep
- [] *This is a new feature and the PR is based against the latest MariaDB development branch.*
=> MDEV-13765 encryption.encrypt_and_grep failed in buildbot with wrong result

mysql-test/suite/innodb_fts/r/foreign_key_update.result, mysql-test/suite/innodb_fts/t/foreign_key_update.test, storage/innobase/row/row0mysql.cc
- During update operation, InnoDB should avoid the initializing the FTS_DOC_ID of foreign table if the foreign table is discarded
./mtr innodb_fts.foreign_key_update
=> MDEV-32346  Assertion failure sym_node->table != NULL in pars_retrieve_table_def on UPDATE

mysql-test/suite/innodb/r/log_upgrade_101_flags.result, mysql-test/suite/innodb/t/log_upgrade_101_flags.test, storage/innobase/include/log0log.inl, storage/innobase/mtr/mtr0mtr.cc, storage/innobase/srv/srv0start.cc
Problem:
========
During upgrade, InnoDB does write the redo log for adjusting
the tablespace size or tablespace flags even before the log has upgraded to configured format. This could lead to data inconsistent if any crash happened during upgrade process.
Fix:
===
srv_start(): Write the tablespace flags adjustment, increased tablespace size redo log only after redo log upgradation.
log_write_low(), log_reserve_and_write_fast(): Check whether the redo log is in physical format.
./mtr innodb.log_upgrade_101_flags
=> MDEV-32445  InnoDB may corrupt its log before upgrading it on startup

storage/innobase/trx/trx0rseg.cc
Fix a scenario where `mariabackup --prepare` fails with assertion
`!m_modifications || !recv_no_log_write` in `mtr_t::commit()`. This
happens if the prepare step of the backup encounters a data directory
which happens to store wsrep xid position in TRX SYS page ( is no
longer the case since 10.3.5). And since MDEV-17458,
`trx_rseg_array_init()` handles this case by copying the xid position
to rollback segments, before clearing the xid from TRX SYS page.
However, this step should be avoided when `trx_rseg_array_init()` is
invoked from mariabackup. The relevant code was surrounded by the
condition `srv_operation == SRV_OPERATION_NORMAL`. An additional check
ensures that we are not trying to copy a xid position which has
already zeroed.
=> MDEV-33540 Avoid writes to TRX_SYS page during mariabackup operations

mysql-test/mysql-test-run.pl, mysql-test/suite/innodb/r/innodb-lru-force-no-free-page.result, mysql-test/suite/innodb/r/log_file_name.result, mysql-test/suite/innodb/t/innodb-lru-force-no-free-page.test, mysql-test/suite/innodb/t/log_file_name.test, storage/innobase/fsp/fsp0file.cc
- Suppress the "Difficult to find free blocks" warning globally to avoid many different test case failing.
- Demote the error information in validate_first_page() to note. So first page can recovered from doublewrite buffer and can throw error in case the page wasn't found in doublewrite buffer.
./mtr innodb.log_file_name innodb.innodb-lru-force-no-free-page
=> MDEV-33635 innodb.innodb-64k-crash - Found warnings/errors in server log file

cmake/cpack_rpm.cmake
Postfix on 51e3f1daf54309d14fe8db438024d88aa110e86a that mariadbd should be the executable name rather than capabilities on a symlink.
not significant
Check RPM builds and that capabilities are added on install.
=> MDEV-33636: RPM caps is on mariadbd exe

mysql-test/suite/innodb/r/innodb_bug30113362.result, storage/innobase/fsp/fsp0fsp.cc, storage/innobase/include/fsp0fsp.h, storage/innobase/row/row0import.cc
Problem:
========
- In case of large file size, InnoDB adds the new extent even though there are many existing unused pages of the segment. Reason is that in case of larger file size, threshold (1/8 of reserved pages) for adding new extent has been reached frequently.
Solution:
=========
- Try to utilise the unused pages in the segment before adding the new extent in the file segment. To achieve that, threshold can be set to larger size for larger files.
need_for_new_extent(): In case of larger file size, try to use the 4 * FSP_EXTENT_SIZE as threshold to allocate the new extent.
Test case given in description can be run against patch and check the file size.
=> MDEV-33542  Inplace algorithm occupies more disk space compared to copy algorithm

mysql-test/suite/rpl/r/rpl_semi_sync_cond_var_per_thd.result, mysql-test/suite/rpl/r/rpl_semi_sync_shutdown_await_ack.result, mysql-test/suite/rpl/t/rpl_semi_sync_cond_var_per_thd.cnf, mysql-test/suite/rpl/t/rpl_semi_sync_cond_var_per_thd.test, mysql-test/suite/rpl/t/rpl_semi_sync_shutdown_await_ack.inc, mysql-test/suite/rpl/t/rpl_semi_sync_shutdown_await_ack.test, sql/log.cc, sql/mysqld.cc, sql/semisync_master.cc, sql/semisync_master.h, sql/sql_class.cc, sql/sql_class.h
When using semi-sync replication with
rpl_semi_sync_master_wait_point=AFTER_COMMIT, the performance of the
primary can significantly reduce compared to AFTER_SYNC's
performance for workloads with many concurrent users executing
transactions. This is because all connections on the primary share
the same cond_wait variable/mutex pair, so any time an ACK is
received from a replica, all waiting connections are awoken to check
if the ACK was for itself, which is done in mutual exclusion.
This patch changes this such that the waiting THD will use its own
local condition variable, and the ACK receiver thread only signals
connections which have been ACKed for wakeup.
Additionally:
1) At master shutdown (when waiting for slaves), instead of the
main loop individually waiting for each ACK, …
=> MDEV-33551: Semi-sync Wait Point AFTER_COMMIT Slow on Workloads with Heavy Concurrency

storage/innobase/lock/lock0lock.cc
From the correctness point of view, it should be safe to release all locks on index records that were not modified by the transaction. Doing so should make the locks after `XA PREPARE` fully compatible with what would happen if the server were restarted: InnoDB table IX locks and exclusive record locks would be resurrected based on undo log records.
Concurrently running transactions that are waiting for a lock may invoke `lock_rec_convert_impl_to_expl()` to create an explicit record lock object on behalf of the lock-owning transaction so that they can attaching their waiting lock request on the explicit record lock object. Explicit locks would be released by `trx_t::release_locks()` during commit or rollback.
Any clustered index record whose `DB_TRX_ID` belongs to a transaction that is in …
=> MDEV-33454 release row locks for non-modified rows at XA PREPARE

storage/innobase/fil/fil0crypt.cc, storage/innobase/fil/fil0fil.cc
- Background encryption threads wait for stop flag to exit early from the tablespace. Alter operation fails to set the stop flag before waiting for the encryption thread to stop using the tablespace.
```
--source include/have_innodb.inc
--source include/have_sequence.inc
--source include/have_file_key_management_plugin.inc
--source include/count_sessions.inc
SET @save_threads = @@GLOBAL.innodb_encryption_threads;
SET default_storage_engine = InnoDB;
SET GLOBAL innodb_encryption_threads = 1;
create table t1(f1 int not null, f2 int not null)engine=innodb;
insert into t1 select seq, seq from seq_1_to_65536;
insert into t1 select seq, seq from seq_1_to_65536;
insert into t1 select seq, seq from seq_1_to_65536;
SET GLOBAL innodb_encrypt_tables=1;
sleep 20;
alter table t1 force, …
```
=> MDEV-33770  Alter operation hangs when encryption thread works on the same tablespace

mysql-test/main/load_timezones_with_alter_algorithm_inplace.result, mysql-test/main/load_timezones_with_alter_algorithm_inplace.test, mysql-test/main/mysql_tzinfo_to_sql_symlink.result, sql/tztime.cc
`$MYSQL_TZINFO_TO_SQL` works by truncating tables. Truncation is an operation that cannot be done in-place and therefore is fundamentally incompatible with `alter_algorithm='INPLACE'`. As a result, we override the default alter_algorithm setting in `tztime.cc` to `alter_algorithm='COPY'` so that timezones can be loaded regardless of the previously set alter_algorithm.
This is a minor bug fix and therefore does not require release notes.
- added new test to load timezones when `alter_algorithm=INPLACE` has been explicitly set.
- updated result file of existing timezone test.
- builds on numerous platforms and main mtr suite are successfully passing. …
=> MDEV-33044 Loading time zones does not work with alter_algorithm INPLACE

mysql-test/main/load_timezones_with_alter_algorithm_inplace.test
Test case doesn't work on embedded builds.
postfix to #3141
nothing
look at embedded builders.
=> MDEV-33044 Loading time zones does not work with alter_algorithm INPLACE (postfix)

.gitlab-ci.yml, support-files/mini-benchmark.sh
Enable mini-benchmark to run with perf
The mini-benchmark.sh script failed to run in the latest Fedora
distributions in GitLab CI. Executing the benchmark inside a Docker
container had failed because the check for `perf` was done in a way that
caused the benchmark to exit because of the `set -e` option. Test and
skip `perf` to allowing the remaining benchmark activities to proceed.
This check was added in acb6684 but inadvertantly reverted in 42a1f94.
Logic was corrected to only run perf when the flag is enabled, and to
prevent perf stat and perf record from being simultaneously enabled.
Set -ex is also added to enable easier identification of mini-benchmark
issues in the future.
None
This can be tested by running the automated GitLab CI. A public mirror is available at …
=> Enable mini-benchmark to run with perf

mysql-test/main/gis.result, mysql-test/suite/compat/oracle/r/gis.result, sql/share/errmsg-utf8.txt
"Operator does not exists" should rather read "Operator does not exist".
This PR fixes the error message. "Operator does not exists" should rather read "Operator does not exist".
n/a
Use the existing test suite
=> MDEV-33803 Error 4162 "Operator does not exists" is incorrectly-worded

mysql-test/suite/galera/r/MDEV-25731.result, mysql-test/suite/galera/r/galera_wan_restart_sst.result, mysql-test/suite/galera/t/MDEV-25731.test, mysql-test/suite/galera/t/galera_ist_mariabackup_verify_ca.cnf, mysql-test/suite/galera/t/galera_wan_restart_sst.test, mysql-test/suite/galera/t/rpl_galera_to_mariadb_clone_slave_using_mariadb-backup.cnf, mysql-test/suite/galera_3nodes/r/galera_allowlist.result, mysql-test/suite/galera_3nodes/t/galera_allowlist.test, mysql-test/suite/galera_3nodes_sr/r/GCF-832.result, mysql-test/suite/galera_3nodes_sr/r/galera_sr_kill_slave_before_apply.result, mysql-test/suite/galera_3nodes_sr/t/GCF-832.test, mysql-test/suite/galera_3nodes_sr/t/galera_sr_kill_slave_before_apply.test
Changes to be committed:
modified:   mysql-test/suite/galera/r/MDEV-25731.result
modified:   mysql-test/suite/galera/t/MDEV-25731.test
modified:   mysql-test/suite/galera/t/galera_ist_mariabackup_verify_ca.test
modified:   mysql-test/suite/galera_3nodes/r/galera_allowlist.result
modified:   mysql-test/suite/galera_3nodes/t/galera_allowlist.test
Consult the documentation on ["Writing good test cases"](https://mariadb.org/get-involved/getting-started-for-developers/writing- …
=> MDEV-33787 : Fix Galera test failures on 10.11

storage/innobase/include/trx0purge.h, storage/innobase/include/trx0rseg.h, storage/innobase/trx/trx0purge.cc, storage/innobase/trx/trx0rseg.cc, storage/innobase/trx/trx0trx.cc
TrxUndoRsegs is wrapper for vector of trx_rseg_t*. It has two constructors, both initialize the vector with only one element. And they are used to push transactions rseg(the singular) to purge queue. There is no function to add elements to the vector. The default constructor is used only for declaration of NullElement.
The TrxUndoRsegs was introduced in WL#6915 in MySQL 5.7 and. MySQL 5.7 would unnecessarily let the purge of history parse the temporary undo records, and then look up the table (via a global hash table), and only at the point of processing the parsed undo log record determine that the table is a temporary table and the undo record must be thrown away.
In MariaDB 10.2 we have two disjoint sets of rollback segments (128 for persistent, 128 for temporary), and purge does not …
=> MDEV-33757 Get rid of TrxUndoRsegs code

mysql-test/suite/rpl/r/rpl_mysql_manager_race_condition.result, mysql-test/suite/rpl/t/rpl_mysql_manager_race_condition.test, sql/mysqld.cc
MDEV-26473 fixed a segmentation fault at startup between the handle
manager thread and the binlog background thread, such that the
binlog background thread could be started and submit a job to the
handle manager, before it had initialized. Where MDEV-26473 made it
so the handle manager would initialize before the main thread
started the normal binary logs, it did not account for the recovery
case. That is, there is still a possibility of a segmentation fault
when a server is recovering using the binary logs such that it can
open the binary logs, start the binlog background thread, and submit
a job to the handle manager before it is initialized.
This PR is organized as follows:
1. The first commit is the regression with a test case that reproduces the issue
2. The second commit is the fix
=> MDEV-33799: mysql_manager_submit Segfault at Startup Still Possible During Recovery

include/mysql/plugin.h
Add doxygen markup so comments get picked up by more tooling. Also fix minor typos and expand documentation where relevant.
None needed
Check type hints with an IDE and/or output via doxygen.
=> Update doxygen annotations in `plugin.h`

support-files/mini-benchmark.sh
Enable configuration of CPU cycle limit for mini-benchmark
As performance improves, the permitted number of CPU cycles to be used
during the benchmark should be lowered to catch performance regressions. An
option `--cpu-limit` is added to better support this.
Additionally, there is a minor fix to the exit behavior of mini-benchmark when an error is encountered.
None
This can be tested by installing MariaDB in a docker container and executing `./support-files/mini-benchmark.sh`
=> Add cpu-limit option for mini-benchmark

storage/innobase/include/trx0undo.inl, storage/innobase/trx/trx0purge.cc, storage/innobase/trx/trx0undo.cc
In commit aa719b5010c929132b4460b78113fbd07497d9c8 (part of MDEV-32050) a bug was introduced in the function `purge_sys_t::choose_next_log()`, which reimplements some logic that previously was part of `trx_purge_read_undo_rec()`. We must invoke `trx_undo_get_first_rec()` with the page number and offset of the undo log header, but we were incorrectly invoking it on the current undo page number, which caused us to parse undo records starting at an incorrect offset.
`purge_sys_t::choose_next_log()`: Pass the correct parameter to `trx_undo_page_get_first_rec()`.
`trx_undo_page_get_next_rec()`, `trx_undo_page_get_first_rec()`, `trx_undo_page_get_last_rec()`: Add debug assertions and make the code more robust by returning `nullptr` on corruption. Should we detect any corrupted undo logs during …
=> MDEV-33819 The purge of committed history is mis-parsing some log

mysql-test/suite/innodb/r/insert_into_empty.result, mysql-test/suite/innodb/t/insert_into_empty.test, storage/innobase/handler/ha_innodb.cc, storage/innobase/include/trx0trx.h, storage/innobase/row/row0merge.cc
Reason:
- InnoDB fails to apply the buffered insert operation if the
after insert trigger does change the same table. This behaviour
leads to empty table for the subsequent insert operation and server
abort.
Solution:
========
- InnoDB should apply buffered insert operation if the after insert
trigger changes the same table.
=> MDEV-32453  Bulk insert fails to apply when trigger does insert operation

mysql-test/suite/rpl/r/rpl_gtid_header_valid.result, mysql-test/suite/rpl/t/rpl_gtid_header_valid.test, sql/log_event.cc, sql/log_event.h, sql/log_event_server.cc
A GTID event can have variable length, with a contributing factor to
the variable length being the optional extra flags field. This field
is a bitmap, where each set bit indicates an additional value that
should be appended to the event, e.g. multi-engine transactions
append a number to indicate the number of additional engines a
transaction uses. However, if the extra flags bit is set, and no
additional fields are appended to the event, the server can still
try to read from memory as if it did exist (note that in debug
builds, there is a DBUG_ASSERT condition that will cause the server
to crash).
This patch fixes this to check that the length of the event is
aligned with the expectation set by the extra flags. The is_valid()
check of a Gtid event is extended to ensure that the …
=> MDEV-33672: Gtid_log_event Construction from File Should Ensure Event Length When Using Extra Flags

mysql-test/suite/innodb/r/lock_isolation.result, mysql-test/suite/innodb/t/lock_isolation.test, storage/innobase/lock/lock0lock.cc
Even after commit b8a671988954870b7db22e20d1a1409fd40f8e3d there is an anomaly where a locking read could return inconsistent results. If a locking read would have to wait for a record lock, then by the definition of a read view, the modifications made by the current lock holder cannot be visible in the read view. This is because the read view must exclude any transactions that had not been committed at the time when the read view was created.
`lock_rec_convert_impl_to_expl_for_trx()`, `lock_rec_convert_impl_to_expl()`: Return an unsafe-to-dereference pointer to a transaction that holds or held the lock, or `nullptr` if the lock was available.
`lock_clust_rec_modify_check_and_lock()`, `lock_sec_rec_read_check_and_lock()`, `lock_clust_rec_read_check_and_lock()`: Return `DB_RECORD_CHANGED` …
=> MDEV-33802 Weird read view after ROLLBACK of another transaction

mysql-test/suite/innodb/r/instant_alter_import.result, mysql-test/suite/innodb/t/instant_alter_import.test, storage/innobase/row/row0import.cc
In commit d74d95961a31b47986d943216489513896108782 (MDEV-18543) there was an error that would cause the hidden metadata record to be deleted, and therefore cause the table to appear corrupted when it is reloaded into the data dictionary cache.
`PageConverter::update_records()`: Do not delete the metadata record, but do validate it.
`RecIterator::open()`: Make the API more similar to 10.6, to simplify merges.
After a table where instant `ALTER TABLE` that dropped or reordered columns had been imported and the server restarted, the table would no longer be accessible.
`./mtr innodb.instant_alter_import`
=> MDEV-33512 Corrupted table after IMPORT TABLESPACE and restart

storage/innobase/btr/btr0btr.cc, storage/innobase/fsp/fsp0fsp.cc, storage/innobase/fut/fut0lst.cc, storage/innobase/ibuf/ibuf0ibuf.cc, storage/innobase/include/fut0lst.h, storage/innobase/trx/trx0purge.cc, storage/innobase/trx/trx0rseg.cc, storage/innobase/trx/trx0undo.cc
`flst_read_addr()`: Remove assertions. Instead, we will check these conditions in the callers and avoid a crash in case of corruption. We will check the conditions more carefully, because the callers know more exact bounds for the page numbers and the byte offsets withing pages.
In the following functions, the assertions will be removed without replacement: `flst_insert_after()`, `flst_insert_before()`, `flst_add_last()`, `flst_add_first()`, `flst_remove()`. These functions insert or delete items in the doubly linked list of pages. There are debug assertions for validating the input. We may copy corrupted pointers from existing list nodes. Corruption will be noticed when the lists are being read.
This code is covered basically by all InnoDB regression tests. Some additional stress testing …
=> MDEV-33325 Crash in flst_read_addr on corrupted data

mysql-test/suite/galera/r/galera_sst_mariabackup,debug.rdiff, mysql-test/suite/galera/r/galera_sst_mariabackup.result, mysql-test/suite/galera/t/galera_sst_mariabackup.cnf, mysql-test/suite/galera/t/galera_sst_mariabackup.test, storage/innobase/trx/trx0rseg.cc
Before MDEV-15158, wsrep xid information was stored in only one place: in the TRX_SYS page. Starting with 10.3, it is not stored there but in the rollback segment header pages, and the latest one is what matters. MDEV-19229 allows the undo tablespaces to be rebuilt when innodb_undo_tablespaces is changed on startup. Previously it was not possible to change that parameter.
These changes caused the fact that rollback segment header pages could contain several wsrep xid's storead and when undo tablespaces were rebuilt there was a effort to restore wsrep xid back to rollback segment header page but because there was several of them the latest wsrep xid was overwritten with more older one.
trx_rseg_read_wsrep_checkpoint
trx_rseg_init_wsrep_xid
Return true if read xid is wsrep xid, false if not …
=> MDEV-32974 : Member fails to join due to old seqno in GTID

tests/upgrade_from/test_upgrade.sh
Update the URLs in two places in the tests/upgrade_from/test_upgrade.sh script.
* boost-program-options dependency points to
archives.fedoraproject.org
* gpgkey for the MariaDB rpm repository points to
archive.mariadb.org/PublicKey
This ensures that the upgrade testing run in .gitlab-ci.yml continues to
function and refers to the correct GPG key.
None, minor fix, no change in functionality
Start a Docker image
```
docker run --rm -w /mariadb/ -v $(pwd):/mariadb/ -it fedora:latest bash
```
Inside docker
```
[root@fb7e29abd0ac mariadb]# ./tests/upgrade_from/test_upgrade.sh 10.5 10.6
```
=> Update URLs in test_upgrade script

mysql-test/main/func_kdf.result, mysql-test/main/func_kdf.test, sql/item_create.cc
- When there is no parameter item_list is NULL.
- This code checks if item_list is NULL before setting arg_count to item_list->elements.
Fix system crash when KDF() was called without parameters.
This function was added to MariaDB in 11.3 (see https://github.com/MariaDB/server/commit/4f9396b9f80031120f325d54f06d346dea7f1bfb and https://mariadb.com/kb/en/kdf) and did not exist in earlier major versions.
```sh
./mtr main.func_kdf
```
=> MDEV-33659 Fix crash in kdf() without parameters

mysql-test/suite/innodb/r/insert_into_empty.result, mysql-test/suite/innodb/t/insert_into_empty.test, storage/innobase/row/row0merge.cc
- This issue is caused by commit 188c5da72a0057e4572b1d7e4efcd0c39332a839 (MDEV-32453). InnoDB fails to end the bulk insert for the table after applying the bulk insert operation. This leads to assertion during commit process.
=> MDEV-33868 Assertion `trx->bulk_insert' failed in innodb_prepare_commit_versioned

storage/innobase/gis/gis0sea.cc, storage/innobase/include/gis0type.h, storage/innobase/include/mtr0log.h, storage/innobase/row/row0sel.cc
Related to `SPATIAL INDEX` search (see [MDEV-14059](https://jira.mariadb.org/browse/MDEV-14059)), InnoDB is allocating additional blocks to store some results. These blocks look like buffer pool blocks, but they are in fact allocated outside the buffer pool for no good reason, potentially causing memory fragmentation. It would be cleaner to make `matched_rec::block` a pointer to something that is returned by `buf_block_alloc()`. This would allow us in [MDEV-29445](https://jira.mariadb.org/browse/MDEV-29445) to remove the frame pointer from the block descriptor.
`matched_rec::rec_buf[]`, `matched_rec::bufp`: Remove.
`matched_rec::block`: Make this a pointer to something that is allocated by `buf_block_alloc()`. In this way, the only case where `buf_block_t` is constructed outside …
=> MDEV-33559 matched_rec::block should be allocated from the buffer pool

sql/sql_class.h, sql/sql_lex.cc, sql/sql_parse.cc, sql/table.cc, sql/table.h
Ideally our methods and functions should do one thing, do that well, and do only that.  add_table_to_list does far more than adding a table to a list, so this commit factors the TABLE_LIST creation out to a new TABLE_LIST constructor.  It then uses placement new() to create it in the correct memory area (result of thd->calloc). Benefits of this approach:
1. Method add_table_to_list now returns as early as possible on an error
2. Fewer side-effects incurred on creating the TABLE_LIST object
3. TABLE_LIST won't be calloc'd if copy_to_db fails
4. Local declarations moved closer to their respective first uses
5. Improved code readability and logical flow: factored a couple of other functions to keep the happy path more to the left, which makes them easier to follow at a glance.
=> Factor TABLE_LIST creation from add_table_to_list

mysql-test/suite/galera_sr/t/MDEV-25718.test
Test was waiting INSERT-clause to make rollback but wait_condition was too tight. State could be
Freeing items or Rollback. Fixed wait_condition to expect one of them.
- [ x] *This is a bug fix and the PR is based …
=> MDEV-33895 : Galera test failure on galera_sr.MDEV-25718

storage/innobase/gis/gis0sea.cc
`rtr_pcur_getnext_from_path()`: Remove a debug assertion that suffers from a data race with `buf_LRU_block_free_non_file_page()`.
No mention is needed, because this is only removing a bogus debug assertion.
Repeatedly run `./mtr innodb_gis.rtree_compress` in a MemorySanitizer instrumented build.
=> MDEV-33855 MSAN use-of-uninitialized-value in rtr_pcur_getnext_from_path()

mysql-test/main/ignored_index.result, mysql-test/main/partition_icp.result, mysql-test/main/partition_icp.test, mysql-test/main/partition_mrr_aria.result, mysql-test/main/partition_mrr_innodb.result, mysql-test/main/partition_mrr_myisam.result, mysql-test/main/partition_pruning.result, sql/ha_partition.cc, sql/ha_partition.h, storage/example/ha_example.cc, storage/rocksdb/mysql-test/rocksdb/r/rocksdb_cf_per_partition.result
MDEV-12404 Index condition pushdown on partitioned tables
Support index condition pushdown within partitioned tables.
- ha_partition will pass the pushed index condition into all of the used
partitions.
- We require that all of the partitions to handle the pushed index
condition in the same way.
- When using ICP, one may read rows (e.g. call h->index_read_map(buf, ...)
only to buf= table->record[0], for two reasons:
* Pushed index condition's Item_field objects point into record[0]
* InnoDB requires this: it calls offset() which assumes record[0].
So, when using ICP, ha_partition will read partition records to
table->record[0] and then will copy record away if it needs it to be
elsewhere.
=> MDEV-12404 Index condition pushdown on partitioned tables

mysql-test/suite/rpl/r/rpl_skip_error.result, mysql-test/suite/rpl/r/rpl_temporary_error2_skip_all.result, mysql-test/suite/rpl/t/rpl_skip_error.test, mysql-test/suite/rpl/t/rpl_temporary_error2.test, mysql-test/suite/rpl/t/rpl_temporary_error2_skip_all-slave.opt, mysql-test/suite/rpl/t/rpl_temporary_error2_skip_all.test, sql/log_event_server.cc
If replicating an event in ROW format, and InnoDB detects a deadlock
while searching for a row, the row event will error and rollback in
InnoDB and indicate that the binlog cache also needs to be cleared,
i.e. by marking thd->transaction_rollback_request. In the normal
case, this will trigger an error in Rows_log_event::do_apply_event()
and cause a rollback. During the Rows_log_event::do_apply_event()
cleanup of a successful event application, there is a DBUG_ASSERT in
log_event_server.cc::rows_event_stmt_cleanup(), which sets the
expectation that thd->transaction_rollback_request cannot be set
because the general rollback (i.e. not the InnoDB rollback) should
have happened already. However, if the replica is configured to skip
deadlock errors, the rows event logic will clear the error …
=> MDEV-27512: Assertion !thd->transaction_rollback_request failed in rows_event_stmt_cleanup

storage/innobase/btr/btr0pcur.cc, storage/innobase/ibuf/ibuf0ibuf.cc, storage/innobase/include/btr0pcur.h, storage/innobase/include/ibuf0ibuf.h, storage/innobase/srv/srv0srv.cc
When the change buffer records for a page span across multiple change buffer leaf pages or the starting record is at the beginning of a page with a left sibling, ibuf_delete_recs deletes only the records in first page and fails to move to subsequent pages.
Subsequently a slow shutdown hangs trying to delete those left over records.
Fix-A: Position the cursor to an user record in B-tree and exit only when all records are exhausted.
Fix-B: Make sure we call ibuf_delete_recs during slow shutdown for pages with IBUF entries to cleanup any previously left over records.
None
RQG test as done by the filer.
It is possible to repeat the issue with good predictability with somewhat complex mtr test, 4k page size and some code modification to force certain path. Otherwise we need multiple large …
=> MDEV-32489 Change buffer index fails to delete the records

mysql-test/suite/innodb/r/insert_into_empty.result, mysql-test/suite/innodb/t/insert_into_empty.test, storage/innobase/row/row0merge.cc
This issue is caused by commit 188c5da72a0057e4572b1d7e4efcd0c39332a839 (MDEV-32453).
trx_t::bulk_insert_apply_for_table(): Remove the assert check_unique_secondary and check_foreigns. InnoDB can apply the bulk insert operation even after disabling the check_foreigns and check_unique_secondary variable.
This change avoids debug assert failure during bulk insert operation.
=> MDEV-33934   Assertion `!check_foreigns' failed in bulk_insert_apply_for_table(dict_table_t*)

strings/ctype-uca.c
This fixes cmake-based builds with -DWITH_EXTRA_CHARSETS=none, which results in a CHARSETS list that does _not_ include ucs2, utf16, or utf32.
"Building with CMake and -DWITH_EXTRA_CHARSETS=none now works"
Compiling with cmake with -DWITH_EXTRA_CHARSETS=none.
Erm well... the contributing info says to target the "master branch" but no such thing exists, so I targeted the current default branch (11.5 as of this writing). However, the problem exists in all previous version branches as well (I was trying to compile 10.11).
=> fix build with WITH_EXTRA_CHARSETS=none in cmake

extra/mariabackup/encryption_plugin.cc, mysql-test/suite/mariabackup/encrypted_export.opt, mysql-test/suite/mariabackup/encrypted_export.result, mysql-test/suite/mariabackup/encrypted_export.test
Problem:
========
mariabackup --prepare fails to write the pages in encrypted format. This issue happens only for default encrypted table when innodb_encrypt_tables variable is enabled.
Fix:
====
backup process should write the value of innodb_encrypt_tables variable in configuration file. prepare should enable the variable based on configuration file.
./mtr mariabackup.encrypted_export
=> MDEV-33334  mariabackup does not always write encrypted files to backup location

mysql-test/suite/compat/oracle/r/sp-inout.result, mysql-test/suite/compat/oracle/t/sp-inout.test
compat/oracle.sp-inout now uses lowercase object names for test compatibility with both case-insensitive and case-sensitive filesystems.
=> MDEV-33616 Tests failing on macOS

mysql-test/suite/innodb/r/insert_into_empty.result, mysql-test/suite/innodb/t/insert_into_empty.test, storage/innobase/handler/ha_innodb.cc, storage/innobase/row/row0ins.cc
Problem:
========
- Partition update operation enables the bulk insert for the transaction while moving the row between partitions. This leads to debug assert failure while removing the row from one of the partition.
Solution:
========
- Disallow the bulk insert operation for non-insert operation of partition table.
=> MDEV-33979 Disallow bulk insert operation during partition update statement

client/mysqlbinlog.cc
Previously, when running mysqlbinlog without providing a binlog file, it would print the entire help text, which was very verbose and made it difficult to identify the actual issue.
Now change the behavior to print a more concise error message instead:
"ERROR: Please provide the log file(s). Run with '--help' for usage instructions."
This makes the error output more user-friendly and easier to understand, especially when running the tool in scripts or automated processes.
What should the release notes say about this change?
- I think this minor change does not need to be included in the release notes. Or simply say "Concise error message when no binlog file is provided. (MDEV-33574)"
The change includes error message change only, no MTR needed.
Instead of displaying the previous 200+ line …
=> MDEV-33574 Improve mysqlbinlog error message

mysql-test/suite/innodb/r/index_length.result, mysql-test/suite/innodb/t/index_length.test, storage/innobase/btr/btr0cur.cc
Problem:
========
- InnoDB wrongly calulates the record size in btr_node_ptr_max_size() when prefix index of
the column has to be stored externally.
Fix:
====
- InnoDB should add the maximum field size to record size when the field is a fixed length one.
./mtr innodb.innodb-index
=> MDEV-22855 Assertion `!field->prefix_len || field->fixed_len == field->prefix_len` failed in btr_node_ptr_max_size

CMakeLists.txt
The cmake WITHOUT_SERVER option excludes a non-existent component `SuportFiles` (note: single "p").
Assuming this is a typo, component `SupportFiles` (note: double "p") does exist .
WITHOUT_SERVER fixed to exclude SupportFiles components.
=> Fix typo in components for WITHOUT_SERVER

mysql-test/suite/mariabackup/undo_space_id.result, mysql-test/suite/mariabackup/undo_space_id.test, storage/innobase/os/os0file.cc, storage/innobase/srv/srv0start.cc
Problem:
========
- Currently mariabackup have to reread the pages in case they are modified by server concurrently. But while reading the undo tablespace, mariabackup failed to do reread the page in case of error.
Fix:
===
Mariabackup --backup functionality should have retry logic while reading the undo tablespaces.
./mtr mariabackup.undo_space_id
=> MDEV-33980  mariadb-backup --backup is missing retry logic for undo tablespaces

mysql-test/suite/innodb/r/row_size_error_log_warnings_3,4k.rdiff, mysql-test/suite/innodb/r/row_size_error_log_warnings_3.result, mysql-test/suite/innodb/t/row_size_error_log_warnings_3.test, storage/innobase/handler/handler0alter.cc
Problem:
=======
During InnoDB non-rebuild online alter operation, InnoDB set the dummy log to clustered index online log. This can be used by concurrent DML to identify whether the table undergoes online DDL. InnoDB fails to reset the dummy log of clustered index in case of error happened during prepare phase.
Solution:
========
Reset the InnoDB clustered index online log in case of error during prepare phase.
./mtr innodb.row_size_error_log_warnings_3
=> MDEV-31161 Assertion failures upon adding a too long key to table with COMPRESSED row

extra/mariabackup/xtrabackup.cc, mysql-test/suite/mariabackup/backup_grants.result, mysql-test/suite/mariabackup/backup_grants.test
MariaDB-backup needs to check for SLAVE MONITOR as that is what is returned by SHOW GRANTS.
Update test to ensure that warnings about missing privileges do not occur when the backup is successful.
Thanks Eugene for reporting the issue.
Remove erroneous MariaDB-Backup warnings about required privileges
=> MDEV-34053 mariadbbackup privilege REPLICA MONITOR issue

mysql-test/suite/innodb/r/temporary_table.result, mysql-test/suite/innodb/t/temporary_table.test, storage/innobase/fsp/fsp0fsp.cc
`fsp_alloc_free_extent()` failed to set `*err = DB_OUT_OF_FILE_SPACE` when the tablespace is full.
InnoDB could fail to report `ER_RECORD_FILE_FULL` when running out of space.
```sh
./mtr innodb.temporary_table,4k
```
This is a bug fix that depends on earlier refactoring in MariaDB Server 10.6.
=> MDEV-34118 fsp_alloc_free_extent() fails to flag DB_OUT_OF_FILE_SPACE

sql/sql_select.cc
Alternative operator name keywords like `and`, `or`, `xor`, etc., are uncommon in MariaDB and can cause obscure build errors when the GCC flag `-fno-operator-names` is applied.
Description of `-fno-operator-names`:
https://gcc.gnu.org/onlinedocs/gcc/C_002b_002b-Dialect-Options.html
> Do not treat the operator name keywords `and`, `bitand`, `bitor`, `compl`, `not`, `or` and `xor` as synonyms as keywords.
Part of the build errors:
/local/p4clients/pkgbuild-LdLa_/workspace/src/RDSMariaDB/sql/sql_select.cc:11171:28: error: expected ‘)’ before ‘and’
11171 |     DBUG_ASSERT(sel >= 0.0 and sel <= 1.00001);
|                            ^~~
/local/p4clients/pkgbuild-LdLa_/workspace/src/RDSMariaDB/include/my_global.h:372:44: note: in definition of macro ‘unlikely’
372 | #define unlikely(x) …
=> MDEV-34112 Replace one operator name keyword

storage/innobase/mtr/mtr0mtr.cc
- InnoDB can print the wrong warning message  like "shutdown is in progress" even though InnoDB is in normal
condition. InnoDB should print the warning message saying "Shutdown is in progress" only when shutdown state is greater than SRV_SHUTDOWN_INITIATED.
=> MDEV-34175 mtr_t::log_close() warning should change the shutdown condition

mysql-test/suite/innodb/r/xa_recovery.result, mysql-test/suite/innodb/t/xa_recovery.test, storage/innobase/trx/trx0trx.cc
`trx_free_at_shutdown()`: Similar to `trx_t::commit_in_memory()`, clear the detailed_error (`FOREIGN KEY` constraint error) before invoking `trx_t::free()`. We only do this on debug instrumented builds in order to avoid a debug assertion failure on shutdown.
Nothing. This was a bogus debug assertion failure.
```sh
./mtr innodb.xa_recovery
```
=> MDEV-34204 Assertion `!*detailed_error' failed on shutdown after XA PREPARE

mysql-test/suite/innodb/r/lock_memory_debug.result, mysql-test/suite/innodb/t/lock_memory_debug.opt, mysql-test/suite/innodb/t/lock_memory_debug.test, storage/innobase/buf/buf0flu.cc, storage/innobase/lock/lock0lock.cc
BUF_LRU_MIN_LEN (256) is too high value for low buffer pool(BP) size. For example, for BP size lower than 80M and 16 K page size, the limit is more than 5% of total BP and for lowest BP 5M, it is 80% of the BP. Non-data objects like explicit locks could occupy part of the BP pool reducing the pages available for LRU. If LRU reaches minimum limit and if no free pages are available, server would hang with page cleaner not able to free any more pages.
Fix: To avoid such hang, we adjust the LRU limit lower than the limit for data objects as checked in buf_LRU_check_size_of_non_data_objects() i.e. one page less than 5% of BP.
This could happen in rare case with BP size < 80M. Too many lock objects created with UPDATE, DELETE, INSERT INTO SELECT from same TABLE with queries over large range in …
=> MDEV-34166 Server could hang with BP < 80M under stress

mysys/crc32/crc32c_x86.cc
According to https://discussions.apple.com/thread/8256853 an attempt to use AVX512 registers on macOS will result in `#UD` (crash at runtime).
The AVX512 intrinsic functions may also be unavailable on Apple Xcode, at least in a version that is based on clang 10.
Furthermore, starting with clang-18 and GCC 14, we must add `evex512` to the target flags. We might also write avx10.1-512, but it could enable some AVX512 flags that we do not have any CPUID check for.
Nothing; macOS on x86 is not an officially supported platform, and GCC 14 and clang-18 probably are not in any stable operating system distribution yet.
See #3195.
=> MDEV-33817 fixup: Disable for macOS

storage/innobase/handler/ha_innodb.cc
`innobase_end()`: Do not attempt to shrink the system tablespace if `innodb_read_only=ON` or `innodb_force_recovery>4`. This fixes a regression due to commit 2d6c2f22a4f9844db45d66e063fbf9314889eb1b (MDEV-32452).
On shutdown with `innodb_fast_shutdown=0`, InnoDB would attempt to write to the system tablespace even though it is supposed to be read-only due to the `innodb_read_only` or `innodb_force_recovery` settings.
This bug was caught when testing #3272, which adds `SET GLOBAL innodb_fast_shutdown=0` to the test `innodb.undo_upgrade`. The failure is sporadic; I repeated it for `innodb.undo_upgrade,64k` on a MemorySanitizer instrumented build.
=> MDEV-34209 InnoDB is disregarding read-only mode on slow shutdown

mysql-test/suite/innodb/r/row_format_redundant.result, mysql-test/suite/innodb/r/undo_upgrade.result, mysql-test/suite/innodb/t/row_format_redundant.test, mysql-test/suite/innodb/t/table_flags.test, mysql-test/suite/innodb/t/undo_upgrade.test, storage/innobase/buf/buf0dblwr.cc, storage/innobase/srv/srv0start.cc
- InnoDB fails to set the TRX_SYS_DOUBLEWRITE_SPACE_ID_STORED flag in transaction system header page while recreating the undo log tablespaces
buf_dblwr_t::init_or_load_pages(): Tries to reset the space id and try to write into doublewrite buffer even when read_only mode is enabled.
In srv_all_undo_tablespaces_open(), InnoDB should try to open the extra unused undo tablespaces instead of trying to creating it.
./mtr innodb.undo_upgrade --mem
=> MDEV-34200 InnoDB tries to write to read-only system tablespace in buf_dblwr_t::init_or_load_pages()

storage/innobase/mtr/mtr0mtr.cc
This bug was found related to MDEV-34212 and #3277.
Some InnoDB tests, most notably `innodb.table_flags,64k` would occasionally fail. I am able to reproduce this locally on a MemorySanitizer build, sporadically.
This bug was revealed due to the recent commit 466ae1cf81f54b729058357bb19c4cf3982e1367 which set `innodb_fast_shutdown=0` during server bootstrap in our regression test driver.
Due to the bug, a write of undo page 50 in the system tablespace was discarded in `buf_page_t::flush()`. A subsequent InnoDB startup failed because an old version of that page would point to a freed undo log page 300.
`mtr_t::commit_shrink()`: Only invoke `fil_space_t::set_create_lsn()` on undo tablespaces, which will be fully reinitialized or created from the scratch. On the system tablespace, we must …
=> MDEV-34216 Possible corruption when shrinking the system tablespace on innodb_fast_shutdown=0

sql/item_strfunc.cc
Upstream libfmt commit https://github.com/fmtlib/fmt/commit/d70729215fba1d54862e407b626abf86ddf409bf now requires the format function to be const.
Adjust the function prototype so it is const and can compile.
Not important
Compile with master version of libfmt
=> MDEV-34206 compile failure: fmt use incompatible with libfmt-10.2.[2]+

storage/innobase/buf/buf0buf.cc, storage/innobase/include/buf0buf.h, storage/innobase/log/log0recv.cc, storage/innobase/trx/trx0undo.cc
Starting with [MDEV-32042](https://jira.mariadb.org/browse/MDEV-32042), we assume that the function `buf_page_get_gen()` is not being invoked while log is being applied during crash recovery. The idea is that any access to buffer pool pages during crash recovery must look up pages via `recv_sys_t::recover()`. This was being violated by the function `trx_undo_mem_create_at_db_start()` during startup.
`trx_undo_mem_create_at_db_start()`: Invoke `recv_sys_t::recover()` instead of `buf_page_get_gen()`, so that all undo log pages will be recovered correctly. Failure to do this could prevent InnoDB from starting up due to `Data structure corruption`, or it could potentially lead to a situation where InnoDB starts up but some transactions were recovered incorrectly.
`recv_sys_t::recover()`: Only …
=> MDEV-34212 InnoDB transaction recovery is incorrect

mysql-test/suite/innodb/r/undo_space_dblwr.result, mysql-test/suite/innodb/t/undo_space_dblwr.test, storage/innobase/srv/srv0start.cc
- InnoDB should avoid printing the error message before restoring the first page from doublewrite buffer.
=> MDEV-34221  Errors about checksum mismatch on crash recovery are confusing

scripts/mysql_install_db.sh
This avoids checking for resolveip if it won't be used by using the same conditional used before deciding to execute resolveip. I ran into this while reducing mariadb's installation footprint.
Install without resolveip?
Eh I'm not really sure which one this falls under.
=> don't require resolveip if it won't be used

mysql-test/suite/innodb/r/temp_truncate_freed.result, mysql-test/suite/innodb/t/temp_truncate_freed.test, storage/innobase/fsp/fsp0fsp.cc
InnoDB fails with out of bound write error after temporary
tablespace truncation. InnoDB fail to clear freed ranges
if shrinking size is the last offset of the freed range.
./mtr innodb.temp_truncate_freed
=> MDEV-34256 InnoDB throws out of bound write due to temporary tablespace truncation

man/myisamchk.1, man/mysql_upgrade.1, man/mysqladmin.1, man/mysqlbinlog.1, man/mysqlcheck.1, man/mysqld_safe.1, man/mysqldump.1
Few man pages have less standard format directive: `.it 1 an-trap` which specifying a formatting instruction related to indentation (adds tab in man page in this)
There is no traces what an-trap should do and removing it does not affect rendering of man page
There should be any mention this on release notes
One can render these man pages as ascii with
```
groff -man -Tascii man/mysqlbinlog.1
groff -man -Tascii man/mysqldump.1
groff -man -Tascii man/mysqladmin.1
groff -man -Tascii man/mysqlcheck.1
groff -man -Tascii man/myisamchk.1
groff -man -Tascii man/mysqld_safe.1
groff -man -Tascii man/mysql_upgrade.1
```
Diff old and new should be the same
=> MDEV-33919: Remove less standard format directive an-trap

include/my_rdtsc.h, storage/innobase/include/sync0arr.inl, storage/innobase/include/ut0counter.h
The shared counter template `ib_counter_t` uses the function `my_timer_cycles()` as a source of pseudo-random numbers to pick a shard. On some platforms, `my_timer_cycles()` could return the constant value 0.
`get_rnd_value()`: Remove.
`my_pseudo_random()`: Implement as an alias of `my_timer_cycles()` or a wrapper for `pthread_self()`.
This is a minor performance improvement, not worth mentioning.
For example, disassemble the function `sync_array_print_innodb` and observe that a call to `pthread_self` is present prior to this fix and absent after this fix (unless you happen to compile for a rare operating system and ISA).
=> MDEV-34297 get_rnd_value() of ib_counter_t is unnecessarily complex

debian/autobake-deb.sh
When building on 64-bit kernel machine in 32-bit docker container CMake falsely (but it works as expected) detects that  container runtime in also 64-bits. Use linux32 command to change runtime environment to 32-bit and then CMake will  correctly disable for example ColumnStore and not try to build it
This commit only works with debian/autobake-debs.sh
Should add nothing as this brings back i386 building in 11.5 and above
This is bit difficult to test as problem start to rise after 11.5. They have `__int128` which is not supported and probably won't be supported in i386 environment. But basics is that have i386 container and launch it with `docker run -it quay.io/mariadb-foundation/bb-worker:debian12-386 bash`. Then try to compile with `debian/autobake-debs.sh`
=> MDEV-34261: Detect if build is running under 32-bit container

mysql-test/mysql-test-run.pl
mtr launches mariadb-test (mysqltest) a few times during the single test run: one known extra run happens before the test, this stage is known as check-testcase. 
This client run is not debug-ready, though. The failure happens very early, then one may need to debug the first client run.
The submitted approach invokes check-testcase client, if `--client-{debugger}` is specified.
The best way to test it is to add abort() to mysqltest.cc:main().
This is a test framework improvement, it should be pushed to the earliest maintained version.
=> mtr: run check-testcase client process under debugger

mysql-test/suite/innodb/r/insert_into_empty.result, mysql-test/suite/innodb/t/insert_into_empty.test, storage/innobase/buf/buf0flu.cc, storage/innobase/buf/buf0lru.cc
When checkpoint age goes beyond the sync flush threshold and buf_flush_sync_lsn is set, page cleaner enters into "furious flush" stage to aggressively flush dirty pages from flush list and pull checkpoint LSN above safe margin. In this stage, page cleaner skips doing LRU flush and eviction.
In 10.6, all other threads entirely rely on page cleaner to generate free pages. If free pages get over while page cleaner is busy in "furious flush" stage, a session thread could wait for free page in the middle of a min-transaction(mtr) while holding latches on other pages.
It, in turn, can prevent page cleaner to flush such pages preventing checkpoint LSN to move forward creating a deadlock situation. Even otherwise, it could create a stall and hang like situation for large BP with plenty of dirty …
=> MDEV-34265 Possible hang during IO burst with innodb_flush_sync enabled

storage/innobase/buf/buf0buf.cc
`buf_pool_invalidate()`: Properly wait for `os_aio_wait_until_no_pending_writes()` to ensure so that there are no pending `buf_page_t::write_complete()` or `buf_page_write_complete()` operations. This will avoid a failure of `buf_pool.assert_all_freed()`.
This bug should affect debug builds only. At this point, the `buf_pool.flush_list` should be clear and all changes should have been written out. The loop around `buf_LRU_scan_and_free_block()` should have eventually completed and freed all pages as soon as `buf_page_t::write_complete()` had a chance to release the page latches.
This regression was introduced in a55b951e6082a4ce9a1f2ed5ee176ea7dbbaf1f2.
This only fixes a debug check and should have no impact on actual operations.
This was found while testing #3282, running `mariadb-backup …
=> MDEV-34307 On startup, [FATAL] InnoDB: Page ... still fixed or dirty

storage/innobase/btr/btr0cur.cc
`btr_cur_t::search_leaf()`: Invoke `btr_cur_need_opposite_intention()` after positioning `page_cur.rec` so that the record will be in the intended page. This is something that was broken in f2096478d5750b983f9a9cc4691d20e152dafd4a or de4030e4d49805a7ded5c0bfee01cc3fd7623522 or related changes.
In extremely rare cases, InnoDB could hang due to a mispredicted page split or merge.
`./mtr innodb.temp_table_savepoint` and many other tests cover this.
=> MDEV-34283 A misplaced btr_cur_need_opposite_intention() check may fail to prevent hangs

storage/innobase/buf/buf0buf.cc, storage/innobase/buf/buf0rea.cc, storage/innobase/handler/ha_innodb.cc, storage/innobase/include/mariadb_stats.h
In commit 99bd22605938c42d876194f2ec75b32e658f00f5 (MDEV-31558) we wrongly thought that there would be minimal overhead for accessing a thread-local variable `mariadb_stats`.
It turns out that in C++11, each access to an `extern thread_local` variable requires conditionally invoking an initialization function. In fact, we do have a custom initializer of this very variable, and that call is actually unavoidable.
In C++20, one could declare `constinit thread_local` variables, but the address of a `thread_local` variable (`&mariadb_dummy_stats`) is not a compile-time constant. We did not want to declare `mariadb_dummy_stats` without `thread_local`, because then the dummy accesses could lead to cache line contention between threads.
`mariadb_stats`: Declare as `__thread` or …
=> MDEV-34296 extern thread_local is a CPU waste

mysql-test/suite/innodb/r/open_files_limit.result, mysql-test/suite/innodb/t/open_files_limit.opt, mysql-test/suite/innodb/t/open_files_limit.test, storage/innobase/handler/ha_innodb.cc
- InnoDB only closes the user tablespace when the number of open files exceeds innodb_open_files limit. In that case, InnoDB should make sure that innodb_open_files value should be greater than number of undo tablespace, system and temporary tablespace.
./mtr innodb.open_files_limit
=> MDEV-34169 Don't allow innodb_open_files to be lesser than number of non-user tablespace

client/mysql_plugin.c, client/mysqltest.cc, include/m_string.h
The `strncpy()` wrapper that was introduced in 567b68129943a1cceab1d7b4c68e2a4ba011cdc0 is checking whether the output was truncated even in cases where the caller does not care about it.
Let us introduce a separate function `safe_strcpy_truncated()` that indidates whether the output was truncated.
Nothing needed; this is a minor performance improvement.
This is low-level code, covered by `mtr`.
Note: The program `client/mariadb-plugin` is apparently not covered by `mtr` at all. I didn’t get any failures after injecting an `abort()` to the start of its `main()` function.
I suspect that will be no `-Wstringop-truncation` issued for this revised `safe_strcpy()`. Whether there will be one for the `safe_strcpy_truncated()` on GCC 8 through 12, we will soon find out in the CI run.
=> MDEV-34266 safe_strcpy() includes an unnecessary conditional branch

sql/mysqld.cc
MDEV-34129 mariadb-install-db appears to hang on macOS
Immediately close down the signal handler loop when we decide to
break connections as it's the start of process termination
anyway, and there's no need to wait once we've invoked break_connections.
=> MDEV-34129 mariadb-install-db appears to hang on macOS

storage/innobase/fsp/fsp0fsp.cc
- InnoDB ignores the error while traversing the used extents during shrinking process. This could
to corrupt the tablespace.  
InnoDB shrinking process handles the error condition while traversing the extents.
=> MDEV-34374 Shrinking tablespace logic fails to handle error condition

extra/perror.c, mysql-test/main/perror-win.result, mysql-test/main/perror.result
As all server errors have a dedicated webpage, the perror utility is extended to print a link to the KB page of the corresponding error.
N/A
The test `main.perror` was updated to include the links printed by the sample tests. All tests are confirmed to pass by running the command `./mtr --suite=main`.
=> MDEV-34168: Extend perror utility to print link to knowledge page

man/mariadbd-safe.1, scripts/mysqld_safe.sh
- Add `mariadbd_safe` to be used as an option group in my.cnf
- Update man page.
=> MDEV-33618: add mariadbd_safe to option groups

storage/innobase/include/srw_lock.h, storage/innobase/include/sux_lock.h, storage/innobase/sync/srw_lock.cc
Performance testing conducted by @mdcallag identified multiple scalability bottlenecks around the spin loop logic for `buf_page_t::lock`. It also suggests that we might better enable spin loops also for `dict_index_t::lock`.
Performance of I/O bound workloads was improved.
I think that this is best tested by @mdcallag. Enabling the spin loops for `index_lock` (79039bdc6f028c86355f0045c70dc3b7c97e05aa) may be turn out to be unnecessary in the advent of the other changes.
This is low-level code, and it is in part covered by by the `innodb_sync-t` unit test. I ran it (as well as the entire regression test suite) for both `PLUGIN_PERFSCHEMA=NO`  and `PLUGIN_PERFSCHEMA=STATIC`.
=> MDEV-34178 Performance regression with IO-bound insert benchmark

mysql-test/suite/innodb/r/log_file_overwrite.result, mysql-test/suite/innodb/t/log_file_overwrite.test, storage/innobase/log/log0recv.cc
- InnoDB tries to write FILE_CHECKPOINT marker when log file size is insufficient. This could corrupt the
log file and make it unrecoverable.
recv_recovery_From_checkpoint_start(): Before writing FILE_CHECKPOINT marker, check whether
we have sufficient log file capacity
Pasted the test case in MDEV page.
=> MDEV-34389  Don't write FILE_CHECKPOINT during recovery when log file is insufficient

mysql-test/suite/binlog/t/binlog_recover_checksum_error.test, mysql-test/suite/galera_3nodes/t/MDEV-29171.test, mysql-test/suite/innodb/r/innodb_buffer_pool_fail.result, mysql-test/suite/innodb/r/recovery_memory,debug.rdiff, mysql-test/suite/innodb/t/alter_copy.test, mysql-test/suite/innodb/t/innodb_buffer_pool_fail.test, mysql-test/suite/innodb/t/recovery_memory.test
- Few of test case should make sure that InnoDB does hit the debug sync point during startup of the server. InnoDB can remove the double quotes of debug point in restart parameters.
./mtr innodb.innodb_buffer_pool_fail innodb.alter_copy innodb.recovery_memory
=> MDEV-34435 Increase code coverage for debug_dbug test case during startup

storage/innobase/handler/ha_innodb.cc
`ha_innobase::info_low()`: For `HA_STATUS_VARIABLE` without `HA_STATUS_VARIABLE_EXTRA`, let us avoid unnecessary and costly updates of the `data_free` or `delete_length` statistics, which are only needed for `SHOW TABLE STATUS`. This optimization had been enabled in 247ecb7597015d02a93732373c742e0c8bd8fc73 but not utilized until now.
This is a minor performance improvement that is not worth mentioning.
`sysbench` with flame graphs.
Note that in the `./mtr` regression test suite, this data is often being masked. The following will report a nonzero `Data_free`:
```diff
diff --git a/mysql-test/suite/innodb/t/default_row_format_create.test b/mysql-test/suite/innodb/t/default_row_format_create.test
index 534a7312620..62a91624c77 100644
--- …
```
=> MDEV-34443 ha_innobase::info_low() does not distinguish HA_STATUS_VARIABLE_EXTRA

mysql-test/suite/innodb/r/alter_copy.result, mysql-test/suite/innodb/t/alter_copy.test, storage/innobase/handler/ha_innodb.cc
`innodb_doublewrite_update()`: Disallow any change if `srv_read_only_mode` holds, that is, the server was started with `innodb_read_only=ON` or `innodb_force_recovery=6`.
This fixes up commit 1122ac978e2e709ae17a19335cbf0e4e5b53ad01 (MDEV-33545).
`SET GLOBAL innodb_doublewrite` will have no effect if `innodb_read_only=ON` or `innodb_force_recovery=6`.
```sh
./mtr innodb.alter_copy
```
Yes, the test name has nothing to do with this change, but it was a test that uses `innodb_read_only` and requires a debug instrumented server. I did not want to slow down the regression tests by adding another server restart to cover this bug.
=> MDEV-34455 innodb_read_only=ON fails to imply innodb_doublewrite=OFF

storage/innobase/btr/btr0cur.cc, storage/innobase/btr/btr0pcur.cc, storage/innobase/buf/buf0buf.cc, storage/innobase/gis/gis0sea.cc, storage/innobase/include/btr0types.h
`BTR_MODIFY_PREV`: Remove. This mode was only used by the change buffer, which commit f27e9c894779a4c7ebe6446ba9aa408f1771c114 (MDEV-29694) removed.
`buf_page_get_gen()`: Revert the change that was made in commit 90b95c6149c72f43aa2324353a76f370d018a5ac (MDEV-33543) because it is not applicable after MDEV-29694. This fixes the performance regression that @vaintroub reported.
A performance regression related to loading pages into the InnoDB buffer pool was fixed.
This is a low-level change that is adequately covered by the regression test suite.
The `BTR_MODIFY_PREV` removal is mechanical, maybe except for `btr_pcur_optimistic_latch_leaves()`. The change to `buf_page_get_gen()` is best reviewed by considering that it is reverting #3234.
I do not think that this change requires any …
=> MDEV-34458 wait_for_read in buf_page_get_low hurts performance

storage/innobase/handler/ha_innodb.cc, storage/innobase/handler/ha_innodb.h, storage/innobase/handler/handler0alter.cc, storage/innobase/handler/i_s.cc, storage/innobase/include/dict0dict.h, storage/innobase/include/dict0dict.inl, storage/innobase/include/dict0mem.h, storage/innobase/lock/lock0lock.cc
During a Sysbench `oltp_point_select` workload with *1 table* and 400 concurrent connections, a bottleneck on `dict_table_t::lock_mutex` was observed in `ha_innobase::info_low()`.
`dict_table_t::lock_latch`: Replaces `lock_mutex`.
In `ha_innobase::info_low()` and several other places, we will acquire a shared `dict_table_t::lock_latch` or we may elide the latch if hardware memory transactions are available.
`innobase_build_v_templ()`: Remove the parameter `bool locked`, and require the caller to hold exclusive `dict_table_t::lock_latch` (instead of holding an exclusive `dict_sys.latch`). This could help some workloads that make use of virtual columns.
This is a performance improvement that may not be worth mentioning, because it affects a special case (massively parallel read-only …
=> MDEV-32176 Contention in ha_innobase::info_low()

mysql-test/main/bad_startup_options_debug.result, mysql-test/main/bad_startup_options_debug.test, sql/mysqld.cc
When getaddrinfo returns and error, the contents
of ai are invalid so we cannot continue based
on their data structures.
In the previous branch of the if statement, we
abort there if there is an error so for consistency we abort here too.
Handle errors looking up getaddrinfo better.
```
$ sql/mariadbd --no-defaults --datadir=/tmp/${PWD##*/}-datadir --socket=/tmp/${PWD##*/}.sock --plugin-dir=${PWD}/mysql-test/var/plugins/ --verbose  --port 3321  --extra-port=4294967295
sql/mariadbd: Warning: Charset id '33' csname 'utf8' trying to replace existing csname 'utf8mb3'
sql/mariadbd: Warning: Charset id '83' csname 'utf8' trying to replace existing csname 'utf8mb3'
2024-06-24  9:19:46 0 [Note] Starting MariaDB 10.11.9-MariaDB source revision 82ba486e5484a9dfb5608956453574542a89930d as process …
```
=> MDEV-34437: handle error on getaddrinfo

mysql-test/include/log_slow_grep.inc, mysql-test/main/analyze_engine_stats2.opt, mysql-test/main/analyze_engine_stats2.result, mysql-test/main/analyze_engine_stats2.test, mysql-test/main/analyze_stmt_prefetch_count.opt, mysql-test/main/analyze_stmt_prefetch_count.result, mysql-test/main/analyze_stmt_prefetch_count.test, mysql-test/main/log_slow_innodb.result, sql/ha_handler_stats.h, sql/log.cc, sql/sql_explain.cc, storage/innobase/buf/buf0rea.cc, storage/innobase/include/mariadb_stats.h
The symptoms were: take a server with no activity and a table that's not in the buffer pool. Run a query that reads the whole table and observe that r_engine_stats.pages_read_count shows about 2% of the table was read. Who reads the rest?
The cause was that page prefetching done inside InnoDB was not counted.
This patch adds r_engine_stats.pages_prefetch_read_count which counts page prefetch requests done in buf_read_ahead_random() and buf_read_ahead_linear().
This patch intentionally doesn't attempt to count the time to read the prefetched pages:
* there's no obvious place where one can do it
* prefetch reads may be done in parallel (right?), it is not clear how to count the time in this case.
TODO: r_engine_stats members are printed into the slow query log. Should we add …
=> MDEV-34190: r_engine_stats.pages_read_count is unrealistically low

mysys/lf_alloc-pin.c
MariaDB supports a "wait-free concurrent allocator based on pinning addresses".
In `lf_pinbox_real_free()` it tries to sort the pinned addresses for better
performance to use binary search during "real free". `alloca()` was used to
allocate stack memory and copy addresses.
To prevent a stack overflow when allocating the stack memory the function checks
if there's enough stack space. However, the available stack size was calculated
inaccurately which eventually caused database crash due to stack overflow.
The crash was seen on MariaDB 10.6.11 but the same code defect exists on all
MariaDB versions.
Crash stack trace example:
```
#0  msort_with_tmp (p=0x40333f0790a0, b=0x40333f0790d0, n=3) at msort.c:40
#1  0x000040000456c86c in msort_with_tmp (n=3, b=0x40333f0790d0, p=0x40333f079100) at …
```
=> MDEV-31151: Fix a stack overflow in pinbox allocator

mysql-test/suite/innodb/r/log_file_overwrite.result, mysql-test/suite/innodb/t/log_file_overwrite.test, storage/innobase/handler/ha_innodb.cc
During read only mode, InnoDB doesn't allow checkpoint to happen. So InnoDB should throw the warning when InnoDB tries to force the checkpoint when innodb_read_only = 1 or
innodb_force_recovery = 6.
./mtr innodb.log_file_overwrite
=> MDEV-34519 innodb_log_checkpoint_now crashes when innodb_read_only is enabled

mysql-test/suite/binlog/r/binlog_truncate_active_log.result, mysql-test/suite/binlog/r/binlog_truncate_multi_engine.result, mysql-test/suite/binlog/r/binlog_truncate_multi_log.result, mysql-test/suite/binlog/t/binlog_truncate_active_log.inc, mysql-test/suite/binlog/t/binlog_truncate_active_log.test, mysql-test/suite/binlog/t/binlog_truncate_multi_engine.test, mysql-test/suite/binlog/t/binlog_truncate_multi_log.test, mysql-test/suite/binlog/t/binlog_truncate_multi_log_unsafe.test, mysql-test/suite/rpl/r/rpl_semi_sync_fail_over.result, mysql-test/suite/rpl/t/rpl_semi_sync_crash.inc, sql/log.cc, sql/mysqld.cc
The current semi-sync binlog fail-over recovery process uses rpl_semi_sync_slave_enabled==TRUE as its condition to truncate a primary server’s binlog, as it is anticipating the server to re-join a replication topology as a replica. However, for servers configured with both rpl_semi_sync_master_enabled=1 and
rpl_semi_sync_slave_enabled=1, if a primary is just re-started (i.e. retaining its role as master), it can truncate its binlog to drop transactions which its replica(s) has already received and executed. If this happens, when the replica reconnects, its gtid_slave_pos can be ahead of the recovered primary’s gtid_binlog_pos, resulting in an error state where the replica’s state is ahead of the primary’s.
This patch changes the condition for semi-sync recovery to truncate the binlog to …
=> MDEV-33465: an option to enable semisync recovery

.gitlab-ci.yml, mysys/crc32/crc32_arm64.c, mysys/my_rdtsc.c, sql/sql_parse.cc, storage/maria/ha_s3.cc, tests/code_quality/cppcheck_ignorelist.txt, tests/code_quality/flawfinder_ignorelist.json
This PR makes changes to the existing cppcheck GitLab CI job in order to make it easier to address new/existing findings. Existing ignorelists are also updated to reflect this and the current state of the codebase. Also, some trivial issues found by cppcheck are addressed.
Refactor GitLab cppcheck job
- Line numbers had to be removed from the ignorelists in order to be diffed against since locations of the same findings can differ across runs. Therefore preprocessing has to be done on the CI findings so that it can be compared to the ignorelist and new findings can be outputted. However, since line numbers have to be removed, a situation occurs where it is difficult tao reference the location of findings in code given the output of the CI job.
- To lessen this pain, change the cppcheck …
=> Small cppcheck fixes and refactor GitLab cppcheck job

mysql-test/suite/innodb/r/innodb_stats_fetch.result, mysql-test/suite/innodb/t/innodb_stats_fetch.test, storage/innobase/dict/dict0stats.cc
- Column stat_value and sample_size in mysql.innodb_index_stats table is declared as BIGINT UNSIGNED without any check constraint. user manually updates the value of stat_value and sample_size to zero. InnoDB aborts the server while reading the statistics information because InnoDB expects at least one leaf page to exist for the index.
- To fix this issue, InnoDB should interpret the value of stat_n_leaf_pages, stat_index_size in innodb_index_stats stat_clustered_index_size, stat_sum_of_other_index_sizes in innodb_table_stats as valid one even though user mentioned it as 0.
./mtr innodb.innodb_stats_fetch
=> MDEV-34474 InnoDB: Failing assertion: stat_n_leaf_pages > 0 in ha_innobase::estimate_rows_upper_bound

mysql-test/main/fulltext_order_by.result, mysql-test/main/name_const_replacement.result, mysql-test/main/name_const_replacement.test, mysql-test/main/union.result, mysql-test/suite/innodb_fts/r/fulltext_order_by.result, sql/item.cc, sql/item_subselect.cc, sql/json_table.cc, sql/opt_subselect.cc, sql/partition_info.cc, sql/sql_base.cc, sql/sql_class.cc, sql/sql_class.h, sql/sql_derived.cc, sql/sql_lex.cc, sql/sql_partition.cc, sql/sql_select.cc, sql/sql_tvc.cc, sql/sql_yacc.yy, sql/table.cc
Improve performance of queries like
SELECT * FROM t1 WHERE field = NAME_CONST('a', 4);
by, in this example, replacing the WHERE clause with field = 4 in the case of ref access.
The rewrite is done during fix_fields and we disambiguate this case from other cases of NAME_CONST by inspecting where we are in parsing.  We rely on THD::where to accomplish this.  To improve performance there, we change the type of THD::where to be an enumeration, so we can avoid string comparisons during Item_name_const::fix_fields.  Consequently, this patch also changes all usages of THD::where to conform likewise.
=> MDEV-33971 NAME_CONST in WHERE clause replaced by inner item

mysql-test/include/not_valgrind_build.inc, mysql-test/main/sp-no-valgrind.test
The version test on not_valgrind_build.inc was
broken as in BB the sp-no-valgrind.test was
executed.
The implication that it wouldn't work on ASAN
was also incorrect as ASAN tests show it running
fine there.
Correct sp-no-valgrind.test for not_valgrind.inc.
failing on valgrind: https://buildbot.mariadb.org/#/builders/551/builds/15311
succeeding on asan: https://buildbot.mariadb.org/#/builders/588/builds/6950/steps/8/logs/stdio
mtr tests it.
=> mtr: remove not_valgrind_build

mysql-test/suite/innodb/r/temp_truncate_freed.result, mysql-test/suite/innodb/t/temp_truncate_freed.test, storage/innobase/buf/buf0buf.cc
Problem:
========
- innodb.temp_truncate_freed fails with ER_WRONG_ARGUMENTS and states that another buffer pool resize is already in progress. Test case has wait condition to ensure that buffer pool resize is completed. There is a possibility that wait condition check could get false impression that InnoDB buffer pool resize completed due to previous buffer pool resize.
Fix:
===
Add more elaborate wait_condition to ensure the current buffer pool resize completed.
buf_pool_t::resize(): Set the buffer pool resize status only after setting previous buffer pool size to current buffer pool size. This should help the test case to make reliable.
./mtr innodb.temp_tablespace_freed
=> MDEV-34552  innodb.temp_tablespace_freed fails with ER_WRONG_ARGUMENTS

mysql-test/suite/rpl/t/rpl_mdev12179.test
Simplify in an attempt to avoid:
mysqltest: At line 275: File already exist: on the write_file lines.
Using write_line as that's what a lot of other tests do for writing small bits to a expect file.
It was failing on write_file with file already existing on the windows-packaging builder only.
This replaces write_file with just a write line in an attempt to acheive the same thing.
Consult the documentation on ["Writing good test cases"](https://mariadb.org/get-involved/getting-started-for-developers/ …
=> MDEV-34568 rpl.rpl_mdev12179 - correct for Windows

mysql-test/suite/innodb/r/lock_release.result, mysql-test/suite/innodb/t/lock_release.test, storage/innobase/buf/buf0dump.cc, storage/innobase/lock/lock0lock.cc, storage/innobase/os/os0file.cc
- During XA PREPARE, InnoDB releases the non-exclusive locks. But it fails to remove the non-exclusive table lock from the transaction table locks. In the mean time, main thread evicts the table from the LRU cache. While rollbacking the XA transaction, InnoDB iterates through the table locks to check whether it holds lock on any system tables and wrongly assumes the evicted table as system table since the table id is 0
Fix:
===
During XA PREPARE, remove the table locks of the transaction while releasing the non-exclusive locks.
./mtr innodb.lock_release
=> MDEV-34542  Assertion `lock_trx_has_sys_table_locks(trx) == __null' failed in void row_mysql_unfreeze_data_dictionary(trx_t*)

sql/log.cc
- Remove unused variable `file` from `MYSQL_BIN_LOG::open()`
- Remove wrong argument in comment
- Remove single/trivial call of function MYSQL_BIN_LOG::init() and remove function
- Remove `delay_close` variable from `MYSQL_BIN_LOG::new_file_impl()` and adapt the logic to `is_relay_log`
- Remove single jump to label `end2` and use code instead; remove label `end2`
- Remove unncesseray assignemt to `close_on_error`
=> Small cleanup of replication code (log.cc)

tests/upgrade_from/test_upgrade.sh
Fedora 40 introdced wget2 as the default wget program, which caused a
break in the functionality of the test_upgrade.sh script. Removing the
`--spider` option and modifying the determination of the latest
distribution to test on fixes the issue. At the same time, added in
another source for the boost-program-options RPM when the fedora version
is 39.
Additionally added rpm sources for the boost-program-options and openssl 1.1. This is necessary when building older versions of MariaDB (e.g., 10.4) on newer linux distributions (e.g., Fedora 39) that do not always have access to all required dependencies. In the above example older MariaDB versions are not compatible with OpenSSL 3.0+, so require an older version.
None
Start a docker container using the fedora:40 image
```
docker run --rm …
```
=> Update test upgrade script for use with latest Fedora

sql/sql_parse.cc
Address Sanitizer's know how to detect stack overrun, so there's no point in us doing it.
As evidenced by perfschema tests where signficant test failures because this function failed under ASAN (MDEV-33210).
Also, so since clang-16, we cannot assume much about how local variables are allocated on the stack (MDEV-31605).
Disabling check idea thanks to Sanja.
Disable stack overrun detection when an alternate Address Sanitizer computation is used.
With clang-16+ and -DWITH_ASAN=1 run the mtr --suite=perfschema, will now pass.
=> MDEV-34099: AddressSanitizer running out of memory regardless of stack_thread size

debian/libmariadbd-dev.install, debian/not-installed
Move mariadb.pc to not-installed from libmariadbd-dev to clear out this situation
As `mariadb.pc` contains mostly the same than `libmariadb.pc` and it mainly only creates distortion for client developers. They use libmariadb.pc not mariadb.pc (which is for embbeded use mainly).
Remove mariadb.pc in Debian libmariadbd-dev-package
As Salsa-CI is currently not having enough space by hand build package in Debian Sid wih `debian/autobake-debs.sh` and after that install current version with `apt install libmariadbd-dev`. Then install needed build packages with `apt install ./package.deb`. When one gets to `libmariadbd-dev` deb package and `libmariadb-dev` there should be any errors.
=> MDEV-34456: Move mariadb.pc to not-installed

scripts/mytop.sh
The mytop utility supports defining filters in .mytop, but this functionality is currently broken.
Specifying filters (filter_status, filter_user, etc) in the mytop config won't work, because any filter specified here is added to the config hash as a literal string.  This change fixes that - if filter_* is defined in the config and matches an existing filter_* key, then run the value through StringOrRegex() and assign the result to the config hash.
Update mytop utility to fix parsing of filter_* entries in .mytop config.
I don't know that the test suite will actually test this script.
That being said, a manual test will work as follows:
- Add a filter_ entry to the .mytop config, eg: filter_state=/data/
- Run mytop, and see if any queries with state 'Sending data' appear.
- Alternatively, …
=>  MDEV-34604 mytop - fix specifying filters in .mytop

.gitlab-ci.yml
> After May 31, 2024, CentOS Stream 8 will be archived and no further
updates will be provided. [1]
CentOS Stream 8 is now EOL and should be updated to using CentOS Stream 9 for compatibility testing in GitLab CI.
[1] https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/
https://www.centos.org/centos-linux-eol/
None
Start CentOS 9 container with 
docker run --rm  -it quay.io/centos/centos:stream9 bash
Follow the build code in .gitlab-ci.yml
A working pipeline can be seen on the public mirror https://salsa.debian.org/robinnewhouse/mariadb-server-mirror/-/pipelines
=> GitLab CI Upgrade CentOS 8 to CentOS 9 build

debian/additions/source_mariadb-10.5.py
Refactor import * statements to only import the required functions instead of all functions from the module. Note that all code changes are non-functional.
N/A
All tests are confirmed to pass by running the command `./mtr --suite=main`.
=> Refactor import * statement

sql/item.cc
MDEV-33971 fix --view-protocol test failure
Allow the NAME_CONST unwrap optimization when the client is not
in the PREPARE step of prepared statement nor in the view
analysis mode.
=> MDEV-33971 fix --view-protocol under main.name_const_replacment test

mysql-test/main/item_types.result, mysql-test/main/item_types.test, sql/item.cc, sql/item.h, sql/sql_select.cc
New runtime diagnostic introduced with MDEV-34490 has detected that `Item_int_with_ref` incorrectly returns an instance of its ancestor class `Item_int`. This commit fixes that.
In addition, this commit reverts a part of the diagnostic related to `clone_item()` checks. As it turned out, `clone_item()` is not required to return an object of the same class as the cloned one. For example, look at `Item_param::clone_item()`: it can return objects of `Item_null`, `Item_int`, `Item_string`, etc, depending on the object state. So the runtime type diagnostic is not applicable to `clone_item()` and is disabled with this commit.
As the similar diagnostic failures are expected to appear again in the future, this commit introduces a new test file in the main suite: item_types.test, and new test cases …
=> MDEV-34634 Types mismatch when cloning items causes debug assertion

storage/innobase/lock/lock0lock.cc
- This issue is caused by commit e71e6133535da8d5eab86e504f0b116a03680780 (MDEV-24671). Change the output of transaction lock wait time in microseconds suffix.
SHOW ENGINE INNODB STATUS output while waiting for the transaction lock
=> MDEV-34066  Output of SHOW ENGINE INNODB STATUS uses the nanoseconds suffix for microseconds

mysys/crc32/crc32c_x86.cc
It is not sufficient to check that the CPU supports the necessary instructions. Also the operating system (or virtual machine hypervisor) must enable all the AVX registers to be saved and restored on a context switch.
Because clang 8 does not support the compiler intrinsic `_xgetbv()` we will require clang 9 or later for enabling the use of `vpclmulqdq` and the related AVX512 features.
MariaDB Server would catch SIGILL on a system where the CPU but not the operating system supports AVX-512.
`InnoDB: Using AVX512 instructions` should continue to be reported on the `amd64-debian-11-msan` builder.
Unfortunately, I do not have the ability to change the boot parameters of an environment to test that `_xgetbv()` would prevent the use of AVX512 instructions when the operating system does not …
=> MDEV-34565: SIGILL due to OS not supporting AVX512

storage/innobase/btr/btr0cur.cc, storage/innobase/btr/btr0pcur.cc
In commit 2f6df9374806665db0764c74187a384b562b150a we fixed the bug by removing some code related to the no longer needed `BTR_MODIFY_PREV` mode.
In commit 73ad436e16c3ac022a2f1c477eac0e9a7e702707 an alternative fix was applied that also fixes the `BTR_SEARCH_PREV` case.
Let us clean up some implicit references to `BTR_MODIFY_PREV` that were missed in 2f6df9374806665db0764c74187a384b562b150a.
`btr_pcur_move_backward_from_page()`: Assume that the latch mode was `BTR_SEARCH_LEAF`.
`btr_pcur_move_to_prev()`: Assert that the latch mode is `BTR_SEARCH_LEAF`. This function is mostly invoked in `row0sel.cc` for read operations, as well as in `row0merge.cc` for reading from the clustered index. All callers indeed use a cursor in the `BTR_SEARCH_LEAF` mode.
This code cleanup does not need to be …
=> MDEV-34458: Remove more traces of BTR_MODIFY_PREV

mysql-test/suite/innodb/r/import_bugs.result, mysql-test/suite/innodb/t/import_bugs.test, storage/innobase/handler/handler0alter.cc
- commit 85db5347311340e39753b0200fb9d459a5024535 (MDEV-33400) avoid the clearing of the instant alter metadata during discard tablespace. But it fails to remove the assignment of n_core_null_bytes with total nullable fields exist in the index for discarded tablespace.
./mtr innodb.import_bugs
=> MDEV-34181  Instant table aborts after discard tablespace

storage/innobase/log/log0log.cc
On systems where `log_sys.lsn_lock` is not based on a `futex` like system call but the `pthread_mutex_wrapper`, we must invoke `lsn_lock.init()` to avoid a corrupted `ib_logfile0` due to race conditions on writes to `log_sys.buf`.
On Apple macOS, IBM AIX, Solaris derivatives and some other platforms, InnoDB would corrupt its `ib_logfile0`, which would not only break crash recovery and `mariadb-backup --backup` but often prevent a normal restart as well.
Without this fix, the test suite on our CI would fail very early on Apple macOS as well as IBM AIX, as well as on Microsoft Windows if we unconditionally enabled `SUX_LOCK_GENERIC` (disabled the futex-like system calls).
=> MDEV-34422 InnoDB writes corrupted log on macOS and AIX due to uninitialized log_sys.lsn_lock

storage/innobase/page/page0page.cc
During InnoDB root page split, InnoDB does the following 
1) First move the root records to the new page(p1)
2) Empty the root, insert the node pointer to the root page
3) Split the new page and make it as child nodes.
4) Finds the split record, allocate another new page(p2) to the index
5) InnoDB stores the record(ret) predecessor to the supremum record of the page (p2).
6) In page_copy_rec_list_start(), move the records from p1 to p2 upto the split record
6) Given table is a compressed row format page, InnoDB attempts to compress the page p2 and failed (due to innodb_compression_level = 0)
7) Since the compression fails, InnoDB gets the number of preceding records(ret_pos) of a record (ret) on the page (p2)
8) Page (p2) is a new page, ret points to infimum record. ret_pos can be 0. …
=> MDEV-34357   InnoDB: Assertion failure in file ./storage/innobase/page/page0zip.cc line 4211

sql/sql_parse.cc, sql/table.cc
Commit a8a75ba2d causes the MariaDB server to crash, usually with signal 11, at random code locations due to invalid pointer values during any table operation. This issue occurs when the server is built with -O3 and other customized compiler flags.
For example, the command `use db1;` causes server to crash in the `check_table_access` function at line sql_parse.cc:7080 because `tables->correspondent_table` is an invalid pointer value of 0x1.
The crashes are due to undefined behavior from using uninitialized variables. The problematic commit a8a75ba2d introduces code that allocates memory and sets it to 0 using thd-\>calloc before initializing it with a placement new operation. This process depends on setting memory to 0 to initialize member variables not explicitly set in the constructor. …
=> MDEV-34625 Fix undefined behavior of using uninitialized member variables

mysql-test/main/tmp_table_count-7586.result, mysql-test/main/tmp_table_count-7586.test
This test ran `show status like '%Created_tmp%'`. This captures `Created_tmp_files` as well as the intended `Created_tmp_tables`. In 11.5, the former got moved to `FLUSH GLOBAL`, so when testing, the result can now be random.
This fix makes the test just use `Created_tmp_tables`.
Run a multi-threaded MTR, `amd64-fedora-38-last-N-failed` should now pass in BuildBot.
=> MDEV-34605 Fix tmp_table_count-7586

mysql-test/suite/encryption/r/innodb_encryption_discard_import.result, mysql-test/suite/encryption/t/innodb_encryption_discard_import.test, storage/innobase/fil/fil0crypt.cc, storage/innobase/handler/ha_innodb.cc, storage/innobase/include/fil0crypt.h
Problem:
========
- After the commit ada1074bb10359342ee00e220fe9c172574265fb (MDEV-14398) fil_crypt_set_encrypt_tables() iterates through all tablespaces to fill the default_encrypt tables list. This was a trigger to encrypt or decrypt when key rotation age is set to 0. But import tablespace does call fil_crypt_set_encrypt_tables() unnecessarily. The motivation for the call is to signal the encryption threads.
Fix:
====
ha_innobase::discard_or_import_tablespace: Remove the fil_crypt_set_encrypt_tables() and add the import tablespace to the default encrypt list if necessary
```
--source include/have_innodb.inc
--source include/have_partition.inc
CREATE TABLE t1 (c1 CHAR(1) ,c2 INT) ENGINE=INNODB
PARTITION BY LINEAR HASH ((c2)) PARTITIONS 8192;
CREATE TABLE t2(f1 INT, f2 INT)ENGINE=InnoDB; …
```
=> MDEV-34670 IMPORT TABLESPACE unnecessarily traverses tablespace list

mysql-test/suite/innodb/r/instant_alter_bugs.result, mysql-test/suite/innodb/t/instant_alter_bugs.test, storage/innobase/handler/handler0alter.cc
Reason:
======
- InnoDB fails to load the instant alter table metadata from clustered index while loading the table definition. The reason is that InnoDB metadata blob has the column length exceeds maximum fixed length column size.
Fix:
===
- InnoDB should treat the long fixed length column as variable length fields that needs external storage while initializing the field map for instant alter operation
./mtr innodb.instant_alter_bugs
=> MDEV-29010	Table cannot be loaded after instant ALTER

debian/additions/debian-start.inc.sh
Fixes error:
/usr/share/mysql/debian-start.inc.sh: line 39: /usr/bin/mariadb --defaults-file=/etc/mysql/debian.cnf: No such file or directory
=> MDEV-33750: postfix debian-start.inc

mysql-test/main/item_types.result, mysql-test/main/item_types.test, sql/item.h, sql/item_cmpfunc.cc, sql/item_cmpfunc.h
New runtime type diagnostic (MDEV-34490) has detected that classes Item_func_eq, Item_default_value and Item_date_literal_for_invalid_dates incorrectly return an instance of its ancestor classes when being cloned. This commit fixes that.
Additionally, it fixes a bug at Item_func_case_simple::do_build_clone() which led to an endless loop of cloning functions calls.
<Not worth mentioning>
New test cases were added to main/item_types.test
=> MDEV-34683 Types mismatch when cloning items causes debug assertion

mysql-test/suite/plugins/r/unix_socket_osuser_match_auth_string.result, mysql-test/suite/plugins/t/unix_socket_osuser_match_auth_string.test, plugin/auth_socket/auth_socket.c
Before this change the unix socket auth plugin returned true only when the OS socket user id matches the MariaDB user name.
The authentication string was ignored.
Now if an authentication string is defined with in `unix_socket` authentication rule, then the authentication string will be used to compare with the socket's user name, and the plugin will return a positive if matching.
Make the plugin to fill in the @@external_user variable.
This change is similar to MySQL commit of https://github.com/mysql/mysql-server/commit/6ddbc58e.
However there's one difference with above commit:
- For MySQL, both OS user matches DB user name and OS user matches the  authentication string will be allowed to connect.
- For MariaDB, we only allows the OS user matches the authentication  string to connect, …
=> [MDEV-33479] Extend Unix socket authentication to support authentication_string

mysql-test/main/spatial_utility_function_geohash.result, mysql-test/main/spatial_utility_function_geohash.test, sql/item_geofunc.cc, sql/item_geofunc.h
MariaDB GIS functionalities are limited when compared to other DBMs. To facilitate the migration from MySQL to MariaDB the GIS functionality should be the same. This PR implements the GIS function `ST_LatFromGeoHash(geohash_str)`. The GIS function ST_LatFromGeoHash takes in input a geohash and returns its latitude. The latitude is returned as a numeric value in the interval [90, -90].
If the argument is NULL, the return value is NULL. If the argument is invalid, an ER_INCORRECT_TYPE is thrown.
To ensure compatibility between the MySQL implementation of this function and the MariaDB implementation, the tests for this function have been cherry-picked from MySQL.
This patch has no side effects.
Adds the function:
`ST_LatFromGeoHash(geohash_str)` and `LatFromGeoHash(geohash_str)`:  takes in …
=>  MDEV-34159: Implement the GIS function ST_LatFromGeoHash

mysql-test/suite/innodb_fts/r/multiple_index.result, mysql-test/suite/innodb_fts/r/plugin_debug.result, mysql-test/suite/innodb_fts/t/multiple_index.test, mysql-test/suite/innodb_fts/t/plugin_debug.test
- Added plugin_debug.test, multiple_index.test to innodb_fts suite from mysql-5.7.
- multiple_index result changes due to stat_n_rows value. Rollback properly sets stat_n_rows in MariaDB.
- plugin_debug result changes is due to position wasn't stored in fts default parser. Simple parser doesn't support phrase search query.
./mtr innodb_fts.plugin_debug innodb_fts.multiple_index
=> MDEV-14231 MATCH() AGAINST( IN BOOLEAN MODE), results mismatch

mysql-test/README
There is a typo at the mysql-test README. so I fixed it!
None.
There is no functional change.
=> Fix typo at mysql-test README

storage/innobase/buf/buf0buf.cc, storage/innobase/buf/buf0rea.cc, storage/innobase/include/buf0buf.h, storage/innobase/include/srw_lock.h, storage/innobase/row/row0import.cc, storage/innobase/sync/srw_lock.cc, storage/innobase/trx/trx0rseg.cc, storage/innobase/trx/trx0sys.cc
When `SUX_LOCK_GENERIC` is defined, the `srw_mutex`, `srw_lock`, `sux_lock` are implemented based on `pthread_mutex_t` and `pthread_cond_t`.  This is the only option for systems that lack a `futex`-like system call.
In the `SUX_LOCK_GENERIC` mode, if `pthread_mutex_init()` is allocating some resources that need to be freed by `pthread_mutex_destroy()`, a memory leak could occur when we are repeatedly invoking `pthread_mutex_init()` without a `pthread_mutex_destroy()` in between.
`pthread_mutex_wrapper::initialized`: A debug field to track whether `pthread_mutex_init()` has been invoked.  This also helps find bugs like the one that was fixed by commit 1c8af2ae53a3a48d64b4167d21b20ff5e1caef36 (MDEV-34422); one simply needs to add `-DSUX_LOCK_GENERIC` to the CMAKE_CXX_FLAGS to catch that …
=> MDEV-34678 pthread_mutex_init() without pthread_mutex_destroy()

extra/mariabackup/xtrabackup.cc
Typo fixed
Irrelevant for this change
Irrelevant for this change
Neither of the boxes apply. I took the latest release-branch.
=> Fix typo in xtrabackup output

mysys/crc32/crc32c_x86.cc
In commit 232d7a5e2dc50181294b927e2bc4b02e282725a8 (#3430) we almost got the detection logic right. However, the `xgetbv` instruction would crash if Linux was started up with the option `noxsave`.
MariaDB Server should no longer crash on startup when the CPU but not the operating system supports AVX512.
`have_vpclmulqdq()`: Check for the XSAVE flag at the correct position and also for the AVX flag.
This was tested by invoking `unittest/mysys/crc32-t` on Ubuntu 22.04, on its Linux 5.15 kernel running with and without the `noxsave` option.
=> MDEV-34565 MariaDB crashes with SIGILL because the OS does not support AVX512

mysql-test/suite/innodb/r/alter_copy_bulk.result, mysql-test/suite/innodb/t/alter_copy_bulk.test, storage/innobase/row/row0ins.cc
- During copy algorithm, InnoDB should disable bulk insert operation if the table has foreign key relation and foreign key check is enabled.
./mtr innodb.alter_copy_bulk
=> MDEV-34756  Validation of new foreign key skipped if innodb_alter_copy_bulk= ON

storage/innobase/buf/buf0buf.cc, storage/innobase/include/srw_lock.h, storage/innobase/include/sux_lock.h, storage/innobase/unittest/innodb_sync-t.cc
Basically any request on a secondary index leaf page would unnecessarily first acquire an exclusive page latch, in case any buffered changes would have to be merged into the page. This would unnecessarily slow down read operations.
`buf_page_ibuf_merge_try()`: A separate function for invoking `ibuf_merge_or_delete_for_page()` when needed. Use the already requested page latch for determining if the call is necessary. If it is and if we are currently holding `rw_latch==RW_S_LATCH`, upgrading to an exclusive latch may involve waiting that another thread acquires and releases a U or X latch on the page. If we have to wait, we must recheck if the call to `ibuf_merge_or_delete_for_page()` is still needed. If the page turns out to be corrupted, we will release and fail the operation. Finally, …
=> MDEV-34759: buf_page_get_low() is unnecessarily acquiring exclusive latch

storage/innobase/log/log0recv.cc
`recv_recovery_from_checkpoint_start()`: Abort startup due to log corruption if we were unable to parse the entire log between the latest log checkpoint and the corresponding `FILE_CHECKPOINT` record.
Also, reduce some code bloat related to log output and  `log_sys.mutex`.
InnoDB crash recovery would wrongly succeed when the log file is corrupted. This would lead to corruption later, with messages noting "log sequence number … is in the future".
This is somewhat covered by the regression test suite. A version of this could be useful to test on 10.11 before the fix of #3458 to ensure that there will be no assertion failures or errors, but instead recovery failures. (Also, there should not be excessively many new recovery failures for a generic workload.)
=> MDEV-34802 Recovery fails to note some log corruption

mysql-test/main/spatial_utility_function_collect.result, mysql-test/main/spatial_utility_function_collect.test, sql/item_sum.cc, sql/item_sum.h, sql/sql_yacc.yy
This PR implements the `DISTINCT` clause for the `ST_Collect` function.
To ensure compatibility between the MySQL implementation of this function and the MariaDB implementation, the tests for this function have been cherry-picked from MySQL.
This patch has no side effects.
Adds the `DISTINCT clause for `ST_Collect` function.
An extensive test suite has been cherry-picked from MySQL.
=> MDEV-34278: Implements DISTINCT for ST_Collect

mysql-test/suite/innodb/r/log_file_size_online.result, mysql-test/suite/innodb/t/log_file_size_online.test, storage/innobase/handler/ha_innodb.cc, storage/innobase/include/log0log.h, storage/innobase/log/log0log.cc, storage/innobase/mtr/mtr0mtr.cc
The recent commit 4ca355d863e3b6a14439eebbb2958afccb3548e3 (MDEV-33894) caused a serious regression for online InnoDB `ib_logfile0` resizing, breaking crash-safety unless the memory-mapped log file interface is being used. However, the log resizing was broken also before this.
If InnoDB was killed soon after executing `SET GLOBAL innodb_log_file_size`, it could fail to recover.
To prevent such regressions in the future, we will extend the test `innodb.log_file_size_online` with a kill and restart of the server and with some writes running concurrently with the log size change.
I tested this on a 4-thread system with the following invocation, not using memory-mapped log (`/dev/shm` or `WITH_INNODB_PMEM`): 
```bash
./mtr --parallel=auto --repeat=10 innodb.log_file_size_online{,}
``` …
=> MDEV-34750 SET GLOBAL innodb_log_file_size is not crash safe

storage/innobase/btr/btr0btr.cc, storage/innobase/btr/btr0cur.cc, storage/innobase/btr/btr0pcur.cc, storage/innobase/buf/buf0buf.cc, storage/innobase/buf/buf0rea.cc, storage/innobase/gis/gis0sea.cc, storage/innobase/ibuf/ibuf0ibuf.cc, storage/innobase/include/buf0buf.h, storage/innobase/include/buf0rea.h, storage/innobase/row/row0import.cc, storage/innobase/row/row0merge.cc, storage/innobase/trx/trx0undo.cc
`btr_cur_t::search_leaf()`: When the index root page is also a leaf page, we may need to upgrade our existing shared root page latch into an exclusive latch. Even if we end up waiting, the root page won't be able to go away while we hold an `index()->lock`. The index page may be split; that is all.
`btr_latch_prev()`: Acquire the page latch while holding a buffer-fix and an index tree latch.
`row_merge_read_clustered_index()`: Remove some code that does not seem to be useful. No difference was observed with regard to removing this code when a `CREATE INDEX` or `OPTIMIZE TABLE` statement was run concurrently with `sysbench oltp_update_index --tables=1 --table_size=1000 --threads=16`.
InnoDB was unnecessarily performing buffer pool lookups when it would have sufficed to wait for a page …
=> MDEV-34791: Redundant page lookups hurt performance

mysql-test/main/show_check.result, mysql-test/suite/funcs_1/r/is_columns_is.result, mysql-test/suite/funcs_1/r/is_columns_is_embedded.result, mysql-test/suite/funcs_1/r/is_statistics.result, sql/sql_show.cc
MySQL-Connector-Net casts SEQ_IN_INDEX to uint and will raise an exception if the type is a System.Int64.
As we don't support a huge number of multi-column indexes reducing to a uint is sufficient to represent all values and maintain compatibility with MySQL-Connector-Net.
Add compatibility to MYSQL-Connector-Net for index introspection.
Current MTR test cases covered the type of SEQ_IN_INDEX
=> MDEV-34864 SHOW INDEX FROM - SEQ_IN_INDEX to ULong

mysql-test/suite/innodb/r/innodb-fk-warnings.result, storage/innobase/btr/btr0btr.cc, storage/innobase/btr/btr0cur.cc, storage/innobase/dict/dict0crea.cc, storage/innobase/dict/dict0dict.cc, storage/innobase/handler/ha_innodb.cc, storage/innobase/include/dict0crea.h, storage/innobase/include/dict0dict.h, storage/innobase/include/ha_prototypes.h, storage/innobase/row/row0ins.cc, storage/innobase/row/row0merge.cc, storage/innobase/row/row0mysql.cc, storage/innobase/row/row0sel.cc
In the bug report MDEV-32817 it occurred that the function `row_mysql_get_table_status()` is outputting a `fil_space_t*` as if it were a numeric tablespace identifier. A closer inspection reveals more errors.
`ib_push_warning()`: Remove. Let us invoke `push_warning_printf()` directly.
`innodb_decryption_failed()`: Report a decryption failure and set the `dict_table_t::file_unreadable` flag. This code was being duplicated in very many places.
`innodb_fk_error()`: Report a `FOREIGN KEY` error.
`dict_foreign_def_get_fields()`: Remove. This code was being used in `dict_create_add_foreign_to_dictionary()` in an apparently uncovered code path. That `ib_push_warning()` call would pass the integer `i+1` instead of a pointer to NUL terminated string (`"%s"`), and therefore the call should have …
=> MDEV-34823 Invalid arguments in ib_push_warning()

storage/innobase/fsp/fsp0fsp.cc, storage/innobase/handler/ha_innodb.cc, storage/innobase/srv/srv0srv.cc
Reason:
- During bootstrap, InnoDB shrinks the system tablespace while purge is
still active on system tablespace. This could lead to deadlock.
Fix:
- Avoid System tablespace shrinking during bootstrap.
-  Move the shrinking logic of system tablespace after purge gets shutdown.
Patch to test this scenario during bootstrap
```
diff --git a/storage/innobase/fsp/fsp0fsp.cc b/storage/innobase/fsp/fsp0fsp.cc
index 64f22c1cbe8..ec604a81315 100644
--- a/storage/innobase/fsp/fsp0fsp.cc
+++ b/storage/innobase/fsp/fsp0fsp.cc
@@ -40,6 +40,7 @@ Created 11/29/1995 Heikki Tuuri
#include "dict0mem.h"
#include "fsp0types.h"
#include "log.h"
+#include "trx0purge.h"
/** Returns the first extent descriptor for a segment.
We think of the extent lists of the segment catenated in the order
@@ -3598,6 +3599,7 …
```
=> MDEV-34855  Bootstrap hangs while shrinking the system tablespace 

sql/item.cc
Code added in 10.5 as fix for MDEV-32608.
During merge in f071b7620b2e the new flag name was used.
Unfortunately missed in the merge was the refactoring performed in c76eabfb5e39a1b0831159decd3e0b544b9ad2e3, that changed the flag types to uint16.
While on little-endian processors, the cast of uint16 and int are the same, this is not true on big-endian processors (cast performed in set_extraction_flag_processor).
The result is big-endian processors cleared the immutable flag rather than set the flag, resulting in MDEV-32608 being unfixed on big-endian processors.
Correct MDEV-34650  for big-endian processors.
main.having_cond_pushdown test on big-endian processors
=> MDEV-34650 main.having_cond_pushdown test failure - crash server (s390x)

mysql-test/suite/encryption/r/innodb-compressed-blob.result, mysql-test/suite/encryption/t/innodb-compressed-blob.test, storage/innobase/buf/buf0buf.cc, storage/innobase/buf/buf0rea.cc, storage/innobase/include/buf0rea.h
`buf_page_t::read_complete()`: Fix an incorrect condition that had been added in commit aaef2e1d8c843d1e40b1ce0c5199c3abb3c5da28 (MDEV-27058). Also for compressed-only pages we must remember that buffered changes may exist.
`buf_read_page()`: Correct the function comment; this is for a synchronous and not asynchronous read. Pass the parameter `unzip=true` to `buf_read_page_low()`, because each of our callers will be interested in the uncompressed page frame.
InnoDB could corrupt secondary index pages of `ROW_FORMAT=COMPRESSED` tables unless `innodb_change_buffering=none` had never been used.
Stress test with `innodb_change_buffering=all`, including server restarts. This fix was tested on a copy of a data directory on which the failure was originally reproduced.
By its design, the change …
=> MDEV-34879 InnoDB fails to merge the change buffer to ROW_FORMAT=COMPRESSED tables

client/mysqlbinlog.cc, mysql-test/suite/binlog/r/binlog_mysqlbinlog_warn_stop_datetime.result, mysql-test/suite/binlog/r/binlog_mysqlbinlog_warn_stop_position.result, mysql-test/suite/binlog/t/binlog_mysqlbinlog_warn_stop_datetime.test, mysql-test/suite/binlog/t/binlog_mysqlbinlog_warn_stop_position.test
Emit warnings if finished processing input files before reaching the boundary conditions indicated by either `--stop-position` or `--stop-datetime`.
=> MDEV-27037 mysqlbinlog emits a warning when reaching EOF before stop-condition

sql/mf_iocache_encr.cc, sql/sql_insert.cc, unittest/mysys/stacktrace-t.c
`my_b_encr_write()`: Initialize also `block_length`, and at the same time `last_block_length`, so that all 128 bits can be initialized with fewer writes (such as a single x86 `movaps` instruction). This fixes an error that was caught in the test `encryption.tempfiles_encrypted`.
`test_my_safe_print_str()`: Fully initialize the `b_stack` buffer in order to avoid a failure of the test `unit.stacktrace`. Previously, unit tests had been disabled in MemorySanitizer builds on our CI.
`handle_delayed_insert()`: Remove a redundant call to `pthread_exit(0)`, which would for some reason cause MemorySanitizer in  `clang-19` to report a stack overflow in a `RelWithDebInfo` build. This fixes a failure of several tests.
Nothing needs to be said, except maybe something about encrypted temporary files.
I …
=> MDEV-34921 MemorySanitizer reports errors for non-debug builds

mysql-test/main/log_slow.test
The loose regex for the MDEV-34539 test ended up
matching the opensuse in the path in buildbot.
Adjust to more complete regex including space,
backtick and \n, which becomes much less common
as a path name.
Un-noteworty
Build in directory containing "use" like build-mariadb-server-rebase-opensuse which I tested with.
Or wait until its merged up to 10.11 on opensuse where it will fail.
=> MDEV-34952 main.log_slow test failure on opensuse builder

storage/maria/ma_loghandler.c
Aria transaction ids are uint16 rather than uint.
Change the type to be more accurate.
Non-impacting - nothing required
Existing mtr tests cover it.
=> Aria - correct type

storage/innobase/include/log0log.h, storage/innobase/log/log0log.cc
Executing a DDL operation concurrently with `SET GLOBAL innodb_log_file_size` could lead to a hang of most InnoDB threads.
`log_t::persist()`: Add a parameter holding_latch to specify whether the caller is already holding exclusive `log_sys.latch`, like `log_write_and_flush()` always is.
Executing a DDL operation concurrently with `SET GLOBAL innodb_log_file_size` when `ib_logfile0` resides on a `mount -o dax` file system (persistent memory mapped log) could lead to a hang of most InnoDB threads.
Build with `CMAKE_CXX_FLAGS` including `-DLOG_LATCH_DEBUG`.
```sh
./mtr --parallel=auto innodb.log_file_size_online
```
=> MDEV-34909 DDL hang during SET GLOBAL innodb_log_file_size on PMEM

storage/innobase/include/fil0fil.h, storage/innobase/include/rw_lock.h, storage/innobase/include/srw_lock.h, storage/innobase/include/trx0rseg.h, storage/innobase/include/trx0trx.h, storage/innobase/sync/srw_lock.cc
Starting with GCC 7 and clang 15, single-bit operations such as `fetch_or(1) & 1` are translated into 80386 instructions such as LOCK BTS, instead of using the generic translation pattern of emitting a loop around `LOCK CMPXCHG`.
Given that the oldest currently supported GNU/Linux distributions ship GCC 7, and that older versions of GCC are out of support, let us remove some work-arounds that are not actually necessary.
`srw_mutex_impl::HOLDER`: Changed from `1U<<31` to `1` in order to work around llvm/llvm-project#37322 which is related to the most significant bit.
`srw_mutex_impl::WAITER`: A multiplier of waiting requests. This used to be `1`, which would now collide with `HOLDER`.
`fil_space_t::set_stopping()`: Remove this unused function.
In MSVC we need `_interlockedbittestandset()` …
=> MDEV-34983: Remove x86 asm work-arounds from InnoDB

mysql-test/suite/galera_3nodes/galera_3nodes.cnf, sql/wsrep_sst.cc
put the command line at the end. so that when a very long command line
is truncated, it doesn't take the actual error message with it
=> reformat galera sst error messages

sql/mysqld.cc
Each time a listener socket becomes ready, MariaDB calls accept() ten
times (MAX_ACCEPT_RETRY), even if all but the first one return EAGAIN
because there are no more connections.  This causes unnecessary CPU
usage - on our server, the CPU load of that thread, which does nothing
but accept(), saturates one CPU core by ~45%.  The loop should stop
after the first EAGAIN.
Perf report:
```
11.01%  mariadbd  libc.so.6          [.] accept4
6.42%  mariadbd  [kernel.kallsyms]  [k] finish_task_switch.isra.0
5.50%  mariadbd  [kernel.kallsyms]  [k] _raw_spin_unlock_irqrestore
5.50%  mariadbd  [kernel.kallsyms]  [k] syscall_enter_from_user_mode
4.59%  mariadbd  [kernel.kallsyms]  [k] __fget_light
3.67%  mariadbd  [kernel.kallsyms]  [k] kmem_cache_alloc
2.75%  mariadbd  [kernel.kallsyms]  [k] fput …
```
=> MDEV-34994: sql/mysqld: stop accept() loop after the first EAGAIN

CMakeLists.txt
All the options that where in buildbot, should
be in the server making it accessible to all
without any special invocation.
If WITH_MSAN=ON, we want to make sure that the
compiler will result in an error if not supported.
-fdebug-macro was an option, not strictly MSAN related, that was included to make debugging easier under
Debug mode builds. It's here for consistency.
We make the -WITH_MSAN=ON append -stdlib=libc++
to the CXX_FLAGS if supported.
With SECURITY_HARDENING options the bootstrap
currently crashes, so for now, we disable SECRUITY_HARDENING if there is MSAN enable.
Remove buildbot config around MSAN invokation and make it in the server.
Include any changed system variables, status variables or behaviour. Optionally …
=> MDEV-34996 Buildbot MSAN options should be in server

mysql-test/main/mdev-31636.result, mysql-test/main/mdev-31636.test, sql/sys_vars.cc
Move memory allocations performed during Sys_var_gtid_binlog_state::do_check to Sys_var_gtid_binlog_state::global_update where they will be freed before the latter method returns.
=> MDEV-31636 Memory leak in Sys_var_gtid_binlog_state::do_check()

mysql-test/include/have_tlsv13.inc, mysql-test/main/tlsv13.result, mysql-test/main/tlsv13.test, mysql-test/suite.pm, vio/viosslfactories.c
Allow users to configure exact ciphers supported for all TLS versions including TLSv1.3 ciphers through the `ssl_cipher` server system variables. This configuration ability is supported by other databases and it may be necessary to meet compliance for certain security requirements/regulations.
ssl_cipher supports configuring TLSv1.3 cipher suites. Note that if no TLSv1.3 ciphers are specified to `--ssl-cipher`, then the TLSv1.3 ciphers enabled by default will still be supported.
Pages that needs updates:
- https://mariadb.com/kb/en/ssltls-system-variables/#ssl_cipher
- https://mariadb.com/kb/en/using-tlsv13/
Test cases were added to the main.ssl_cipher MTR.
---
All new code of the whole pull request, including one or several files that are either new files or modified ones, are …
=> MDEV-34869 ssl_cipher parameter cannot configure TLSv1.3 and TLSv1.2 ciphers at the same time

storage/innobase/log/log0recv.cc
A server that was running with `innodb_log_file_size=96M` and `innodb_buffer_pool_size=6M` had inserted some data into a table that was subsequently dropped. When the server was killed and restarted, an assertion failed in `recv_sys_t::parse()` while a `FSP_SIZE` change was unnecessarily being processed during the `skip_the_rest:` loop in `recv_scan_log()`.
The `ib_logfile0` contents was as follows:
1. The checkpoint start LSN points to the start of some mini-transaction.
2. There may be log records for modifying files for which a `FILE_MODIFY` had been written before the checkpoint. These records were "purged" by advancing the checkpoint.
3. At some point during the initial parsing with `store=true` the space reserved for `recv_sys.pages` will run out and `recv_scan_log()` would switch …
=> MDEV-34907 Bogus assertion failure and busy work while parsing FILE_ records

mysql-test/suite/binlog/r/binlog_mdev25611.result, mysql-test/suite/binlog/t/binlog_mdev25611.test, sql/log.cc, storage/innobase/handler/ha_innodb.cc
MDEV-25611: RESET MASTER causes the server to hang
RESET MASTER waits for storage engines to reply to a binlog checkpoint
requests. If this response is delayed for a long time for some reason, then
RESET MASTER can hang.
Fix this by forcing a log sync in all engines just before waiting for the
checkpoint reply.
(Waiting for old checkpoint responses is needed to preserve durability of
any commits that were synced to disk in the to-be-deleted binlog but not yet
synced in the engine.)
=> MDEV-25611: RESET MASTER causes the server to hang

storage/innobase/log/log0log.cc, tpool/aio_simulated.cc, tpool/tpool.h
`log_file_t::read()`, `log_file_t::write()`: Invoke `pread()` or `pwrite()` directly, so that we can give more accurate diagnostics in case of a failure, and so that we will avoid the overhead of setting up 5(!) stack frames and related objects.
This could be a minor performance improvement, probably not worth mentioning.
The log writing and crash recovery are exercised by the existing test suite, in particular by the `innodb`, `encryption`, and `mariabackup` suites.
This could be applicable to other versions as well. 10.11 is the earliest maintained branch after the last major refactoring of the log reading and writing in 685d958e38b825ad9829be311f26729cccf37c46.
=> MDEV-34450 os_file_write_func() is an overkill for ib_logfile0

mysql-test/suite/innodb/r/stat_tables.result, mysql-test/suite/innodb/t/stat_tables.test, storage/innobase/handler/handler0alter.cc
Statements like `ALTER TABLE t STATS_PERSISTENT 0` would fail to delete the persistent InnoDB statistics for the table, which would cause a duplicate key error on a subsequent operation that would create or rename tables.
Note that `DROP TABLE` will on purpose not attempt to drop persistent statistics if they were not enabled for the table. This will reduce the chances of `DROP TABLE` failing due to a locking conflict.
`commit_try_norebuild()`: If the `STATS_PERSISTENT` attribute of the table is being changed to disabled, drop the persistent statistics of the table.
Statements like `ALTER TABLE t STATS_PERSISTENT 0` failed to delete the persistent InnoDB statistics for the table, which would cause a duplicate key error on a subsequent operation that would create or rename tables.
```sh …
```
=> MDEV-34207: ALTER TABLE...STATS_PERSISTENT=0 fails to drop statistics

storage/innobase/dict/dict0dict.cc, storage/innobase/include/dict0dict.h, storage/innobase/include/lock0lock.h, storage/innobase/include/srw_lock.h, storage/innobase/include/transactional_lock_guard.h, storage/innobase/sync/srw_lock.cc
MariaDB is compiled with C++ exceptions enabled, and that disallows
some optimizations (e.g. the stack must always be unwinding-safe).  By
adding `noexcept` to functions that are guaranteed to never throw,
some of these optimizations can be regained.  Low-level locking
functions that are called often are a good candidate for this.
This shrinks the executable a bit (tested with GCC 14 on aarch64):
text	  data	   bss	   dec	   hex	filename
24448910	2436488	9473185	36358583	22ac9b7	build/release/sql/mariadbd
24448474	2436488	9473601	36358563	22ac9a3	build/release/sql/mariadbd
(See https://github.com/MariaDB/server/pull/3529#issuecomment-2363091181)
No runtime effect.
No runtime effect.
=> innobase/{lock0lock,dict0dict}: add `noexcept` to lock/unlock methods

client/mysqldump.cc, sql/log.cc
* Sibling of #3485, #3493 and #3518
This commit ports two fixes from #3360 according to the bug-fixing process to 11.4, covering cases introduced during 11.4.x.
* `client/mysqldump.cc`: Error message template had `%u` for a `long` arg (`MYSQL::thread_id`)
* `sql/log.cc`: Log message template had a `%s` but received no arg.
* Fixed data size mismatches that were garbling error and debug outputs (or possibly even crashes) on problematic platforms
* This should  match #3538.
* `client/mysqldump.cc`: I’m not sure which platforms has `sizeof(long)` different from `sizeof(int)`.
* `sql/log.cc`: The dangling `%s` could pick up a garbage byte sequence in *ideal* scenarios.
* *This is a new …
=> Fix a couple of `my_snprintf` arg mismatches

mysql-test/suite/innodb/r/purge.result, mysql-test/suite/innodb/t/purge.test, storage/innobase/row/row0purge.cc
`row_purge_reset_trx_id()`: Reserve large enough offsets for accommodating the maximum width `PRIMARY KEY` followed by `DB_TRX_ID`,`DB_ROLL_PTR`. We do not want to allocate anything from `heap`.
A memory leak was possible when an InnoDB table was defined with a 32-column `PRIMARY KEY`.
```sh
./mtr innodb.purge
```
=> MDEV-34078 Memory leak in InnoDB purge with 32-column PRIMARY KEY

client/mysql.cc, client/mysqladmin.cc, client/mysqlbinlog.cc, client/mysqlcheck.c, client/mysqldump.cc, client/mysqlimport.cc, client/mysqlshow.c, client/mysqlslap.c, mysql-test/suite/client/client-env-variable.cnf, mysql-test/suite/client/client-env-variable.result, mysql-test/suite/client/client-env-variable.test
Note: mysql_upgrade already uses environment variable as default. This feature was not added in for mysql_plugin and mysqltest 
Only `mysql` client program was using $MYSQL_HOST as the default host.
Add the same feature in most other client programs but using $MARIADB_HOST instead.
Set up environment variable `export MARIADB_HOST=your_test_server`
Run each client program with the following commands:
`client/mysqlslap -h another_test_server -P 3306 -u admin -p`
`client/mysqlslap  -P 3306 -u admin -p`
Verify that $MARIADB_HOST is used when `-h` is not specified. Also verify $MARIADB_HOST does not override command line argument.
All new code of the whole pull request, including one or several files that are either new files or modified ones, are contributed under the BSD-new license. I am …
=> [MDEV-14978] Client programs to use $MARIADB_HOST consistently

extra/mariabackup/xtrabackup.cc, storage/innobase/buf/buf0flu.cc, storage/innobase/fil/fil0fil.cc, storage/innobase/include/log0recv.h, storage/innobase/log/log0recv.cc, storage/innobase/mtr/mtr0mtr.cc
It turns out that we were performing a lot of unnecessary processing while parsing the log records.
In `mariadb-backup --backup`, we only have to invoke the `undo_space_trunc` and `log_file_op` callbacks as well as validate the mini-transaction checksums. There is absolutely no need to access `recv_sys.pages` or `recv_spaces`. This is what the new mode `recv_sys_t::store::BACKUP` will do.
In the `skip_the_rest:` loop, the minimum that needs to be done is to process all `FILE_` records until the end of the log is reached. Additionally, in case we invoked `file_name_t::add_freed_page()` for a `FREE_PAGE` record before switching to the  `skip_the_rest:` loop, we must invoke `file_name_t::remove_freed_page()` for any `INIT_PAGE` record. Any other records that we encounter during this parsing …
=> MDEV-34850: Busy work while parsing FILE_ records

storage/innobase/include/trx0purge.h, storage/innobase/trx/trx0rec.cc
In commit b7b9f3ce825a08f16ad851c16f603365ae473195 (MDEV-34515) we accidentally made the InnoDB MVCC code acquire a shared purge_sys.latch twice. Recursive shared latch acquisition may cause a deadlock of InnoDB threads if another thread in between will start waiting for an exclusive latch.
`purge_sys_t::latch`: In debug builds, use `srw_lock_debug` instead of `srw_spin_lock`, so that bugs like this will result in debug assertion failures.
`trx_undo_report_row_operation()`: Pass the `view_guard` to `trx_undo_prev_version()` and the rest of the arguments in the same order, so that the work to permute argument registers is minimized.
This does not need to be mentioned, because there is no release that would include the bug but not this fix.
Stress test with any workload that includes …
=> MDEV-35174 Possible hang in trx_undo_prev_version()

mysql-test/suite/innodb/r/page_compression_windows.result, mysql-test/suite/innodb/t/page_compression_windows.opt, mysql-test/suite/innodb/t/page_compression_windows.test, storage/innobase/os/os0file.cc
Remove workaround for MDEV-13941, it served for long enough.
Apparently Innodb is using `is_sparse` parameter in `os_file_set_size()` inconsistently, and it passes is_sparse=false now during first file extension. With MDEV-13941 workaround in place, it would unsparse the file, which is makes compression not to work at all anymore.
page_compressed Innodb tables on Windows will work again.
mtr test is added
=> MDEV-34929 page-compressed tables do not work on Windows

mysql-test/suite/innodb/r/recovery_shutdown.result, mysql-test/suite/innodb/r/sys_truncate_debug.result, mysql-test/suite/innodb/r/undo_leak.result, mysql-test/suite/innodb/r/undo_leak_fail.result, mysql-test/suite/innodb/t/recovery_shutdown.test, mysql-test/suite/innodb/t/sys_truncate_debug.test, mysql-test/suite/innodb/t/undo_leak.opt, mysql-test/suite/innodb/t/undo_leak.test, mysql-test/suite/innodb/t/undo_leak_fail.opt, mysql-test/suite/innodb/t/undo_leak_fail.test, storage/innobase/dict/dict0load.cc, storage/innobase/fsp/fsp0fsp.cc, storage/innobase/include/dict0load.h, storage/innobase/include/fil0fil.h, storage/innobase/include/fsp0fsp.h, storage/innobase/include/fsp0sysspace.h, storage/innobase/include/trx0sys.h, storage/innobase/srv/srv0srv.cc, storage/innobase/srv/srv0start.cc, storage/innobase/trx/trx0purge.cc
- InnoDB fails to shrink the system tablespace when it contains
the leaked undo log pages caused by MDEV-30671.
- InnoDB does free the unused segment in system tablespace
before shrinking the tablespace.
inode_info: Structure to store the inode page and offsets.
fil_space_t::garbage_collect():
Frees the system tablespace unused segment
fsp_free_unused_seg(): Frees the unused segment
fsp_get_sys_used_segment(): Iterates through all default
file segment and index segment present in system tablespace.
Added the test case innodb.undo_leak which basically leaks the undo segment by purge thread.
=> MDEV-34529  Shrink the system tablespace when system tablespace contains MDEV-30671 leaked undo pages

storage/innobase/btr/btr0btr.cc, storage/innobase/btr/btr0cur.cc, storage/innobase/dict/dict0load.cc, storage/innobase/trx/trx0undo.cc
InnoDB could avoid a `buf_pool.page_hash` look up as well as some operations on buffer page descriptors in a few places.
`dict_index_t::clear()`, `btr_drop_temporary_table()`: Make use of the root page guess if it is available.
`btr_read_autoinc()`: Invoke `btr_root_block_get()` to access the root page.
`btr_blob_free()`: Retain a buffer-fix on the page across `mtr_t::commit()` in order to avoid a `buf_pool.page_hash` lookup.
`dict_load_table_one()`: Remove a redundant check for page id. It was already validated in `buf_page_t::read_complete()`.
`trx_t::apply_log()`: Make use of `buf_pool.page_fix()` to avoid some `mtr_t` related overhead.
This is a minor performance fix that probably is not worth a special mention.
This low-level code should be well covered by the existing regression …
=> MDEV-35125: Unnecessary buf_pool.page_hash lookups

storage/innobase/buf/buf0flu.cc, storage/innobase/buf/buf0lru.cc, storage/innobase/handler/ha_innodb.cc, storage/innobase/include/buf0buf.h, storage/innobase/include/srv0srv.h, storage/innobase/srv/srv0srv.cc
A debug assertion in `buf_LRU_get_free_block()` could fail if `SET GLOBAL innodb_lru_scan_depth` is being executed during a workload that involves allocating buffer pool pages.
`buf_pool_t::LRU_scan_depth`: Replaces `srv_LRU_scan_depth`.
`buf_pool_t::flush_neighbors`: Replaces `srv_flush_neighbors`.
`innodb_buf_pool_update<T>()`: Update a parameter of `buf_pool` while holding `buf_pool.mutex`.
This is not worth mentioning, because `SET GLOBAL` is a rarely executed operation that requires SUPER privileges, and because there likely is no bad impact outside `CMAKE_BUILD_TYPE=Debug`.
The variables are covered by the regression test suite. In addition, the stress test that reproduced the bug in the first place should be run.
This bug affects 10.5 as well, but because the code has been …
=> MDEV-35149 Race condition around SET GLOBAL innodb_lru_scan_depth

mysql-test/suite/innodb_fts/r/fulltext.result, mysql-test/suite/innodb_fts/t/fulltext.test, storage/innobase/handler/handler0alter.cc
- InnoDB fulltext rebuilds the FTS COMMON table while adding the new fulltext index. This can be optimized by avoiding rebuilding the FTS COMMON table in case of FTS COMMON TABLE already exists.
./mtr innodb_fts.fulltext
=> MDEV-35183  ADD FULLTEXT INDEX unnecessarily DROPS FTS COMMON TABLES

extra/mariabackup/xtrabackup.cc, storage/innobase/fil/fil0fil.cc, storage/innobase/fsp/fsp0file.cc, storage/innobase/include/os0file.h, storage/innobase/include/os0file.inl, storage/innobase/log/log0log.cc, storage/innobase/log/log0recv.cc, storage/innobase/os/os0file.cc, storage/innobase/srv/srv0start.cc
Removed 'purpose' parameter from os_file_create() and related functions, and OS_AIO_NORMAL, OS_AIO_ASYNC
Always use FILE_FLAG_OVERLAPPED when opening Windows files in Innodb.
PS. Evaluated option of overlapping writes and flushes in Innodb group commit (log_write_up_to),  since [corresponding MySQL 
commit ](https://github.com/mysql/mysql-server/commit/c41ad32dda8145b4b0db0b937007a06f001a041a) suggested it could be faster with FILE_FLAG_OVERLAPPED on Windows. It was not, thus group commit logic remained the same.
Should not be mentioned in release notes, since it is merely a cleanup.
MTR already tests it well, no further test is required.
=> MDEV-35171 remove OS_FILE_NORMAL, OS_FILE_AIO

mysql-test/suite/rpl/r/rpl_semi_sync_cond_var_per_thd.result, mysql-test/suite/rpl/t/rpl_semi_sync_cond_var_per_thd.test, sql/semisync_master.cc, sql/semisync_master.h, sql/sql_class.cc, sql/sql_class.h
In between the binlogging of a transaction and its wait, it is
possible that its entry in Active_tranx was removed if semi-sync was 
switched off and on. This fires an assertion that checks before
awaiting an ACK that the entry must exist in Active_tranx.
The fix is to ensure that the entry exists before awaiting the ACK,
and if there is no entry, write an informative message to the user
explaining that the transaction is skipping its wait. Additionally,
debug-build only logic is added to ensure that the cause of the 
missing entry is due to semi-sync being turned off and on.
Initial PR organized as three commits:
1. Regression MTR test to show the problem
2. Fix
3. Extension to the test/result to ensure informational note is provided
A general note, I'm not thrilled about moving …
=> MDEV-34122: Assertion entry failed in Active_tranx::assert_thd_is_waiter

storage/innobase/log/log0recv.cc
During the execution of the test `innodb.innodb-32k-crash` some debug assertions that had been added to `log_sort_flush_list()` in 0d175968d1181a0308ce6caccc2e4fbc972ca6c6 are occasionally failing when executing the test `innodb.innodb-32k-crash`.
Furthermore, an assertion that was added to `recv_recovery_from_checkpoint_start()` in #3488 is occasionally failing when the last mini-transaction had been incompletely written.
This mostly fixes bogus debug assertions; nothing needs to be mentioned.
On a system with 152 hardware threads, I executed the following:
```bash
./mtr --parallel=160 --repeat=1000 innodb.innodb-32k-crash{,,,,,,,,,}{,,,,,,,}{,}
```
This used to easily reproduce the failures within less than 10 repetitions. Now both failures are gone, but there may still be occasional …
=> MDEV-35225 Bogus debug assertion failures in innodb.innodb-32k-crash

mysql-test/suite/innodb/r/lock_isolation.result, mysql-test/suite/innodb/t/lock_isolation.test, storage/innobase/handler/ha_innodb.cc
`convert_error_code_to_mysql()`: Treat `DB_DEADLOCK` and `DB_RECORD_CHANGED` in the same way, that is, signal to the SQL layer that the transaction had been rolled back.
When `innodb_snapshot_isolation=ON` caused an `ER_CHECKREAD` error to be flagged, the SQL layer would remain unaware that the InnoDB transaction had actually been rolled back.
```sh
./mtr innodb.lock_isolation
```
Without the code change, the test would trigger an assertion failure.
=> MDEV-35235 innodb_snapshot_isolation=ON fails to signal transaction rollback

storage/innobase/fil/fil0fil.cc, storage/innobase/include/fil0fil.h, storage/innobase/include/os0file.h, storage/innobase/os/os0file.cc
When MariaDB Server is run in a container under Windows Subsystem for Linux, the `fstat(2)` system calls that InnoDB invokes in `os_file_set_size()` or `os_file_get_size()` are causing a failure in case the file had been renamed in the past. This could happen at least on `ALTER TABLE` or `OPTIMIZE TABLE`.
`os_file_get_size()`: Invoke `lseek(2)` or `SetFilePointerEx()` instead of `fstat(2)`. We do not mind if the file pointer is moving to the end of the file, because InnoDB exclusively invokes positioned reads and writes, or in some rare cases, appends to an existing file.
`os_file_set_size()`: Invoke `os_file_get_size()` instead of `fstat()`.
Under Windows Subsystem for Linux, MariaDB Server should no longer crash when executing some DDL statements, such as `ALTER TABLE` or `OPTIMIZE …
=> MDEV-29015/MDEV-29260/MDEV-34938: os_file_get_size() WSL work-around

sql/item_jsonfunc.h, sql/item_sum.cc, sql/item_sum.h
Creates new parent Item_sum_str for Item_func_group_concat and Item_func_collect, migrating shared methods from each of those latter classes to the former.  Simultaneously, tighten up the method scopes.
=> MDEV-34940: Fix Item_func_collect inheritance

mysql-test/main/vector_innodb.result, mysql-test/main/vector_innodb.test, sql/sql_insert.cc
Similarly to 4b814066dcd, don't enable bulk insert when issuing create ...
insert into a table containing vector index. InnoDB can't handle situation
when bulk insert is enabled for one table but disabled for another. We can't
do bulk insert on vector index as it does table updates currently.
N/A
mtr vector_innodb
=> MDEV-35130 - Assertion fails in trx_t::check_bulk_buffer upon CREATE.. SELECT with vector key

extra/mariabackup/xtrabackup.cc, mysql-test/suite/mariabackup/disabled.def, sql/sql_table.cc
-->
In commit 1c55b845e0fe337e647ba230288ed13e966cb7c7 (MDEV-32932) the test `mariabackup.innodb_ddl_on_intermediate_table` was introduced but disabled.
`xb_load_single_table_tablespace()`: Properly handle missing `FTS_` tables.
`mariadb-backup --backup` could fail if an `ALTER TABLE` or `OPTIMIZE TABLE` statement is concurrently being executed on an InnoDB table that contains `FULLTEXT INDEX`.
```sh
./mtr mariabackup.innodb_ddl_on_intermediate_table
```
=> MDEV-35257 Backup fails during an ALTER TABLE with FULLTEXT INDEX

mysql-test/suite/innodb/r/alter_copy_bulk.result, mysql-test/suite/innodb/t/alter_copy_bulk.test, storage/innobase/handler/ha_innodb.cc, storage/innobase/include/trx0trx.h, storage/innobase/row/row0merge.cc
Problem:
=======
- InnoDB fails to write the buffered insert operation during
create..select operation. This happens when bulk_insert
in transaction is reset to false while unlocking a source table.
Fix:
===
- InnoDB should apply the previous buffered changes to
all tables if we encounter any statement other than
pure INSERT or INSERT..SELECT statement in
ha_innobase::external_lock() and start_stmt().
- Remove the function bulk_insert_apply_for_table()
start_stmt(), external_lock(): Assert that trx->duplicates
should be enabled during bulk insert operation
./mtr innodb.alter_copy_bulk
=> MDEV-35237  Bulk insert fails to apply buffered operation during CREATE..SELECT statement

sql/handler.cc, storage/innobase/handler/ha_innodb.cc
The tests fail on assertion
ut_ad(!wsrep_is_wsrep_xid(&trx->xid));
in `innobase_recover_rollback_by_xid()`.
The fix is to avoid async rollback for prepared transactions when wsrep is ON or wsrep recovery is in progress. The rationale is that the rollback of prepared transactions must complete before the node starts applying write sets after SST, or in case of wsrep recovery, the recovery must complete before the process exists.
Change the assertion into stronger one
ut_ad(!(WSREP_ON || wsrep_recovery));
to catch if the async rollback codepath is taken when wsrep is enabled.
Prior to this change, MTR tests wsrep.wsrep-recover, wsrep.wsrep-recover-v25 failed on assertion. These tests pass now.
=> MDEV-35265 wsrep.wsrep-recover, wsrep.wsrep-recover-v25 fail on assertion

storage/innobase/row/row0vers.cc
Post-push fix: row_vers_impl_x_locked() must be invoked under unlatched lock_sys, the corresponding assertion was removed in MDEV-34466 and was not restored in MDEV-34690. This fix restores it.
If the changes are not amenable to automated testing, please explain why not and carefully describe how to test …
=> MDEV-34690 lock_rec_unlock_unmodified() causes deadlock

CMakeLists.txt
Libmariadb introduced a cmake change that required 3.12 or newer.
Since none of the platforms we currently support have anything lower than 3.12 available, we should make this a proper requirement for the Server as well.
=> MDEV-35301: Bump minimum cmake version to 3.12.0

mysql-test/include/search_pattern_in_file.inc, mysql-test/include/wait_for_pattern_in_file.inc, mysql-test/suite/rpl/r/rpl_semi_sync_after_sync_coord_consistency.result, mysql-test/suite/rpl/r/rpl_semi_sync_no_missed_ack_after_add_slave.result, mysql-test/suite/rpl/r/rpl_semi_sync_shutdown_await_ack.result, mysql-test/suite/rpl/t/rpl_semi_sync_after_sync_coord_consistency.test, mysql-test/suite/rpl/t/rpl_semi_sync_no_missed_ack_after_add_slave.test, mysql-test/suite/rpl/t/rpl_semi_sync_shutdown_await_ack.inc, mysql-test/suite/rpl/t/rpl_semi_sync_shutdown_await_ack.test, sql/log.cc, sql/slave.cc
For a primary configured with wait_point=AFTER_SYNC, if two threads
T1 (binlogging through MYSQL_BIN_LOG::write()) and T2 were
binlogging at the same time, T1 could accidentally wait for its
semi-sync ACK using the binlog coordinates of T2. Prior to
MDEV-33551, this only resulted in delayed transactions, because all
transactions shared the same condition variable for ACK signaling.
However, with the MDEV-33551 changes, each thread has its own
condition variable to signal. So T1 could wait indefinitely when
either:
1) T1's ACK is received but not T2's when T1 goes into
wait_after_sync(), because the ACK receiver thread has already
notified about the T1 ACK, but T1 was _actually_ waiting on T2's
ACK, and therefore tries to wait (in vain).
2) T1 goes to wait_after_sync() before any ACKs have …
=> MDEV-35109: Semi-sync Replication stalling Primary using wait point=AFTER_SYNC

mysql-test/suite/innodb/r/stat_tables.result, mysql-test/suite/innodb/t/stat_tables.test, storage/innobase/dict/dict0stats.cc
Problem:
========
- dict_stats_table_clone_create() does not initialize the flag stats_error_printed in either dict_table_t or dict_index_t. Because dict_stats_save_index_stat() is operating on a copy of a dict_index_t object, it appears that
dict_index_t::stats_error_printed will always be false for actual metadata objects, and uninitialized in
dict_stats_save_index_stat().
Solution:
=========
dict_stats_table_clone_create(): Assign stats_error_printed for table and index while copying the statistics
./mtr innodb.table_stats
=> MDEV-32667   dict_stats_save_index_stat() reads uninitialized index->stats_error_printed

mysql-test/suite/sys_vars/r/session_track_system_variables_basic.result, mysql-test/suite/sys_vars/t/session_track_system_variables_basic.test
With MDEV-34915 adjusting the mtr output of session variables to be in order, the original omition for x86_32 (added by MDEV-31609) is no longer required.
nothing - internal test result
examining the sys_vars.session_track_system_variables_basic test on a x86_32 builder.
=> MDEV-34915 track session variables - test adjust

storage/innobase/dict/dict0stats.cc
- While saving the InnoDB table statistics, InnoDB does clone
the table object and its statistics to protect the metadata
in case if table is being dropped. From 10.6 onwards, any
background task inside InnoDB on the table takes MDL.
So metadata is protected by MDL of the table. Avoid the
cloning of the table and its associated index statistics.
./mtr --suite=innodb
=> MDEV-35363   Avoid cloning of table statistics while saving the InnoDB table stats

sql/mysqld.cc, sql/sys_vars.cc, storage/maria/ha_maria.cc
* Udate: *The Jira issue number for this PR is: [MDEV-35434](https://jira.mariadb.org/browse/MDEV-35434)*
This commit backports a fix group from #3360 for 11.5.
These are the only mistakes introduced during 11.5.x.
When these members switched from plain `char*` to `LEX_CSTRING`, not all usages were converted. Specifically, in this commit are args of `my_snprintf` derivatives.
Because until MDEV-21978 (#3360), automated type checks were unavailable for those functions due to their incompatibility, so these tools didn’t catch them.
`str` is the initial member of `LEX_CSTRING` (`typedef` of `struct st_mysql_const_lex_string`), so this difference did not cause incompatibility on most …
=> Add missing `LEX_STRING::str`s for `my_snprintf`

sql/ha_partition.cc, sql/log.cc, sql/partition_info.cc, sql/semisync_master.cc, storage/innobase/btr/btr0btr.cc, storage/innobase/dict/dict0load.cc, storage/innobase/handler/ha_innodb.cc, storage/innobase/os/os0file.cc, storage/innobase/row/row0sel.cc, storage/maria/ma_info.c, storage/maria/ma_loghandler.c
* Update: *The Jira issue number for this PR is: [MDEV-35430](https://jira.mariadb.org/browse/MDEV-35430)*
* Sibling of #3485
* To clarify, my coding period for Google Summer of Code (GSoC) 2024 ended.
While this code originates from my GSoC project, this publication (i.e., commit and PR descriptions) isn’t.
#3360 uncovered countless *potential minor security vulnerabilities* on `my_snprintf` uses.
This commit ports a squashed subset of their fixes according to the bug-fixing process to 10.6, covering cases that weren’t applicable for 10.5 (#3485).
(My GSoC mentor said that they aren’t much of a problem and I can open a PR normally.)
Similar to #3485, I haven’t changed `size_t`s from …
=> Extract some of #3360 fixes to 10.6.x

sql/opt_range.cc
* Update: *The Jira issue number for this PR is: [MDEV-35432](https://jira.mariadb.org/browse/MDEV-35432)*
This commit backports a lone fix from #3360 for 11.2, our oldest 11.x in maintenance.
It is the only mistake introduced during 11.0–11.2.
Not needed
Use `DBUG` to confirm that the log doesn’t have an extraneous `ll` suffix
=> Fix `DBUG_PRINT` format of `group_trp->records`

mysys/array.c, mysys/waiting_threads.c, plugin/hashicorp_key_management/hashicorp_key_management_plugin.cc, sql/log_event_server.cc, sql/sql_plugin.cc, sql/sql_table.cc, storage/innobase/fil/fil0fil.cc, storage/innobase/fsp/fsp0fsp.cc, storage/innobase/handler/ha_innodb.cc, storage/innobase/log/log0recv.cc, storage/innobase/os/os0file.cc, storage/maria/ma_loghandler.c
* Update: *The Jira issue number for this PR is: [MDEV-35431](https://jira.mariadb.org/browse/MDEV-35431)*
* Sibling of #3485 and #3493
* To clarify, my coding period for Google Summer of Code (GSoC) 2024 ended.
While this code originates from my GSoC project, this publication (i.e., commit and PR descriptions) isn’t.
#3360 uncovered countless *potential minor security vulnerabilities* on `my_snprintf` uses.
This commit ports a squashed subset of their fixes according to the bug-fixing process to 10.11, covering cases that weren’t applicable for 10.5 (#3485) and 10.6 (#3493).
(My GSoC mentor said that they aren’t much of a problem and I can open a PR normally.)
Similar to the previous …
=> Extract some of #3360 fixes to 10.11.x

mysql-test/main/mysql_upgrade.result, mysql-test/main/mysql_upgrade.test, plugin/auth_socket/CMakeLists.txt
Fixed main.mysql_upgrade to pass when unix_socket plugin is unavailable.
Also don't redefine _GNU_SOURCE, which was previously defined by command line/environment. This fixes silent auth_socket build failure with MYSQL_MAINTAINER_MODE=ERR.
N/A
mtr main.mysql_upgrade
=> MDEV-35421 - main.mysql_upgrade fails without unix_socket plugin

storage/innobase/include/btr0cur.h
After MDEV-21136 fix, the btr_cur_t::path_arr field stayed declared, but not used, wasting space in each btr_cur_t and btr_pcur_t. Remove it.
=> MDEV-35457 Remove btr_cur_t::path_arr

extra/mariabackup/xtrabackup.cc, storage/innobase/btr/btr0sea.cc, storage/innobase/buf/buf0buddy.cc, storage/innobase/dict/dict0crea.cc, storage/innobase/dict/dict0dict.cc, storage/innobase/dict/dict0load.cc, storage/innobase/fil/fil0fil.cc, storage/innobase/include/buf0buf.h, storage/innobase/include/dict0boot.h, storage/innobase/include/dict0dict.h, storage/innobase/include/fil0fil.h, storage/innobase/include/hash0hash.h, storage/innobase/include/lock0lock.h, storage/innobase/include/lock0priv.inl, storage/innobase/include/univ.i, storage/innobase/include/ut0rnd.h, storage/innobase/include/ut0rnd.inl, storage/innobase/lock/lock0lock.cc, storage/innobase/lock/lock0prdt.cc, storage/innobase/row/row0mysql.cc
This supercedes #3593, which was accidentally closed and can’t be resurrected.
The `HASH_` macros are unnecessarily obfuscating the logic, so we had better replace them.
`hash_cell_t::remove()`: Implement most of the `HASH_DELETE` logic. This is based on `buf_pool_t::page_hash_table::remove()`.
`xb_filter_hash_free()`: Avoid any hash table lookup; just traverse the hash bucket chains and free each element.
`rm_if_not_found()`: Make use of `find_filter_in_hashtable()`.
`dict_sys_t::acquire_temporary_table()`, `dict_sys_t::find_table()`: Define non-inline to avoid unnecessary code duplication.
`dict_sys_t::add(dict_table_t *table)`, `dict_table_rename_in_cache()`: Look for duplicate while finding the insert position.
`dict_table_change_id_in_cache()`: Merged to the only caller …
=> MDEV-35190 HASH_SEARCH duplicates effort before HASH_INSERT or HASH_DELETE

client/mysqldump.c, plugin/server_audit/server_audit.c, sql/item_cmpfunc.cc, sql/item_geofunc.cc, sql/item_strfunc.cc, sql/log_event_server.cc, sql/my_decimal.cc, sql/slave.cc, sql/sql_acl.cc, sql/sql_class.h, sql/sql_trigger.cc, sql/sql_type.h, sql/sql_yacc.yy, sql/table.cc, sql/wsrep_var.cc, storage/innobase/handler/ha_innodb.cc, storage/innobase/trx/trx0undo.cc, storage/maria/s3_func.c, storage/mroonga/lib/mrn_multiple_column_key_codec.cpp, storage/myisam/ha_myisam.cc, storage/myisam/mi_check.c, storage/myisam/myisamchk.c, storage/oqgraph/ha_oqgraph.cc, storage/spider/spd_db_mysql.cc
* Update: *The Jira issue number for this PR is: [MDEV-35429](https://jira.mariadb.org/browse/MDEV-35429)*
* To clarify, my coding period for Google Summer of Code (GSoC) 2024 ended.
While this code originates from my GSoC project, this publication (i.e., commit and PR descriptions) isn’t.
#3360 uncovered countless *potential minor security vulnerabilities* on `my_snprintf` uses.
This commit ports a squashed subset of their fixes according to the bug-fixing process to 10.5, our oldest maintained version.
(My GSoC mentor said that they aren’t much of a problem and I can open a PR normally.)
Most `size_t`s were still simple `uint`s back here, though I didn’t include their changes from `%d` …
=> Extract some of #3360 fixes to 10.5.x

storage/innobase/btr/btr0cur.cc, storage/innobase/buf/buf0buf.cc, storage/innobase/buf/buf0rea.cc, storage/innobase/include/buf0buf.h, storage/innobase/include/buf0rea.h, storage/innobase/row/row0merge.cc
A race condition was observed between two `buf_page_get_zip()` for a page. One of them had proceeded to `buf_read_page()`, allocating and x-latching a `buf_block_t` that initially comprises only an uncompressed page frame. While that thread was waiting inside `buf_block_alloc()`, another thread would try to access the same page. Without acquiring a page latch, it would wrongly conclude that there is corruption because no compressed page frame exists for the block.
`buf_page_get_zip()`: Simplify the logic and correct the documentation. Always acquire a shared latch to prevent any race condition with a concurrent read operation. No longer increment a buffer-fix; the latch is sufficient for preventing page relocation or eviction.
`buf_read_page()`: Add the parameter `bool unzip=true`. In …
=> MDEV-35413 InnoDB: Cannot load compressed BLOB

storage/innobase/dict/dict0load.cc
`table->space_id` is `ulint` on 10.6 and `uint32_t` on 10.11+, but I included its format specifier change in 10.6 rather than 10.11.
PR #3650 reverts the change from 10.6; this commit reapplies it on 10.11 as a follow up on its batch (MDEV-35431, merged #3518).
N/A
Note that this’ll be a merge conflict if this merges before #3518 merges to 10.11.
N/A
=> MDEV-35478 part 2: Redo `space_id` format fix

storage/innobase/dict/dict0load.cc
It is `ulint` on 10.6 and `uint32_t` on 10.11+, but I included its format specifier change in 10.6 (MDEV-35430, merged #3493) rather than 10.11.
This commit reverts that change so 10.11 can reapply it.
N/A
N/A
=> MDEV-35478 Correction for table->space_id in dict_load_tablespace() was mistakenly applied on an earlier branch

storage/innobase/ha/ha0storage.cc
ha_storage_put_memlim(): Initialize node->next in order to avoid a crash on a subsequent invocation, due to dereferencing an uninitialized pointer.
This fixes a regression that had been introduced in #3584 (MDEV-35189).
Because the bug is being fixed in the same releases that introduce it, no mention is needed. 
Apparently, this subsystem is badly covered by existing regression tests. It would be challenging to test this, because there is some rate-limiting of updates of the cache. This was tested with a small stress test using `cmake -DWITH_ASAN=ON`.
=> MDEV-35472 Server crash in ha_storage_put_memlim upon reading from INNODB_LOCKS

extra/innochecksum.cc, mysql-test/suite/innodb/r/innochecksum_undo_page.result, mysql-test/suite/innodb/t/innochecksum_undo_page.opt, mysql-test/suite/innodb/t/innochecksum_undo_page.test, mysql-test/suite/innodb_zip/r/innochecksum_2.result, mysql-test/suite/innodb_zip/r/innochecksum_3.result
Innochecksum misinterprets the freed pages as active one.
This leads the user to think there are too many valid
pages exist.
- To avoid this confusion, innochecksum introduced one
more option --skip-freed-pages and -r to avoid the freed
pages while dumping or printing the summary of the tablespace.
- Innochecksum can safely assume the page is freed if
the respective extent doesn't belong to a segment and marked as
freed in XDES_BITMAP in extent descriptor page.
- Innochecksum shouldn't assume that zero-filled page as extent
descriptor page.
./mtr innodb.innochecksum_undo_page
=> MDEV-35394  Innochecksum misinterprets freed undo pages

sql/mysqld.cc
Follow up to https://github.com/MariaDB/server/pull/3459. 
Differences in `handle_connections_sockets()` are larger in comparison to 10.11 port so I thought to make it a separate branch.
---
Backport of 2f5174e556cd247133aa14d7b37372ae49fe83c5: MDEV-33075 Resolve server shutdown issues on macOS, Solaris, and FreeBSD.
This commit addresses multiple server shutdown problems observed on macOS,
Solaris, and FreeBSD:
1. Corrected a non-portable assumption where socket shutdown was expected
to wake up poll() with listening sockets in the main thread.
Use more robust self-pipe to wake up poll() by writing to the pipe's write
end.
2. Fixed a random crash on macOS from pthread_kill(signal_handler)
when the signal_handler was detached and the thread had already exited.
Use more robust …
=> MDEV-33075 [backport/2f5174e556] [10.5] Resolve server shutdown issues on macOS, Solaris, and FreeBSD

include/my_rdtsc.h
Misplaced brace in my_rdtsc.h results in RV32 failing to compile.
ref: https://github.com/MariaDB/server/pull/1981/files#r1859762957
Thanks Jessica Clark for the note.
Fixed compilation on RISC v 32
Cross compile to a RISCv32
=> MDEV-35513 fails to compile on RISC-V 32

mysql-test/suite/innodb/r/purge_pessimistic.result, mysql-test/suite/innodb/t/purge_pessimistic.opt, mysql-test/suite/innodb/t/purge_pessimistic.test, storage/innobase/btr/btr0cur.cc, storage/innobase/include/trx0sys.h, storage/innobase/include/trx0trx.h, storage/innobase/include/ut0pool.h, storage/innobase/row/row0purge.cc, storage/innobase/trx/trx0sys.cc
`row_purge_remove_sec_if_poss_leaf()`: If the `PAGE_MAX_TRX_ID` belongs to an active transaction, return the impossible value `~0` so that `row_purge_remove_sec_if_poss_tree()` is guaranteed to recheck if the record needs to be purged. It could be the case that the active transaction would insert this record between the time this check completed and `row_purge_remove_sec_if_poss_tree()` acquired a latch on the secondary index leaf page again.
This fixes a regression that had been introduced in #3448.
InnoDB could issue bogus messages into the error log:
```
[ERROR] InnoDB: tried to purge non-delete-marked record in index …
```
I tested this on `CMAKE_BUILD_TYPE=RelWithDebInfo` and `CMAKE_BUILD_TYPE=Debug` builds by repeatedly running the following test case:
```sql
--source …
```
=> MDEV-35508 Race condition between purge and secondary index INSERT or UPDATE

storage/innobase/btr/btr0cur.cc
`btr_cur_t::search_leaf()`: In the `BTR_SEARCH_PREV` and `BTR_MODIFY_PREV` modes, reset the previous search status before invoking `page_cur_search_with_match()`. Otherwise, we the search could invoke in a totally wrong subtree.
See [MDEV-35525](https://jira.mariadb.org/browse/MDEV-35525).
The bug was reproduced as part of testing #3562 in the random query generator (RQG) by using `innodb_change_buffering=all` and `innodb_page_size=4k`. Possibly also using `innodb_change_buffering_debug`.
=> MDEV-35525: Index corruption in reverse scans

unittest/json_lib/json_normalize-t.c
Like MDEV-35583, initialize THR_KEY_mysys explicitly by calling MY_INIT and my_end.
=> MDEV-35585 unit.json_normalize crashes on mac

mysql-test/suite/innodb/r/alter_copy_bulk.result, mysql-test/suite/innodb/r/innodb-64k-crash,dynamic.rdiff, mysql-test/suite/innodb/r/innodb-64k-crash,redundant.rdiff, mysql-test/suite/innodb/r/innodb-64k-crash.result, mysql-test/suite/innodb/r/insert_into_empty,32k.rdiff, mysql-test/suite/innodb/r/insert_into_empty,64k.rdiff, mysql-test/suite/innodb/r/insert_into_empty,8k.rdiff, mysql-test/suite/innodb/r/insert_into_empty.result, mysql-test/suite/innodb/t/alter_copy_bulk.test, mysql-test/suite/innodb/t/innodb-64k-crash.opt, mysql-test/suite/innodb/t/innodb-64k-crash.test, mysql-test/suite/innodb/t/insert_into_empty.test, storage/innobase/row/row0merge.cc
Problem:
=======
InnoDB wrongly stores the primary key field in externally stored off page during bulk insert operation. This leads to assert failure.
Solution:
========
row_merge_buf_blob(): Should store the primary key fields inline. Store the variable length field data externally based on the row format of the table.
g.
./mtr innodb.alter_copy_bulk innodb.insert_into_empty
=> MDEV-35475  Assertion `!rec_offs_nth_extern(offsets1, n)' failed in cmp_rec_rec_simple_field

unittest/mysys/dynstring-t.c, unittest/sql/my_json_writer-t.cc
These tests, unit.my_json_writer and unit.dynstring, rely on THR_KEY_mysys but it is not initialized.  On Linux, the corresponding thread variable is null, but on macOS it has a nonzero value.  In all cases, initialize the variable explicitly by calling MY_INIT and my_end appropriately.
=> MDEV-35583 Tests failing on macOS

client/mysqlimport.c, client/mysqltest.cc, mysys/thr_alarm.c, mysys/thr_timer.c, plugin/feedback/sender_thread.cc, sql/mysqld.cc, storage/mroonga/vendor/groonga/src/groonga_benchmark.c, tests/thread_test.c, unittest/mysys/stack_allocation-t.c, unittest/sql/my_apc-t.cc
Threads can normally exit without a explicit pthread_exit call.
There seem to date to old glibc bugs, many around 2.2.5.
The semi related bug was https://bugs.mysql.com/bug.php?id=82886.
To improve safety in the signal handlers DBUG_* code was removed.
These where also needed to avoid some MSAN unresolved stack issues.
This is effectively a backport of 2719cc4925c032f483edb0e61c0f487e0c429ae6.
Nothing, internal refactor
Plenty of unit tests and other  tests around exit to sufficiently test these changes.
=> MDEV-35574 remove obsolete pthread_exit calls

include/my_sys.h, mysys/my_create.c, mysys/my_init.c, mysys/my_open.c, mysys/my_static.c, mysys/my_symlink2.c, storage/innobase/handler/ha_innodb.cc, storage/innobase/include/os0file.h, storage/innobase/os/os0file.cc
The mode_t type is required by the standard for
umask and open libc calls.
This has only been changed inside innodb as the global my_umask (which should be the same type), but is an int, is exposed as a defined plugin accessable variable and therefore would break ABI compatibility if this was changed.
It also isn't creating compile warnings in the global server, only within innodb.
Clang-19 reports these was warnings:
[55/123] Building CXX object storage/innobase/CMakeFiles/innobase.dir/os/os0file.cc.o storage/innobase/os/os0file.cc:1075:46: warning: implicit conversion loses integer precision: 'ulint' (aka 'unsigned long') to 'mode_t' (aka 'unsigned int') [-Wshorten-64-to-32]
1075 |                 file = open(name, create_flag | O_CLOEXEC, os_innodb_umask);
|                        ~~~~ …
=> Change my_umask{,_dir} to mode_t and remove os_innodb_umask

storage/innobase/unittest/innodb_sync-t.cc
unit.innodb_sync calls my_end to cleanup its memory
=> MDEV-35587 unit.innodb_sync leaks memory on mac

storage/innobase/buf/buf0flu.cc, storage/innobase/include/log0log.h, storage/innobase/log/log0log.cc
If InnoDB is killed in such a way that there had been no writes to a newly resized `ib_logfile101` after it replaced `ib_logfile0` in `log_t::write_checkpoint()`, it is possible that recovery will accidentally interpret some garbage at the end of the log as valid.
`log_t::write_buf()`: To prevent the corruption, write an extra NUL byte at the end of `log_sys.resize_buf`, like we always did for the main `log_sys.buf`. To remove some conditional branches from a time critical code path, we instantiate a separate template for the rare case that the log is being resized. Define as `__attribute__((always_inline))` so that this will be inlined also in the rare case the log is being resized.
`log_t::writer`: Pointer to the current implementation of `log_write_up_to()`. For quick access, this is …
=> MDEV-35577  online log file resizing corrupts redo log

unittest/json_lib/json_normalize-t.c
The ok() function outputs the TAP context string in both the success and failure cases. The strings were worded to make sense in the failure case, yet were confusing in the success case. This changes the strings to be appropriate, and even more informative in either the success or failure cases.  In the cases where input, expected, and result values are included in the context string, they have been adjusted such that expected and actual result values are aligned for easy visual comparison.
This adjusts the context strings of the unit test assertions such that they make sense in both the success and failure cases, as well as aligns the expected and actual result strings for at-a-glance distinction.
No release notes are needed for this change in unittest output
Run …
=> unittest output improvement for json_normalize-t

strings/my_vsnprintf.c
strerror_s on Linux will, for unknown error codes, display 'Unknown error <codenum>' and our tests are written with this assumption. However, on macOS, sterror_s returns 'Unknown error: <codenum>' in the same case, which breaks tests.  Make my_strerror consistent across the platforms by removing the ':' when present.
=> MDEV-35578 innodb_gis.rtree_debug fails on mac

storage/innobase/handler/ha_innodb.cc
The assertion fails during wsrep recovery step, in function innobase_rollback_by_xid(). The transaction's xid is normally cleared as part of lookup by xid, unless the transaction has a wsrep specific xid.
This is a regression from MDEV-24035 (commit ddd7d5d8e34c3edd) which removed the part clears xid before rollback for transaction with a wsrep specific xid.
Nothing.
Should fix regression on wsrep.wsrep-recover.
=> MDEV-35660 Assertion `trx->xid.is_null()' failed

mysql-test/suite/innodb/r/stats_persistent.result, mysql-test/suite/innodb/t/stats_persistent.test, storage/innobase/include/dict0mem.h, storage/innobase/pars/pars0opt.cc
`opt_calc_index_goodness()`: Correct an inaccurate condition. We can very well use a clustered index of a table that is subject to online rebuild. But we must not choose an index that has not been committed (it is a secondary index that was not fully created) or that is corrupted or not a normal B-tree index.
`opt_search_plan_for_table()`: Remove some redundant code, now that `opt_calc_index_goodness()` checks against corrupted indexes.
During the execution of `OPTIMIZE TABLE mysql.innodb_index_stats` or `OPTIMIZE TABLE mysql.innodb_table_stats` or a similar statement, InnoDB could execute an unnecessary and costly full scan of these tables while updating persistent statistics.
The test case allows this code to be exercised. The main observation in the following:
```sh
./mtr --rr …
```
=> MDEV-35443: opt_search_plan_for_table() may degrade to full table scan

unittest/mysys/CMakeLists.txt, unittest/mysys/dynamic_array-t.c
This demonstrates and tests the basic usage of DYNAMIC_ARRAY.
Additional tests could be added to demonstrate and test the remaining functions and capabilities.
No release notes are needed for this change, as this only adds a test.
build and then run:
unittest/mysys/dynamic_array-t
=> MDEV-35683: add basic unit test for DYNAMIC_ARRAY

mysql-test/suite/innodb/r/insert_into_empty,4k.rdiff, mysql-test/suite/innodb/r/insert_into_empty,8k.rdiff, mysql-test/suite/innodb/r/insert_into_empty.result, mysql-test/suite/innodb/t/insert_into_empty.test, storage/innobase/row/row0ins.cc
Problem:
=======
- insert..select statement on partition table fails to use bulk insert for the transaction.
Solution:
========
- Enable the bulk insert operation for insert..select statement for partition table.
=> MDEV-34119  Assertion `page_dir_get_n_heap(new_page) == 2U' failed in dberr_t PageBulk::init()

mysql-test/suite/rpl/r/rpl_xa.result, mysql-test/suite/rpl/r/rpl_xa_gtid_pos_auto_engine.result, sql/share/errmsg-utf8.txt
Copy error messages from 11.7 down to 11.4 (they are unused) to preserve their order
=> MDEV-35773 ER_PSEUDO_THREAD_ID_OVERWRITE in 11.4 shifts error messages

extra/mariabackup/xtrabackup.cc, mysql-test/suite/encryption/r/debug_key_management.result, mysql-test/suite/encryption/r/doublewrite_debug.result, mysql-test/suite/encryption/t/debug_key_management.test, mysql-test/suite/encryption/t/doublewrite_debug.opt, mysql-test/suite/encryption/t/doublewrite_debug.test, storage/innobase/buf/buf0buf.cc, storage/innobase/buf/buf0dblwr.cc, storage/innobase/include/log0recv.h, storage/innobase/log/log0recv.cc, storage/innobase/srv/srv0start.cc
- InnoDB fails to recover the full crc32 encrypted page from doublewrite buffer. The reason is that buf_dblwr_t::recover() fails to identify the space id from the page because the page has been encrypted from FIL_PAGE_FILE_FLUSH_LSN_OR_KEY_VERSION bytes.
Fix:
===
buf_dblwr_t::recover(): preserve any pages whose space_id does not match a known tablespace. These could be encrypted pages of tablespaces that had been created with
innodb_checksum_algorithm=full_crc32.
buf_page_t::read_complete(): If the page looks corrupted and the tablespace is encrypted and in full_crc32 format, try to restore the page from doublewrite buffer.
recv_dblwr_t::recover_encrypted_page(): Find the page which has the same page number and try to decrypt the page using space->crypt_data. After decryption, compare the …
=> MDEV-34898   Doublewrite recovery of innodb_checksum_algorithm=full_crc32 encrypted pages does not work

mysql-test/suite/innodb/r/create_select.result, mysql-test/suite/innodb/t/create_select.test, storage/innobase/handler/ha_innodb.cc
`ha_innobase::delete_table()`: Clear `trx->dict_operation_lock_mode` after, not before `invoking trx->rollback()`, so that `row_undo_mod_parse_undo_rec()` will be invoked with `dict_locked=true` and `dict_sys_t::freeze()` will not be invoked for loading a table definition. Inside `dict_sys_t::freeze()`, an assertion `!have_any()` would fail when the current thread is already holding the latch.
This fixes up c5fd9aa562fb15e8d6ededceccbec0c9792a3243 (MDEV-25919).
InnoDB could hang if `CREATE TABLE…SELECT` would fail, for example, due to a lock wait timeout.
```sh
./mtr innodb.create_select
```
=> MDEV-35647 Possible hang during CREATE TABLE…SELECT error handling

mysql-test/main/myisam_explain_non_select_all.result, mysql-test/suite/innodb/r/innodb.result, mysql-test/suite/innodb/r/innodb_mysql.result, mysql-test/suite/perfschema/r/multi_table_io.result, sql/sql_class.h, sql/sql_delete.cc
Reintroduces delete_while_scanning optimization for multi_delete. Reverse some test changes from the initial feature devlopment now that we delete-on-the-fly once again.
=> MDEV-35568 Reintroduce delete_while_scanning for multi_delete

mysql-test/main/bad_startup_options.result, mysql-test/main/bad_startup_options.test, mysql-test/main/ssl_cipher.result, mysql-test/main/ssl_cipher.test
Increase TLS functionality coverage in MTRs.
A few additional test coverage added:
- Server behaves safely with invalid `ssl-cipher` configuration
- Server behaves safely when cipher and server certificate are incompatible
N/A
N/A
BSD-new license. I am contributing on behalf of my employer Amazon Web
Services, Inc.
=> Add MTRs to further test coverage around TLS functionality

storage/innobase/btr/btr0sea.cc, storage/innobase/buf/buf0buf.cc, storage/innobase/buf/buf0dblwr.cc, storage/innobase/buf/buf0flu.cc, storage/innobase/buf/buf0rea.cc, storage/innobase/fil/fil0crypt.cc, storage/innobase/fil/fil0fil.cc, storage/innobase/handler/ha_innodb.cc, storage/innobase/include/buf0buf.h, storage/innobase/include/buf0dblwr.h, storage/innobase/include/buf0flu.h, storage/innobase/include/buf0rea.h, storage/innobase/include/buf0types.h, storage/innobase/include/fil0fil.h, storage/innobase/include/os0file.h, storage/innobase/log/log0recv.cc, storage/innobase/mtr/mtr0mtr.cc, storage/innobase/os/os0file.cc
This is a follow up to #3531.
Most InnoDB functions do not throw any exceptions, not even indirectly `std::bad_alloc`, which could be thrown by a C++ memory allocation function. Let us annotate many functions with `noexcept` in order to reduce the code footprint related to exception handling.
This is a minor change that does not need to be documented.
This low level code should be well covered by the existing regression tests.
=> MDEV-35438 Annotate InnoDB I/O functions with noexcept

mysql-test/suite/encryption/r/recovery_memory.result, mysql-test/suite/encryption/t/recovery_memory.opt, mysql-test/suite/encryption/t/recovery_memory.test, storage/innobase/log/log0recv.cc
This fixes a regression that had been introduced in #3507. In a multi-batch crash recovery, we would fail to invoke `fil_space_set_recv_size_and_flags()` while parsing the remaining log, before starting the first recovery batch.
`recv_sys_t::parse<storing=NO>()`: Do invoke `fil_space_set_recv_size_and_flags()` and do parse enough of page 0 to facilitate that.
InnoDB crash recovery could fail to recover the correct size of a file when the `innodb_buffer_pool_size` is too small to process the `ib_logfile0` in a single batch.
```sh
./mtr encryption.recovery_memory
```
=> MDEV-35699 Multi-batch recovery occasionally fails

storage/innobase/include/log0log.h, storage/innobase/log/log0log.cc
`log_t::persist()`: Remove the parameter `holding_latch`, and assert `latch_holding_any()`. We used to avoid acquiring a latch when log resizing was not in progress. That allowed a race condition to occur where `log_t::write_checkpoint()` has just completed log resizing. In that case, we could wrongly invoke `pmem_persist()` on the old `log_sys.buf` instead of the new one, which was shortly before known as `log_sys.resize_buf`.
`log_write_persist()`: A non-inline wrapper function that will invoke `log_sys.persist()` while holding a shared `log_sys.latch`.
This is a rare race condition, probably not worth mentioning, because the use of PMEM is very rare.
This code is being covered by the following test:
```sh
./mtr innodb.log_file_size_online
```
=> MDEV-35802 Race condition in log_t::persist()

sql/mysqld.cc, sql/sql_plugin.cc, storage/spider/spd_copy_tables.cc, storage/spider/spd_direct_sql.cc, storage/spider/spd_ping_table.cc, storage/spider/spd_udf.cc, storage/spider/spd_udf.h
clang/UBSAN shows this up as an error as the argument is incorrect.
The argument is void* rather than char*.
not required.
basic bootstrap when compiled WITH_UBSAN under clang.
=> MDEV-35554/ MDEV-33158 UBSAN runtime error: call to function show_cached_thread_count() (and plugin interface)

client/mysqlbinlog.cc, mysql-test/suite/binlog/r/binlog_mysqlbinlog_warn_stop_datetime.result, mysql-test/suite/binlog/r/binlog_mysqlbinlog_warn_stop_position.result, mysql-test/suite/binlog/t/binlog_mysqlbinlog_warn_stop_datetime.inc, mysql-test/suite/binlog/t/binlog_mysqlbinlog_warn_stop_datetime.test, mysql-test/suite/binlog/t/binlog_mysqlbinlog_warn_stop_position.inc, mysql-test/suite/binlog/t/binlog_mysqlbinlog_warn_stop_position.test
Fix regression introduced by commit [9588526](https://github.com/MariaDB/server/commit/95885261f0) which attempted to address [MDEV-27037](https://jira.mariadb.org/browse/MDEV-27037). With the regression, mariadb-binlog cannot process multiple log files when --stop-datetime is specified.
The PR is to keep recording timestamp of last processed event, and after all log files are processed, if the last recorded timestamp has not reached specified --stop-datetime, it will emit a warning. This applies when processing local log files, or log files from remote servers. Also added MTR test cases to ensure it works as expected in different scenario.
This PR does not impact the commit [242b67f](https://github.com/MariaDB/server/commit/242b67f1de) to emit warning when reaching EOF before specified …
=> MDEV-35528: mariadb-binlog cannot process more than 1 logfiles when --stop-datetime is specified

include/mysql/plugin.h, include/mysql/service_debug_sync.h
storage/maria/ma_open.c:352:7: runtime error: call to function debug_sync(THD*, char const*, unsigned long) through pointer to incorrect function type 'void (*)(void *, const char *, unsigned long)'
The THD argument is a void *. Because of the way myisam is .c files the function prototype is mismatched.
As Marko pointed out the MYSQL_THD is declared as void * in C.
Thanks Jimmy Hú for noting that struct THD is the equalivalant in C to the class THD. The C NULL was also different to the C++ nullptr.
Corrected the definitions of MYSQL_THD and DEBUG_SYNC_C to be C and C++ compatible.
nothing to be said, internal fix.
mtr + debug + ubsan - will not start a basic bootstrap without this fix.
=> MDEV-35687 Various UBSAN function-type-mismatch debug_sync and myisam

sql/log.cc
`ATTRIBUITE_FORMAT` from #3360 uncovers issues on `my_snprintf` uses.
This commit fixes the one in `Binlog_commit_by_rotate::` `replace_binlog_file()` about “required size too big”.
All I found is that it’s not present in 11.4 (after I prepared previous batches for all maintained branches), for GitHub blame can’t process a file with over 10K lines.
*But 11.7 wasn’t Generally Available yet?*
I suppose we can trigger this issue by running the `simulate_required_size_too_big` test (wherever it is) in __32-bit Linux__.
=> MDEV-35818: Fix `replace_binlog_file` info message

sql/semisync_master.cc
* This came after I prepared #3493.
N/A? – This only impacts Big-Endian CPUs.
So just #3360.
=> MDEV-35430: Add cast to semi-sync wait skip msg

extra/mariabackup/xtrabackup.cc, mysql-test/suite/mariabackup/innodb_redo_log_overwrite.combinations, mysql-test/suite/sys_vars/r/sysvars_innodb.result, mysql-test/suite/sys_vars/t/sysvars_innodb.test, storage/innobase/CMakeLists.txt, storage/innobase/handler/ha_innodb.cc, storage/innobase/include/log0log.h, storage/innobase/include/log0recv.h, storage/innobase/include/univ.i, storage/innobase/log/log0log.cc, storage/innobase/log/log0recv.cc, storage/innobase/mtr/mtr0mtr.cc, storage/innobase/srv/srv0start.cc
`HAVE_INNODB_MMAP`: Remove, and unconditionally enable this code.
`log_mmap()`: On 32-bit systems, ensure that the size fits in 32 bits.
`log_t::resize_start()`, `log_t::resize_abort()`: Only handle memory-mapping if `HAVE_PMEM` is defined. The generic memory-mapped interface is only for reading the log in recovery. Writable memory mappings are only for persistent memory, that is, Linux file systems with `mount -o dax`.
The configuration parameter `innodb_log_file_mmap` will be available in all target platforms.
This is covered by the regression test suite. The test `sys_vars.sysvars_innodb` will ensure that the parameter is present.
I tested this by running the regression test suite on IA-32 and AMD64 in my local development environment.
=> MDEV-35785 innodb_log_file_mmap is not defined on 32-bit systems

mysql-test/include/mtr_check.sql, mysql-test/suite/innodb/r/log_file_size_online.result, mysql-test/suite/innodb/t/log_file_size_online.test, storage/innobase/log/log0log.cc
`log_t::resize_start()`: If the `ib_logfile101` cannot be created, be sure to reset `log_sys.resize_lsn`.
`log_t::resize_abort()`: In case `SET GLOBAL innodb_log_file_size` is aborted, delete the `ib_logfile101`.
The error handling of `SET GLOBAL innodb_log_file_size` was improved.
```bash
./mtr --parallel=6 innodb.log_file_size_online{,,,} --repeat=5
```
Without the fix, the test would fail to resize the log from 5 MiB.
=> MDEV-35810 Missing error handling in log resizing

include/my_cpu.h
`MY_RELAX_CPU()`: On GCC and compatible compilers (including clang and its derivatives), let us use a null inline assembler block as the fallback. This should benefit s390x and LoongArch, for example.
Also, let us remove the generic fallback block that does exactly the opposite of what this function aims to achieve: avoid hogging the memory bus so that other threads will have a chance to let our spin loop to proceed.
On RISC-V, we will use `__builtin_riscv_pause()` which is a valid instruction encoding in all ISA versions according to https://gcc.gnu.org/pipermail/gcc-patches/2021-January/562936.html
Spin loops on other ISA than x86, POWER, ARM were simplified.
This is a low level change that is covered by `./mtr --suite=innodb`. On https://buildbot.mariadb.org we might  observe a …
=> MDEV-35827 The generic MY_RELAX_CPU is expensive

mysql-test/suite/mariabackup/undo_truncate.combinations, mysql-test/suite/mariabackup/undo_truncate.opt, mysql-test/suite/mariabackup/undo_truncate.result, mysql-test/suite/mariabackup/undo_truncate.test, storage/innobase/log/log0recv.cc
`recv_sys_t::parse()`: Correctly handle the `storing==BACKUP` case, and simplify some logic around `storing==YES` as well.
`mariadb-backup --backup` could fail when backing up a server where `innodb_undo_log_truncate=ON` is set.
The added test `mariabackup.undo_truncate` is based on an idea of @Thirunarayanan (#3743). It nondeterministically covers this logic, including the function `backup_undo_trunc()`, for both `innodb_encrypt_log=ON` and `innodb_encrypt_log=OFF`.
=> MDEV-35830 Fix innodb_undo_log_truncate in backup

mysql-test/main/lowercase_table4.result
Update main.lowercase_table4 for new default collation at 11.6 as described in https://mariadb.com/kb/en/setting-character-sets-and-collations/
=> MDEV-35805 Update main.lowercase_table4 for new default collation

mysys_ssl/openssl.c
Based on FreeBSD patch.
The FreeBSD inclusion of check_openssl_compatibility prevented any use of the crypto callbacks and as such the later differences where ignored.
The later differences in coc_malloc didn't propegate to the other callback functions of CRYPTO_set_mem_functions where a reduced argument list also applied.
Looking where[2] libressl added the functions it was of the same prototype 10 years ago so omitting any version check.
[1] https://github.com/freebsd/freebsd-ports/blob/a34cf9c2dbf503c8248371ba3bab24f34d2d045d/databases/mariadb106-server/files/patch-mysys__ssl_openssl.c
[2] https://github.com/libressl/openbsd/commit/5ebad8aceae77c6da6a1e47c3f7e70e8ffae3dae#diff-7f393e5489e6c5780773408f11ca27d9b3bb8f55b174631a1e9467a1dd3010b9R22
Add compatibility for libressl
Build/test …
=> MDEV-35838 libressl support differences in CRYPTO_set_mem_functions

mysql-test/suite/innodb/r/bulk_load.result, mysql-test/suite/innodb/t/bulk_load.opt, mysql-test/suite/innodb/t/bulk_load.test, sql/sql_load.cc, storage/innobase/handler/ha_innodb.cc, storage/innobase/include/row0merge.h, storage/innobase/include/trx0trx.h, storage/innobase/row/row0ins.cc, storage/innobase/row/row0merge.cc, storage/innobase/trx/trx0rec.cc
Problem:
=======
- During load statement, InnoDB bulk operation relies on temporary directory and it got crash when exhausted.
Solution:
========
- For load statement, InnoDB bulk operation does the following
1) Avoids creation of temporary file for clustered index.
2) Use normal insert operation for clustered index
3) Writes the undo log for first insert operation alone
./mtr innodb.bulk_load
- x] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.
=> MDEV-34703  LOAD DATA INFILE using Innodb bulk load aborts

plugin/handler_socket/client/hslongrun.cpp, plugin/handler_socket/client/hstest.cpp, plugin/handler_socket/handlersocket/database.cpp, plugin/handler_socket/handlersocket/database.hpp, plugin/handler_socket/handlersocket/handlersocket.cpp, plugin/handler_socket/handlersocket/hstcpsvr.cpp, plugin/handler_socket/handlersocket/hstcpsvr.hpp, plugin/handler_socket/handlersocket/hstcpsvr_worker.cpp, plugin/handler_socket/handlersocket/hstcpsvr_worker.hpp, plugin/handler_socket/libhsclient/hstcpcli.hpp
Change uses of auto_ptr to unique_ptr
=> MDEV-35632 HandlerSocket uses deprecated C++98 auto_ptr

storage/innobase/lock/lock0lock.cc
It's supposed that the function gets the previous lock set on a record. But if there are several locks set on a record, it will return only the first one. Continue locks list iteration till the certain lock even if the certain bit in lock bitmap is set.
If the changes are not amenable to automated testing, …
=> MDEV-35708 lock_rec_get_prev() returns only the first record lock

client/mysqlimport.cc
Since bulk load is fixed, in some newer versions of the server, reenable it, after checking that MDEV-34703 was really fixed in server.
Reenabled Innodb bulk load in the mariadb-import for the server versions where MDEV-34703 was fixed.
mariadb-import will load Innodb tables. faster (for new versions of the server)
The only useful test is loading a large multi-GB  Innodb tables. This excludes the MTR testing.
=> MDEV-34703 followup - reenable Innodb bulk load in mariadb-import

mysql-test/suite/innodb/r/foreign_sql_mode,COPY,NON-STRICT.rdiff, mysql-test/suite/innodb/r/foreign_sql_mode,COPY,NOSTRICT.rdiff, mysql-test/suite/innodb/r/foreign_sql_mode,INPLACE,NON-STRICT.rdiff, mysql-test/suite/innodb/r/foreign_sql_mode.result, mysql-test/suite/innodb/t/foreign_sql_mode.combinations, mysql-test/suite/innodb/t/foreign_sql_mode.test, sql/sql_table.cc, storage/innobase/dict/dict0crea.cc, storage/innobase/handler/handler0alter.cc
- MDEV-34392(commit cc810e64d40367208b3f3f35c0277f0c8586a293) adds the check for nullability of foreign key column when foreign key relation is of UPDATE_CASCADE or UPDATE SET NULL. This check makes DDL fail when it violates foreign key nullability. This patch basically does the nullability check for foreign key column only for strict sql mode
./mtr innodb.foreign_sql_mode
=> MDEV-35445   Disable foreign key column nullability check for strict sql mode

sql/log_event_server.cc
Two-Phase ALTER added a `sa_seq_no` field, but `Gtid_log_event::write()`’s size calculation doesn’t have an addend in its name.
This means `sa_seq_no` can overrun `Gtid_log_event::write()`’s buffer.
This patch resizes the buffer to match `write()`'s code.
`Gtid_log_event` is variable-sized, but it’s possible that an instance flags all its fields for writing.
Fixed internal buffer overrun when writing a GTID event with all flags active.
**TODO:** We need a test that writes a `Gtid_log_event` with every field flagged active, not only so Valgrind (or a manual `DBUG_ASSERT`) can catch buffer overruns, but also to validate future new fields that they don’t impact any existing fields.
* ~~[ ] *This is a new feature or a refactoring, and the PR is based against the `main` branch.*~~
=> MDEV-35665 Potential Buffer Overrun in Gtid_log_event::write()

mysql-test/main/kill_debug.result, mysql-test/main/kill_debug.test, sql/handler.cc, sql/sql_table.cc
CHECKSUM TABLE causes variety of crashes when killed. This bug it not specific to PERFORMANCE_SCHEMA.
Removed duplicate handler::ha_rnd_end() call.
See description.
mtr kill_debug
=> MDEV-33285 - Assertion `m_table' failed in ha_perfschema::rnd_end on CHECKSUM TABLE

mysql-test/suite/innodb/r/foreign_key.result, mysql-test/suite/innodb/t/foreign_key.test, storage/innobase/row/row0ins.cc
`row_ins_cascade_calc_update_vec()`: Skip any virtual columns in the update vector of the parent table.
Based on mysql/mysql-server@0ac176453bfef7fb1fdfa70af74618c32910181c
See the test case.
```sh
./mtr innodb.foreign_key
```
=> MDEV-29182 Assertion fld->field_no < table->n_v_def failed on cascade

extra/wolfssl/CMakeLists.txt, extra/wolfssl/user_settings.h.in
Workaround build bugs with preprocessor flags du-jour
1. OPENSSL_ALL does not work anymore (error in ssl.h) nor WOLFSSL_MYSQL_COMPATIBLE, would work, when building library.
2. OPENSSL_EXTRA has to be used instead of OPENSSL_ALL now. WOLFSSL_MYSQL_COMPATIBLE needs to be used to workaround their conflicting definition of protocol_version, which is used in server code.
Upgrade WolfSSL submodule
By building and testing server on platforms where wolfssl is built.
=> Update WolfSSL to the latest release 5.7.6

mysql-test/suite/s3/mysqldump.result
This is a fixup for MDEV-32250, introduced via
b24ecd7ca6b5d59be524d4e6413736dc88c26ee0, the test case was not recorded given the new mariadb-dump format.
=> MDEV-35921: s3.mysqldump fails in buildbot

mysql-test/suite/innodb/r/avoid_deadlock_with_blocked.result, mysql-test/suite/innodb/t/avoid_deadlock_with_blocked.test, storage/innobase/include/hash0hash.h, storage/innobase/include/lock0lock.h, storage/innobase/include/lock0lock.inl, storage/innobase/include/lock0priv.h, storage/innobase/include/lock0priv.inl, storage/innobase/include/lock0types.h, storage/innobase/lock/lock0lock.cc, storage/innobase/lock/lock0prdt.cc
This version of the patch is 11.4. Please see 10.6 [pull request](https://github.com/MariaDB/server/pull/3723) for code review discussions and notes.
=> 11.4 MDEV-34877 Port "Bug #11745929 Change lock priority so that the transaction holding S-lock gets X-lock first" fix from MySQL to MariaDB

mysql-test/suite/perfschema/r/threads_innodb.result, mysql-test/suite/perfschema/t/threads_innodb.opt, storage/innobase/fil/fil0crypt.cc, storage/innobase/handler/ha_innodb.cc, storage/innobase/include/srv0srv.h
`page_encrypt_thread_key`: The key for `fil_crypt_thread()`.
All other InnoDB threads should already have been registered for performance_schema ever since
commit a2f510fccff23e5011486c240587b8f1a98ecacc
`PERFORMANCE_SCHEMA.THREADS` was not showing all InnoDB threads.
```sh
./mtr perfschema.threads_innodb
```
=> MDEV-33978 P_S.THREADS is not showing all server threads

mysql-test/suite/innodb/r/import_cfg.result, mysql-test/suite/innodb/r/innodb-wl5522-debug.result, mysql-test/suite/innodb/t/import_cfg.test, mysql-test/suite/innodb/t/innodb-wl5522-debug.test, storage/innobase/row/row0import.cc, storage/innobase/row/row0quiesce.cc
Problem:
=======
- Import tablespace fails to check the index fields descending property while matching the schema given in cfg file with the table schema.
Fix:
===
- Introduce the new version format for the cfg file which has the descending bool information for all index fields
row_import_cfg_read_index_fields(): Read the field descending property from cfg file depends on the config version
row_quiesce_write_index_fields(): Write the descending property of the index fields into cfg file
./mtr innodb.import_cfg --mem
Basically which does create old version cfg file and import tablespace with old cfg file
Taken the cfg file from 10.11 (with patch) and tried to run it in 10.6, tested how it behaves:
```
primary key with descending field in 10.6
========================================= …
```
=> MDEV-35169  ALTER TABLE...IMPORT TABLESPACE does not work with INDEX DESC

.gitlab-ci.yml, support-files/mini-benchmark.sh, tests/code_quality/cppcheck_ignorelist.txt, tests/code_quality/flawfinder_ignorelist.json
Make GitLab CI green again on `main` branch. See commit for details.
N/A
This can be tested easily by simply running GitLab CI on this branch before and after the changes in this PR.
Before this change:
With this change:
This targets intentionally the `main` branch as with the current number of failures it is not feasible to fix everything on all branches. It is better to have `main` green now, and be active in responding to future regressions on `main` as they are detected.
Note that this has no functional changes to MariaDB Server itself, and thus safe to merge. The faster this is merged, the faster we can start catching new testable regressions.
All new code of the whole pull request, including one or several files that are either new files or modified ones, are contributed under the …
=> All-green GitLab CI in main branch in January 2025

mysql-test/suite/innodb/r/innodb_row_lock_time_ms.result, mysql-test/suite/innodb/t/innodb_row_lock_time_ms.test
The test fails trying to compare (innodb/lock)_row_lock_time_avg with some limit. We can't predict (innodb/lock)_row_lock_time_avg value, because it's counted as the whole waiting time divided by the amount of waits. Both waiting time and amount of waits depend on the previous tests execution. The corresponding counters in lock_sys can't be reset with any query. Remove (innodb/lock)_row_lock_time_avg comparision from the test.
information_schema.global_status.innodb_row_lock_time can't be reset, compare its difference instead of absolute value.
Reviewed by: Marko Mäkelä
Include any changed system variables, status variables or behaviour. Optionally list any https://mariadb.com/kb/ pages that need …
=> MDEV-34489 innodb.innodb_row_lock_time_ms fails

mysql-test/suite/innodb_fts/r/index_table.result, mysql-test/suite/innodb_fts/t/index_table.test, storage/innobase/fts/fts0config.cc, storage/innobase/fts/fts0fts.cc, storage/innobase/row/row0mysql.cc
`row_create_index_for_mysql()`: Tolerate `DB_LOCK_TABLE_FULL` better.
`fts_create_one_common_table()`, `fts_create_one_index_table()`: Do not corrupt the error state of a non-active transaction object.
`fts_config_set_value()`: Only run another statement if there was no error yet.
Some DDL error handling for InnoDB `FULLTEXT INDEX` was improved.
This is somewhat covered by the tests `innodb_fts.index_table` and `innodb_fts.innodb-fts-ddl,vers_trx`.
This is a bug fix, targeting the 10.6 release because that was the major version on which this bug was originally reproduced. The 10.5 branch might be affected as well, but it is close to end of life.
=> MDEV-36061 Incorrect error handling on DDL with FULLTEXT INDEX

storage/innobase/dict/dict0stats.cc, storage/innobase/pars/pars0pars.cc
`dict_stats_fetch_from_ps()`: Acquire `dict_sys.latch` as few times as possible, and release `dict_sys.latch` after invoking `pars_sql()`, so that we will not be unnecessarily holding `dict_sys.latch` while possibly waiting for data to be read into the buffer pool.
InnoDB hangs related to I/O waits during `dict_stats_fetch_from_ps()` should be less likely.
Stress testing with RQG. This code is somewhat covered by the regression test suite, for example by the test `innodb.alter_not_null`.
=> MDEV-35436 dict_stats_fetch_from_ps() unnecessarily holds exclusive dict_sys.latch

mysql-test/suite/sql_sequence/alter.opt, mysql-test/suite/sql_sequence/alter.result, mysql-test/suite/sql_sequence/alter.test, sql/ha_sequence.cc, sql/ha_sequence.h, sql/sql_table.cc, storage/innobase/handler/handler0alter.cc
`mysql_alter_table()`: Consider `ha_sequence::storage_ht()` when determining if the storage engine changed.
`ha_sequence::check_if_supported_inplace_alter()`: A new function, to ensure that `ha_innobase::check_if_supported_inplace_alter()` will be called on `ALTER TABLE name_of_sequence SEQUENCE=0`.
`ha_innobase::check_if_supported_inplace_alter()`: For any change of the `SEQUENCE` attribute, always return `HA_ALTER_INPLACE_NOT_SUPPORTED`, forcing `ALGORITHM=COPY`.
`ALTER TABLE…SEQUENCE=…` no longer corrupts the InnoDB data dictionary.
```sh
./mtr sequence.alter
```
=> MDEV-36038 ALTER TABLE…SEQUENCE does not work correctly with InnoDB

storage/innobase/buf/buf0flu.cc, storage/innobase/handler/ha_innodb.cc, storage/innobase/include/log0log.h, storage/innobase/log/log0log.cc
`log_t::writer_update()`: Enable `log_writer_resizing` only if `resize_lsn>1`, to ensure that `log_t::resize_abort()` will not choose the wrong `log_sys.log_writer`.
`log_t::resize_start()`: Before invoking `writer_update()`, assign `resize_lsn>1` if applicable, so that the resizing will start correctly.
When `SET GLOBAL innodb_log_file_size` is frequently attempted and interrupted during a write workload, InnoDB could crash due to attempting to write to a non-existing copy of a log.
Stress testing with RQG generating `SET GLOBAL innodb_log_file_size` and `KILL` statements.
=> MDEV-36082 Race condition between log_t::resize_start() and log_t::resize_abort()

mysql-test/main/my_getopt_case_insensitive.opt, mysql-test/main/my_getopt_case_insensitive.result, mysql-test/main/my_getopt_case_insensitive.test, mysql-test/suite/wsrep/r/wsrep_mixed_case_cmd_arg.result, mysql-test/suite/wsrep/t/wsrep_mixed_case_cmd_arg.cnf, mysql-test/suite/wsrep/t/wsrep_mixed_case_cmd_arg.opt, mysql-test/suite/wsrep/t/wsrep_mixed_case_cmd_arg.test, mysys/my_getopt.c
my_getopt compares option names case-sensitively, causing "Unknown option" errors when users type mixed-case options like wsrep_slave_UK_checks in lowercase wsrep_slave_fk_checks.
Made the comparison in the getopt_compare_strings() case-insensitive.
N/A
`./mtr main.my_getopt_case_insensitive`
=> MDEV-27126 my_getopt compares option names case sensitively

storage/innobase/log/log0recv.cc
`recv_sys_t::parse()`: Allocate `decrypt_buf` also for `storing==BACKUP` but limit its size to correspond to 1 byte of record payload. Ensure that `last_offset=0` for `storing==BACKUP`.
When parsing `INIT_PAGE` or `FREE_PAGE`, avoid an unnecessary `l.copy_if_needed()` for `storing!=YES`.
When parsing `EXTENDED` in `storing==BACKUP`, properly invoke `l.copy_if_needed()` on a large enough `decrypt_buf`.
When parsing `WRITE`, `MEMMOVE`, `MEMSET` in `storing==BACKUP`, skip further validation (and potential overflow of the tiny `decrypt_buf `), like we used to do before #3755.
`mariadb-backup --backup` could crash due to dereferencing a null pointer if the server is configured with `innodb_undo_log_truncate=ON` and `innodb_encrypt_log=ON`.
Our stress test coverage of …
=> MDEV-36152 mariadb-backup --backup crash during innodb_undo_log_truncate=ON, innodb_encrypt_log=ON

storage/innobase/log/log0log.cc
Writing the redo log resized will write uninitialized data. There is a MEM_MAKE_DEFINED construct in the code to bless this however it was correct on the initial length, but not the changed length.
The MEM_MAKE_DEFINED is moved earlier in the code where the length contains the correct value.
If anything: innodb.log_file_size_online test result made reliable MSAN compiled code.
```
buildbot@1209234bb2fb:/build$ mysql-test/mtr  innodb.log_file_size_online 
Logging: /source/mysql-test/mariadb-test-run.pl  innodb.log_file_size_online
VS config: 
vardir: /build/mysql-test/var
Creating var directory '/build/mysql-test/var'...
MariaDB Version 12.0.0-MariaDB
- binaries built …
```
=> MDEV-36155: MSAN use-of-uninitialized-value innodb.log_file_size_online

client/mysql.cc, mysql-test/main/client.result, mysql-test/main/client.test
______
This PR is for testing script execution in a specified `--script-dir`
A new static variable, `script_dir`, has been added to **mysql.cc** and set to NULL. Additionally, a new option has been introduced in `my_long_options` to locate and assign the `script_dir`. The behavior of com_source has also been modified to append `script_dir` to its directory if the specified file is not found.
This PR can be tested by running the server and adding the `--script-dir` option in the terminal.
Here's an example: 
`mariadb --script-dir=foo/bar`
`mariadb[database_name]> source filename.sql`
where filename is located at `foo/bar`
=> MDEV-23818 mysql option --script-dir

mysql-test/suite/innodb/r/alter_partitioned_debug.result, mysql-test/suite/innodb/t/alter_partitioned_debug.test, storage/innobase/dict/dict0stats.cc, storage/innobase/handler/ha_innodb.cc
In #3729 a race condition was exposed.
`ha_innobase::check_if_incompatible_data()`: If the statistics have already been initialized for the table, skip the invocation of `innobase_copy_frm_flags_from_create_info()` in order to avoid unexpectedly ruining things for other threads that are concurrently accessing the table.
`dict_stats_save()`: Add debug instrumentation that is necessary for reproducing the interlocking of the failure scenario.
N/A. The symptoms are not reproducible in any release.
```sh
./mtr innodb.alter_partitioned_debug
```
=> MDEV-36227 Race condition between ALTER TABLE…EXCHANGE PARTITION and SELECT

extra/mariabackup/xtrabackup.cc
When running mariabackup with --prepare --export options, a deprecation warning appears because the program name is set to "mysqld" instead of "mariadbd"
The fix ensures that when running in mysqld mode, we properly set the program name to "mariadbd" to avoid the deprecation warning while maintaining the original functionality
Fixed "mysqld: Deprecated" warning in --prepare --export mode
Testing Instructions:
- Steps to reproduce and verify:
```bash
$ mariadb-backup --prepare --export --target-dir=/path/to/backup
```
- Expected results:
- The prepare command should complete successfully
- The deprecation warning "mysqld: Deprecated program name. It will be removed in a future release, use 'mariadb/bin/mariadb-backup' instead" should NOT appear
=> MDEV-36206: Fix mysqld deprecation warning

extra/mariabackup/backup_mysql.cc, extra/mariabackup/write_filt.cc, extra/mariabackup/xtrabackup.cc
- Remove the redundant check of TRX_SYS page change in wf_incremental_process(). This is a regression which caused by commit 1c55b845e0fe337e647ba230288ed13e966cb7c7.
./mtr --suite=mariabackup
=> MDEV-36253  Redundant check in wf_incremental_process()

mysql-test/include/long_test.inc, mysql-test/main/backup_locks.test, mysql-test/suite/binlog_encryption/encrypted_master.test, mysql-test/suite/funcs_2/t/innodb_charset.test, mysql-test/suite/innodb/t/innodb_bug52663.test, mysql-test/suite/mariabackup/log_page_corruption.test, mysql-test/suite/parts/t/partition_exchange_innodb.test, mysql-test/suite/parts/t/partition_exchange_memory.test, mysql-test/suite/parts/t/partition_exchange_myisam.test, mysql-test/suite/rpl/r/rpl_gtid_crash.result, mysql-test/suite/rpl/t/rpl_gtid_crash-slave.opt, mysql-test/suite/rpl/t/rpl_gtid_crash.test, mysql-test/suite/rpl/t/rpl_heartbeat_basic.test, mysql-test/suite/rpl/t/rpl_semi_sync.test, mysql-test/suite/rpl/t/rpl_semi_sync_after_sync.test, mysql-test/suite/rpl/t/rpl_semi_sync_after_sync_row.test, mysql-test/suite/rpl/t/rpl_typeconv.test, sql/slave.cc
- Suppress a couple errors the slave can get as the master crashes.
- The mysql-test-run occasionally takes 120 seconds between crashing
the master and starting it back up for some (unknown) reason. For
now, work-around that by letting the slave try for 500 seconds to
connect to master before giving up instead of only 100 seconds.
Signed-off-by: Kristian Nielsen <knielsen@knielsen-hq.org>
=> Fix sporadic failures of rpl.rpl_gtid_crash

support-files/mariadb.service.in, support-files/mariadb@.service.in
After an OOM kill, the process should be restarted by systemd. Prior to this change, that did not happen.
The comment in the file says it doesn't use on-failure in case of config errors, which I assume is caused by an unclean exit code. on-abnormal is the same as on-failure except for unclean exit code.
Changed systemd Restart mode to ensure that the server is restarted in abnormal situations such as OOM.
=> MDEV-36009 - Systemd: Restart on OOM

mysql-test/suite/multi_source/master_info_file.opt, mysql-test/suite/multi_source/master_info_file.result, mysql-test/suite/multi_source/master_info_file.test, mysql-test/suite/multi_source/show_slave_auth_info.cnf, mysql-test/suite/multi_source/show_slave_auth_info.result, mysql-test/suite/multi_source/show_slave_auth_info.test
* Subtask of [MDEV-30189 Add and alias remaining mariadbd replication command line options as system variables](https://jira.mariadb.org/browse/MDEV-30189)
Add MTR tests
* `multi_source.master_info_file`
* `rpl.rpl_show_slave_auth_info`
N/A
=> MDEV-36238 Functional Tests for --master-info-file and --show-slave-auth-info

mysql-test/main/mdev-34413-icp-reverse-order.combinations, mysql-test/main/mdev-34413-icp-reverse-order.result, mysql-test/main/mdev-34413-icp-reverse-order.test, mysql-test/main/myisam_explain_non_select_all.result, mysql-test/main/myisam_icp.result, mysql-test/main/order_by_optimizer_innodb.result, mysql-test/main/rowid_filter_innodb.result, mysql-test/main/rowid_filter_innodb.test, mysql-test/main/subselect.result, mysql-test/main/subselect_no_exists_to_in.result, mysql-test/main/subselect_no_mat.result, mysql-test/main/subselect_no_opts.result, mysql-test/main/subselect_no_scache.result, mysql-test/main/subselect_no_semijoin.result, mysql-test/suite/maria/icp.result, sql/ha_partition.cc, sql/ha_partition.h, sql/handler.cc, sql/handler.h, sql/opt_index_cond_pushdown.cc, sql/opt_range.cc, sql/sql_select.cc
This PR contains two commits.
Allows index condition pushdown for reverse ordered scans, a previously
disabled feature due to poor performance.  This patch adds a new
API to the handler class called set_end_range which allows callers to
tell the handler what the end of the index range will be when scanning.
Combined with a pushed index condition, the handler can scan the index
efficiently and not read beyond the end of the given range.  When
checking if the pushed index condition matches, the handler will also
check if scanning has reached the end of the provided range and stop if
so.
If we instead only enabled ICP for reverse ordered scans without
also calling this new API, then the handler would perform unnecessary
index condition checks.  In fact this would continue until the end of …
=> MDEV-34413 Index Condition Pushdown for reverse-ordered scans

client/mysqlslap.c, mysql-test/main/mysqlslap.result, mysql-test/main/mysqlslap.test
`mariadb-slap` crashes with a floating point exception when run with `-i0` due to division by zero in `generate_stats()`. This occurs when calculating average timing by dividing by the number of iterations.
Instead of modifying the minimum value for the `-i` option (which would cause unexpected warning messages even with valid values), this PR implements a targeted fix in the `generate_stats()`. The solution checks if `iterations == 0` before performing the division, and in such cases, returns early from the function.
Fixed a floating point exception (division by zero) crash in `mariadb-slap` when running with `-i0` (zero iterations).
This PR can be tested by manually running mariadb-slap with zero iterations, which would previously cause a crash:
```
$ mariadb-slap -i0 --only-print
``` …
=> MDEV-34621: Fix division by zero in mariadb-slap when iterations=0

mysql-test/suite/innodb_gis/r/rollback.result, mysql-test/suite/innodb_gis/t/rollback.test, storage/innobase/gis/gis0sea.cc
- InnoDB spatial index keep track of all active r-tree search cursor. While deleting a record from the index, spatial index discards the page present in the active r-tree search cursor.
rtr_check_discard_page() have the assumption that all active r-tree cursor should point to shadow block for the matched records. If the cursor was opened when the table is empty then there won't be any shadow block.
./mtr innodb_gis.rollback
=> MDEV-35420 Server aborts while deleting the record in spatial index

include/my_cpu.h
Clang does not have the builtin __builtin_riscv_pause().
Fix building with Clang and GCC (other than 13) on RISC-V
Build test with Clang and GCC (other than 13).
=> MDEV-36217: Fix building with Clang and GCC on RISC-V

mysys/my_default.c
Currently, if the `--default-group-suffix` argument is not passed when initializing
an instance of MariaDB, the `MYSQL_GROUP_SUFFIX` environment variable, if set, is used to specify the group suffix. 
Add an additional check for the `MARIADB_GROUP_SUFFIX` environment variable before checking for `MYSQL_GROUP_SUFFIX`. This environment variable will take precedence over the `MYSQL_GROUP_SUFFIX` if both are set, with the goal of furthering MariaDB's branding. 
This behaviour is consistent with how `MARIADB_HOME` is checked before `MYSQL_HOME` ([MDEV-21365](https://jira.mariadb.org/browse/MDEV-21365)). 
N/A 
Create a custom config file with at least two different suffix groups.  
For example:
`test.cnf`
```
[mysqld]
max_connections=100
[mysqld_test1]
max_connections=300
[mysqld_test2] …
```
=> MDEV-21375: Get option group suffix from $MARIADB_GROUP_SUFFIX in addition to $MYSQL_GROUP_SUFFIX

mysql-test/suite/innodb/r/stat_tables.result, mysql-test/suite/innodb/t/stat_tables.test, storage/innobase/handler/ha_innodb.cc
`ha_innobase::statistics_init()`, `ha_innobase::info_low()`: Correctly handle a `DB_READ_ONLY` return value from `dict_stats_save()`. Fixes up #3729.
N/A. This regression is not present in any release.
```sh
./mtr innodb.stat_tables
```
=> MDEV-36373 Bogus Warning: ... storage is corrupted

mysql-test/suite/sys_vars/t/sysvars_innodb.opt, mysql-test/suite/sys_vars/t/sysvars_innodb.test, sql/mysqld.cc
In #3483 there was a spelling mistake that somehow causes the deprecated parameter `innodb_purge_rseg_truncate_frequency` to be rejected at server startup.
The start-up parameter `innodb_purge_rseg_truncate_frequency` that is deprecated and with no effect was not recognized as a valid start-up option. 
```sh
./mtr sys_vars.sysvars_innodb
```
=> MDEV-36378 Recognize innodb_purge_rseg_truncate_frequency

extra/mariabackup/xtrabackup.cc, mysql-test/suite/mariabackup/incremental_compressed.result, mysql-test/suite/mariabackup/incremental_compressed.test
Problem:
=======
- During prepare of incremental backup, mariabackup does create new file in target directory with default file size of 4 * innodb_page_size. While applying .delta file to corresponding data file, it encounters the FSP_SIZE modification on page0 and tries to extend the file to the size which is 4 in our case. Since the table is in compressed row format, page_size for the table is 8k. This lead to shrinking of tablespace file from 65536 to
32768. This issue happens only in windows because os_file_set_size() doesn't check for the current size and shrinks the file.
Solution:
==========
xtrabackup_apply_delta(): Check for the current size before doing setting size for the file.
./mtr mariabackup.incremental_compressed
=> MDEV-36270 mariabackup.incremental_compressed fails in 10.11+

support-files/mariadb.service.in, support-files/mariadb@.service.in
…ilities
In resolving MDEV-33301 (76a27155b4cd8174e900577dd01df2db1327b120) we moved all the capabilities from CapabilityBoundingSet to AmbientCapabilities where only add/moving CAP_IPC_LOCK was intended.
The effect of this is the defaulting running MariaDB HAS the capability CAP_DAC_OVERRIDE CAP_AUDIT_WRITE allowing it to access any file, even while running as a non-root user.
Resolve this by making CAP_IPC_LOCK apply to AmbientCapabilities and leave the remaining CAP_DAC_OVERRIDE CAP_AUDIT_WRITE to CapabilityBoundingSet for the use by auth_pam_tool.
SECURITY: Correct mistake in previous release where systemd MariaDB services had capabilities CAP_DAC_OVERRIDE CAP_AUDIT_WRITE by default allowing arbitrary file access .
```
chown -R root:root /var/lib/mysql
chmod ugo-rwX
systemctl start …
```
=> MDEV-36229: Remove CAP_DAC_OVERRIDE CAP_AUDIT_WRITE from AmbientCapabilities

storage/innobase/trx/trx0trx.cc
MDEV-24035 (#3676) broke the `cmake -DCMAKE_BUILD_TYPE=Debug` build on GCC 4.8.5, which is not entirely C++11 compliant.
N/A. GCC 4.8.5 was the default compiler of Red Hat Enterprise Linux 7, which is not under regular maintenance anymore.
On RHEL 7:
```sh
cmake -DCMAKE_BUILD_TYPE=Debug .
make -j$(nproc) innobase
```
=> MDEV-24035 fixup: GCC 4.8.5 CMAKE_BUILD_TYPE=Debug

mysql-test/suite/encryption/r/doublewrite_debug.result, mysql-test/suite/encryption/t/doublewrite_debug.opt, mysql-test/suite/encryption/t/doublewrite_debug.test, storage/innobase/buf/buf0buf.cc, storage/innobase/buf/buf0dblwr.cc, storage/innobase/include/log0recv.h, storage/innobase/log/log0recv.cc
- InnoDB fails to recover the full crc32 page_compressed page from doublewrite buffer. The reason is that buf_dblwr_t::recover() fails to identify the space id from the page because the page has compressed from FIL_PAGE_FILE_FLUSH_LSN_OR_KEY_VERSION bytes.
Fix:
===
recv_dblwr_t::recovery_page_compressed(): Find the page which has the same page number and try to decompress the page. After the decompression, compare the space id and write the recovered page back to the file.
buf_page_t::read_complete(): If the page looks corrupted and tablespace is compressed in full_crc32 format, try to restore page from doublewrite buffer
recv_dblwr_t::recover_encrypted_page(): Skip the page which doesn't have key_version in FIL_PAGE_FCRC32_KEY_VERSION field
./mtr encryption.doublewrite_debug
=> MDEV-36180 Doublewrite recovery of innodb_checksum_algorithm=full_crc32 page_compressed pages does not work

mysql-test/suite/innodb/r/innodb-index-online.result, mysql-test/suite/innodb/t/innodb-index-online.test, storage/innobase/row/row0log.cc
Reason:
=======
- InnoDB DML commit aborts the server when InnoDB does online virtual index. During online DDL, concurrent DML commit operation does read the undo log record and their related current version of the clustered index record. Based on the operation, InnoDB do build the old tuple and new tuple for the table. If the concurrent online index can be affected by the operation, InnoDB does build the entry
for the index and log the operation.
Problematic case is update operation, InnoDB does build the update vector. But while building the old row, InnoDB fails to fill the non-affected virtual column. This lead to server abort while build the entry for index.
Fix:
===
- First, fill the virtual column entries for the new row. Duplicate the old row based on new row and change only the …
=> MDEV-36281	DML aborts during online virtual index

storage/innobase/dict/dict0defrag_bg.cc, storage/innobase/dict/dict0dict.cc, storage/innobase/dict/dict0stats.cc, storage/innobase/handler/ha_innodb.cc, storage/innobase/handler/handler0alter.cc, storage/innobase/include/dict0dict.h, storage/innobase/lock/lock0lock.cc, storage/innobase/trx/trx0purge.cc
`trx_purge_close_tables()`: Before releasing any metadata locks (MDL), release all table references, in case an `ALTER TABLE…ALGORITHM=COPY` operation has confused our logic.
`trx_purge_table_acquire()`, `trx_purge_table_open()`: Do not acquire any table reference before successfully acquiring a necessary metadata lock. In this way, if purge is waiting for MDL, a concurrent `ha_innobase::commit_inplace_alter_table(commit=true)` that is holding a conflicting `MDL_EXCLUSIVE` will only observe its own reference on the table that it may need to replace.
`dict_table_open_on_id()`: Simplify the logic.
`dict_stats`: A helper for acquiring MDL and opening the tables `mysql.innodb_table_stats` and `mysql.innodb_index_stats`.
`innodb_ft_aux_table_validate()`: Contiguously hold `dict_sys.latch` …
=> MDEV-36122 Assertion ctx0->old_table->get_ref_count() == 1

mysql-test/main/spatial_utility_function_geohash.result, mysql-test/main/spatial_utility_function_geohash.test, sql/item_geofunc.cc, sql/item_geofunc.h
decode_geohash now properly filters non ASCII values from the input.
=> MDEV-36168 ASAN error in Item_func_latlongfromgeohash::decode_geohash

mysql-test/main/spatial_utility_function_isvalid.result, mysql-test/main/spatial_utility_function_isvalid.test, sql/spatial.cc
Like MDEV-35062, reserve sufficient space in the result for q_append'ed data, as q_append does not itself reserve space like it's append counterpart.
=> MDEV-36042 Assertion failed in Binary_string::q_append

mysql-test/suite/innodb_fts/r/innodb_ft_aux_table.result, mysql-test/suite/innodb_fts/t/innodb_ft_aux_table.test, storage/innobase/handler/ha_innodb.cc
`innodb_ft_aux_table_validate()`: If the table is found in InnoDB but not valid for the parameter, only invoke `dict_sys.unlock()` once.
This fixes a regression due to #3856.
N/A. This regression will not be present in any release.
```sh
./mtr innodb_fts.innodb_ft_aux_table
```
=> MDEV-36420 Assertion failure in SET GLOBAL innodb_ft_aux_table

mysql-test/main/spatial_utility_function_collect.combinations, mysql-test/main/spatial_utility_function_collect.result, mysql-test/main/spatial_utility_function_collect.test, sql/item_sum.cc
The GIS function st_collect can now be used with GROUP BY.  Previously, such queries resulted in a crash because Item_func_stcollect did not specify quick_group = false and did not implement reset_field, update_field methods.
With quick_group as false, an implementation of Item_sum tells the SQL layer that the aggregate can be computed with the TemporaryTableWithPartialSums algorithm.  That is the case for st_collect.  This is convenient because the SQL layer will rely on the Item_sum to produce the correct, updated aggregate value for a given result field.  Otherwise, using reset_field and update_field implementations gives greater flexibility when computing the aggregate but requires more complexity.
=> MDEV-36167 Assertion in Item_sum_st with st_collect and group by

mysql-test/suite/innodb/r/instant_alter_debug,redundant.rdiff, mysql-test/suite/innodb/r/instant_alter_debug.result, mysql-test/suite/innodb/t/instant_alter_debug.test, storage/innobase/handler/handler0alter.cc
Problem:
========
- InnoDB does consecutive instant alter operation, first instant DDL fails, it fails to reset the old instant information in table during rollback. This lead to consecutive instant alter to have wrong assumption about the exisitng instant column information.
Fix:
====
dict_table_t::instant_column(): Duplicate the instant information field of the table. By doing this, InnoDB alter retains the old instant information and reset it during rollback operation
./mtr innodb.instant_alter_debug
=> MDEV-36236 Instant alter aborts when InnoDB fails to rollback instant operation correctly

sql/sql_parse.cc
mysql_prepare_create_table_finalize returns true if there's an error.
The point of checking the identifier name of the index is to see if there's an error.
The primary key doesn't have name, which is quite valid, so no point in checking empty names.
Checking empty names where the key->name.str is a null pointer results in a UBSAN error in Well_formed_prefix_status further down the stack.
Avoid checking validity of nameless primary keys.
Under UBSAN with a basic bootstrap.
=> MDEV-36480 USAN: checking identifier names for 0 length names

storage/connect/plgxml.h, storage/connect/tabxml.cpp
Connect engine fails to build with libxml2 2.14.0.
Connect engine uses "#ifndef BASE_BUFFER_SIZE" to determine if libxml2 is available. If libxml2 is unavailable it did redefine xmlElementType enum of libxml/tree.h. The reasons for this redefinition is vague, most probably some of these constants were used when connect was compiled with MSXML, while libxml2 was disabled.
However BASE_BUFFER_SIZE constant was removed from libxml2 recently, as a result connect fails to build due to xmlElementType constants redefinition.
Use LIBXML2_SUPPORT instead of BASE_BUFFER_SIZE for libxml2 availability check.
=> MDEV-36427 - FTBFS with libxml2 2.14.0

mysql-test/suite/innodb/t/innodb_buffer_pool_resize_temporary.test, storage/innobase/buf/buf0buf.cc
`buf_block_t::initialise()`: Remove a redundant call to `page.lock.init()` that was already executed in `buf_pool_t::create()` or `buf_pool_t::resize()`.
This fixes a regression that was introduced in #3826.
N/A
Ensure that `-DSUX_LOCK_GENERIC` is defined in a `CMAKE_BUILD_TYPE=Debug` build:
```diff
diff --git a/storage/innobase/include/srw_lock.h b/storage/innobase/include/srw_lock.h
index 79a3e7c42a7..43ab43d90a6 100644
--- a/storage/innobase/include/srw_lock.h
+++ b/storage/innobase/include/srw_lock.h
@@ -30,7 +30,7 @@ this program; if not, write to the Free Software Foundation, Inc.,
#endif
-#if !defined SUX_LOCK_GENERIC && 0 /* defined SAFE_MUTEX */
+#if !defined SUX_LOCK_GENERIC && 1 /* defined SAFE_MUTEX */
#endif
```
=> MDEV-36489 10.11 crashes during bootstrap on macOS

storage/innobase/log/log0log.cc, storage/innobase/log/log0recv.cc
`log_t::clear_mmap()`: Do not modify `buf_size`; we may have `file_size==0` here during bootstrap.
`log_t::set_recovered()`: If we are writing to a memory-mapped log, update `log_sys.buf_size` to the record payload area of `log_sys.buf`.
This fixes up #3925.
N/A. This bug is not present in any release.
In a `cmake -DWITH_INNODB_PMEM=ON` build:
```sh
./mtr --boot-rr --rr innodb.innodb
```
Set `watch -l log_sys.buf_size` and `watch -l log_sys.buf` and ensure that the `log_sys.buf_size` is either the specified `innodb_log_file_size` or the size of a memory-mapped `ib_logfile0` that will be used for writing.
=> MDEV-36587 InnoDB uses too much memory

sql/bloom_filters.h, sql/vector_mhnsw.cc
This patch optimises the dot_product function by leveraging vectorisation through SIMD intrinsics. Specifically, the function now uses __builtin_vec_vupkhsh and __builtin_vec_vupklsh to efficiently convert input values from lower to higher data types.
This transformation enables parallel execution of multiple operations, significantly improving the performance of dot product computation on supported architectures.
Performance Analysis:
The original dot_product function does undergo auto-vectorisation when compiled with -O3. However, performance analysis has shown that the newly optimised implementation performs better on Power10 and achieves comparable performance on Power9 machines.
Output Changes:
The logical output of the dot_product function remains unchanged (i.e., it still computes …
=> MDEV-36184 - To optimise dot_product in Power9 and Power10 architecture

mysql-test/lib/My/SafeProcess.pm, mysql-test/lib/My/SafeProcess/safe_process.cc, mysql-test/mariadb-test-run.pl
This commit allows specifying the open-files limit dynamically instead of previously hard coding it with 1024 files  using a new option in MTR ```open-files-limit=X``` 
With only 1024 open file descriptors it is impossible to use
mtr for high concurrency testing.
This commit removes the hardcoded value and adds a new
option to control the limit when running tests: ```./mtr --open-files-limit=X.```
The default is still 1024, but it can now be changed when needed,
making it easier to test scenarios that require different number of
open file descriptors at the same time e.g: partition_notwin.test
This is part of the MTR infrastructure so it can be tested manually and locally using the ```--open-filies-limit=<value>```
e.g: ```./mtr --open-files-limit=1000 alter_algorithm.test```
Note that in …
=> MDEV-33671 Remove hardcoded open-files limit in safe_process.cc

mysql-test/suite/gcol/r/innodb_virtual_basic.result, mysql-test/suite/gcol/t/innodb_virtual_basic.test, storage/innobase/trx/trx0rec.cc
Starting with mysql/mysql-server@02f8eaa9988dadb73dd68630dd82393cfa19bfb8 and 2e814d4702d71a04388386a9f591d14a35980bfe the index ID of indexes on virtual columns was being encoded insufficiently in InnoDB undo log records.  Only the least significant 32 bits were being written.  This could lead to some corruption of the affected indexes on `ROLLBACK`, as well as to missed chances to remove some history from such indexes when purging the history of committed transactions that included `DELETE` or an `UPDATE` in the indexes.
`dict_hdr_create()`: In debug instrumented builds, initialize the `DICT_HDR_INDEX_ID` close to the 32-bit barrier, instead of initializing it to `DICT_HDR_FIRST_ID` (10).  This will allow the changed code to be exercised while running the following:
```sh
./mtr …
```
=> MDEV-36613 Incorrect undo logging for indexes on virtual columns

mysql-test/suite/multi_source/master_info_file.result, mysql-test/suite/multi_source/master_info_file.test
`Master_SSL_Verify_Server_Cert=0` was optional before that secure-by-default change.
Now, passwordless connections must disable SSL certificate verification.
Because the default unnamed connection cannot be deleted by RESET REPLICA ALL, it must be explicitly left passwordless and having `Master_SSL_Verify_Server_Cert=0`.
The named connection is cleaned up by RESET REPLICA ALL and thus not affected.
N/A – this is a CI test.
Run it, and check that its post-test MTR internal check no longer complains `Master_SSL_Verify_Server_Cert` being Yes.
=> MDEV-36238 11.4 follow-up: `Master_SSL_Verify_Server_Cert=0`

include/my_base.h, mysql-test/suite/innodb/r/alter_copy_bulk.result, mysql-test/suite/innodb/t/alter_copy_bulk.test, sql/ha_partition.cc, sql/sql_insert.cc, sql/sql_table.cc, storage/innobase/handler/ha_innodb.cc, storage/innobase/handler/handler0alter.cc, storage/innobase/include/trx0trx.h, storage/innobase/include/trx0types.h, storage/innobase/row/row0ins.cc, storage/innobase/row/row0mysql.cc, storage/innobase/trx/trx0trx.cc, storage/mroonga/ha_mroonga.cpp
DEV-36504  Memory leak after CREATE TABLE..SELECT
Problem:
========
- After commit cc8eefb0dca1372378905fbae11044f20364c42d (MDEV-33087),
InnoDB does use bulk insert operation for ALTER TABLE.. ALGORITHM=COPY
and CREATE TABLE..SELECT as well. InnoDB fails to clear the bulk
buffer when it encounters error during CREATE..SELECT. Problem
is that while transaction cleanup, InnoDB fails to identify
the bulk insert for DDL operation.
Fix:
====
- Represent bulk_insert in trx by 2 bits. By doing that, InnoDB
can distinguish between TRX_DML_BULK, TRX_DDL_BULK. During DDL,
set bulk insert value for transaction to TRX_DDL_BULK.
- Introduce a parameter HA_EXTRA_ABORT_ALTER_COPY which rollbacks
only TRX_DDL_BULK transaction.
- bulk_insert_apply() happens for TRX_DDL_BULK transaction happens
only …
=> MDEV-36504  Memory leak after CREATE TABLE..SELECT

extra/mariabackup/xtrabackup.cc, storage/innobase/handler/ha_innodb.cc, tpool/aio_liburing.cc, tpool/tpool_generic.cc
The kernel warnings adding in MDEV-26674 where at the very early stages of kernel development. Since then RHEL9 and its clones and compatible distros have stabilised on the 5.14 kernel which no longer has broken behaviour as the initial kernels but users are still receiving warnings and disabling of innodb_native_aio.
Because of this, its safe to revert the kernel checks. We've checked that the kernel of RHEL9 works correctly with io_uring. During this it was discovered that the default RHEL9 kernels will have sysctl kernel.io_uring_disabled=2 set which disable io_uring usage for all users. This is either out of compatibility or from the early days where there where more io_uring bug reports. Either way, we don't need to provide another slightly broken layer of control around this, the …
=> MDEV-36182 revert incorrect 5.14 kernel warnings and correct liburing interface usage

mysql-test/suite/rpl/r/rpl_semi_sync_master_disable_with_slave.result, mysql-test/suite/rpl/t/rpl_semi_sync_master_disable_with_slave.test, sql/semisync_master.cc
Under `@@rpl_semi_sync_master_wait_no_slave = 0`, when `rpl_semi_sync_master_clients` decrements to zero, the primary reverts to async replication.
This code did not check whether Semi-Sync is still globally enabled or not as it didn’t matter before.
However, after #3089 ([MDEV-33551](https://jira.mariadb.org/browse/MDEV-33551)) split the transactions’ACK condition variables to per-transaction, this function now needs Semi-Sync’s transaction tracker to unblock these condition variables in batch, but this tracker is `NULL` when Semi-Sync Primary is disabled.
* FWIW, the Semi-Sync Primary subsystem can “orphanate” its Binlog Dump threads(’ connection to their replicas) when it disables (`SET @@rpl_semi_sync_master_enabled = 0`) while they remain connected.
```console
$ SET …
```
=> MDEV-36359: Patch NULL deref after disabling semi-sync primary

THIRDPARTY
There are several files under the GPL with BISON expection license.
However none of them are 'GPL-2.0-or-later' today, all of them are 'GPL-3.0-or-later' now, and none of them have '... version 1.24 of Bison' and all of them have '... version 2.2 of Bison'.
Search done by using:
grep -i -e "of bison" -r .
for quick file listing,
and by:
grep --before=20 --after=20 -i -e "bison" -r . | grep --after=2 --before=20 -i exception
to list the whole license blocks (with the GPL part), but it contains few false positive results (matched code instead of license block)
Nothing?
Use GREP commands listed above,
or try some of your own to try to disprove my findings.
=> MDEV-35999 - Update THIRDPARTY license file to reflect reality

mysql-test/main/func_time.result, mysql-test/main/func_time.test, mysql-test/main/strict.result, mysql-test/main/strict.test, sql/item_timefunc.cc
STR_TO_DATE function in MariaDB does date to string conversion for invalid dates strings, e.g.: 1949-02-30, and 1949-06-31, but null is return by other invalid dates such as 1949-01-32 because the checking function returns null for any date whose day is larger than 31, which is too naive and needs to be changed.
This commit changed the rule of check_date in extract_date_time function, which is executed after extracting date and time and check if
the result is valid. Now the conversion will consider the number of days in a month, including skip years.
Execute the main suite in mysql-test-run.
This is a new feature introducing stricter date check before a conversion is generated and affect backwards compatibility.
All new code of the whole pull request, including one or several files that …
=> MDEV-11341 STR_TO_DATE does not return NULL for invalid dates

debian/libmariadb-dev.install, debian/libmariadbd-dev.install, debian/rules
https://jira.mariadb.org/browse/MDEV-23538
Change so that the client library config can be accessed using the name
libmariadb.pc or mariadb.pc. Rename old mariadb.pc to mariadbd.pc to better
indicate that the config is for the daemon build, not client.
In downstream Debian we already ship the libmariadb.pc as mariadb.pc:
https://salsa.debian.org/mariadb-team/mariadb-10.5/-/commit/2f183af990fbe1cfa8c343998c7640f45f45368b
=> MDEV-23538: Rename mariadb.pc to mariadb-embedded-server.pc to avoid confusion

mysql-test/suite/multi_source/connects_tried.result, mysql-test/suite/multi_source/connects_tried.test
Improve the `multi_source.connects_tried` feature test:
* Replace the main course from *checking `Connect_Tried` after sleeping a specific time* to *checking the duration after reaching a minimum `Connect_Tried`*
* Not using a specific SLEEP eliminates the possibility (of failure) that it awakens before the `Connects_Tried` counter increments.
* In replacement-based tests of conventional views (SHOW & variants), assert the parallel values without distinguishing which is which
* There were rare cases where both values end up equal (even though one was configured to tick more frequently than the other).
* Comment touchups
N/A
It has been evident that timing tests easily lead to sporadic failures.
Perhaps our CI (Buildbot) are overloaded with concurrent jobs that their thread schedulers had …
=> MDEV-35304 fixup: Timing-independent MTR test

mysql-test/suite/innodb/r/stats_persistent.result, mysql-test/suite/innodb/t/stats_persistent.test, storage/innobase/dict/dict0dict.cc
- InnoDB fails to check the table is being dropped or evicted while acquiring the MDL for the table when table open operation mode is DICT_TABLE_OP_OPEN_ONLY_IF_CACHED.
Fix:
===
dict_acquire_mdl_shared(): Check whether the table name length before retrying to acquire MDL for the table. In case of evicted or dropped table, new table length is 0.
./mtr innodb.stats_persistent
=> MDEV-36649 dict_acquire_mdl_shared() aborts when table mode is DICT_TABLE_OP_OPEN_ONLY_IF_CACHED

mysql-test/main/join.result, mysql-test/main/join.test, sql/sql_base.cc
"t1 JOIN t2 USING(col1,...)" calls mark_common_columns() to mark the listed columns as used in both used tables, t1 and t2.
Due to a typo bug, it would mark the wrong column in the second table (t2): instead of t2.col1 it would mark the last column in t2.
The harmful effects included JOIN_TAB(t2)->covering_keys not being set correctly. This changed the cost to access the table and then caused different query plans depending on which table was the second in the JOIN ... USING syntax.
- [X ] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/-/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
=> MDEV-36592: In JOIN ... USING(columns), query plan depends on join order

debian/additions/mariadb.conf.d/60-galera.cnf
The `wsrep_provider` setting is mandatory and needs to be present as a guidance for the setup of Galera cluster. `wsrep_cluster_name` and `innodb_autoinc_lock_mode` are not mandatory.
See: https://mariadb.com/kb/en/configuring-mariadb-galera-cluster/
Update galera configuration settings as in KB doc.
There is no impact since it's all commented settings but we might want to test that default settings are working.
=> MDEV-31134: sync galera settings with KB doc

mysql-test/suite/multi_source/connects_tried.result, mysql-test/suite/multi_source/connects_tried.test, sql/sql_repl.cc
* Follow-up of [MDEV-35304](https://jira.mariadb.org/browse/MDEV-35304)
CHANGE MASTER can set `Master_Retry_Count` to be lower than `Connects_Tried`, which’ll look strange to those unaware of that CHANGE.
Now, setting `Master_Retry_Count` also resets `Connects_Tried` to 0.
Amend MDEV-35304’s with:
* STOP REPLICA does not reset `Connects_Tried` to 0, but RESET REPLICA does, and also does changing `Master_Retry_Count` with CHANGE MASTER.
This PR adds a test case to `multi_source.connects_tried`.
This PR also
* swaps some other tests’ SELECTs so they’re all `FROM status_before JOIN status_after USING(Connection_name)`; no function change
* “simplifies” START/STOP SLAVE + `wait_for_slave_to_start`/`stop.inc` to `start`/`stop_slave.inc`
The bug is about a feature exclusive to the `main` …
=> MDEV-36340: Reset `Connects_Tried` with `Master_Retry_Count=X`

mysql-test/main/sp-no-valgrind.test, sql/mysqld.cc
As discussed with @montywi, this patch fixes two things:
1. It ensures that when the server is compiled with valgrind, that the proper server suffix is appended. This is used by tests.
2. It also adds the same kind of suffix for -asan
This ensures that one does not need to add SERVER_SUFFIX as part of BUILD scripts either.
=> HAVE_valgrind typo fixup and -asan suffix

storage/innobase/buf/buf0buf.cc, storage/innobase/buf/buf0flu.cc, storage/innobase/include/buf0buf.h
A statement `SET GLOBAL innodb_buffer_pool_size=…` could fail for no good reason when the buffer pool contains many pages that can actually be evicted.
`buf_flush_LRU_list_batch()`: Keep evicting as long as the buffer pool is being shrunk, for at most `innodb_lru_scan_depth` extra blocks. Disregard the flush limit for pages that are marked as freed in files.
`buf_pool_t::will_be_withdrawn()`: Allow also `ptr=nullptr` (the condition will not hold for it).
This fixes a regression that was introduced in #3826 and caught by the test `innodb.temp_truncate_freed` in MariaDB Server 11.4.
N/A; this regression is not present in any release.
In 11.4:
```sh
./mtr --valgrind innodb.temp_truncate_freed
```
This was tested by @Thirunarayanan.
=> MDEV-36646: innodb_buffer_pool_size change aborted

mysql-test/suite/rpl/r/rpl_semi_sync_ssl_stop.result, mysql-test/suite/rpl/t/rpl_semi_sync_ssl_stop.test, sql/rpl_mi.cc, sql/rpl_mi.h, sql/semisync_slave.cc, sql/semisync_slave.h, sql/slave.cc
> When a replica stops an established semi-sync connection (e.g. from running `STOP REPLICA`/`STOP SLAVE`), it is supposed to kill the corresponding binlog dump thread on the primary server.
This is done by the replica creating a new connection to its primary which issues a `KILL` command targeting the established connection.
However, when connections are configured to use SSL, this new connection created by the replica to kill the dump thread doesn't have any logic to configure SSL options, and thereby the connection can't be made, and the dump thread will never be killed.
⸺ @bnestere, MDEV-36663
Asynchronous and Semi-Sync replication are in distinct files.
Heck, they don’t even share some of the behavior, such as this graceful KILL.
It’s difficult to share code without introducing …
=> MDEV-36663 Semi-sync Replica Can't Kill Dump Thread When Using SSL

storage/innobase/handler/ha_innodb.cc
Reason:
=======
- MDEV-16239 does apply the DML logs after bulk insert for ALTER TABLE..ALGORITHM=COPY, but InnoDB fails to reset the bulk_insert in ha_innobase::extra(HA_EXTRA_END_ALTER_COPY). This leads to crash while applying DML logs.
Solution:
=======
ha_innobase::extra(HA_EXTRA_END_ALTER_COPY): Reset TRX_DDL_BULK at the end of bulk insert operation
./mtr innodb.alter_copy_bulk
=> MDEV-36682  Conflict between MDEV-36504 and MDEV-16329

mysql-test/main/mdl_sync.result, mysql-test/main/mdl_sync.test
SELECT FROM information_schema.metadata_lock_info may sporadically return MDL_SHARED lock acquired by InnoDB purge thread.
Fix proposed in a7bf0a42d0c wasn't enough to solve this problem: apparently it did protect against purging old rows, but not against locking the table.
Reverted a7bf0a42d0c in favour of solution proposed in e996f77cd87. That is use wait_all_purged.inc to make sure purge is completed.
=> MDEV-36648 - main.mdl_sync extra test.t2 row in I_S.metadata_lock_info

mysql-test/main/lowercase_table2.result, sql/sql_show.cc
```lower_case_table_names``` has three values only 0, 1, 2 ... On windows the default is 1 but when changing that value to 2 (or testing it on MacOS since the default value should also be 2) it should deal with table/db names with their original created table name and compare lowercase only not convert them into lowercase 
```get_lookup_field_values()``` should only convert the names to lowercase when ```lower_case_table_names``` is 1 only not 2 
Nothing should be changed since this was already mentioned in 
https://mariadb.com/kb/en/identifier-case-sensitivity/ 
On windows 64-bit machines use the following test case
```bash 
perl mysql-test-run.pl lowercase_table2.test 
```
In the ```lowercase_table2.test``` and ```lowercase_table2.result``` both have already covered a test case where …
=> MDEV-14432: mysqldump does not preserve case of table names in generated sql

mysql-test/main/desc_index_range.result, mysql-test/main/desc_index_range.test, mysql-test/main/myisam.result, mysql-test/suite/maria/maria2.result, sql/opt_range.cc, sql/opt_range.h
Extend loose index scan to support descending indexes.
This is achieved by removing a block skipping creating loose index
scan plan for descending index, as well as generalising the execution
of such plans.
The generalisation applies to all levels looking for min/max in loose
index scan. In the highest level (get_next), generalise min and max to
first and last, so that it still proceeds in the direction agreeing
with the index parity. In the lower levels, combine next_min and
next_max methods into next_min_max, and combine next_min_in_range and
next_max_in_range into next_min_max_in_range. This retains existing
logic of these functions and reduces code duplication, while allowing
handling of all four combinations (min, max) x (asc index, desc
index).
-------
See the commit message. …
=> MDEV-32732 Support DESC indexes in loose scan optimization

sql/sql_base.cc, sql/sql_class.h, sql/table_cache.cc, storage/innobase/trx/trx0purge.cc
Valgrind is single threaded and only changes threads as part of system calls or waits.
I found some busy loops where the server assumes that some other thread will change the state, which will not happen with valgrind.
Added VALGRIND_YIELD to the loops, which calls pthread_yield() if HAVE_VALGRIND is defined.
Added pthread_yield() to the loops in table_cache.
We should consider changing some of the VALGRIND_YIELD calls to call pthread_yield() as busy loop without any sleep() is usually a bad thing.
Reviewer: svojtovich@gmail.com
=> MDEV-36684 - main.mdl_sync fails under valgrind (test for Bug#42643)

sql/sql_prepare.cc
The SQL service leaves the affected rows uninitialized.
The initialization of the spider plugin that uses
this service will fail under MSAN because there isn't an initialized value to return at the end of the query.
=> MDEV-35009: Initialize affected_rows in SQL service

storage/innobase/mtr/mtr0mtr.cc
`log_t::append_prepare_wait()`: Do not attempt to read `log_sys.write_lsn` because it is not protected by `log_sys.latch` but by `write_lock`, which we cannot hold here. The assertion could fail if `log_t::write_buf()` is executing concurrently, and it has not yet executed `log_write_buf()` or updated `log_sys.write_lsn`.
Fixes up #3925
N/A. This replaces a bogus debug assertion.
Run a write-heavy workload with the default `innodb_log_buffer_size` and possibly `innodb_flush_log_at_trx_commit=0`. Possibly, add a sleep to `log_write_buf()`. If running on Linux `/dev/shm`, be sure to compile with `cmake -DWITH_INNODB_PMEM=OFF` in order to cover the correct code path.
I tested this by running the default `mtr` suites while `mysql-test/var` was a symbolic link to a SATA device, as well as when …
=> MDEV-36760 log_t::append_prepare_wait(): Bogus assertion on write_lsn

client/mysqlcheck.c, client/mysqlslap.c, cmake/maintainer.cmake, extra/mariabackup/fil_cur.cc, extra/mariabackup/fil_cur.h, include/my_attribute.h, mysql-test/suite/innodb/r/innodb-wl5522-debug.result, sql/sql_statistics.cc, sql/threadpool_generic.cc, sql/tztime.cc, storage/connect/ha_connect.cc, storage/innobase/row/row0quiesce.cc, storage/maria/ma_loghandler.c, storage/maria/ma_open.c, storage/maria/ma_pagecache.c, storage/maria/ma_recovery.c, storage/mroonga/CMakeLists.txt, storage/mroonga/vendor/groonga/lib/expr.c, storage/perfschema/unittest/pfs_instr-t.cc, storage/rocksdb/CMakeLists.txt, storage/spider/spd_db_conn.cc
`page_is_corrupted()`: Do not allocate the buffers from stack, but from the heap, in `xb_fil_cur_open()`.
`row_quiesce_write_cfg()`: Issue one type of message when we fail to create the `.cfg` file.
`update_statistics_for_table()`, `read_statistics_for_table()`, `delete_statistics_for_table()`, `rename_table_in_stat_tables()`: Use a common stack buffer for `Index_stat`, `Column_stat`, `Table_stat`.
`translog_init_with_table()`: Do not duplicate `TRANSLOG_PAGE_SIZE_BUFF`.
Let us also globally enable the option `-Wframe-larger-than=16384` that was introduced in clang 3.0, to reduce the possibility of introducing such stack overflow in the future. For RocksDB and Mroonga we relax these limits.
The stack usage of MariaDB was reduced. Most notably, `mariadb-backup` should no longer crash due …
=> MDEV-34388: Stack overflow on Alpine Linux

mysql-test/suite/innodb/r/alter_temp_fail.result, mysql-test/suite/innodb/t/alter_temp_fail.opt, mysql-test/suite/innodb/t/alter_temp_fail.test, sql/ddl_log.cc, storage/innobase/btr/btr0cur.cc, storage/innobase/fil/fil0fil.cc, storage/innobase/row/row0log.cc, storage/innobase/row/row0umod.cc, storage/innobase/row/row0upd.cc
Problem:
=======
- During inplace algorithm, concurrent DML fails to write the log operation into the temporary file. InnoDB fail to mark the error for the online log.
Fix:
===
row_log_online_op(): Mark the error in online log when InnoDB ran out of temporary spac
./mtr innodb.alter_temp_fail
=> MDEV-36017 Alter table aborts when temporary directory is full

mysql-test/suite/innodb/r/insert_into_empty.result, mysql-test/suite/innodb/t/insert_into_empty.test, storage/innobase/trx/trx0trx.cc
- InnoDB fails to reset bulk_insert of a transaction while freeing the transaction during shutting down of a server.
=> MDEV-36771 Assertion 'bulk_insert == TRX_NO_BULK' failed in trx_t::assert_freed

cmake/maintainer.cmake, extra/CMakeLists.txt, include/my_pthread.h, mysql-test/include/no_msan_without_big.inc, mysql-test/include/not_msan.inc, mysql-test/include/not_msan_with_debug.inc, mysql-test/main/alter_table_lock.test, mysql-test/main/cte_recursive.test, mysql-test/main/join_cache_notasan.cnf, mysql-test/main/join_cache_notasan.result, mysql-test/main/join_cache_notasan.test, mysql-test/main/mysqld--help.result, mysql-test/main/mysqld--help.test, mysql-test/main/sum_distinct-big.test, mysql-test/suite/funcs_1/t/myisam_views-big.test, mysql-test/suite/innodb_gis/t/rtree_purge.test, mysql-test/suite/maria/max_length.test, mysql-test/suite/perfschema/t/statement_digest_long_query.test, mysql-test/suite/sys_vars/t/thread_stack_basic.test, sql/mysqld.cc, sql/sql_acl.cc, sql/sql_class.cc, sql/sys_vars.cc, storage/connect/bsonudf.cpp, storage/connect/bsonudf.h, storage/connect/jsonudf.cpp, storage/connect/jsonudf.h, storage/innobase/CMakeLists.txt, storage/mroonga/vendor/groonga/lib/ii.c
MSAN + CMAKE_BUILD_TYPE=Debug has stack overrun issues
Just a POC at the moment. Some tests still failing:
```
main.subselect_sj2_jcl6                  w2 [ fail ]
Test ended at 2025-05-23 10:34:57
CURRENT_TEST: main.subselect_sj2_jcl6
mysqltest: In included file "/source/mysql-test/main/subselect_sj2.test": 
included from /source/mysql-test/main/subselect_sj2_jcl6.test at line 18:
At line 893: query 'call p1()' failed: ER_STACK_OVERRUN_NEED_MORE (1436): Thread stack overrun:  444864 bytes used of a 458752 byte stack, and 16000 bytes needed. Consider increasing the thread_stack system variable.
```
non-user facing
CMAKE_BUILD_TYPE=Debug under MSAN like https://mariadb.com/kb/en/compile-and-using-mariadb-with-sanitizers-asan-ubsan-tsan-msan/ but without CMAKE_C,CXX_FLAGS=-O2
=> MDEV-36316/MDEV-36327/MDEV-36328 Msan debug innodb

storage/innobase/buf/buf0flu.cc, storage/innobase/include/log0log.h
If the execution of the two reads in `log_t::get_lsn_approx()` is interleaved with concurrent writes of those fields in `log_t::write_buf()` or `log_t::persist()`, the returned approximation will be an upper bound. If `log_t::append_prepare_wait()` is pending, the approximation could be a lower bound.
We must adjust each caller of `log_t::get_lsn_approx()` for the possibility that the return value is larger than
`MAX(oldest_modification)` in `buf_pool.flush_list`.
`af_needed_for_redo()`: Add a comment that explains why the glitch is not a problem.
`page_cleaner_flush_pages_recommendation()`: Revise the logic for the unlikely case `cur_lsn < oldest_lsn `.  The original logic would have invoked `af_get_pct_for_lsn()` with a very large age value, which would likely cause an overflow of the …
=> MDEV-36886 log_t::get_lsn_approx() isn't lower bound

storage/example/ha_example.cc
In the main.plugin this function is called assuming the function prototype int (*)(THD *, st_mysql_show_var *, void *, system_status_var *, enum_var_type)' as changed in b4ff64568c88ab3ce559e7bd39853d9cbf86704a.
We update the ha_example::show_func_example to match the prototype on which it is called.
internal test issue.
Under clang UBSAN tests run the unit test main.plugin.
=> MDEV-36729: ha_example::show_func_example is incorrectly defined

mysql-test/main/derived.result, mysql-test/main/derived.test, sql/table.cc
MariaDB server crashes when a query includes a derived table containing unnamed column (eg: `SELECT '' from t`). When `Item` object representing such unnamed column was checked for valid, non-empty name in `TABLE_LIST::create_field_translation`, the server crahsed(assertion `item->name.str && item->name.str[0]` failed).
This fix removes the redundant assertion. The assert was a strict debug guard that's no longer needed because the code safely handles empty strings without it.
Selecting `''` from a derived table caused `item->name.str` to be an empty string. While the pointer itself wasn't `NULL` (`item->name.str` is `true`), its first character (`item->name.str[0]`) was null terminator, which evaluates to `false` and eventually made the assert fail. The code immediately after the assert …
=> MDEV-24588: Assertion `item->name.str && item->name.str[0]` failed in `TABLE_LIST::create_field_translation` on SELECT

sql/bloom_filters.h
Only glibc and not musl currently supports the mechanisms of IFUNC. This fixes 11.8 branch build on Alpine Linux.
Build error was:
```console
mariadb-11.8.2/sql/vector_mhnsw.cc: In static member function 'static const FVector* FVector::create(metric_type, void*, const void*, size_t)': mariadb-11.8.2/sql/vector_mhnsw.cc:299:19: error: multiversioning needs 'ifunc' which is not supported on this target
299 |   static FVector *align_ptr(void *ptr) { return (FVector*)ptr; }
|                   ^~~~~~~~~
mariadb-11.8.2/sql/vector_mhnsw.cc:113:3: error: use of multiversioned function without a default
```
Fix build problem on musl (Alpine Linux)
Build MariaDB server 11.8.2 on Alpine Linux, see https://gitlab.alpinelinux.org/alpine/aports/-/tree/master/main/mariadb
=> MDEV-36995: ifunc is not supported by musl

CODING_STANDARDS.md
* #3853 fixup 
#3853 intended to update `CODING_STANDARDS.md` to say C++17 re. #3758, but somehow didn’t (lost diff when I squashed?), and it __still__ says C++11.
N/A
N/A?
=> MDEV-35837: Update CODING_STANDARDS to C++17

mysql-test/suite/innodb_fts/r/innodb_fts_misc_1.result, mysql-test/suite/innodb_fts/t/innodb_fts_misc_1.test, storage/innobase/handler/ha_innodb.cc
Problem:
=========
- During truncation of a fulltext table, InnoDB does create the table and does insert the default config fts values in fulltext common config table using create table transaction.
- Before committing the create table transaction, InnoDB does update the dictionary by loading the stopword into fts cache and write the stopword configuration into fulltext common config table by creating a separate transaction. This leads to lock wait timeout error and rollbacks the transaction.
- But truncate table holds dict_sys.lock and rollback also tries to acquire dict_sys.lock. This leads to assertion during rollback.
Solution:
=========
ha_innobase::truncate(): Commit the create table transaction before updating the dictionary after create table.
./mtr innodb_fts.innodb_fts_misc_1
=> MDEV-30363   InnoDB: Failing assertion: trx->error_state == DB_SUCCESS in que_run_threads

mysql-test/main/opt_hints_derived_condition_pushdown.result, mysql-test/main/opt_hints_derived_condition_pushdown.test, mysql-test/main/opt_hints_merge.result, mysql-test/main/opt_hints_merge.test, sql/opt_hints.cc, sql/opt_hints.h, sql/opt_hints_parser.cc, sql/opt_hints_parser.h, sql/sql_select.cc, sql/table.cc
Implements and tests the following optimizer hints:
- DERIVED_CONDITION_PUSHDOWN
- NO_DERIVED_CONDITION_PUSHDOWN
- MERGE
- NO_MERGE
Each of these are table-level hints.  The first pair enable and disable, respectively, the condition pushdown for derived tables which is typically controlled by the condition_pushdown_for_derived optimizer switch.  The second pair enable and disable, respectively, the derived table merge optimization which is typically controlled by the derived_merge optimizer switch.
=> MDEV-36106 New-style hints: [NO_]DERIVED_CONDITION_PUSHDOWN, [NO_]MERGE

mysql-test/suite/innodb/t/doublewrite.test
innodb.doublewrite: Added sleep to ensure page cleaner thread wake up from my_cond_wait
Tested in s390x-ubuntu platform and no failure
Added the following code:
```
set global innodb_log_checkpoint_now=1;              
--let CLEANUP_IF_CHECKPOINT=XA COMMIT 'x';drop table t1;                
--source ../include/no_checkpoint_end.inc
```
After adding the above code, InnoDB gracefully skips the test case.
```
innodb.doublewrite '32k,strict_crc32'    [ skipped ]  Extra checkpoint 1 after 61047 (77875,77842)
innodb.doublewrite '64k,strict_crc32'    [ skipped ]  Extra checkpoint 1 after 61048 (94277,94228)
innodb.doublewrite '32k,strict_full_crc32' [ skipped ]  Extra checkpoint 1 after 60901 (77729,77696)
innodb.doublewrite '64k,strict_full_crc32' [ skipped ]  Extra checkpoint 1 after 60902 …
```
=> MDEV-36650  Unexpected checkpoint in the test innodb.doublewrite

extra/mariabackup/xtrabackup.cc
`log_hdr_buf`: Align to an 8-byte boundary, because we will actually assume at least 4-byte alignment in `log_crypt_write_header()`.
This fixes a regression that had been introduced in commit 685d958e38b825ad9829be311f26729cccf37c46 (MDEV-14425) where a 512-byte alignment requirement was relaxed too much.
Depending on the build settings, `mariadb-backup --backup` might produce a corrupted log when the server is running with `innodb_encrypt_log`. This bug was only caught in internal testing with non-standard build parameters.
Build with clang, targeting ARMv8, and run
```sh
./mtr encryption.recovery_memory
```
=> MDEV-37049 my_assume_aligned assertion in mariabackup

storage/innobase/row/row0log.cc
In a UBSAN debug build, the comparisons with next_mrec_end are made with index->online_log's head/tail members' block ptr with a sort buffer size offset (1048576).
The logic that flows though to this point means that even srv_sort_buf_size above a null pointer wouldn't contain the value of next_mrec_end.
As such this is a UBSAN type fix where we first check if the head.block / tail.block is null before doing the asserts around this debug condition. This would be required for the assertions conditions not to segfault anyway.
nothing - test environment only change
clang-20.1 UBSAN + Debug build and run mtr test per test suite.
=> MDEV-37033 UBSAN: row_log_table_apply_ops runtime error: applying non-zero offset 1048576 to null pointer

mysql-test/suite/innodb/r/doublewrite_debug.result, mysql-test/suite/innodb/t/doublewrite_debug.test, storage/innobase/srv/srv0start.cc
Problem:
=======
- There are two failures occurs for this test case:
(1) set global innodb_buf_flush_list_now=1 doesn't make sure that pages are being flushed.
(2) InnoDB page cleaner thread aborts while writing the checkpoint information. Problem is that When InnoDB startup aborts, InnoDB changes the shutdown state to SRV_SHUTDOWN_EXIT_THREADS. By changing the shutdown state, InnoDB doesn't advance the log_sys.lsn (avoids fil_names_clear()). After InnoDB shutdown(innodb_shutdown()) is being initiated, shutdown state again changed to SRV_SHUTDOWN_INITIATED. This leads the page cleaner thread to fail with assertion ut_ad(srv_shutdown_state > SRV_SHUTDOWN_INITIATED) in log_write_checkpoint_info()
Solution:
=========
(1)  In order to avoid (1) failure, InnoDB can make the variable …
=> MDEV-35863 innodb.doublewrite_debug test case fails to start the server

mysql-test/suite/innodb/r/trx_deadlock.result, mysql-test/suite/innodb/t/trx_deadlock.opt, mysql-test/suite/innodb/t/trx_deadlock.test, sql/transaction.cc
A deadlock forces the on going transaction to rollback implicitly. Within a transaction block, started with START TRANSACTION / BEGIN, implicit rollback doesn't reset OPTION_BEGIN flag. It results in a new implicit transaction to start when the next statement is executed. This behaviour is unexpected and should be fixed. However, we should note that there is no issue with rollback.
We fix the issue to keep the behaviour of implicit rollback (deadlock) similar to explicit COMMIT and ROLLBACK i.e. the next statement after deadlock error is not going to start a transaction block implicitly unless autocommit is set to zero.
This bug-fix corrects the behaviour by not starting a new transaction block implicitly after a deadlock error within a transaction block.
./mtr innodb.trx_deadlock
=> MDEV-36959 Deadlock does not rollback transaction fully

support-files/MacOSX/ReadMe.txt, support-files/MacOSX/postflight.sh, support-files/binary-configure.sh, support-files/mariadb.service.in, support-files/mariadb@.service.in
It was mysql_install_db, and this is changed to mariadb-install-db.
This install script is part of the service as a useful instigation
step, and a no-op in subseqeuent runs.
This script does however change the auth_pam_tool_dir ownership.
When running a multi-instance based on username, changing the
auth_pam_tool_dir will only cause troubles for the other users.
If you are running multiple instances on username is seems you
are unlikely do be having pam access for all users. Even
if you where the solution on auth_pam_tool_dir would be a group
permission and group access based on the users.
As such skip the changing of ownership.
per JIRA
start service under a multi-instance username
=> MDEV-36738: mariadb@.service incorrectly changing pam ownership in mariadb-install-db

mysql-test/main/repair.result, mysql-test/main/repair.test, storage/csv/ha_tina.cc
When REPAIRing a CSV table, the CSV engine marks the table as having no rows in the case that there are rows only in memory but not yet written to disk.  In this case, there's actually nothing to repair, since nothing exists on disk; make REPAIR idempotent for CSV tables.
=> MDEV-23699 Assertion failed in ha_tina::delete_row

sql/vector_mhnsw.cc
This patch introduces loop unrolling by a factor of 4 in the
dot_product() function used in vector-based distance calculations.
The goal is to improve SIMD utilization and overall performance during
high-throughput vector operations, particularly in indexing and search
routines that rely on this function.
Observations from benchmarking (ann-benchmark):
- Query Performance (QPS) improved by 4–10% across datasets.
- Indexation time reduced by 22–28%.
- Loop unrolling factors of 8 or 16 yielded similar performance to
factor-4 but made the code less readable. Hence, a factor of 4 was
chosen to maintain a balance between performance and code clarity.
This change is architecture-specific (PowerPC) and should not
introduce any behavioural regressions or side effects in unrelated
parts of the …
=> MDEV-37107 - Optimise dot_product by loop-unrolling by a factor of 4

mysql-test/suite/innodb/r/innodb_defrag_stats.result, mysql-test/suite/innodb/t/innodb_defrag_stats.test, storage/innobase/dict/dict0dict.cc
While updating the persistent defragmentation statistics for the table, InnoDB opens the table only if it is in cache. If dict_table_open_on_id() fails to find the table in cache then it fails to unfreeze dict_sys.latch. This lead to crash
./mtr innodb.innodb_defrag_stats
=> MDEV-37123 dict_table_open_on_id() fails to release dict_sys.latch

strings/my_vsnprintf.c
5 years ago e843033d0233927b8f51d7dbe21993bdfb01ecdf worked around a MSAN bug when retrieving a double from a va_list.
The construct {{__msan_check_mem_is_initialized(ap,size)}} where ap is a va_list is undefined as {{__msan_check_mem_is_initialized}} expects a pointer. The implementation detail of va_list is architecture dependant and on aarch64 this isn't a pointer.
The need to do any msan action is no unnecessary since this has been corrected in recent clang versions.
As such the additions from e843033d0233927b8f51d7dbe21993bdfb01ecdf have been reverted.
Tested with clang-20.1 and the test cases from MDEV-22690 and MDEV-22691.
not user visible change
msan builder on arm64 (https://github.com/MariaDB/buildbot/pull/769)
```
main.opt_trace_ucs2                      w5 [ pass ]    153 …
```
=> MDEV-37048 revert MSAN my_vsnprintf_ex for double workaround

sql/mysqld.cc
Currently, when MariaDB server creates socket connections, the log message "Server socket created on IP: '\[IP\]'" lacks port information, making it ambiguous especially when multiple ports are in use (e.g., default port 3306 and extra_port). This can make it difficult for users to identify which socket corresponds to which port.
This PR modifies the log message to include the port number, improving clarity and debugging capabilities.
N/A
1. Start MariaDB server with an extra port:
```bash
./build/sql/mariadbd --datadir=./data --user=root --extra_port=3307 &
```
2. Check the server logs
Before change:
```
...
2025-06-30 19:12:21 0 [Note] Crash table recovery finished.
2025-06-30 19:12:21 0 [Note] Server socket created on IP: '0.0.0.0'.
2025-06-30 19:12:21 0 [Note] Server socket created on …
```
=> MDEV-36987 Add port information to server socket creation log message

mysql-test/suite/mariabackup/backup_ssl.result, mysql-test/suite/mariabackup/backup_ssl.test, sql-common/client.c
Passwordless authentication fails for mariabackup with "certificate is self-signed", is a  side-effect of the new zero configuration SSL + SSL by default + SSL server verification by default in 11.4
It was previously corrected on *nix, and unix socket only in MDEV-35368. That fix did not work on Windows, where passwordless connections can be secure with auth_gssapi  (on by default for "root")
Fixed by implementing [the same logic as Connector/C has](https://github.com/mariadb-corporation/mariadb-connector-c/blob/b5a2c9f3c275861447ca21ee1f01560135ec6c2f/plugins/auth/my_auth.c#L66)
mariadb-backup  failure with "Certificate is self-signed" for passwordless authentication was fixed.
mtr tests updated
If the changes are not amenable to automated testing, please explain why not and carefully …
=> MDEV-37143 mariabackup fails with "self-signed certificate" on Windows

mysys/crc32/crc32c_x86.cc
Recently, evex512 was removed from gcc trunk [1] which will eventually become gcc 16, and that leads to a build failure
in mariadb, originally reported downstream in a Gentoo bug [2].
```
/home/kostadin/mariadb-11.4.7/mysys/crc32/crc32c_x86.cc:134:23: error: attribute ‘target’ argument ‘evex512’ is unknown
134 | static inline __m128i xor3_128(__m128i a, __m128i b, __m128i c)
|                       ^~~~~~~~
/home/kostadin/mariadb-11.4.7/mysys/crc32/crc32c_x86.cc:141:23: error: attribute ‘target’ argument ‘evex512’ is unknown
141 | static inline __m128i xnor3_128(__m128i a, __m128i b, __m128i c)
|                       ^~~~~~~~~
/home/kostadin/mariadb-11.4.7/mysys/crc32/crc32c_x86.cc:148:23: error: attribute ‘target’ argument ‘evex512’ is unknown
148 | static inline __m512i …
```
=> Fix building with gcc 16 (evex512 removal)

mysys/crc32/crc32c_x86.cc
The AVX512 accelerated CRC-32 computation that had been added in #3195 was disabled in #4081 for GCC 16.
Let us enable that logic by applying
dr-m/crc32_simd@075bacb0cc7da8df18afa15a827ae4d11166fe32 which makes use of the `avx10.1` target attribute that had been introduced in GCC 15.
N/A. GCC 16 had not been released yet, and there is no MariaDB release where the regression that was introduced in #4018 would not have been fixed.
I tested this on https://godbolt.org by choosing x86-64 gcc version 15.1 or trunk. In clang, there is no `avx10.1` target attribute yet.
=> MDEV-37170 Enable AVX10.1 CRC-32 on GCC 16

storage/rocksdb/mysql-test/rocksdb_rpl/r/rpl_xa.result
In 805e7ca3adef50e17889ea17a1b86da6c3fb8580 the errors codes for "Pseudo thread id should not be modified by the client as it will be overwritten" changed from 4196 back to 4205 where it was previously however this test case wasn't re-recorded.
nothing - test change only.
mtr test rocksdb_rpl.rpl_xa
=> fix incorrect merge 15700f54c212 (part 2) rocksdb_rpl.rpl_xa

mysql-test/main/mysqladmin.test, mysql-test/main/statistics_upgrade_not_done.test
The causes of these test failures are sparatic and haven't been generated locally. The stack trace looks like it could be an internal MSAN error too. Disable for the time being as there is some server coverage of these test paths elsewhere.
nothing.
see if they are skipped in msan.
=> MDEV-37169: MSAN disable main.{mysqladmin,statistics_upgrade_not_done}

client/mysqldump.c, mysql-test/main/mysqldump.result, mysql-test/suite/multi_source/mariadb-dump_slave.result, mysql-test/suite/multi_source/mariadb-dump_slave.test, mysql-test/suite/rpl/r/rpl_mysqldump_gtid_slave_pos.result, mysql-test/suite/rpl/t/rpl_mysqldump_gtid_slave_pos.test
* This bug’s reported 10½ years ago!? :astonished:
Store the _SLAVE_ STATUS when pausing replicas for `mariadb-dump --dump-slave`;
use that (instead of a new SHOW _SLAVE_ STATUS) to resume replicas when the program ends.
> When making a dump with --dump-slave option, upon completion mysqldump starts slave threads [IO & SQL for all multi-source connections] even if they were not stopped by mysqldump itself.
> This behavior breaks delayed/manually synchronized slaves which have not to be running all the time.
> ⸺ [MDEV-7611][]
* Fix `mariadb-dump --dump-thread` starts replication threads that were not running
* The new `multi_source.mariadb-dump_slave` tests this issue for multi-source and, by consequence, single-source replication.
* Edge cases and changed side-effects remain testable by …
=> MDEV-7611 mysqldump --dump-slave always starts stopped slave

mysql-test/suite/innodb/r/scrub_debug.result, mysql-test/suite/innodb/t/scrub_debug.test, storage/innobase/page/page0page.cc
`page_delete_rec_list_end()`: Do not attempt to scrub the data of an empty record.
The test case would reproduce a debug assertion failure in branches where 358921ce32203a9a8dd277a5ba7ac177c9e79e53 is present. MariaDB Server 10.6 only supports ascending indexes, and in those, the empty string would always be sorted first, never last in a page.
Nevertheless, we fix the bug also in 10.6, in case it would be reproducible in a slightly different scenario.
This is a rare corner case, probably not worth mentioning. It only affects empty secondary index records where also the `PRIMARY KEY` is an empty string.
I tested a cherry-pick of this on top of 56ce9e72a1832a581cfaea27602a290bf253e9e6 in the current 10.11 branch.
```sh
mysql-test/mtr innodb.scrub_debug
```
Without the fix but only the test, …
=> MDEV-37183 Scrubbing empty record breaks recovery

mysql-test/main/derived.result, mysql-test/main/derived.test, mysql-test/main/derived_view.result, sql/table.cc
MDEV-37044 derived_wth_keys optimization not applied where it should
Since commit 271fed41061 we have these functions for key parameters tmp_table_max_key_length()
tmp_table_max_key_parts()
This commit uses these in TABLE::check_tmp_key() called from generate_derived_keys_for_table() used in key generation for result tables of materialized derived tables/views
Materialized derived tables with long generated keys may be faster.
mtr main.derived
=> MDEV-37044 derived_wth_keys optimization not applied where it should

mysql-test/main/opt_hints_split_materialized.result, mysql-test/main/opt_hints_split_materialized.test, sql/opt_hints.cc, sql/opt_hints.h, sql/opt_hints_parser.cc, sql/opt_hints_parser.h, sql/opt_split.cc, sql/table.h
Support for optimizer hints NO_SPLIT_MATERIALIZED and SPLIT_MATERIALIZED.  These hints allow fine-grained control of the "lateral derived" optimization within a query.
=> MDEV-36092 New-style hint: [NO_]SPLIT_MATERIALIZED

mysql-test/suite/binlog/t/binlog_mysqlbinlog_warn_stop_position.inc
Hash tables don’t have a specific ordering to avoid the overhead of tracking the order. But consequentially, the output of this test from [MDEV-34614][] (#3600) may be in a different order – notably, in big-endian platforms like S390x.
This patch adds `--sort_result` to affected test cases to overcome this difference without changing the code.
(Both insertion-order and natural (Domain ID)-order make sense for these GTID filters, and *both would need more or less significant modifications to the Hash set*.)
N/A (test output inconsistency)
Build and run the test on [various platforms](https://buildbot.mariadb.org/#/grid?branch=refs%2Fpull%2F4200%2Fhead), namely, S390x
[MDEV-34614]: https://jira.mariadb.org/browse/MDEV-34614
=> Sort output of `binlog_mysqlbinlog_warn_stop_gtid`

storage/innobase/buf/buf0flu.cc, storage/innobase/fil/fil0fil.cc
The test `innodb.undo_truncate` occasionally demonstrates a race condition where scrubbing is writing zeroes to a freed undo page, and `innodb_undo_log_truncate=ON` truncating the same tablespace. The truncation is an exception to the rule that InnoDB tablespace file sizes can only grow, never shrink.
Currently the `fil_space_t::size` and `fil_node_t::size` are protected by `fil_system.mutex`, which used to be a highly contended resource. We do not want to revert back to acquiring the mutex in `fil_space_t::io()` because that would introduce an obvious scalability bottleneck.
In fact, during or slightly after the time `fil_space_t::io()` is assessing the size, the size may be changed by another thread. A concurrent increase of the size is not a problem, but shrinking the size may be. That …
=> MDEV-37103 innodb_immediate_scrub_data_uncompressed=ON may break innodb_undo_log_truncate=ON

mysql-test/suite/innodb/r/innodb_buffer_pool_shrink_temporary.result, mysql-test/suite/innodb/t/innodb_buffer_pool_shrink_temporary.opt, mysql-test/suite/innodb/t/innodb_buffer_pool_shrink_temporary.test, storage/innobase/buf/buf0buf.cc
`buf_pool_t::shrink()`: When relocating a dirty page of the temporary tablespace, reset the oldest_modification() on the discarded block, like we do for persistent pages in `buf_flush_relocate_on_flush_list()`.
`buf_pool_t::resize()`: Add debug assertions to catch this error earlier.
This bug does not seem to affect non-debug builds.
N/A
```sh
./mtr innodb.innodb_buffer_pool_shrink_temporary
```
=> MDEV-37250 buf_pool_t::shrink() assertion failure

mysql-test/suite/innodb/r/innodb_buffer_pool_shrink.result, mysql-test/suite/innodb/t/innodb_buffer_pool_shrink.test, storage/innobase/buf/buf0buf.cc
`buf_pool_t::shrink()`: If we run out of pages to evict from `buf_pool.LRU`, abort the operation. Also, do not leak the spare `block` that we may have allocated.
This fixes a regression that was introduced in #3826.
Shrinking `innodb_buffer_pool_size` could cause the server to hang or crash if all data pages are being removed from the buffer pool.
```sh
./mtr innodb.innodb_buffer_pool_shrink
```
=> MDEV-37263 Hang or crash when shrinking innodb_buffer_pool_size

mysql-test/suite/rpl/r/rpl_alter_convert_partition.result, mysql-test/suite/rpl/t/rpl_alter_convert_partition.test, sql/sql_partition.cc, sql/sql_table.cc, sql/sql_table.h
Note this patch is a draft to showcase the issue and is constructed
in a way to elicit feedback from reviewers, rather than a patch
ready-to-be-approved.
MDEV-33658 part 1’s refactoring ecaedbe299fe11372c36319f9b732b81e9f54883
introduced a new function init_key_info which (in part) aims to
calculate the total key length; however, it doesn’t account for the
key already having been initialized (as happens when called via
ALTER TABLE .. CONVERT PARTITION .. TO TABLE). This leads to crashes
when this key is later iterated over, because the iterator will try
to iterate over additional key parts which don’t exist because the
length reports as longer than the actual memory owned. The crash
reported by MDEV-36906 highlights this in function key_copy. 
A few possibilities for fixes:
1. In the …
=> MDEV-36906: RBR crashes upon DML after CONVERT PARTITION

mysql-test/main/failed_auth_unixsocket.result, mysql-test/main/failed_auth_unixsocket.test
Don't log the change_user result to the test result file.
=> MDEV-37308 main.failed_auth_unixsocket fails

mysql-test/suite/sys_vars/r/slave_parallel_threads_basic.result, mysql-test/suite/sys_vars/t/slave_parallel_threads_basic.test
Add explicit column aliases to `SELECT` statements in `slave_parallel_threads_basic` to ensure consistent column names across both normal and view-protocol modes.
The test `sys_vars.slave_parallel_threads_basic.test` was failing in view-protocol mode due to different column naming behavior. Without an explicit column alias, view-protocol mode generates an automatic name (`Name_exp_1`) while normal mode uses the full expression as the column name.
N/A
Execute the test `slave_parallel_threads_basic` in view-protocol mode using `./build/mysql-test/mysql-test-run.pl --force --parallel=auto --skip-rpl --view-protocol sys_vars.slave_parallel_threads_basic`. 
**Before this change**
The test fails like so:
```
==============================================================================
TEST …
```
=> MDEV-36385 Fix slave_parallel_threads_basic test in view-protocol mode

mysql-test/suite/innodb/r/bulk_load.result, mysql-test/suite/innodb/t/bulk_load.test, storage/innobase/row/row0ins.cc
Problem:
=======
- InnoDB modifies the PAGE_ROOT_AUTO_INC value on clustered index
root page. But before committing the PAGE_ROOT_AUTO_INC changes
mini-transaction, InnoDB does bulk insert operation and
calculates the page checksum and store as a part of redo log in
mini-transaction. During recovery, InnoDB fails to validate the
page checksum.
Solution:
========
- Avoid writing the persistent auto increment value before doing
bulk insert operation.
InnoDB bulk insert breaks the recovery when persistent autoinc is involved 
./mtr innodb.bulk_load
=> MDEV-37192  Crash recovery after bulk load data reports corruption

storage/innobase/srv/srv0srv.cc
`srv_printf_innodb_monitor()`: After acquiring a latch, abort the iteration if `innodb_adaptive_hash_index=OFF`. If the adaptive hash index was disabled in a concurrently executing thread, `btr_search_sys_t::partition::clear()` would have freed `part->heap`, leading to us dereferencing a null pointer.
InnoDB could crash if `innodb_adaptive_hash_index` is being disabled while `SHOW ENGINE INNODB STATUS` is executing.
Concurrent connections executing the following statements:
```sql
SET GLOBAL innodb_adaptive_hash_index=ON;
SET GLOBAL innodb_adaptive_hash_index=ON;
SHOW ENGINE INNODB STATUS;
```
=> MDEV-37360: SIGSEGV in srv_printf_innodb_monitor

mysql-test/suite/innodb/r/alter_copy_bulk.result, mysql-test/suite/innodb/t/alter_copy_bulk.test, storage/innobase/include/dict0mem.h, storage/innobase/row/row0ins.cc
Problem:
=======
- During copy algorithm, InnoDB fails to detect the duplicate key error for unique hash key blob index. Unique HASH index treated as virtual index inside InnoDB. So bulk insert operation doesn't detect the duplicate key error while building the index.
Solution:
========
- Avoid bulk insert operation when table does have unique hash key blob index.
has_unique_blob(): Check whether the table has any unique blob index
dict_table_t::unique_blob : Indicates that table has long unique blob column
Avoid the bulk insert operation for copy algorithm When table has unique blob index.
./mtr innodb.alter_copy_bulk
=> MDEV-37296 ALTER TABLE allows adding unique hash key with duplicate values

extra/mariabackup/backup_mysql.cc, extra/mariabackup/xtrabackup.cc, mysql-test/suite/mariabackup/full_backup.test, mysql-test/suite/mariabackup/partial.test, mysql-test/suite/mariabackup/partial_exclude.test, mysql-test/suite/mariabackup/unsupported_redo.test
Ever since commit 685d958e38b825ad9829be311f26729cccf37c46 (MDEV-14425) `mariadb-backup --backup` had some trouble to keep up with write workloads of the `mariadbd` server.
Debarun Banerjee found out that `mariadb-backup --backup` was copying the log in the wrong way and not pausing when it made sense to do so. This change includes his fix as well (#4178) as some dead code removal from `xtrabackup_copy_mmap_logfile()`.
Some earlier changes to the default behaviour of `mariadb-backup --backup` will be reverted, by making the configuration parameters OFF by default. These parameters were basically working around this bug:
* #3866 introduced `--innodb-log-checkpoint-now` and made it ON by default. Making the server execute a log checkpoint can be really I/O intensive.
* #3282 introduced …
=> MDEV-36159 mariabackup failed after upgrade

mysql-test/mariadb-test-run.pl, tpool/aio_libaio.cc
Where io_setup fails, this is a serious issue, normally because of the lack of fs.aio-max-nr configured in the kernel. We adjust the error message to be a Warning, because like "native AIO failed: falling back to innodb_use_native_aio=OFF", its user actionable.
A default configuation of the server and indeed raising innodb_write_io_threads and innodb_read_io_threads couldn't exceed the default fs.aio-max-nr value. If a user is constructing multipe instances of MariaDB that exceed this value then they should be seeing the warning and taking action.
There are CI environments, as Otto points on on Launchpad, that have insufficient fs.aio-max-nr configure to run mtr in parallel. This however a genuine distro problem and to resolve.
For us, and our developers, we'd rather see the warning so we …
=> MDEV-37411: Clear warnings for io_setup failure

mysql-test/suite/rpl/r/rpl_heartbeat_at_rotate.result, mysql-test/suite/rpl/t/rpl_heartbeat_at_rotate.test, sql/log.cc, sql/slave.cc
Replication can stop in error if a Heartbeat log event is sent to a
replica during rotation. There are two bugs at play:
1. Prior to MDEV-30128 (added in 11.0), there is a bug when checking
legacy events. When the replica rotates its relay logs, it
initializes its Format_description_log_event with binlog version 3
(this is hard-coded). So immediately after rotation (and until a
new Format_descriptor with binlog_format 4 is sent from the 
master), the IO thread is expecting binlog_format 3. This
invalidates any events that are sent with an event type higher
than 14. In theory, we wouldn't expect any events to be sent
in-between a rotate and the next format descriptor log event, but 
if a long enough period of time passes between then, the primary
will generate and send a Heartbeat event …
=> MDEV-29981: Replica stops with "Found invalid event in binary log"

sql/opt_split.cc
add_ext_keyuse_for_splitting assumed the added_key_field->cond was of type Item_func_eq. In 11.8 there are cases where this is actually of type Item_func_equal in some cases which is not a class descendant of Item_func_eq.
The only use of this class is accessing its arguments() method which is defined all the way up the hierarchy of both Item_func_equal and Item_func_eq in the class Item_args.
To resolve future mis-castings of this method we assume the topmost class of Item_args.
nothing.
mtr case `main.derived_split_innodb` once merged to 11.8 branch
Unsure how to trigger in 10.11.
=> MDEV-37438: UBSAN add_ext_keyuse_for_splitting downcast Item_func_equal -> Item_func_eq

mysql-test/main/subquery_merge.result, mysql-test/main/subquery_merge.test, sql/sql_lex.cc
Exclude associated contexts when excluding SELECT_LEXs.  These exclusions can happen when merging derived tables into the parent SELECT_LEX.  Later, attempting to call fix_fields() on an Item that interacts with a merged SELECT_LEX should not be able to access a context associated with a merged select.
Usage of outer references in merged selects can cause problems, especially in prepared statements.
=> MDEV-32294 fix_fields() problem with inconsistent outer context paths

storage/rocksdb/mysql-test/rocksdb/include/bulk_load_unsorted.inc, storage/rocksdb/mysql-test/rocksdb/t/unique_check.test, storage/rocksdb/rdb_datadic.cc
Correct MSAN errors in a few of the rocksdb tests.
Some rocksdb test either timed out or was slow so adjust these for the msan case.
nothing.
rocksdb.issue896 + rocksdb.type_char_indexes_collation
=> MDEV-37504 MemorySanitizer: use-of-uninitialized-value myrocks::Rdb_key_def::pack_field

mysys/crc32/crc32c_x86.cc
It turns out that there is no need to use the `evex512` target attribute that had been introduced in GCC 14 and clang 18, and will be removed in GCC 16.
At the time when the `evex512` attribute was introduced, Intel had an idea to release products with AVX10.1-256, supporting the AVX512 instruction set but limited to 256-bit registers.  The `evex512` attribute would have been needed to "opt in" to the 512-bit instruction variants (using the EVEX instruction prefix). Later on, Intel revised its plans to make AVX10.1 always 512-bit.
This follows up #3270, #4081, #4170.
N/A
I have tested this on https://godbolt.org. On our CI we do have some hosts that support AVX512 and will run this code.
=> MDEV-33817/MDEV-37170 fixup: Remove evex512

mysql-test/suite/innodb/t/innodb-index-online.test, mysql-test/suite/innodb/t/innodb-table-online.test, mysql-test/suite/innodb/t/monitor.test, storage/innobase/include/srv0mon.h, storage/innobase/include/srv0mon.inl, storage/innobase/srv/srv0mon.cc
- Moved srv_mon_reset_all definition from srv0mon.inl to srv0mon.cc
- Log via sql_print_warning() instead of fprintf()
- Removed UNIV_INLINE from declaration
The logs emitted by "srv_mon_reset_all()" are formatted 
1. SET GLOBAL innodb_monitor_enable = 'all';
2. SET GLOBAL innodb_monitor_reset_all = 'all';
3. Verify the log in the file provided in "--log-error= " while starting the server
=> MDEV-36993: Format log for srv_mon_reset_all.

storage/innobase/mtr/mtr0mtr.cc
`log_t::append_prepare_wait()`: Relax the debug assertion in case log_overwrite_warning() has been called. In this case, the contents of `log_sys.buf` (and the `ib_logfile0`) is basically unrecoverable garbage, and it does not matter which write was last persisted.
This assertion would easily fail in the 11.4 branch in the test `encryption.innochecksum` after merging MDEV-36024.
N/A
On two systems that I have access to, 8f30f028c548fee7c8cdde61cdd84f500fa6af50 (a merge of 10.11 to 11.4) would crash in the test `encryption.innochecksum` when this change is absent, and pass when this change is present.
=> MDEV-37553: Assertion failure lsn - get_flushed_lsn(std::memory_order_relaxed) < capacity()

sql/CMakeLists.txt
The compile time on aarch64 in RHEL8 (gcc-8.5 compiler) for these two files was approaching 10 minutes. With the -fno-strict-aliasing compile flag, same that was added in release builds, this now compiles in 30 seconds.
nothing - non-release build
See how long it takes
=> SQL parser: add -fno-strict-aliasing to gcc<9 aarch build

strings/conf_to_src.c
Caused by MDEV-30577 when the CHARSET_INFO structure changed.
As hinted by clang:
error: no member named 'csname' in 'struct charset_info_st'; did you mean 'cs_name'?
Because the target conf_to_src has the properties EXCLUDE_FROM_DEFAULT_BUILD it hasn't been noticed.
nothing - convenience not distributed executable
explicitly build the target and it will compile:
```
cmake --build . --target conf_to_src
```
Run codebase under static analyser.
10.6 faults also exist, but I'm not concerned.
=> MDEV-30692: conf_to_src incompatible with CHARSET_INFO changes (postfix)

sql/wsrep_allowlist_service.cc
MDEV-37136 allowed connections by default if wsrep_schema is not initialized, but this allows process to connect to a node which is joining to the cluster and receiving SST (i.e. all incoming connections are allowed until the storage engines get initialized). We need to allow all connections by default to maintain upgradability if nothing else is configured.
However, if user has given wsrep_allowlist string or stored allowed connections to mysql.wsrep_allowlist table used address should be checked.
When node is joining to the cluster and receiving SST InnoDB storage engine is not initialized, thus mysq.wsrep_allowlist table is not available and wsrep_schema is not initialized. In this case we still should check has user configured allowed connections using wsrep_allowlist configuration …
=> MDEV-37548 : wsrep_allowlist allows all connections during SST

mysql-test/suite/innodb/r/leaf_page_corrupted_during_recovery.result, mysql-test/suite/innodb/t/leaf_page_corrupted_during_recovery.test, storage/innobase/log/log0recv.cc
Problem:
=======
When InnoDB encounters a corrupted page during crash recovery, server would abort due to improper handling of page locks and space references. The recovery process was not properly cleaning up resources when corruption was detected, leading to inconsistent state and server termination.
Solution:
=========
recover_low(): Move page lock recursive acquisition after deferred/non-deferred page creation logic to ensure consistent locking behavior for both code paths. Ensure proper block recursive unlock for non-deferred tablespaces
recv_recover_page(): Simplify corrupted page cleanup by removing redundant space reference handling.
Server abort when encountering corrupted pages during crash recovery. This fix prevents
unexpected server shutdowns during crash recovery when …
=> MDEV-37412 Corrupted page during recovery aborts the server

sql/sql_class.cc, storage/innobase/dict/dict0crea.cc, storage/innobase/dict/dict0dict.cc, storage/innobase/eval/eval0eval.cc, storage/innobase/handler/ha_innodb.cc, storage/innobase/handler/ha_innodb.h, storage/innobase/handler/handler0alter.cc, storage/innobase/include/eval0eval.inl, storage/innobase/include/ha_prototypes.h, storage/innobase/include/trx0i_s.h, storage/innobase/include/trx0trx.h, storage/innobase/lock/lock0lock.cc, storage/innobase/row/row0ins.cc, storage/innobase/row/row0sel.cc, storage/innobase/row/row0uins.cc, storage/innobase/trx/trx0i_s.cc, storage/innobase/trx/trx0purge.cc, storage/innobase/trx/trx0trx.cc, storage/rocksdb/ha_rocksdb.cc
Let InnoDB access some data members of `THD` directly, instead of invoking non-inline accessor functions. Note: `my_thread_id` will be used instead of the potentially narrower `ulong` data type.
Also, let us remove some functions from `sql_class.cc` that were only being used by InnoDB or RocksDB, for no reason. RocksDB always had access to the internals of `THD`.
The performance of InnoDB was slightly improved.
The performance impact has been tested in [MDEV-37152](https://jira.mariadb.org/browse/MDEV-37152) as part of #4252.
The modified code should be well exercised by the default regression tests. No change in behaviour is expected.
I believe that this would benefit the 10.6 branch as well, but there are several other performance fixes that were already omitted from the 10.6 branch.
=> MDEV-37619 The forced use of THD accessors hurts InnoDB performance

mysql-test/suite/encryption/r/innodb-read-only.result, mysql-test/suite/encryption/t/innodb-read-only.test, storage/innobase/fil/fil0crypt.cc
Encryption thread creation is only done when server is not in read only mode.
1. Modified srv_start to call fil_crypt_threads_init() only
when srv_read_only_mode is not set.
2. Modified encryption.innodb-read-only to capture number of
encryption threads created for both scenarios when
server is not read only as well as when server is read only.
This PR is a bug fix reported in MDEV-37299. 
When the server was started in read-only mode with encryption enabled,
the fix ensures that InnoDB avoids creating any encryption thread. 
No user-visible changes apart from the fix.
Test encryption.innodb-read-only contains scenario that can be used to test this change.
=> MDEV-37299: Fix server crash when encryption is ON and server is read-only

mysql-test/main/func_json.result, mysql-test/main/func_json.test, sql/item_jsonfunc.cc
Regression from MDEV-36765 / 2b24ed87f0028180e692ba391132f55284377c02.
json_unescape can return a string length 0 without it being an error.
The regression caused this 0 length empty string to appear as an error and result in a NULL return value.
Corrected regression to return empty string rather than errously returning NULL in JSON_VALUE.
test case included
=> MDEV-37428 JSON_VALUE returns NULL for a key with an empty string value rather than an empty string

mysql-test/suite/innodb/r/alter_copy_stats.result, mysql-test/suite/innodb/r/innodb-alter-debug.result, mysql-test/suite/innodb/r/xap_release_locks_on_dict_stats_table.result, mysql-test/suite/innodb/t/alter_copy_stats.test, mysql-test/suite/innodb/t/innodb-alter-debug.test, mysql-test/suite/innodb/t/xap_release_locks_on_dict_stats_table.test, mysql-test/suite/innodb_fts/t/versioning.test, storage/innobase/dict/dict0stats.cc, storage/innobase/handler/ha_innodb.cc, storage/innobase/handler/ha_innodb.h, storage/innobase/handler/handler0alter.cc
Problem:
=======
- InnoDB statistics calculation for the table is done after every 10 seconds by default in background thread dict_stats_thread()
- Doing multiple ALTER TABLE..ALGORITHM=COPY causes the dict_stats_thread() to lag behind, therefore calculation of stats for newly created intermediate table gets delayed
Fix:
====
- Stats calculation for newly created intermediate table is made independent of background thread. After copying gets completed, stats for new table is calculated as part of ALTER TABLE ... ALGORITHM=COPY.
dict_stats_rename_table(): Rename the table statistics from temporary table to non-temporary table
This is a cherry-pick fix of mysql commit@cfe5f287ae99d004e8532a30003a7e8e77d379e3
./mtr innodb.alter_copy_stats
=> MDEV-35163  InnoDB persistent statistics fail to update after ALTER TABLE...ALGORITHM=COPY

mysql-test/suite/galera/r/MDEV-30418.result, mysql-test/suite/galera/t/MDEV-30418.test, mysql-test/suite/wsrep/r/wsrep_variables_wsrep_off.result, mysql-test/suite/wsrep/t/wsrep_variables_wsrep_off.test, sql/sys_vars.cc, sql/wsrep_var.cc
Problem was that wsrep was disconnected and new slave threads tried to connect to cluster but failed as
we were disconnected state.
Allow changing wsrep_slave_threads only when wsrep is enabled and we are connected to a cluster. In other cases report error and issue a warning.
If the changes are not amenable to automated testing, please …
=> MDEV-30418 : Setting wsrep_slave_threads causes thread hang

storage/innobase/btr/btr0btr.cc, storage/innobase/btr/btr0cur.cc, storage/innobase/btr/btr0pcur.cc, storage/innobase/buf/buf0buf.cc, storage/innobase/buf/buf0lru.cc, storage/innobase/buf/buf0rea.cc, storage/innobase/dict/dict0dict.cc, storage/innobase/include/buf0buf.h, storage/innobase/include/trx0purge.h, storage/innobase/lock/lock0lock.cc, storage/innobase/trx/trx0purge.cc, storage/innobase/trx/trx0rec.cc
`buf_pool_t::page_guess()`: Avoid a memory transaction, because we would be checking several conditions inside it. Synchronize with `buf_page_t::init()` in order to avoid false guesses.
`buf_pool_t::page_hash_table::append()`: Define non-`inline`.
`buf_pool_t::page_hash_table::replace()`, `buf_pool_t::page_hash_table::remove()`: Move the inline definition to the compilation unit of the only caller, to declutter the header.
`buf_page_create_low()`, `buf_page_init_for_read()`: Do not initialize the block descriptor before holding a latch on `buf_pool.page_hash`, in order to avoid false positive matches in `buf_pool_t::page_guess()`.
`trx_undo_report_row_operation()`: Check the cheaper and less likely condition first.
Also, remove several redundant `TRANSACTIONAL_TARGET`. Some of the …
=> MDEV-36190: Optimize transaction_lock_guard use

mysql-test/main/win.result, mysql-test/main/win.test, mysql-test/suite/encryption/r/tempfiles_encrypted.result, sql/sql_window.cc
MDEV-31744: Assertion with COUNT(*) OVER (ORDER BY const RANGE BETWEEN...)
When the query uses several Window Functions:
SELECT
WIN_FUNC1() OVER (ORDER BY 'const', col1),
WIN_FUNC2() OVER (ORDER BY col1 RANGE BETWEEN CURRENT ROW
AND 5 FOLLOWING)
compare_window_funcs_by_window_specs() will try to get the Window Specs to
reuse the ORDER BY lists. If the lists produce the same order (like above)
Window Spec of the WIN_FUNC2 will reuse the ORDER BY list of WIN_FUNC1.
However, WIN_FUNC2 has a RANGE-type window frame. It expects to get
ORDER BY list with one element, which it will use to compute frame bounds.
Proving it with ORDER BY list from WIN_FUNC1 ('const', col1) was caused an
assertion failure
The fix is to:
- Use the original ORDER BY list when constructing RANGE-type frames
- Fix an …
=> 10.11-MDEV-31744: frame_range_n_bottom assertion error

debian/control
The dependency on libxml2 will be populated by its shlibs:Depends directive.
Thanks Simon Chopin for pointing out the error of our ways and I'm counting this as the review/author.
ref: https://bugs.launchpad.net/ubuntu/+source/libxml2/+bug/2125555
Probably not user visible.
Install tests on Ubuntu 25.10.
=> MDEV-37776: connect engine Debian packaging shouldn't depend explictly on libxml2

cmake/cpack_rpm.cmake
mysql-selinux-1.0.14 provides the necessary labels for MariaDB to function correctly in selinux environment. mysql-selinux-1.0.14
Thanks Pavol Sloboda for the bug forwarding and a ready to package solution.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2395701
As this is affecting upstream packages only, there isn't added portability put into AlmaLinux/Rocky Linux.
Per JIRA.
test builds before rebase:
https://buildbot.mariadb.org/#/grid?branch=bb-10.11-MDEV-37680-danblack-pkgtest
https://buildbot.mariadb.org/#/grid?branch=bb-11.4-MDEV-37680-danblack-pkgtest
Depends on CI change https://github.com/MariaDB/buildbot/pull/845 that catches added dependencies.
=> MDEV-37680/MDEV-24941: RHEL9+,Centos-stream and Fedora to pull mysql-selinux-1.0.14+ dependency

mysql-test/suite/galera/disabled.def, mysql-test/suite/galera/r/MW-329.result, mysql-test/suite/galera/t/MW-329.test
Better to use KILL HARD and wait until connection is really gone.
Test case changes only.
- [ x] *This is a bug fix, and the PR is based against the earliest maintained branch in which the bug can be reproduced.*
- [ x] …
=> MDEV-35951 : Complete freeze during MW-329 test

sql/sql_class.cc
THD class has an instance of Gap_time_tracker_data, which has a
reference to "Gap_time_tracker" using "bill_to" field.
During clean_up_after_query, reset bill_to field to NULL.
=> MDEV-37774: ASAN crash in Gap_time_tracker's log_time()

mysql-test/suite/galera_3nodes/r/galera_garbd_backup.result, mysql-test/suite/galera_3nodes/t/galera_garbd_backup.test
This contains test case changes only.
1) Make sure InnoDB buffer pool has no dirty pages at begining 2) Use FTWRL to ensure tables are flushed to disk
3) Add wait condition to ensure tables and rows are replicated in the cluster 4) Use sort to ensure same order of the files in the find
If the changes are not amenable to automated testing, …
=> MDEV-37209 : mtr galera_3nodes.galera_garbd_backup test failures

mysql-test/main/information_schema_db.result, mysql-test/main/information_schema_db.test
MDEV-20549 test output was affected by incompletely closed preceding connections.
Fix for similar issue was attempted by f4eb0953b136, it introduced wait_until_disconnected.inc. For an explanation of why it didn't work see bead24b7f3d commit comment.
Another fix was attempted in bead24b7f3d. It didn't help either, because connection is removed from information_schema.processlist after COM_QUIT handling.
Make test for MDEV-20549 agnostic to concurrent connections by querying information_schema.processlist only for connections that it uses.
=> MDEV-37797 - main.information_schema_db fails sporadically

mysql-test/suite/encryption/r/recovery_memory.result, mysql-test/suite/encryption/t/recovery_memory.combinations, mysql-test/suite/encryption/t/recovery_memory.test, storage/innobase/ibuf/ibuf0ibuf.cc
`ibuf_upgrade_needed()`: Adjust the check for the case that the InnoDB system tablespace had been created without
`innodb_checksum_algorithm=full_crc32` and `innodb_encrypt_tables` was enabled at the time the change buffer was upgraded.
MariaDB Server would fail to start up after an upgrade if the InnoDB system tablespace had been created while `innodb_checksum_algorithm=full_crc32` was not in effect, and `innodb_encrypt_tables` was enabled during the upgrade.
```sh
./mtr encryption.recovery_memory
```
=> MDEV-36556: MariaDB restart after upgrade fails with innodb_encrypt_tables

sql/wsrep_schema.cc, sql/wsrep_xid.cc
Uninitialized value was created by an allocation of 'xid' in the stack frame
- [x ] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/-/CODING_STANDARDS.md) file and my PR conforms to this where …
=> MDEV-37809 : MSAN use-of-uninitialized-value in wsrep_xid_print
