MariaDB/server

storage/cassandra/ha_cassandra.cc

On BigEndian build fails with:
[ 109s]
/home/abuild/rpmbuild/BUILD/mariadb-10.0.17/storage/cassandra/ha_cassandra.cc:890:22:
error: invalid conversion from 'longlong*
{aka long long int*}
' to 'long long int' [-fpermissive]
[ 109s] value->x.long_value= (longlong *)*cass_data;
[ 109s] ^
This commit fixes it
Signed-off-by: Dinar Valeev <dvaleev@suse.com>

Fix BigEndian build

---

sql/log.cc

This adds a unlock(LOCK_log) for the unlikely(!is_open()) branch

MDEV-7977 MYSQL_BIN_LOG::write_incident failing to release LOCK_log

---

storage/oqgraph/graphcore-types.h
storage/oqgraph/graphcore.cc
storage/oqgraph/graphcore.h
storage/oqgraph/ha_oqgraph.cc
storage/oqgraph/ha_oqgraph.h
storage/oqgraph/mysql-test/oqgraph/create_attr.result
storage/oqgraph/mysql-test/oqgraph/create_attr.test
storage/oqgraph/mysql-test/oqgraph/create_attr_legacy.result
storage/oqgraph/mysql-test/oqgraph/regression_mdev6282.result
storage/oqgraph/mysql-test/oqgraph/regression_mdev6282.test
storage/oqgraph/mysql-test/oqgraph/regression_mdev6345.result
storage/oqgraph/mysql-test/oqgraph/regression_mdev6345.test
storage/oqgraph/oqgraph_judy.cc
storage/oqgraph/oqgraph_thunk.cc
storage/oqgraph/oqgraph_thunk.h

Also various minor partial tidy up

Fix connection thread handling to address MDEV-6282 MDEV-6345 and MDEV-6784

---

mysql-test/t/bootstrap.test
sql/sql_plugin.cc

This aids packagers to install/uninstall plugins without starting a full
mysql instance.
for MDEV-7781.

MDEV-7781 Allow {un,}install plugins during bootstrap/skip-grant-tables

---

storage/innobase/handler/i_s.cc
storage/xtradb/handler/i_s.cc

mainly to reduce clang warnings

c99 style for assigning structure members

---

storage/innobase/include/os0sync.h
storage/xtradb/include/os0sync.h

This is an addendum to the fix for MDEV-7026. The ARM memory model is
similar to that of PowerPC and thus needs the same semantics with
respect to memory barriers. That is, os_atomic_test_and_set_*_release()
must be a store with a release barrier followed by a full
barrier. Unlike x86 using __sync_lock_test_and_set() which is
implemented as “exclusive load with acquire barriers + exclusive store”
is insufficient in contexts where os_atomic_test_and_set_*_release()
macros are used.

Fixes MDEV-7658: MDEV-7026 fix reintroduces MDEV-6615 on AArch64

---

sql/log_slow.h

When macro is expanded in an expression like ~QPLAN_QC_NO (e.g. in the
Query_cache::send_result_to_client() function in sql/sql_cache.cc) then without
the parenthesis the expression will be evaluated to a wrong value.

Add parenthesis in macro definitions to prevent order of operation problems

---

sql/sql_analyze_stmt.h

A 64bit counter can overflow within the time of a query
so lets take it that the measurement is the small value
rather than an order 1e12 millisecond query.
$ ./mtr analyze_format_json
Logging: ./mtr  analyze_format_json
vardir: /home/dan/software_projects/mariadb-server/mysql-test/var
Creating var directory '/home/dan/software_projects/mariadb-server/mysql-test/var'...
MariaDB Version 10.1.8-MariaDB
Collecting tests...
Installing system database...
==============================================================================
TEST                                      RESULT   TIME (ms) or COMMENT
-------------------------------------------------------------------------- …

MDEV-8981: Analyze stmt - cycles can overflow

---

extra/CMakeLists.txt
storage/innobase/CMakeLists.txt
storage/innobase/ut/ut0crc32.cc
storage/xtradb/CMakeLists.txt
storage/xtradb/ut/ut0crc32.cc

based on @janlindstrom  and @vaintroub feedback/questions in #133 here is a patch that ensures compilation on power platforms only and only includes the optimised code on little endian.

Do not build optimised power crc32 on bigendian

---

debian/autobake-deb.sh

When the debian/control gets stripped off the libcrack3 dependency,
it should also strip off the mariadb-cracklib-password-check-10.2
package entry, otherwise the resulting Debian source package will
not be re-buildable independently later.
Successful build visible at https://launchpad.net/~mysql-ubuntu/+archive/ubuntu/mariadb-10.2/+builds?build_text=&build_state=all (ppc64 build for e717ceb, the other builds fail due to inherited other problems in current 10.2 master). Builds at https://buildbot.askmonty.org/buildbot/grid?branch=ok-debpkg-10.2&category=main also fail due to inherited problems from current 10.2 master, so it is not useful for QA in at the moment.

MDEV-9186 - Debian packaging: extend libcrack hack to create correct control file

---

mysys/my_rnd.c

header file has the CPP guff
cppchecker reported the error
[mysys/my_rnd.c:100]: (error) Invalid number of character '{' when these macros are defined: '__cplusplus'.

MDEV-9433: mysys/my_rnd.c - remove #ifdef __cplusplus

---

debian/dist/Debian/mariadb-server-10.0.postinst
debian/dist/Ubuntu/mariadb-server-10.0.postinst

Unmask the systemd mysql.service if left behind by mysql-server-5.6
Without this a simple 'apt-get install mariadb-server' would end
up with a system where mysqld is not running despite it was
running OK with mysql-server-5.6 installed, and users might wrongly
think mariadb-server package is broken when the real cause was
the removal of mysql-server-5.6 that left a /etc/systemd/system/
file behind pointing to /dev/null.

MDEV-9354: Debian: unmask the mysql.service on installation

---

storage/innobase/ut/crc32_power8/crc32.S
storage/xtradb/ut/crc32_power8/crc32.S

Corrected as per upstream:
https://github.com/antonblanchard/crc32-vpmsum/compare/f2145e5858c283d6a95ea1bc613db50b4d514303...aaf0ac4

MDEV-9699: power8 crc32: Per the PPC64 ABI, v20-v31 are non-volatile registers

---

plugin/auth_pam/mapper/pam_user_map.c

Small fix for segfaults I've been experiencing when using groups with the PAM user mapping plugin. Also changed the return from pam_sm_authenticate() to PAM_AUTH_ERR if no user or group is matched. As it was before a user could pass the authentication even if they did not belong to the appropriate group. In my case that meant they'd then be mapped to the "anonymous catch-all user" described here - https://mariadb.com/blog/configuring-pam-group-mapping-mariadb
This is a very handy plugin by the way :)

MDEV-10214: Fix segfault when using groups in PAM user mapping plugin

---

configure.cmake

HAVE_FALLOC_PUNCH_HOLE_AND_KEEP_SIZE only needed a compile check
rather than a RUN check so after changing to a compile check there
is one less variable to manually set while cross compiling.
Added in 21adad00

Cross Compile HAVE_FALLOC_PUNCH_HOLE_AND_KEEP_SIZE change to compile check

---

mysql-test/mysql-test-run.pl

Based off #194 feedback. Thanks @elenst 
fixed --callgrind by removing --base
closes #194

MDEV-10294: MTR using --valgrind-option to specify a tool / fixing callgrind [10.1]

---

CMakeLists.txt

Use insider knowledge of how the MY_CHECK_AND_SET_COMPILER_FLAG function to get WITH_ASAN option working with MariaDB 10.1.  A more complicated solution would pass a result variable into that function instead.

MDEV-10412 fix WITH_ASAN option for 10.1

---

BUILD/autorun.sh

This patch removes die() function from the BUILD/autorun.sh. It was
introduced in the c682570431 commit (Fix BUILD/autorun.sh to really bail
out on error.). Last users of die() was removed in the 8664de22 commit
(WL#5665: Removal of the autotools-based build system) and since it is
not used anywhere.
No functionality changes. Just cleanup.

remove die() from BUILD/autorun.sh

---

storage/tokudb/mysql-test/tokudb/r/rows-32m-rand-insert.result

Was:
CURRENT_TEST: tokudb.rows-32m-rand-insert
--- /source/storage/tokudb/mysql-test/tokudb/r/rows-32m-rand-insert.result	2016-08-29 10:16:55.216852004 +0000
+++ /source/storage/tokudb/mysql-test/tokudb/r/rows-32m-rand-insert.reject	2016-08-29 10:43:18.661888803 +0000
@@ -1009,6 +1009,7 @@
test.t	check	status	OK
optimize table t;
Table	Op	Msg_type	Msg_text
+test.t	optimize	note	Table does not support optimize, doing recreate + analyze instead
test.t	optimize	status	OK
check table t;
Table	Op	Msg_type	Msg_text
I submit this under the MCA

MDEV-10757: Fix tokudb test rows-32m-rand-insert

---

sql-common/client.c

because it is zero always in this place as we have check for this above
which checks that net->vio isn't 0 and exit.
--

no need to set net->vio to zero in mysql_real_connect

---

scripts/mysql_install_db.pl.in
scripts/mysql_install_db.sh

When using mariaDb in docker mode it can fail as it calls mysql_install_db but as we are going through a slightly different install process the test database has not been created, therefore we should fall back to the mysql database as per https://mariadb.com/kb/en/mariadb/mariadb-10112-mysql_install_db-aborts-on-unkown-file-test/

MDEV-10830 - Fix undefined database test error when running mysql_install_db

---

scripts/mysql_install_db.pl.in
scripts/mysql_install_db.sh

Since MDEV-7875 (da0991c6), not all sql source files are in the source directory, maria_add_gis_sp_bootstrap.sql is in the build directory.
When mariadb is build out of the source tree mysql_install_db should be able to see all these when --{src,build}dir are used/
After patch:
<pre>
~/repos/build-mariadb-server-10.1]$  mkdir /tmp/datadir && scripts/mysql_install_db --srcdir=../mariadb-server --builddir=`pwd` --datadir=/tmp/datadir --log-bin=/tmp/datadir/mysqlbin --socket /tmp/s.sock 
Installing MariaDB/MySQL system tables in '/tmp/datadir' ...
2016-09-19 15:33:50 140578819905728 [Note] /home/dan/repos/build-mariadb-server-10.1/sql/mysqld (mysqld 10.1.18-MariaDB) starting as process 24072 ...
2016-09-19 15:33:51 140578819905728 [Note] InnoDB: Using mutexes to ref count buffer pool pages …

MDEV-10832 - Out of tree build: mysql_install_db to see all .sql files

---

storage/innobase/handler/ha_innodb.cc
storage/innobase/include/lock0lock.h
storage/innobase/lock/lock0lock.cc
storage/xtradb/handler/ha_innodb.cc
storage/xtradb/include/lock0lock.h
storage/xtradb/lock/lock0lock.cc

This branch introduces a new scheduling algorithm (Variance-Aware-Transaction-Scheduling, VATS) for the record lock manager of InnoDB and XtraDB. Instead of using First-Come-First-Served (FCFS), the newly introduced algorithm uses an Eldest-Transaction-First (ETF) heuristic, which prefers older transactions over new ones. A configuration parameter (innodb_lock_schedule_algorithm) is introduced for users to choose between VATS and FCFS (the default one). We've extensively tested this algorithm in many workloads. The algorithm is very simple, and the changes are very local, but it significantly improves performance (in terms of average latency and throughput) and predictability (in terms of reduction of tail and quantile latencies) For more details, please refer to this paper …

MDEV-11039 - Add new scheduling algorithm for reducing tail latencies

---

storage/xtradb/handler/ha_innodb.cc

innodb_buffer_pool_populate has not had an effect since 10.0.23
in commit 1e270d504d56cb015efe060b319e3a5b9bc6513f when its
functionality was removed.
As we've only just enabled LIBNUMA in MDEV-10829 it isn't logical
to have innodb_buffer_pool_populate aliasing for innodb_numa_interleave
this late in the game.
So the simplest way is just to remove innodb_buffer_pool_populate.

MDEV-9451: Remove innodb_buffer_pool_populate from xtradb (10.2)

---

sql/item_strfunc.cc
storage/innobase/gis/gis0geo.cc
storage/innobase/gis/gis0rtree.cc
storage/myisam/rt_split.c

my_isinf(square) || my_isnan(square) -> !isfinite(square)
There are only 3 logical states for a number. The isfinite is a single call rather than multiple leaving scope for compiler/architecture optimization.
Changed the logic as follows in a few files.
my_isinf(square) || my_isnan(square) -> !isfinite(square)

MDEV-11451: isinf || isnan -> !isfinite

---

mysql-test/suite/sys_vars/r/innodb_buffer_pool_dump_pct_basic.result
mysql-test/suite/sys_vars/t/innodb_buffer_pool_dump_pct_basic.test
mysql-test/unstable-tests

Since 10.2 (2e814d4702d71a04388386a9f591d14a35980bfe) this test
changed and the race condition of MDEV-10651 no longer forms part
of this test.
As such re-enable this test.
Also include save/restore of the default values of this variable.

MDEV-10651: enable test sys_vars.innodb_buffer_pool_dump_pct_basic

---

storage/innobase/page/page0zip.cc

With innodb compressed pages formerly as crc32 changing to the
innodb checksum, optimize for speed by only calcuating the big
endian variant of crc32 after checking that the little endian
doesn't validate the page.

MDEV-11075: changing to algorithm innodb from crc32

---

storage/innobase/include/ut0crc32.h
storage/innobase/srv/srv0start.cc
storage/innobase/ut/ut0crc32.cc
storage/xtradb/include/ut0crc32.h
storage/xtradb/srv/srv0start.cc
storage/xtradb/ut/ut0crc32.cc

To stop the expansion of booleans to represent different crc32 implementations for display purposes lets just use a pointer.

MDEV-9872: Generic CRC32 message using ptr

---

storage/innobase/ut/ut0crc32.cc
storage/xtradb/ut/ut0crc32.cc

From https://github.com/MariaDB/server/pull/212#discussion_r91666636 @dr-m asked about runtime checks for Power.
Here it is. They aren't totally needed as Power8 is the first processor supporting MariaDB. It adds one syscall on initialization so it isn't too much to add anyway. It does reduce one less thing to account for if someone wants to back port support to Power7 or earlier (MDEV-10984) however.

MDEV-11075: Power - runtime detection of optimized instructions

---

.travis.yml

Without these packages installed, MariaDB builds these packages from the bundled source. As we are limited on compile time anyway lets just use the packages.
There are a couple of packages not yet whitelisted on travis. Added these as comment reference for the time being with the aim that once these are whitelisted they can be included in the packages.

Travis: add lib{stemmer,xml2,pcre3}-dev

---

.travis.yml

depends on no_ipv6 PR to succeed.

MDEV-10750 - travis: gcc-5 and gcc-6

---

mysql-test/mysql-test-run.pl

mtr --mem plugin was an issue because plugin was treated
as a directory where mtr treated as a tmp location rather
than a legitimate test name.
This removes functionality of where ./mtr --mem /tmp/dir could be
a directory.
Now MTR_MEM=/tmp/dir ./mtr is needed.
The case where MTR_MEM=/tmp/dir ./mtr --mem has the equalivant
effect.
Thanks Elena for helping and identifing edge cases.

MDEV-11619: mtr --mem {no arguement of a directory}

---

sql/sql_base.cc

This caused gcc-6.3.1 errors:7450cb7f6
mariadb-server/sql/sql_base.cc: In function ‘bool fix_all_session_vcol_exprs(THD*, TABLE_LIST*)’:
mariadb-server/sql/sql_base.cc:4821:7: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
for (Field **df= t->default_field; df && *df; df++)
^~~
mariadb-server/sql/sql_base.cc:4826:9: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘for’
for (Virtual_column_info **cc= t->check_constraints; cc && *cc; cc++)
^~~
It was obvious from 7450cb7f6 that the indenting should of been removed

whitespace - fix indenting after commit 7450cb7f6 (10.2)

---

mysql-test/r/stat_tables_par.result
mysql-test/r/stat_tables_par_innodb.result
mysql-test/t/stat_tables_par.test

Test results are distorted by a small rounding error
during an intermediate stage of calculating the result.
By using the SQL ROUND function we stablise tests.
I submit this under the MCA

MDEV-10515: Correct stat_tables_par test results

---

mysql-test/extra/binlog_tests/ctype_ucs_binlog.test
mysql-test/suite/binlog/r/binlog_row_ctype_ucs.result
mysql-test/suite/binlog/r/binlog_stm_ctype_ucs.result

The fix from MDEV-10866 was insufficient.
Attempt 2 at fixing this.
binlog.binlog_row_ctype_ucs 'row'        w18 [ fail ]
Test ended at 2017-02-13 10:36:57
<pre>
CURRENT_TEST: binlog.binlog_row_ctype_ucs
--- /mariadb/mysql-test/suite/binlog/r/binlog_row_ctype_ucs.result        2017-02-06 09:29:43.116183650 +1100
+++ /mariadb/mysql-test/suite/binlog/r/binlog_row_ctype_ucs.reject        2017-02-13 10:36:56.984056229 +1100
@@ -71,21 +71,21 @@
/*!50003 SET @OLD_COMPLETION_TYPE=@@COMPLETION_TYPE,COMPLETION_TYPE=0*/;
DELIMITER /*!*/;
-#700101  6:46:40 server id #  end_log_pos # CRC32 XXX  Start: binlog v 4, server v #.##.## created 700101  6:46:40
+#170213 10:36:56 server id #  end_log_pos # CRC32 XXX  Start: binlog v 4, server v #.##.## created 170213 10:36:56
</pre>
...
I submit this under …

MDEV-12055: Correct binlog_stm_ctype_ucs test

---

sql/item.h
sql/sql_type.h

Error can be seen here: https://hastebin.com/azomatocoq.scala
sql/item.h: defined uint32 char_to_byte_length_safe(size_t, uint32)
sql/sql_type.h: defined uint32 char_to_byte_length_safe(uint32, uint32)
As @knielsen observed, C++ overloading allows this on 64bit
because size_t and uint32 differ.
Since item.h does a #include "sql_type.h", there is no point in
redifining this function in item.h

fix 32bit redefine of char_to_byte_length_safe

---

storage/innobase/fil/fil0crypt.cc

Fixes compile error that highlights problem:
/source/storage/innobase/fil/fil0crypt.cc: In function 'void fil_crypt_rotate_page(const key_state_t*, rotate_thread_t*)':
/source/storage/innobase/fil/fil0crypt.cc:1770:15: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
if (space == TRX_SYS_SPACE && offset == TRX_SYS_PAGE_NO) {
@dr-m, @janlindstrom  should be an obvious one.

fil_crypt_rotate_page - space_id should be compared to TRX_SYS_SPACE not space

---

storage/xtradb/fil/fil0crypt.cc

like 9a218f4fb871c1169dd6015a3be9d965929dbd1f
sorry for missing it first time @janlindstrom

xtradb: fil_crypt_rotate_page, space_id should be compared to TRX_SYS_SPACE

---

.travis.compiler.sh
.travis.yml

container builds are faster and as most packages are now whitelisted this is possible.
Added clang version to build to be nice to @Sp1l in freebsd maintenance land and because clang just general gives more hints on silly c code that is probably incorrect. Tokudb and mroonga where just too messy to deal with in clang due to excessive warnings/errors.
Disable main.mysqlhotcopy_myisam in container builds consistently failed and I've come across the same thing in a docker based MTR run at work.
Added the skeleton travis coverity config for enabling if anyone agrees with the concept of a "*converity*" branch the same way as bb-* to trigger the build, and where to send the results too. MDEV-6262 has some references.

10.2 travis container+clang

---

cmake/libutils.cmake

This is to be friendly to our OSX users where
the libtool path is very different.
Ref:
* https://github.com/Homebrew/homebrew-core/blob/master/Formula/mariadb.rb#L44..L46

Don't use full path of libtool

---

plugin/aws_key_management/CMakeLists.txt

Update AWS SDK version from 1.0.8 to 1.0.100
Commit b64910ce27a4df33e3ad2e3f40764e8b3271a9aa (MDEV-12453)
enabled AWS_SDK to build correctly on buildbot.
Travis still had build faults like below despite many common elements
between the builds;
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:79:9: error: no member named 'strcoll' in the global namespace; did you mean 'strtoll'?
[ 24%] Building CXX object storage/rocksdb/CMakeFiles/rocksdblib.dir/rocksdb/db/internal_stats.cc.o
using ::strcoll;
~~^
/usr/include/stdlib.h:169:3: note: 'strtoll' declared here
strtoll(const char *__str, char **__endptr, int __base);
^
Failing build: https://travis-ci.org/grooverdan/mariadb-server/jobs/219607054#L1307
Fixed build: …

MDEV-12453: AWS SDK version failed to build on OSX

---

storage/xtradb/sync/sync0arr.cc

@dr-m - missed one. It wasn't in 10.0.
To fix OSX error:
https://travis-ci.org/grooverdan/mariadb-server/jobs/225036945#L4667
/Users/travis/build/grooverdan/mariadb-server/storage/xtradb/sync/sync0arr.cc:530:5: warning: format specifies type 'unsigned long' but the argument has type 'os_thread_id_t' (aka '_opaque_pthread_t *') [-Wformat]
mutex->thread_id,
^~~~~~~~~~~~~~~~

MDEV-12488: Remove type mismatch in InnoDB printf-like calls

---

storage/rocksdb/rdb_datadic.cc

Show up on big endian machines:
http://buildbot.askmonty.org/buildbot/builders/kvm-rpm-centos73-ppc64/builds/140/steps/compile/logs/stdio
debug assert is sufficient.

MDEV-12469: static_assert cannot be determined on bigendian

---

extra/mysqld_safe_helper.c

/home/travis/build/MariaDB/server/extra/mysqld_safe_helper.c:62:21: warning: too many arguments in call to 'do_usage'
do_usage(argv[0]);
~~~~~~~~        ^
1 warning generated.

mysqld_safe_help - remove warning

---

sql/sql_class.cc

/home/travis/build/MariaDB/server/sql/sql_class.cc:1941:15: warning: 'this' pointer cannot be null in well-defined C++ code; pointer may be assumed to always convert to true [-Wundefined-bool-conversion]
if (this && WSREP(this) && wsrep_thd_is_BF(this, FALSE))
^~~~ ~~

Remove compile warning - "this" canot be null

---

support-files/wsrep.cnf.sh

From: https://github.com/devexp-db/mariadb/blob/f27/mariadb-galera.cnf.patch
Without a provider this has no effect however this reduces means enabling is only setting the provider.

MDEV-12646: wsrep.cnf - wsrep_on=1 by default

---

storage/rocksdb/CMakeLists.txt

Just disabling rocksdb on Big Endian for now. Sound reasonable @spetrunia ?
(from: http://buildbot.askmonty.org/buildbot/builders/p8-rhel6-bintar/builds/820/steps/test/logs/stdio)
Errors like the following indicate a potential endian storage issue:
rocksdb.rocksdb_range                    w1 [ fail ]
Test ended at 2017-04-27 18:56:11
CURRENT_TEST: rocksdb.rocksdb_range
--- /home/buildbot/maria-slave/p8-rhel6-bintar/build/storage/rocksdb/mysql-test/rocksdb/r/rocksdb_range.result	2017-04-27 17:41:27.740050347 -0400
+++ /home/buildbot/maria-slave/p8-rhel6-bintar/build/storage/rocksdb/mysql-test/rocksdb/r/rocksdb_range.reject	2017-04-27 18:56:11.230050346 -0400
@@ -25,15 +25,15 @@
select * from t2 force index (a) where a=0;
pk	a	b
0	0	0
-1	0	1
-2	0	2
-3	0	3
-4	0	4
-5	0	5
-6	0	6
-7	0	7
-8	0	8 …

MDEV-12469: rocksdb having large numberic storage errors on ppc64 (BE)

---

storage/innobase/include/ut0ut.h
storage/innobase/ut/ut0ut.cc

Reintroduce 3d1a7cba71f6c843639f0b9a48b12017ff610112
removing the maths from ut_delay.
Existing definitions of UT_COMPILE_BARRIER used.

MDEV-8684: innodb ut_delay - no maths

---

scripts/galera_new_cluster.sh

Apologies. Introduced in a9a38fcd7aa4599d78fe9407d5f38c31394cd17c
<pre>
$ ls -la /bin/sh
lrwxrwxrwx 1 root root 4 Feb 18  2016 /bin/sh -> dash
$ ./galera_new_cluster.sh -h
Usage: ./galera_new_cluster.sh
The script galera_new_cluster is used to bootstrap new Galera Cluster,
when all the nodes are down. Run galera_new_cluster on the first node only.
On the remaining nodes simply run 'service @DAEMON_NAME@ start'.
For more information on Galera Cluster configuration and usage see:
https://mariadb.com/kb/en/mariadb/getting-started-with-mariadb-galera-cluster/
$ ./galera_new_cluster.sh --help
Usage: ./galera_new_cluster.sh
The script galera_new_cluster is used to bootstrap new Galera Cluster,
when all the nodes are down. Run galera_new_cluster on the first node only.
On the remaining nodes …

MDEV-13032: fix galera_new_cluster to be POSIX

---

.travis.compiler.sh
.travis.yml

mysqlhotcopy tests has been disabled as per MDEV-10995 however the earlier reason for failure was a missing dependency libdbd-mysql rather than any container issues.
Re-enable these tests in travis.

travis: enable (main,archive).mysqlhotcopy_\1 test

---

.travis.yml

Fakeroot was missing from the dependences so the debian build didn't build. I think travis took it out of their base image.
The MDEV-13002 fix c7141fa75df91ae4c2a1214283111eeb1c2eda11 hasn't quite merged into 10.2 however its not far off. So take out the allowed failures that resulted in plugins for this test.
Even with fakeroot added the debian build ran out of space (https://travis-ci.org/grooverdan/mariadb-server/jobs/248211177). As such I removed the cache for this build.

travis fakeroot + remove allowed failures

---

.travis.yml

18a2b0a1681af73181bd98d23ae0973fc1249df5 wasn't sufficient.
The path needed to be set so ccache wasn't picked up.
Success as per https://travis-ci.org/grooverdan/mariadb-server/jobs/248239117
@svoj, Hope you, your neighbour and their dog come to a non-destructive tranquillity soon.

travis: force deb build not to use ccache

---

sql/item_timefunc.cc

CID 971836 (#1 of 1): Same on both sides (CONSTANT_EXPRESSION_RESULT)
pointless_expression: The expression val != end && val != end does not
accomplish anything because it evaluates to either of its identical
operands, val != end.
All code in this region was from the original commit in 2002.

item_timefunc: identical operands

---

storage/archive/ha_archive.cc

max_data_file_size is overwritten in next statement
so this assignment didn't ever get used.
Found by Coverity (ID 1409644)

ha_archive::info remove hidden assignment

---

storage/maria/ma_loghandler.c

translog_stop_writing doesn't release a lock (though
does to a DBUG_ASSERT).
Better to just release the lock.
Found by Coverity id 972092
I submit under the MCA.

ma_loghandler: release file_header_lock on error

---

storage/maria/ma_loghandler.c

Release the lock for the error path.
Found by Coverity (id 972093).

ma_loghandler: translog_set_only_in_buffers failed to release lock

---

storage/maria/ma_pagecache.c

make_lock_and_pin didn't release the lock so we should.
Found by Coverity (id 972095).

ma_pagecache: release lock in pagecache_read

---

sql/sql_class.cc

Found by Coverity (id 971843).

sql_class: incorrect assignment in Security_context::destroy

---

client/mysqlbinlog.cc
mysql-test/suite/binlog/r/flashback.result
mysql-test/suite/binlog/t/flashback.test
sql/log_event.cc
sql/log_event.h

Problem
-------
For one-statement contains multiple row events, Flashback didn't reverse the
sequence of row events inside one-statement.
Solution
--------
Using a new array 'events_in_stmt' to store the row events of one-statement,
when parsed the last one event, then print from the last one to the first one.
In the same time, fixed another bug, without -vv will not insert the table_map
into print_event_info->m_table_map, then change_to_flashback_event() will not
execute because of Table_map_log_event is empty.

MDEV-12067 flashback does not correcly revert update/replace statements

---

include/my_dir.h

Replace S_IREAD, S_IWRITE and S_IEXEC with more modern equivalents.
Fixes building for Android.
See https://www.gnu.org/software/libc/manual/html_node/Permission-Bits.html and http://pubs.opengroup.org/onlinepubs/7908799/xsh/sysstat.h.html.

Remove obsolete synonyms for access bits

---

.travis.yml

Even disabling the ccache on the Debian build didn't always prevent
the Travis build running out of space.
As an alternative strategy, the number of alternative compilers has been
reduced to save space. This additional space has been partially reused
by the ccache.
Debian build specific packages have been removed from other builds.

travis: Debian build - minimise packages, enable ccache

---

client/mysql.cc

field_names[x][y] is a pointer
client/mysql.cc: In function 'void build_completion_hash(bool, bool)':
client/mysql.cc:2855:37: error: invalid conversion from 'char' to 'char*' [-fpermissive]
field_names[i][num_fields*2]= '\0';

client: mysql - fix type

---

mysql-test/mysql-test-run.pl

The same code and comment as removed is just before the fix_vs_config_dir function call. This function doesn't change the bindir however it does use it. As such remove the duplicated code.

mtr: fix_vs_config doesn't change bindir

---

mysql-test/suite/binlog/r/binlog_unsafe.result
mysql-test/suite/binlog/t/binlog_unsafe.test

Increased size in tests to allow for 100 character hostname.
<pre>
[11:32 dan ~/repos/build-mariadb-server-10.0]$ hostname
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
[11:33 dan ~/repos/build-mariadb-server-10.0]$ hostname | wc -c
64
[11:31 dan ~/repos/build-mariadb-server-10.0]$ (cd mysql-test/; ./mtr  binlog.binlog_unsafe)
Logging: /home/dan/repos/mariadb-server/mysql-test/mysql-test-run.pl  binlog.binlog_unsafe
vardir: /home/dan/repos/build-mariadb-server-10.0/mysql-test/var
Creating var directory '/home/dan/repos/build-mariadb-server-10.0/mysql-test/var'...
MariaDB Version 10.0.31-MariaDB-debug
- binaries are debug compiled
Sphinx 'indexer' binary …

MDEV-12436: binlog.binlog_unsafe - assumed len(hostname) <= 50

---

storage/maria/ma_check.c
storage/myisam/mi_check.c

coverity maria repair parallel

---

.travis.compiler.sh
.travis.yml

Also removed clang-3.9
clang-6.0 is now the development version.
clang-3.6 (that is the distro version of trusty) is still being tested as the low end compatibility (for travis GCC_VERSION=4.8).

travis: add clang-5.0

---

cmake/submodules.cmake

It is possible that a .git directory isn't definitive on the
existance of a working git tree. A git worktree over sshfs
for instance will fail to build unless the main repository
also exists in the same directory. Adding this extra test
will make the detection that little more ruggardised for these
odd build environments.

submodules.cmake: git returns 128 if not in a repository

---

sql/event_db_repository.cc
sql/events.cc
sql/item_subselect.cc
sql/opt_range.cc
sql/opt_subselect.cc
sql/records.cc
sql/records.h
sql/sql_acl.cc
sql/sql_delete.cc
sql/sql_help.cc
sql/sql_join_cache.cc
sql/sql_plugin.cc
sql/sql_select.cc
sql/sql_servers.cc
sql/sql_table.cc
sql/sql_udf.cc
sql/sql_update.cc
sql/sql_window.cc
storage/spider/spd_trx.cc

```c++
READ_RECORD read_record;
...
// this
// read_record.read_record(&read_record);
// becomes just
read_record.read_record();
```

simplify READ_RECORD usage NFC

---

mysql-test/suite/plugins/r/qc_info.result
mysql-test/suite/plugins/r/qc_info_priv.result
mysql-test/suite/plugins/t/qc_info.test
plugin/qc_info/qc_info.cc
sql/sql_cache.cc
sql/sql_cache.h

This pull request adds HITS column to QUERY_CACHE_INFO table of [qc_info](https://mariadb.com/kb/en/the-mariadb-library/query-cache-information-plugin/) plugin.
Our case is that we plan to turn off query cache on our production server, because we believe it becomes a bottleneck in some situations.
Load testing shows that server becomes overloaded if query cache is turned off. It is because there are some queries that begin to kill server when not using query cache. The problem is to figure out what exactly are those queries.
Currently there is no way to figure out whether the query has used query cache or not. The query_cache_info plugin shows the contents of the query cache, but it does not show any usage statistics. Moreover there is no session stat variable that could help understand …

Hits statistics for queries in query cache (for query cache information plugin)

---

CMakeLists.txt

Do not work with `TokuDB` so `-DWITHOUT_TOKUDB_STORAGE_ENGINE=1` is required to use TSAN.

add TSAN option to cmake

---

scripts/wsrep_sst_rsync.sh

Corrects the following error with rsync sst on FreeBSD:
WSREP_SST: [ERROR] rsync daemon port '4444' has been taken
The FreeBSD version of grep doesn't play nicely with the -w parameter mixed with [[:space:]] and ends up matching nothing. This causes the script to loop and attempt to spawn more than one instance of rsync, which fails with the initial instance already having the port open. Because of this, the entire script fails and no sst occurs resulting in the error message listed above appearing in the log file.

Fixes Galera rsync sst on FreeBSD

---

support-files/policy/apparmor/usr.sbin.mysqld

At least the Debian package reads configuration from there.

apparmor: allow to read /etc/mysql/mariadb.conf.d/*

---

storage/innobase/sync/sync0debug.cc

reapply 6192f0bffa798c01acc85db9f427ed02234aead4
TSAN warnings count decreased from 206 to 195

fix a data race

---

mysql-test/suite/compat/oracle/r/sp-param.result
mysql-test/suite/compat/oracle/t/sp-param.test
sql/sp_head.cc
sql/sp_head.h
sql/sp_rcontext.cc
sql/sp_rcontext.h
sql/sql_type.cc
sql/sql_type.h
sql/sql_yacc_ora.yy

I share this patch under term of MCA.

MDEV-13919 sql_mode=ORACLE: Derive length of VARCHAR SP parameters 

---

scripts/wsrep_sst_common.sh
scripts/wsrep_sst_xtrabackup-v2.sh

wsrep_sst_common: Setting "-c ''" for my_print_defaults just takes no values from config at all. $MY_PRINT_DEFAULTS is already set at the top of the script to have --defaults-file and --defaults-extra-file. If WSREP_SST_OPT_CONF if set to "--defaults-file=/etc/my.cnf --defaults-extra-file=/etc/my.extra.cnf", then "my_print_defaults -c "" --defaults-file=/etc/my.cnf" succeeds, but if WSREP_SST_OPT_CONF is empty - no default values are taken at all.
wsrep_sst_xtrabackup-v2: innobackupex does not support --defaults-extra-file, so ${WSREP_SST_OPT_CONF} cannot be used as an argument, it has been changed to ${WSREP_SST_OPT_DEFAULT}. Removed --defaults-file= from INNOMOVE line, because WSREP_SST_OPT_CONF already includes it (INNOBACKUP was fine, INNOMOVE - not).

wrep_sst_common and wsrep_sst_xtrabackup-v2 bugfixes to read sst parameters from configs

---

scripts/wsrep_sst_common.sh

Fix for the following error messages during SST:
/usr/local/mysql/bin/wsrep_sst_rsync: 258: /usr/local/mysql/bin/wsrep_sst_rsync: [[: not found
/usr/local/mysql/bin/wsrep_sst_rsync: 263: /usr/local/mysql/bin/wsrep_sst_rsync: [[: not found
/usr/local/mysql/bin/wsrep_sst_rsync: 268: /usr/local/mysql/bin/wsrep_sst_rsync: [[: not found

MDEV-13909 Fix wsrep_sst_rsync fails on debian

---

storage/innobase/include/sync0policy.h
storage/innobase/include/sync0policy.ic
storage/innobase/include/sync0types.h

This particular one flooded TSAN report.
TSAN warnings reduced from 212 to 135 for `main.create` test.
It's a bit funny that code which supposed to be detecting threading bugs is racy itself.

fix a data race in debug build

---

storage/oqgraph/graphcore.cc
storage/oqgraph/mysql-test/oqgraph/general-Aria.result
storage/oqgraph/mysql-test/oqgraph/general-MyISAM.result
storage/oqgraph/mysql-test/oqgraph/general-innodb.result
storage/oqgraph/mysql-test/oqgraph/regression_1196036.result
storage/oqgraph/mysql-test/oqgraph/regression_1213120.result
storage/oqgraph/oqgraph_shim.h

This was partially discussed on oqgraph-devel (thread starting at https://lists.launchpad.net/oqgraph-dev/msg00319.html) with @pastcompute, but not fully reviewed yet.

MDEV-10980: Fix reverse queries in OQGRAPH.

---

storage/innobase/include/sync0rw.ic
storage/innobase/sync/sync0rw.cc

```
Read of size 8 at 0x7b780000cf10 by thread T21:
#0 rw_lock_validate(rw_lock_t const*) storage/innobase/sync/sync0rw.cc:883 (mysqld+0x0000012b0cea)
#1 rw_lock_own(rw_lock_t*, unsigned long) storage/innobase/sync/sync0rw.cc:1022 (mysqld+0x0000012b144c)
#2 buf_page_hash_get_low storage/innobase/include/buf0buf.ic:1091 (mysqld+0x0000013de005)
#3 buf_page_get_gen(page_id_t const&, page_size_t const&, unsigned long, buf_block_t*, unsigned long, char const*, unsigned int, mtr_t*, dberr_t*) storage/innobase/buf/buf0buf.cc:4230 (mysqld+0x0000013f4ed4)
#4 btr_cur_search_to_nth_level(dict_index_t*, unsigned long, dtuple_t const*, page_cur_mode_t, unsigned long, btr_cur_t*, unsigned long, char const*, unsigned int, mtr_t*, unsigned long) storage/innobase/btr/btr0cur.cc:1314 …
```

fix some data races

---

storage/innobase/include/sync0rw.ic
storage/innobase/sync/sync0rw.cc

Another set of races.
```
WARNING: ThreadSanitizer: data race (pid=1174)
Atomic write of size 8 at 0x7b5c00000648 by thread T3:
#0 __tsan_atomic64_fetch_add <null>
#1 rw_lock_x_unlock_func storage/innobase/include/sync0rw.ic:409
#2 pfs_rw_lock_x_unlock_func storage/innobase/include/sync0rw.ic:784
#3 log_complete_checkpoint storage/innobase/log/log0log.cc:1450
#4 log_io_complete_checkpoint storage/innobase/log/log0log.cc:1467
#5 log_io_complete(log_group_t*) storage/innobase/log/log0log.cc:844
#6 fil_aio_wait(unsigned long) storage/innobase/fil/fil0fil.cc:5490
#7 io_handler_thread storage/innobase/srv/srv0start.cc:340
#8 <null> <null>
Previous read of size 8 at 0x7b5c00000648 by main thread:
#0 rw_lock_s_lock_spin(rw_lock_t*, unsigned long, char const*, unsigned int) …
```

fix data races

---

.travis.yml

Doesn't actually fix any OSX test failures. Shows a few new warnings and doesn't compile fail.

travis: osx - xcode 8.3 -> 9.1

---

mysys/my_fopen.c

my_freebsd_freopen was added in 998065c3a6f3 on January 2011
It was added because of https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=79887 which
was fixed in 7.4 and 8.2.
Both of these reached end of life in February 2011
https://www.freebsd.org/releases/
FYI @Sp1l
I submit the code removal under the MCA.

mysys: Remove freebsd freopen implementation - not relevant to stable releases

---

sql/table.cc

From comment in unreg.h:
```
Types of values in the MariaDB extra2 frm segment.
Each value is written as
type:       1 byte
length:     1 byte  (1..255) or \0 and 2 bytes.
binary value of the 'length' bytes.
```
length == 1 is valid.
Please, review and merge.

FRM: fail to load extra2 option with size 1 fix

---

sql/item.cc

This was added in c79641594348 but would hurt all other compilers because of Visual Studio. Hopefully this has been fixed now.
As groaned at by @cvicentiu and as covered recently by @svoj, volatile is for memory hardware devices and isn't a toy.
I submit this code and comment removal under the MCA.

Remove use of volatile in stored_field_cmp_to_item

---

storage/oqgraph/graphcore.cc
storage/oqgraph/graphcore.h
storage/oqgraph/ha_oqgraph.cc
storage/oqgraph/mysql-test/oqgraph/general-Aria.result
storage/oqgraph/mysql-test/oqgraph/general-MyISAM.result
storage/oqgraph/mysql-test/oqgraph/general-innodb.result
storage/oqgraph/mysql-test/oqgraph/general.inc

This algorithm returns all reachable leaf nodes from a given origin, or all root nodes that can reach a given destination.
Currently, I had to perform a self-join on the graph table to get a list of all leaf nodes (all destids that themselves are not an origid). This becomes rather expensive the larger the graph is.
I created a simple, large graph of 2 million nodes in (essentially just a chain of nodes, so A->B->C->...) and finding the leaf node from the root node took about 45 seconds. With the new
"leaves" latch it completes in about 7 seconds.
Briefly discussed on oqgraph-dev (thread starting at https://lists.launchpad.net/oqgraph-dev/msg00314.html), but no review was done yet (other than mtr and works for me).
@pastcompute Want to comment on this one too? :)

MDEV-11271 - Add "leaves" algorithm to OQGRAPH.

---

mysql-test/mysql-test-run.pl

This adds option for number of lines of queries results to include in a failure report. Very helpful `--tail-lines=0` as it filters out needless info.
Please, merge.

MDEV-14525 - Scipts: --tail-lines option for mtr

---

mysys/my_getopt.c

Because its so sad when innodb_buffer_pool_size=8T doesn't work.
<pre>
2017-12-04 19:28:18 0 [ERROR] /usr/local/mysql/bin/mysqld: Error while setting value '8T' to 'innodb-buffer-pool-size'
2017-12-04 19:28:18 0 [ERROR] Parsing options for plugin 'InnoDB' failed.
2017-12-04 19:28:18 0 [ERROR] /usr/local/mysql/bin/mysqld: unknown variable 'innodb_buffer_pool_size=8T'
2017-12-04 19:28:18 0 [ERROR] Aborting
</pre>

mysys: handle T, P, E suffixs

---

mysql-test/suite/encryption/t/debug_key_management.test
mysql-test/suite/encryption/t/encrypt_and_grep.test
mysql-test/suite/encryption/t/innodb_encryption.test

If real table count is different from what is expected by the test, it just hangs on waiting to fulfill hardcoded number. And then exits with **failed** after 10 minutes of wait: quite unfriendly and hard to figure out what's going on.
@janlindstrom Please, review and merge.

Tests: detect table count for some encryption tests

---

scripts/mysql_install_db.sh

mysql_install_db: Use --defaults-group-suffix if specified

---

debian/additions/debian-start.inc.sh

MDEV-14796: debian: insecure root password is only if plugin is empty

---

sql/sql_partition.cc

```
/home/kevg/work/mariadb/sql/sql_partition.cc:286:47: error: cannot initialize a parameter of type 'HA_CREATE_INFO *' (aka 'st_ha_create_information *') with an rvalue of type 'ulonglong' (aka 'unsigned long long')
(ulonglong)0, (uint)0);
^~~~~~~~~~~~
/home/kevg/work/mariadb/sql/partition_info.h:281:72: note: passing argument to parameter 'info' here
bool set_up_defaults_for_partitioning(handler *file, HA_CREATE_INFO *info,
^
```

fix build for recent clang

---

extra/mariabackup/xtrabackup.cc

To keep both sides of this if statement equivalent, defaults-group-suffix needed to be included in the else branch.
Placed defaults-group-suffix moved to the second argument for consistency with b75d767689aff33f4d6963169bb7044165494885.

MDEV-15025 - mariabackup: use defaults-group-suffix even if no --defaults-file

---

mysql-test/suite/galera_3nodes/galera_3nodes.cnf
mysql-test/suite/galera_3nodes/include/have_ipv6.inc
mysql-test/suite/galera_3nodes/t/galera_innobackupex_backup.test
mysql-test/suite/galera_3nodes/t/galera_safe_to_bootstrap.test
mysys/my_default.c
scripts/wsrep_sst_common.sh
scripts/wsrep_sst_mysqldump.sh
scripts/wsrep_sst_rsync.sh
scripts/wsrep_sst_xtrabackup-v2.sh
scripts/wsrep_sst_xtrabackup.sh
sql/wsrep_sst.cc
sql/wsrep_sst.h

group processing by parse_cnf (aka my_print_defaults) resulted in sst scripts fetching potentially a different set of settings than what the mysqld was running.
Replace a lot of group mysqld with --mysqld to be more accurate and now default-group-suffix and --defaults-file-extra a parse though like in 10.1.
Fix a few unnecessary use of grep/cut/tail for string processing.

MDEV-15044 - sst use of mysqld --default* options, sst script enhancements, mtr tests

---

scripts/wsrep_sst_mysqldump.sh

Take any 10.X (X > 1) for wsrep_sst_mysqldump.
Also escape . as its a pattern.
I  submit this under the MCA.

MDEV-15045 - wsrep_sst_mysqldump: enforce a minimum version only

---

sql/wsrep_utils.cc

SST processes should inherit mysqld's process group.
This is a backport of Nirbhay's patch ebe061900b01e4b9ad69860a0e15df44b0ebbb92

MDEV-15046 - "Address already in use" on restart

---

mysql-test/mysql-test-run.pl

MTR explicitly removes the anonymous users 36 lines below this. Its easier if it doesn't install them in the first place.
Since 736afe868094b9aa24211c3772fb3b297d62d8fc the mysql_system_tables_data.sql only installs the anonymous user if skip_auth_anonymous IS NULL. Installing anonymous users is prevented by setting this to 1.
I hesitated removing "DELETE FROM mysql.user where user= ''" because the install from 5.0/5.1 made it look like mtr was designed to be run against any version. It probably can be removed in an non-GA after this is merged.

MDEV-15027 - mtr: set @skip_auth_anonymous=1

---

support-files/mariadb.service.in
support-files/mariadb@.service.in

When galera is used, we want a stop to kill off not only the mysqld process, but the entire process group created by galera to perform sst or wsrep_notify_cmd.
This requires ebe0619, which currently only in 10.2+ so #570 pushes this back to 5.5-galera.
Warning minor merge conflicts with other outstanding systemd PRs like ##387 and #510.

systemd: revert to KillMode=control-group (default) for galera

---

sql/table.cc

gcc7 warning:
sql/table.cc: In member function ‘int TABLE_SHARE::init_from_binary_frm_image(THD*, bool, const uchar*, size_t)’:
sql/table.cc:2032:11: warning: this statement may fall through [-Wimplicit-fallthrough=]
if (vers_can_native)
^~
sql/table.cc:2037:9: note: here
default:
^~~~~~~
I'm assuming this is intentional.

versioning: add explict fallthough to prevent gcc warning

---

sql/threadpool_generic.cc

This is a very minimal cleanup for 10.2. I have work in progress of other threadpool resource management issues that I'll target against 10.3.

threadpool: release mutex on io_poll_create failure

---

extra/mariabackup/xtrabackup.cc

extra/mariabackup/xtrabackup.cc: In function ‘ulint xb_process_datadir(const char*, const char*, handle_datadir_entry_func_t)’:
extra/mariabackup/xtrabackup.cc:4534:1: warning: ‘snprintf’ output may be truncated before the last format character [-Wformat-truncation=]
xb_process_datadir(
^~~~~~~~~~~~~~~~~~
mariabackup/xtrabackup.cc:4607:11: note: ‘snprintf’ output 2 or more bytes (assuming 4001) into a destination of size 4000
snprintf(dbpath, sizeof(dbpath), "%s/%s", path, dbinfo.name);
~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
I submit this under the MCA. Probably should of targeted an earlier branch.

MariaBackup: gcc7 - snprintf output overflow warning

---

sql/my_decimal.h

which says:
We need the up-cast here, since my_decimal has sign() member functions,
which conflicts with decimal_t::size
But decimal_t does not provide `size` field.
--------

fix comment in my_decimal_set_zero()

---

sql/mysqld.cc

we have two the same 'if' clauses that check opt_bin_log argument
in mysqld.cc and both clauses go successively one after another.
Let's merge them into one
---

merge two the same consistently 'if' clauses into one

---

storage/innobase/buf/buf0buf.cc
storage/innobase/include/log0log.h
storage/innobase/include/log0recv.h
storage/innobase/include/ut0new.h
storage/innobase/log/log0log.cc
storage/innobase/log/log0recv.cc
storage/innobase/row/row0log.cc
storage/innobase/row/row0merge.cc

Rework of #333. This is hooks allocate_large which is used for innodb buffer pool allocation and parts of online table operations.
An alternate PR covering just the innodb buffer pool pages is also provided if this is too general. I prefer this implementation.

MDEV-10814: innodb large allocations - Don't dump

---

storage/innobase/os/os0file.cc

MDEV-8743: ib_logfile0 Use O_CLOEXEC so galera SST scripts don't get fd

---

scripts/wsrep_sst_common.sh

To prevent accidential overwriting of files due to mysqld file
descriptors being open we ensure where that only FDs 1, 2 and 3
are open of which SST scripts really only use stdout and stderr.
So this is the defence in depth of the other PRs to CLOEXEC within the server.
Passes galera test suite as much as without this patch.

MDEV-8743: wsrep_sst_common close FDs > 2

---

mysql-test/suite/galera/disabled.def
mysql-test/suite/galera/r/galera_bf_abort_for_update.result
mysql-test/suite/galera/t/galera_bf_abort_for_update.test

Cherry picked upstream fixes for test galera_bf_abort_for_update, and re-enabled it.

MDEV-13549 Fix and re-enable test galera.galera_bf_abort_for_update

---

mysql-test/suite/galera/include/galera_wsrep_recover.inc

The error log redirection for wsrep_recover run does not work in old version.
For the wsrep_recovery run, error logging is supposed to go into:
mysql-test/suite/galera/include/galera_wsrep_recover.inc
In old version, this works only partially, 4 first lines of error messages after mysql startup
do go into the galera_wsrep_recover.log, but after that the default error log file is enforced
and remaining error logging goes into the default error log file.
In this patch this problem is fixed by passing --log-error option in mysql startup
This fix was tested with galera_gcache_recover test, which is currently in disabled state.
Note that the test does not pass even after this fix, as there are further more issues
in later test phases.

MDEV-15540 fix for MTR tests using wsrep_recover.inc

---

mysql-test/suite/galera/disabled.def
mysql-test/suite/galera/r/galera_var_slave_threads.result
mysql-test/suite/galera/t/galera_var_slave_threads.test

Two changes were made to the test:
1) Suppress warning "Refusing exit for the last slave thread."
This warning was already suppressed, but on the wrong node.
2) The test occasionally fails because it expects that the
number of applier threads changes immediately after
changing the value of ```variable wsrep_slave_threads```.
Which is not true. This patch turns snippets like this:
```
SET GLOBAL wsrep_slave_threads = x;
SELECT COUNT(*) = x FROM INFORMATION_SCHEMA.PROCESSLIST WHERE USER = 'system user';
```
Into proper wait_conditions:
```
SET GLOBAL wsrep_slave_threads = x;
let $wait_condition = SELECT COUNT(*) = x FROM ...;
--source include/wait_condition.inc
```

MDEV-13549 Fix and re-enable test galera.galera_var_slave_threads

---

include/my_valgrind.h
storage/innobase/mem/mem0mem.c
storage/xtradb/mem/mem0mem.c

Learn both valgrind and asan to catch this bug:
```c++
mem_heap_t* heap = mem_heap_create(1024);
byte* p = reinterpret_cast<byte*>(heap) + sizeof(mem_heap_t);
*p = 123;
```
Overflows of the last allocation in a block will be catched too.
mem_heap_create_block(): poison newly allocated memory

MDEV-15030 Add ASAN instrumentation

---

mysql-test/suite/galera/disabled.def
mysql-test/suite/galera/r/galera_suspend_slave.result
mysql-test/suite/galera/t/galera_suspend_slave.test

Test galera_suspend_slave checks that after suspending a galera
node, like this:
```
--perl
my $pid_filename = $ENV{'NODE_2_PIDFILE'};
my $mysqld_pid = `cat $pid_filename`;
chomp($mysqld_pid);
system("kill -SIGSTOP $mysqld_pid");
exit(0);
EOF
```
the remaining one node cluster is no longer able to successfully
INSERT new rows:
```
--error ER_UNKNOWN_COM_ERROR,ER_LOCK_WAIT_TIMEOUT,ER_LOCK_DEADLOCK,ER_ERROR_DURING_COMMIT
INSERT INTO t1 VALUES (1);
```
On rare occasions when the system is overloaded, it appears that
suspending the process with ```system("kill -SIGSTOP $mysqld_pid")```
takes some time, enough for the subsequent INSERT to succeed. In which
case the test fails because it rightly expects the INSERT to fail.
To fix the problem, the patch makes sure that the cluster has shrinked …

MDEV-13549 Fix and re-enable test galera.galera_suspend_slave

---

mysql-test/suite/galera/disabled.def
mysql-test/suite/galera/r/galera_gtid_slave.result
mysql-test/suite/galera/t/galera_gtid_slave.test

This patch makes two changes:
* It replaces `--sleep 1` with appropriate wait_conditions, and
removes another `--sleep 1` which is no longer necessary, after
MDEV-14144 has been fixed.
* It moves the `RESET MASTER` from node_1 at the very end, when it
it sure that the other nodes have applied the the final cleanup
`DROP TABLE t1,t2.`
This solves the problem with the `DROP TABLE` not being replicated
to the asynchronous slaves, which would make the test fail with:
`Timeout in wait_condition.inc for SELECT COUNT(*) = 0 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 't1';`

MDEV-13549 Fix and re-enable MTR test galera.galera_gtid_slave

---

mysql-test/r/ps.result
mysql-test/suite/sys_vars/r/max_prepared_stmt_count_basic.result
mysql-test/suite/sys_vars/t/max_prepared_stmt_count_basic.test
sql/mysqld.cc
sql/mysqld.h
sql/sys_vars.cc

The upper 1M limit for max_prepared_stmt_count was set over 10 years
ago. It doesn't suite current hardware and a sysbench oltp_read_write
test with 512 threads will hit this limit.
What are your thoughts on removing this in 10.3?

increase upper value of max_prepared_stmt_count to 1G

---

mysql-test/suite/galera/disabled.def
mysql-test/suite/galera/r/MW-284.result
mysql-test/suite/galera/t/MW-284.test
sql/sql_parse.cc

Failed due to missing RESET MASTER

MDEV-13549 Fix and re-enable MTR test galera.MW-284

---

scripts/wsrep_sst_mysqldump.sh

Any accidental missing of wsrep_sst_mysqldump and server version means we could miss this section.
Its safer just to say !=5.

MDEV-15023 - wsrep_sst_mysqldump: safer test of version != 5

---

mysql-test/suite/galera/r/galera_wsrep_desync_wsrep_on.result
mysql-test/suite/galera/t/galera_wsrep_desync_wsrep_on.test

The test tends to fail if many parallel instances of it are executed:
```
mysqltest: At line 23: query 'ALTER TABLE t1 ADD PRIMARY KEY (f1)' failed:
1317: Query execution was interrupted
```
The `ALTER` fails because it is BF aborted due to an earlier `INSERT SELECT`
that is being applied:
```
INSERT INTO t1 (f1) SELECT ...
--connection node_2
SET GLOBAL wsrep_desync = TRUE;
SET SESSION wsrep_on = FALSE;
ALTER TABLE t1 ADD PRIMARY KEY (f1);
SET SESSION wsrep_on = TRUE;
SET GLOBAL wsrep_desync = FALSE;
```
And because the `ALTER` is executed with `wsrep_on = OFF`, it does not
run in total order isolation.
To avoid the problem it must be ensured that the `ALTER` only after the
large `INSERT SELECT` is done. To do so it is sufficient to issue
`SELECT COUNT(*) FROM t1;` from `node_2` before …

MDEV-13549 Fix test galera.galera_wsrep_desync_wsrep_on

---

mysql-test/suite/galera/disabled.def
mysql-test/suite/galera/r/galera_gra_log.result
mysql-test/suite/galera/t/galera_gra_log.test

Test would occasionally fail as follows:
```
mysqltest: At line 20: query 'SELECT COUNT(*) = 0 FROM t1' failed:
1317: Query execution was interrupted
```
This was due to a `CREATE TABLE` applied concurrently that would
occasionally cause the `SELECT` to be BF aborted, due to MDL
conflict.
The `SELECT` is executed while `wsrep_on=OFF`. The change makes sure
it is executed only after wsrep is enabled again.

MDEV-15808 Fix and re-enable test galera.galera_gra_log

---

mysql-test/r/mysqld--help.result
mysys/default.c

Also clarify the default options, if present, must be part of the first arguments.

defaults-groups-suffix in print_defaults

---

mysql-test/suite/galera/include/galera_st_kill_slave.inc

This patch fixes a lock wait timeout error on `SELECT @@GLOBAL.WSREP_ON`
in `wait_wsrep_ready.inc`:
```
--connection node_2
...
--source include/kill_galera.inc
--connection node_1
--source include/wait_until_connected_again.inc # This includes wait_wsrep_ready.inc
```
The problem is that on node_2, kill_galera.inc may return before
the node is killed. So node_1 may still see that node_1 is alive
and will attempt to sync wait when doing those `SELECT` statements.
But sync wait is doomed to fail given that node_1 is killed, hence
the lock wait timeout.
One possible fix is to disable wsrep_sync_wait before including
wait_until_connected_again.
However, it appears that including wait_until_connected_again is
not necessary at all in node_1, so this patch removes it altogether.

MDEV-15929 Fix lock wait timeout on `SELECT @@GLOBAL.WSREP_ON`

---

mysql-test/suite/galera/disabled.def
mysql-test/suite/galera/t/galera_pc_ignore_sb.test

* After killing one galera node with include/kill_galera,
wait for cluster to shrink
* Remove unnecessary include/wait_until_connected_again.inc

MDEV-15811 Fix and re-enable test galera.galera_pc_ignore_sb

---

mysql-test/suite/galera/disabled.def
mysql-test/suite/galera/r/galera_var_retry_autocommit.result
mysql-test/suite/galera/t/galera_var_retry_autocommit.test
sql/sql_parse.cc

The test was not deterministic and would occasionally fail, due to the
use of `sleep`.
This patch is a complete rewrite of the test using proper sync points.

MDEV-15794 Fix and re-enable test galera_var_retry_autocommit

---

mysql-test/suite/galera/t/galera_gcs_fragment.test

Test galera_gcs_fragment performs cluster reconfiguration, so
`auto_increment_offset` may change, and check test case at the
end of test fails.

Save / restore auto_increment_offset in test galera_gcs_fragment

---

scripts/mysql_install_db.sh

mysql_test_db.sql is in the srcdir
Otherwise out of tree build:
<pre>
build-mariadb-server-10.3]$ scripts/mysql_install_db --datadir=/tmp/mysqldatadir-auth-dyn --plugin-dir=mysql-test/var/plugins/  --auth-root-socket-user=dan --auth-root-authentication-method=socket --builddir=.  --srcdir=../mariadb-server-10.3
FATAL ERROR: Could not find ./scripts/mysql_test_db.sql
</pre>
attn: @svoj

MDEV-12645: mysql_install_db --no-test (postfix)

---

sql/sp.cc

(clang-3.8)
sql/sp.cc:2834:53: warning: implicit conversion of NULL constant to 'size_t' (aka 'unsigned long') [-Wnull-conversion]
size_t prefix_length= dot ? dot - tmp.str + 1 : NULL;
~~~~~~~~~~~~~                            ^~~~
0
introduced 583eb96c2492

sp_cache_package_routine: fix compile warning

---

include/my_global.h
include/mysql/psi/mysql_socket.h
sql/mysqld.cc

In MDEV-8743, the port/socket of mysqld was changed to set FD_CLOEXEC.
The existing mysql_socket_socket function already set that with
SOCK_CLOEXEC when the socket was created. So here we move the fcntl
functionality to the mysql_socket_socket as port/socket are the only
callers.
Preprocessor checks of SOCK_CLOEXEC cannot be done as its a 0 if not
there and SOCK_CLOEXEC (being the value of the enum in bits/socket_type.h)
Preprocesssor logic for arithmetic and non-arithmetic defines are
hard/nonportable/ugly to read. As such we just check in my_global.h
and define HAVE_SOCK_CLOEXEC if we have it.
There was a disparity in behaviour between defined(WITH_WSREP) and
not depending on the OS, so the WITH_WSREP condition was removed
from setting calling fcntl.
All sockets are now maked …

MDEV-8743: mysqld port/socket - FD_CLOEXEC if no SOCK_CLOEXEC

---

client/mysqltest.cc
mysql-test/main/connect-abstract.cnf
mysql-test/main/connect-abstract.result
mysql-test/main/connect-abstract.test
sql/mysqld.cc

The functionality of the socket system varible is extended
here such that a preciding '@' indicates that the remainder of
the name is an abstract socket. This is consistent with the
approached used by systemd in socket activativation.
Client side: https://github.com/MariaDB/mariadb-connector-c/pull/43

MDEV-15655: Add Linux abstract socket support

---

debian/autobake-deb.sh

simple back-port of @ottok 
closes MDEV-14928 and MDEV-12642

MDEV-12642: Build deb source packages on buildbot, just not on Travis-CI

---

.gitignore

I'm using the CMake project import in QtCreator IDE to browse the source. This import generates CodeBlocks .cbp files.

Ignore .cbp QtCreator project files and macOS .DS_Store Finder junk.

---

CMakeLists.txt
cmake/ctest.cmake
mysql-test/suite/unit/suite.pm
unittest/sql/CMakeLists.txt

Assign all tests added via MY_ADD_TEST to a bogus default_ignore target,
so that they are not ran by default when doing bare make test. Add default
test named MTR that calls mysql-test-run suite, which is now the single
test run by make test.
In consequence, modified unit/suite.pm to exclude the MTR test and run the
real ctests flagged for default_ignore target, thus no circular
loop.

MDEV-16075: Workaround to run MTR test suite for make test

---

mysql-test/r/check_constraint.result
mysql-test/r/constraints.result
mysql-test/r/type_json.result
mysql-test/t/check_constraint.test
sql/table.cc

One can create table with the same name for `field` and `table` `check` constraint.
For example:
`create table t(a int check(a>0), constraint a check(a>10));`
But when inserting new rows same error is always raised.
For example with
```insert into t values (-1);```
and
```insert into t values (10);```
same error `ER_CONSTRAINT_FAILED` is obtained.
By the assumption that previous error should be raised only in case of `table` constraints,
this patch will distinguish between `field` and `table` error message
by adding newly created `ER_FIELD_CONSTRAINT_FAILED` error which occurs only when `field`
constraint is violated.

MDEV-16630: Ambiguous error message when check constraint matches table name

---

scripts/wsrep_sst_common.sh

POSIX shell support in 10.0-galera would require f16ead51fbbf03ca51db9343960785b431fab157 however this shellcheck component wasn't included.
shellcheck -s sh wsrep_sst_common.sh
In wsrep_sst_common.sh line 258:
[ -n $3 ] && reval=$3
^-- SC2070: -n doesn't work with unquoted arguments. Quote or use [[ ]].
^-- SC2086: Double quote to prevent globbing and word splitting.

MDEV-15549 - wsrep_sst_common: fix per shellcheck

---

scripts/wsrep_sst_rsync.sh

Hi,
This PR adds the ability to use stunnel during rsync SST, thus encrypting data on the wire.
You then just have to have `stunnel` binary available, and the following in server configuration :
```
[sst]
tkey = /etc/mysql/certs/client-key.pem
tcert = /etc/mysql/certs/client-cert.pem
```
`stunnel` will then be used.
You will also have to be sure your `certs` dir is hashed :
`openssl  rehash /etc/mysql/certs/`
Thank you 👍 
Ben

MDEV-15511 - Use stunnel during rsync SST if available

---

debian/control

Hi,
adding missing dependencies resolve the problem and `mariabackup` can be installed and run without problem:
https://jira.mariadb.org/browse/MDEV-15869

MDEV-15869 Mariabackup is lacking some dependencies declaration

---

mysql-test/suite/galera/r/galera_var_desync_on.result
mysql-test/suite/galera/t/galera_var_desync_on.test
sql/wsrep_var.cc

Manually setting wsrep_desync after FTWRL should not be allowed.

MDEV-15933 Cannot resume Node SYNCED state when wsrep_desync is done after FTWRL

---

.travis.yml

before @ottok explodes about travis breaking......

travis: llvm repo gpg key missing - use travis defination

---

sql/item.cc

The common case for this function is that both types are the same.
The Item_result defination from include/mysql.h.pp is the following enum
enum Item_result
{
STRING_RESULT=0, REAL_RESULT, INT_RESULT, ROW_RESULT, DECIMAL_RESULT,
TIME_RESULT
};
The compilers aren't quite smart enough to optimize to this shortcut so
this makes it quicker.
Before the change:
0000000000012730 <item_cmp_type(Item_result, Item_result)>:
12730:       89 f0                   mov    %esi,%eax
12732:       09 f8                   or     %edi,%eax
12734:       74 4c                   je     12782 <item_cmp_type(Item_result, Item_result)+0x52>
12736:       83 ff 02                cmp    $0x2,%edi
12739:       75 0a                   jne    12745 <item_cmp_type(Item_result, Item_result)+0x15>
1273b:       b8 02 00 00 …

MDEV-15838 - item_cmp_type: simplier for a faster codepath

---

mysql-test/mysql-test-run.pl

For e.g. on Ubuntu 14.04 /run/shm is not a symlink to /dev/shm, as in later versions of Ubuntu or Debian, nor is it world writeable. Adding this check will make MTR fall through to the next default location, which is /dev/shm.

MDEV-17022: check if mtr --mem location is writeable

---

storage/rocksdb/ha_rocksdb.cc
storage/rocksdb/mysql-test/rocksdb/r/autoinc_vars.result
storage/rocksdb/mysql-test/rocksdb/t/autoinc_vars.test

Currently RocksDB engine doesn't update AUTO_INCREMENT in the UPDATE statement.
For example,
CREATE TABLE t1 (pk INT AUTO_INCREMENT, a INT, PRIMARY KEY(pk)) ENGINE=RocksDB;
INSERT INTO t1 (a) VALUES (1);
UPDATE t1 SET pk = 3; ==> AUTO_INCREMENT should be updated to 4.

MDEV-16703: update AUTO_INCREMENT in the UPDATE statement

---

storage/connect/javaconn.cpp
storage/connect/jdbconn.cpp
storage/connect/jmgoconn.cpp
storage/connect/tabjmg.cpp

The argument takes a pointer, so casting ```false``` to ```jboolean``` and expecting an implicit conversion to NULL is just ugly.
Avoids compile errors of the from from clang are avoided:
/storage/connect/jdbconn.cpp:1473:41: error: cannot initialize a parameter of type 'jboolean *' (aka 'unsigned char *') with an rvalue of type 'jboolean' (aka 'unsigned char')
name = env->GetStringUTFChars(label, (jboolean)false);
^~~~~~~~~~~~~~~
/usr/lib/jvm/java-8-oracle/include/jni.h:1616:58: note: passing argument to parameter 'isCopy' here
const char* GetStringUTFChars(jstring str, jboolean *isCopy) {

connect engine: GetStringUTFChars takes pointer arg

---

scripts/galera_new_cluster.sh

Not sure why I added these in the first commit of this however they aren't used.
I submit this deletion under the MCA.

galera_new_cluster.sh: unused variables

---

mysql-test/suite/galera/r/galera_sst_xtrabackup-v2_data_dir.result
mysql-test/suite/galera/t/galera_sst_xtrabackup-v2_data_dir.cnf
mysql-test/suite/galera/t/galera_sst_xtrabackup-v2_data_dir.test
scripts/wsrep_sst_common.sh
scripts/wsrep_sst_rsync.sh
scripts/wsrep_sst_xtrabackup-v2.sh

Current versions of xtrabackup-v2 and mariabackup support the option
--innodb-data-home-dir, but this parameter is not passed to them from
the SST script, since the SST script does not receive this information
from mysqld. The transfer of this information to the SST is already
fixed by the MDEV-10754 patch, but we need to process it in the SST
script. Also, we should take into account that on the joiner side
the corresponding information is not read yet from the configuration
file (at the mysqld side) during the start of SST, so the script must
itself read it.
https://jira.mariadb.org/browse/MDEV-10756

MDEV-10756: wsrep_sst_xtrabackup-v2 does not support innodb_data_home_dir

---

mysql-test/suite/galera/disabled.def
sql/sql_base.cc

While executing CTAS galera applier thread can cause CTAS to abort and rollback. Rollback can take time causing applier thread to shutdown node after several unsuccessful retries to apply transaction. CTAS should finish before transaction is applied.

MDEV-15845 Test failure on galera.galera_concurrent_ctas

---

mysql-test/suite/galera_3nodes/r/galera_certification_double_failure.result

There was change in error reporting from my_error to my_message so this test was left unrecorded.

MDEV-16052 galera mtr galera_certification_double_failure fails with deadlock

---

scripts/galera_new_cluster.sh

- When bootstraping the galera cluster it's good to get correct return code from the (failed) execution.

Return code from starting MariaDB.

---

sql/field.cc
storage/rocksdb/mysql-test/rocksdb_rpl/r/rpl_blob_key.result
storage/rocksdb/mysql-test/rocksdb_rpl/t/rpl_blob_key.test

The blob key length could be shorter than the length of the entire blob,
for example,
CREATE TABLE t1 (b BLOB, i INT, KEY(b(8)));
INSERT INTO t1 VALUES (REPEAT('a',9),1);
The key length is 8, while the blob length is 9.
So we need to set the correct key length in Field_blob::sort_string().

MDEV-16768: fix blob key length

---

include/my_valgrind.h
mysys/my_alloc.c

alloc_root(): unpoison only requested amount of bytes instead of a
possible bigger aligned-sized buffer.

MDEV-17248 Improve ASAN memory pool instrumentation

---

storage/innobase/sync/sync0rw.cc

rw_lock_x_lock_wait_func(): remove duplicated logic added in incorrect merge
Affected counters are affected by InnoDB monitor. But they aren't stable and thus
can not be realiably tested.

MDEV-17306 rw_lock_x_lock_wait_func() double increments rw_x_spin_round_count

---

mysql-test/suite/galera/r/galera_drop_database.result
mysql-test/suite/galera/t/galera_drop_database.test
storage/innobase/fts/fts0fts.cc
storage/xtradb/fts/fts0fts.cc

When converting table identifiers to a new format,
some tables can be renamed twice, which subsequently
leads to the appearance of "false" auxiliary tables
belonging to another main (parent) table (which does
not actually have auxiliary tables).
This is because the table number is repeatedly added
to the aux_tables_to_rename vector inside the function
fts_check_and_drop_orphaned_tables.
To correct this error, we must add a check for the
occurrence of the table number in the aux_tables_to_rename
vector before adding a new element.
https://jira.mariadb.org/browse/MDEV-16656

MDEV-16656: DROP DATABASE crashes the Galera Cluster

---

mysql-test/suite/galera/r/versioning_trx_id.result
mysql-test/suite/galera/t/versioning_trx_id.cnf
mysql-test/suite/galera/t/versioning_trx_id.test
mysql-test/suite/versioning/r/trx_id.result
mysql-test/suite/versioning/t/trx_id.test
sql/table.cc
sql/wsrep_applier.cc

Patch fixes two bugs:
1) BEGIN_TIMESTAMP of MYSQL.TRANSACTION_REGISTY is '0-0-0' on replication record insertion
2) BEGIN_TIMESTAMP equals COMMMIT_TIMESTAMP in MYSQL.TRANSACTION_REGISTRY
Fixed by calling THD::set_time() at appropriate places

MDEV-16211 Contents of transaction_registry not replicated by Galera

---

storage/innobase/include/ut0counter.h
storage/xtradb/include/ut0counter.h

ib_counter_t: make all reads/writes to m_counter relaxed atomical
[Buildbot](http://buildbot.askmonty.org/buildbot/grid?category=main&branch=tt-10.1-MDEV-17313-counter-race)

MDEV-17313 Data race in ib_counter_t

---

include/my_bit.h

my_reverse_bits(): add a cast to fix a bit shift
[Buildbot](http://buildbot.askmonty.org/buildbot/grid?category=main&branch=tt-10.0-MDEV-17358-reverse-bits)

MDEV-17358 my_reverse_bits() is incorrect due to UB

---

README

Also change Jira link to actual domain. The mariadb.org/jira web server redirect
might not be maintained at some point.

README: Add reporting security vulns. direction

---

client/mysqltest.cc
mysql-test/lib/v1/mysql-test-run.pl
mysql-test/mysql-test-run.pl

Hello,
I was reading the source and found a small problem. 
A few link of some URL written in the comment seems to have moved.
I fixed the link of the URL I wanted to see.
But there seems to be another similar links.
If necessary, I can also fix it. How do you like it?

improve(test) framework manual is moved

---

.travis.compiler.sh

Apparently, there is room to squeeze a little bit more cache as seen in these build speedups:
https://travis-ci.org/shinnok/server/builds/449288361
https://travis-ci.org/shinnok/server/builds/449346985

travis: increase ccache size for linux jobs

---

sql/wsrep_mysqld.cc
storage/innobase/handler/ha_innodb.cc

* warning: unused variable ‘node_addr_max’ [-Wunused-variable]
* Two warnings in WSREP_DEBUG() formats

Fixes to format and unused variable compilation warinings

---

mysql-test/suite/galera/r/galera_var_slave_threads.result
mysql-test/suite/galera/t/galera_var_slave_threads.test

- Fixed cleanup phase, no more slave threads should be created
- Save/restore auto increment offsets
- Unnecessary disabling of wsrep_sync_wait, removed
- Fixed result file, was recorded with timeout on wait condition!

Fix test galera.galera_var_slave_threads

---

sql/sql_parse.cc
storage/innobase/handler/ha_innodb.cc

Moved the before_command() hook to called as soon as possible, after my_net_read_packet()
returns. This is because before_command() entry has wait loop to pause client for as long
as background rollback for the client is processing.
before_command() call was earlier inside dispatch_command(), and some adjusting was needed to
handle in do_command() level, the case where clinet's transaction was brute force aborted and
deadlock error needs to be returned for the client.
In ha_innodb.cc:wsrep_kill_one_transaction(), THD::awake() used, when victim has already been
aborted by wsrep_thd_bf_abort(). This would only cause two awake() signals for same victim.
Also an idle THD would be signaled, which is now avoided.

Sporadic failures of galera.galera_FK_duplicate_client_insert test

---

include/wsrep.h

The merges from upstream galera 4 integration missed proper definition
for WSREP_TO_ISOLATION_END
This is fixed in this commit, and mtr tests executing RSU loads should work now

fix for DDL in RSU mode execution

---

mysql-test/suite/galera/r/galera_toi_ddl_locking.result
mysql-test/suite/galera/t/galera_toi_ddl_locking.test
sql/wsrep_mysqld.cc

This commit contains mege from upstream galera 4 integration to handle CREATE ROLES replication.
This fix will enable galera_roles test to pass
galera_toi_ddl_locking.test was missing dbug_syn reset, which cused failure in post execution
environment checking

galera_roles galera_toi_ddl_locking fixes

---

sql/sql_parse.cc
sql/wsrep_mysqld.cc

wsrep_close_client_connections() called THD::awake() by holding LOCK_thd_data,
this caused doube locking of the mutex. This has been fixed
if client connection was killed while being idle, it would bail out immediately
after my_net_read_packet(), without calling before_command() hook.
However, in the end of do_command(), the after_command() hook is called unconditionally.
This caused an assert inside after_command() for bad client state,
in galera_var_reject_queries test, where such connection close was exercised.

Fixes for galera.galera_var_reject_queries and galera_bf_abort_shutdown

---

sql/sql_parse.cc

When executing sub statements don't call wsrep_commit_empty.

Fixes for galera.mysql-wsrep#110 and galera.ev51914

---

mysql-test/suite/galera/r/galera_ist_mariabackup,debug.rdiff
mysql-test/suite/galera/r/galera_sst_rsync,debug.rdiff
mysql-test/suite/galera/r/galera_sst_rsync2,debug.rdiff

Records .rdiff files for tests galera_ist_mariabackup,
galera_sst_rsync, and galera_sst_rsync2.

Record .rdiff files

---

mysql-test/suite/galera_sr/r/galera_sr_conflict.result
mysql-test/suite/galera_sr/t/galera_sr_conflict.test
sql/wsrep_high_priority_service.cc

Test fails due to timeout in wait condition error, which expects
applier thread to show up in process list state "committed".
This was not the case due to missing call to thd_proc_info() after
applier appends and commits a fragment.

Fix test galera_sr.galera_sr_conflict

---

sql/table_cache.cc

The WITH_WSREP block here, in tdc_remove_table() was used to silence the assertion in the use
case where high priority DROP TABLE has BF aborted a blocking local transaction. The victim was
marked to abort asap.
However, this practice has changed, and DROP TABLE will now wait for the victim to abort and release
MDL locks, before continuing. Threfore, the full WITH_WSREP patch has been removed .

Fixes for review #1 from svoj

---

mysql-test/suite/galera/r/MW-284.result
mysql-test/suite/galera/t/MW-284.test
sql/sql_parse.cc
sql/wsrep_trans_observer.h

set global wsrep_on=OFF
RESET MASTER
set global wsrep_on=ON
is usual pattern to enable executing RESET MASTER in active node
but, in general, this is wrong pattern, and should be reworked in all tests

Fix for MW-284, and other tests which set wsrep_on=OFF

---

sql/wsrep_schema.cc
sql/wsrep_sst.cc

This pull request fixes restoring view from an empty cluster table (should be empty view as a result) instead of printing an error message. This fixes `galera_3nodes.galera_pc_bootstrap` and `galera.galera_log_output_csv`

Failed to recover view fix

---

sql/wsrep_applier.cc

Initializing transaction start time for applier THD, this time value will be used to
populate begin_timestamp in mysql.transaction_registry table for the applied transaction

Fix for galera.versioning_trx_id test

---

mysql-test/suite/galera/r/galera_as_slave_gtid_replicate_do_db.result
mysql-test/suite/galera/r/galera_gtid_slave.result
mysql-test/suite/galera/r/galera_gtid_slave_sst_rsync.result
mysql-test/suite/galera/t/galera_as_slave_gtid_replicate_do_db.test
mysql-test/suite/galera/t/galera_gtid_slave.test
scripts/wsrep_sst_rsync.sh

* Fixed: galera_gtid_slave, galera_gtid_slave_sst_rsync and galera_as_slave_gtid_replicate_do_db.
* Galera as slave configurations galera nodes are using mysqld.1 and mysqld.2. Fixed to use that nodes and re-recorded.
* Use different name for log-bin-index than log-bin.

Fix for galera as slave tests

---

include/my_global.h

Current implementation is conflicting. If `UNICODE` is defined, `FormatMessage()` will be `FormatMessageW()`, and variable `win_errormsg` with type `char` can not be passed to it, which should be changed to `TCHAR` instead. Since we don't use UNICODE here, we can use `FormatMessageA()` directly to avoid conversion error.
```
my_global.h(1092): error C2664: 'DWORD FormatMessageW(D
WORD,LPCVOID,DWORD,DWORD,LPWSTR,DWORD,va_list *)' : cannot convert argument 5 from 'char [2048]' to 'LPWSTR'
```

Fix UNICODE issue of dlerror()

---

mysql-test/suite/innodb/r/innodb-index.result
mysql-test/suite/innodb/t/innodb-index.test
storage/innobase/handler/handler0alter.cc
storage/xtradb/handler/handler0alter.cc

ha_innobase::prepare_inplace_alter_table(): check max column length for every
index in a table, not just added in this particular ALTER TABLE with ADD INDEX ones.
[Buildbot](http://buildbot.askmonty.org/buildbot/grid?category=main&branch=tt-10.0-MDEV-17833-copy-inplace-error)

MDEV-17833 ALTER TABLE is not enforcing prefix index size limit

---

mysql-test/suite/galera/r/galera_ist_mariabackup,debug.rdiff
mysql-test/suite/galera/r/galera_ist_mariabackup.result
mysql-test/suite/galera/r/galera_ist_mariabackup_innodb_flush_logs.result
mysql-test/suite/galera/r/galera_sst_mariabackup.result
mysql-test/suite/galera/r/galera_sst_rsync,debug.rdiff
mysql-test/suite/galera/r/galera_sst_rsync.result
mysql-test/suite/galera/t/galera_bf_abort_shutdown.test

* Record .result and/or .rdiff files for galera_ist_mariabackup, galera_ist_mariabackup_innodb_flush_logs, galera_sst_mariabackup and galera_sst_rsync.
* Missing "have_debug_sync.inc" in galera_bf_abort_shutdown

Fixes for tests that fail in release build

---

include/mysql/service_wsrep.h
sql/handler.cc
sql/item_func.cc
sql/item_strfunc.h
sql/mysqld.cc
sql/sql_parse.cc
sql/wsrep_applier.cc
sql/wsrep_binlog.cc
sql/wsrep_check_opts.cc
sql/wsrep_dummy.cc
sql/wsrep_high_priority_service.cc
sql/wsrep_mysqld.cc
sql/wsrep_mysqld.h
sql/wsrep_notify.cc
sql/wsrep_priv.h
sql/wsrep_schema.cc
sql/wsrep_server_service.cc
sql/wsrep_sst.cc
sql/wsrep_storage_service.cc
sql/wsrep_thd.cc
sql/wsrep_thd.h
sql/wsrep_thd_pool.cc
sql/wsrep_utils.cc
sql/wsrep_utils.h
sql/wsrep_var.cc
sql/wsrep_xid.cc

Cleaned up obsolete code from service_wsrep.h
The following enums are obsoloted by wsrep-lib and should no longer
be exposed: wsrep_conflict_state, wsrep_exec_mode, wsrep_query_state,
wsrep_trx_state.
Removed the enums from service_wsrep.h and cleaned up corresponding
dead code from wsrep_mysqld.h.
wsrep_recover run causing memory leaks
Enabling shutdown phase memory leak testing, triggered regression with tests, which
startup mysqld with --wsrep_recover option, following tests failed:
galera.galera_ist_mariabackup
galera.galera_ist_mysqldump
galera.galera_ist_restart_joiner
galera.galera_ist_rsync
galera.galera_pc_recovery
galera.galera_sst_rsync
galera.galera_sst_rsync2
galera.galera_sst_rsync_data_dir
galera.mysql-wsrep#31
This commit will gracefully tear down wsrep-lib use after …

Fixes according to Bar's review

---

mysql-test/suite/galera_3nodes/r/galera_var_dirty_reads2.result
mysql-test/suite/galera_3nodes/t/galera_var_dirty_reads2.test

Wsrep-lib submodule was updated to position which fixes
an assertion after desync/pause, resume/resync operations
in non-primary view.
Ensure that node_2 reaches ready state before dropping table at the
end of the test.
Recorded galera_var_dirty_reads2 which is now passing.

Updated wsrep-lib submodule, recorded galera_var_dirty_reads2

---

sql/wsrep_dummy.cc

The cleanup in commit f6bbdfdc33458fb31ecd54a371d6999c709c2209
was not complete, obsolete wsrep API enums were still left in
wsrep_dummy.cc. This caused build failure when compiling
embedded server.
Removed obsolete and commented-out code from wsrep_dummy.cc.

Fixed embedded server compilation errors

---

mysql-test/suite/wsrep/my.cnf
mysql-test/suite/wsrep/t/binlog_format.cnf
mysql-test/suite/wsrep/t/binlog_format.opt
mysql-test/suite/wsrep/t/mdev_6832.cnf
mysql-test/suite/wsrep/t/mdev_6832.opt
mysql-test/suite/wsrep/t/mdev_6832.test
mysql-test/suite/wsrep/t/mdev_7798.cnf
mysql-test/suite/wsrep/t/mdev_7798.opt
mysql-test/suite/wsrep/t/mdev_7798.test
mysql-test/suite/wsrep/t/pool_of_threads.cnf
mysql-test/suite/wsrep/t/pool_of_threads.opt
sql/wsrep_mysqld.cc

* Disabled wsrep-on for all tests in wsrep suite.
* For test which need wsrep-on=ON additional .cnf file is created and .opt file removed.

Fixes for wsrep suite

---

mysql-test/suite/galera/r/galera_sst_mariabackup_data_dir,debug.rdiff
mysql-test/suite/galera/r/galera_sst_mariabackup_data_dir.result
mysql-test/suite/galera/t/galera_sst_mariabackup_data_dir.cnf
mysql-test/suite/galera/t/galera_sst_mariabackup_data_dir.test
scripts/wsrep_sst_mariabackup.sh

Currently there is no test file in the project that would
check the operation of the matiabackupt SST script with
the innodb_data_home_dir parameter. This fix adds this
test to the galera test suite.
https://jira.mariadb.org/browse/MDEV-17786

DEV-17786: Add mariabackup test case for galera_sst_xtrabackup-v2_data_dir

---

include/mysql/service_wsrep.h
mysql-test/suite/galera/r/MW-369.result
mysql-test/suite/galera/t/MW-369.inc
mysql-test/suite/galera/t/MW-369.test
sql/service_wsrep.cc
sql/sql_insert.cc
storage/innobase/handler/ha_innodb.cc
storage/innobase/handler/ha_innodb.h
storage/innobase/row/row0ins.cc

for the UPDATE key type. In particular mark keys for the
UPDATE operation as UPDATE instead of EXCLUSIVE depending
on the cluster-wide supported application protocol version
to reduce the possibility of multi-master conflicts when
updating parent tables.

References codership/mariaDB-wsrep#69 Server-side support

---

storage/innobase/row/row0ins.cc

This patch fixes regressions commit:
d3cd7aa76f078063029b8e7a4adb4fd65099bfa5
That commit fixed sql_sequence.create test, but introduced many
regressions in SR tests. The fix changes flags set in function
row_ins_clust_index_entry() so that:
a) wsrep skip_locking logic is restored (i.e. if skip_locking is set
we want flag BTR_NO_LOCKING_FLAG);
b) the original logic of innodb is preserved (i.e. condition for
BTR_NO_ROLLBACK should be evaluated before condition for
BTR_NO_LOCKING_FLAG)

Fixup for commit "Fix for sql_sequence.create innodb test"

---

storage/innobase/handler/ha_innodb.cc
storage/innobase/include/trx0trx.h
storage/innobase/trx/trx0roll.cc
storage/innobase/trx/trx0trx.cc

This patch will fix BF aborting of native threads, e.g. threads which have declared
wsrep_on=OFF.
Earlier, we have used, for innodb trx locks, was_chosen_as_deadlock_victim
flag, for marking inodb transactions, which are victims for wsrep BF abort.
With native threads (wsrep_on==OFF), re-using was_chosen_as_deadlock_victim flag may lead
to inteference with real deadlock, and to deal with this, the patch has added new
flag for marking wsrep BF aborts only: was_chosen_as_wsrep_victim

Fix for MW-286 test

---

mysql-test/suite/galera/r/galera_sst_mysqldump,debug.rdiff
mysql-test/suite/galera/r/galera_sst_mysqldump.result
mysql-test/suite/galera/t/galera_sst_mysqldump.cnf

The test was probably not merged correctly, and a whole section of the .rdiff file was merged in .test file.
Restored the test and recorded it.
Part of fix also is in galera 4.x branch so latest commit should be used.

Fixed galera.galera_sst_mysqldump

---

mysql-test/suite/galera_sr/r/galera_sr_unit_statements.result
mysql-test/suite/galera_sr/t/galera_sr_unit_statements.test
sql/sys_vars.cc
sql/wsrep_var.cc
sql/wsrep_var.h

Enable streaming replication when wsrep_trx_fragment_unit is updated
and wsrep_trx_fragment_size is greater than 0.
Improvements to the test itself
* Expected counts of replicated rows was wrong because of missing
switch to connection node_1.
* Added checks for SR table contents
* Removed unnecessary wait conditions (wsrep_sync_wait is enabled)
* Removed unnecessary --sleep 1

Fixes for MTR test galera_sr.galera_sr_unit_statements

---

mysql-test/suite/galera_sr/t/galera_sr_cc_master.test

Fixed wrong wsrep_cluster_address usage, was still using environment
variable NODE_GALERAPORT_1.

Fix MTR test galera_sr.galera_sr_cc_master

---

sql/wsrep_mysqld.cc
sql/wsrep_utils.cc

When bootstrapping wsrep, we need to set IP address to bind on. If bind-address=* this will fail. Skipping guess from bind-address if it is set to *.

WSREP doesn't handle wildcard bind address

---

storage/innobase/os/os0event.cc

[Buildbot](http://buildbot.askmonty.org/buildbot/grid?category=main&branch=tt-10.2-MDEV-18043-event-data-race)

 MDEV-18043 data race in os_event 

---

debian/autobake-deb.sh

Add check for git command. Check for internet connectivity using bash /dev/tcp interface.

autobake-deb: fixes for AWS SDK build eligibility checks.

---

mysql-test/suite/galera/r/galera_sst_mariabackup_encrypt_with_key.result
sql/wsrep_sst.cc

The address of mysql defaults file (my.snf) was not passed to SST script.
This lead to failures with tests, which need to read SST section from the configuration,
galera.galera_sst_mariabackup_encrypt_with_key is one example of such test failures
The fix is backporting the deafault file address build-up as it is done is 10.3 source code
Also new result file was recorded for galera.galera_sst_mariabackup_encrypt_with_key, the difference
was only "--connection node" lines appearing with debug build test run.

Fix for test galera.galera_sst_mariabackup_encrypt_with_key

---

debian/mariadb-server-10.3.install
man/wsrep_sst_xtrabackup-v2.1
man/wsrep_sst_xtrabackup.1

Packaging is broken for debian-based systems after removing
xtrabackup scripts. This is due to the fact that links to the
scripts are not removed from the installation file
(from the debian/mariadb-server-10.3.install).
Also in this fix some comments have been added to the
documentation, indicating that using xtrabackup[-v2] is
an deprecated, therefore user should use mariabackup instead.
https://jira.mariadb.org/browse/MDEV-18064

MDEV-18064: Packaging is broken for debian-based systems

---

.travis.compiler.sh
.travis.yml

gcc supported releases are 7/8 (https://gcc.gnu.org/) and version 6 is getting bug fixes.
clang 6 is stable, 7 is quantification and 8 is development (hence being in allowed failures)
Wno-unused-command-line-argument was exceptionally common because of the way include paths are added globally to C{,XX}FLAGS so ignore for the time being. There are other warnings more important that should be rectified.

10.4 travis - newer compilers, ignore common clang warnings

---

mysql-test/suite/galera_sr/r/galera_sr_kill_query.result
mysql-test/suite/galera_sr/t/galera_sr_kill_query.test

* Removed have_innodb.inc: test already sources galera_cluster.inc
* Removed big_test.inc: test is quite quick
* Changed wait conditions:
```
--let $wait_condition = SELECT COUNT(*) = 0 FROM t1;
--source include/wait_condition.inc
```
to simple query:
`SELECT COUNT(*) = 0 FROM t1;`
wsrep_sync_wait is enabled, no need for wait_condition
* Updated wsrep-lib to include commit "Check if client was interrupted
before fragment replication"

Fixes for MTR test galera_sr.galera_sr_kill_query

---

sql/sql_class.cc
sql/wsrep_binlog.cc
sql/wsrep_binlog.h
sql/wsrep_mysqld.cc
sql/wsrep_mysqld.h
sql/wsrep_trans_observer.h
sql/wsrep_var.cc

* Move call to enable streaming to wsrep_open(), so that streaming is
attempted only if wsrep_on()
* Move various streaming replication definitions from wsrep_binlog.h
to wsrep_mysqld.h

Enable streaming in wsrep_open()

---

mysql-test/suite/galera_sr/r/mysql-wsrep-features#35.result
mysql-test/suite/galera_sr/t/mysql-wsrep-features#35.test

Test sets sync point sync.wsrep_apply_cb, but was not waiting for it
to be reached. Also, reset debug sync at the end of test, so that no
sync point are left behind after the test finishes.

Make test galera_sr.mysql-wsrep-features#35 deterministic

---

mysql-test/suite/galera_sr/r/mysql-wsrep#215.result
mysql-test/suite/galera_sr/t/mysql-wsrep#215.test
sql/wsrep_client_service.cc

* Improvements to test mysql-wsrep#215: removed sleep in favor of
appropriate wait condition and fixed usage of debug sync points.
* Check for NULL cache in
Wsrep_client_service::prepare_fragment_for_replication

Fix MTR test galera_sr.mysql-wsrep#215

---

.travis.yml

rocksdb used zstd so lets install it for the osx test.

MDEV-15578 - travis: add zstd for osx

---

mysql-test/suite/wsrep/r/wsrep-recover,binlogon.rdiff
mysql-test/suite/wsrep/r/wsrep-recover.result
mysql-test/suite/wsrep/t/wsrep-recover-step.inc
mysql-test/suite/wsrep/t/wsrep-recover.cnf
mysql-test/suite/wsrep/t/wsrep-recover.combinations
mysql-test/suite/wsrep/t/wsrep-recover.test
sql/handler.cc
sql/sql_class.cc
sql/wsrep_trans_observer.h
sql/wsrep_xid.cc
sql/wsrep_xid.h
storage/innobase/handler/ha_innodb.cc
storage/innobase/trx/trx0trx.cc

This pull request contains fixes required to make wsrep XID persisted properly in InnoDB rollback segment header. A test wsrep.wsrep-recovery was added to check that the XID is persisted properly and will be recovered properly after a crash.

Fixes to wsrep XID durability

---

mysql-test/suite/innodb/r/innodb-virtual-columns.result
mysql-test/suite/innodb/t/innodb-virtual-columns.test
storage/innobase/handler/ha_innodb.cc
storage/xtradb/handler/ha_innodb.cc

There was an incorrect check for MariaDB and InnoDB
tables fields count. Corruption was reported when there was no corruption.
Also, a warning message had incorrect field numbers for both MariaDB and InnoDB
tables.
ha_innobase::open(): fixed check and message
[Buildbot](http://buildbot.askmonty.org/buildbot/grid?category=main&branch=tt-10.0-MDEV-16499-virtual-innodb)

MDEV-16499 [10.1] ER_NO_SUCH_TABLE_IN_ENGINE followed by "Please drop the table and recreate" upon adding FULLTEXT key to table with virtual column

---

mysql-test/suite/galera/disabled.def
mysql-test/suite/galera/r/galera_gtid_slave_sst_rsync.result
mysql-test/suite/galera/t/galera_gtid_slave_sst_rsync.test

If galera.galera_gtid_slave_sst_rsync is repeated more than once it will fail due incorrect GTID position. After stopping SLAVE node reset also GTID_SLAVE_POS variable.

MDEV-18176 Galera test failure on galera.galera_gtid_slave_sst_rsync

---

storage/innobase/os/os0proc.cc
storage/xtradb/os/os0proc.cc

Poisoning memory after munmap() and friends is totally incorrect as this memory
could be anything.
os_mem_free_large(): remove memory poisoning
[Buildbot](http://buildbot.askmonty.org/buildbot/grid?category=main&branch=tt-10.0-MDEV-18243-incorrect-asan)

MDEV-18243 incorrect ASAN instrumentation

---

storage/innobase/include/buf0buf.h
storage/innobase/include/dict0mem.h
storage/innobase/include/fil0fil.h
storage/xtradb/include/buf0buf.h
storage/xtradb/include/dict0mem.h
storage/xtradb/include/fil0fil.h

When performing a hash search via HASH_SEARCH we first look at a key of a node
and then at its pointer to the next node in chain. If we have those in one cache
line instead of a two we reduce memory reads.
I found dict_table_t, fil_space_t and buf_page_t suitable for such improvement.
[Buildbot](http://buildbot.askmonty.org/buildbot/grid?category=main&branch=tt-10.0-MDEV-18233-hash-cache)

MDEV-18233 Moving the hash_node_t to improve locality of reference

---

sql/wsrep_schema.cc

Wsrep_schema::replay_transaction attempted to open table with
hardcoded name "SR", recently renamed "streaming_log".
Fixes failure in galera_sr.galera_sr_transaction_replay.

Fix hardcoded streaming log table name

---

mysql-test/suite/galera_sr/t/GCF-1051.test

Test GCF-1051 was using wrong table name for streaming log table,
renamed to mysql.wsrep_streaming_log.

Fixup galera_sr.GCF-1051 after streaming log table renaming

---

mysql-test/suite/galera/disabled.def
mysql-test/suite/galera/r/galera_autoinc_sst_mariabackup.result
mysql-test/suite/galera/t/galera_autoinc_sst_mariabackup.cnf
mysql-test/suite/galera/t/galera_autoinc_sst_mariabackup.test
sql/wsrep_server_service.cc
sql/wsrep_server_service.h
sql/wsrep_sst.cc
storage/innobase/trx/trx0rseg.cc

Wsrep lib was changed so that the sst_received() does not take GTID as argument, but rather fetches it via server_service interface after the storage has been initialized. The corresponding changes were made to Wsrep_server_service. This guarantees that the provider gets the correct start position after the storage engine recovery.
Wsrep_server_service::log_view() and trx_rseg_update_wsrep_checkpoint() were fixed to properly deal with group UUID change.
The test galera_autoinc_sst_mariabackup was fixed to work with gcache.size=10M configuration setting and recorded.

MDEV-18177 Fixed SST processing on joiner

---

mysys/safemalloc.c

Not sure why this was added (94d722b6a43b86ee760f07915921cf58f9869a5d) however flushes normally happen after fprintf. Thought stderr was unbuffered so it wasn't needed. I assuming its to flush it out before a slow backtrace.

MDEV-16296 - safemalloc: warn, flush after fprintf

---

mysys/safemalloc.c

Fix from https://github.com/MariaDB/server/pull/761#issuecomment-392742007 thanks @svoj 

safemalloc: put bad_ptr error arguments in right order

---

mysql-test/suite/galera_3nodes/r/galera_safe_to_bootstrap.result
mysql-test/suite/galera_3nodes/t/galera_safe_to_bootstrap.test
sql/mysqld.cc
sql/wsrep_server_state.cc

Made sure that the wsrep server state instance is always deleted at server shutdown if it has been allocated during server startup.
Fixed galera_safe_to_bootstrap to restore autoinc offsets after the test and recorded. The test does not report memory leaks anymore.

Fix memleak after exit on cluster connect failure, fix galera_safe_to_bootstrap

---

storage/innobase/handler/ha_innodb.cc
storage/innobase/lock/lock0lock.cc

pushed the decision for innodb tranaction and system locking down to lock_trx_handle_wait()
level. With this, we can avoid releasing these mutexes for executions where these mutexes
were acquired upfront.
There remained old use of trx->lock.was_chosen_as_wsrep_victim in wsrep_innobase_kill_one_trx()
which is now removed as obsolete.

Fixes according to email:  Remainig items from all reviews

---

mysql-test/suite/galera/t/galera_gcache_recover_full_gcache.test

The test failed because of error during write set replication
which was due to cluster configuration change. Worked around the
error by waiting the configuration change to happen before running
insert statements.

Fixed galera_gcache_recover_full_gcache commit error

---

sql/mysqld.cc

We need to call wsrep_init_globals() before wsrep_init_startup() for SST methods which are not required to execute before initialization of storage engine.

Changed ordering of WSREP init

---

plugin/wsrep_info/mysql-test/wsrep_info/my.cnf

In the config file, options `wsrep-on` and `wsrep-cluster-address`
must be listed under each specific [mysqld.x] section.
Otherwise `mysql-test-run.pl` does not identify that the test has
wsrep-on, and when starting servers, it won't wait for the servers
to be ready.

Fix MTR test wsrep_info.plugin

---

mysql-test/suite/galera_sr/r/galera_sr_cc_slave.result
mysql-test/suite/galera_sr/t/galera_sr_cc_slave.test
sql/wsrep_high_priority_service.cc
sql/wsrep_mysqld.cc
sql/wsrep_mysqld.h
sql/wsrep_schema.cc
sql/wsrep_schema.h
sql/wsrep_server_service.cc
sql/wsrep_server_service.h

This pull request concerns the recovery of streaming appliers which are required to apply fragments received from the group. Without this patch the streaming appliers are not restored in all cases when the server leaves and joins the cluster, which may cause inconsistencies if streaming replication is used.
The only change outside streaming replication context is a change to wsrep_schema object deallocation, which is now done when the server exits.

Fixes for streaming applier recovery

---

scripts/wsrep_sst_mysqldump.sh

If LOG_BIN is enabled on joiner side, we will execute two additional commands:
1. RESET MASTER
2. SET @@global.gtid_binlog_state='$GTID_BINLOG_STATE'
Command will fail if global.wsrep_on=ON. So we need to temporary disable it.

Fixed wsrep_sst_mysqldump script when executing while wsrep_on=ON

---

mysql-test/suite/galera_3nodes/r/galera_ipv6_mariabackup.result
mysql-test/suite/galera_3nodes/r/galera_ipv6_mysqldump.result
mysql-test/suite/galera_3nodes/t/galera_ipv6_mariabackup.cnf
mysql-test/suite/galera_3nodes/t/galera_ipv6_mariabackup.test
mysql-test/suite/galera_3nodes/t/galera_ipv6_mysqldump.test

Fixed tests which started failing after merge from 10.3.
Asserts in galera_ipv6_mariabackup needed to be changed to match Galera 4 behavior. In Galera 4 the IST happens on every cluster configuration change to populate certification index and replay configuration change history on joiner. Also made galera_ipv6_mariabackup more deterministic in donor selection.
Removed extra connection to node_3 from galera_ipv6_mysqldump which was likely a merge error.
Wsrep-lib was updated to be more allowing for compiler warnings by default, -Werror is now enabled only if WSREP_LIB_MAINTAINER_MODE is explicitly passed in cmake options.

Fix for galera_3nodes galera_ipv6_mysqldump and galera_ipv6_mariabackup

---

mysql-test/suite/galera/disabled.def
mysql-test/suite/galera/r/galera_gcache_recover_manytrx.result
mysql-test/suite/wsrep/r/wsrep-recover-v25,binlogon.rdiff
mysql-test/suite/wsrep/r/wsrep-recover-v25.result
mysql-test/suite/wsrep/t/wsrep-recover-step.inc
mysql-test/suite/wsrep/t/wsrep-recover-v25.cnf
mysql-test/suite/wsrep/t/wsrep-recover-v25.combinations
mysql-test/suite/wsrep/t/wsrep-recover-v25.test
sql/handler.cc
sql/wsrep_xid.cc
sql/wsrep_xid.h
storage/innobase/handler/ha_innodb.cc

Backported fixes to wsrep recovery from 10.4. Reworked and renamed the test wsrep-recover to wsrep-recover-v25 to match wsrep API 25 behavior and to avoid merge issues with 10.4 later on.
Enabled and recorded galera_gcache_recover_manytrx.
When merging these changes back to 10.4, the test wsrep-recover-v25 needs to be recorded again since the seqnos generated by Galera 4 will be slightly different.

MDEV-15740 Fixes to Galera transaction recovery

---

mysys/my_fopen.c

According to close(2) "Retrying the close() after a failure return is
the wrong thing to do"
Corrects 5c81cb880a054f34803e2821489533274ebf6c4e in MDEV-15635

my_fclose: Don't retry on close

---

mysql-test/include/galera_resume.inc
mysql-test/include/galera_suspend.inc
mysql-test/include/mtr_check.sql
mysql-test/suite/galera_3nodes/r/galera_evs_suspect_timeout.result
mysql-test/suite/galera_3nodes/r/galera_garbd.result
mysql-test/suite/galera_3nodes/r/galera_ist_gcache_rollover.result
mysql-test/suite/galera_3nodes/r/galera_safe_to_bootstrap.result
mysql-test/suite/galera_3nodes/r/galera_var_dirty_reads2.result
mysql-test/suite/galera_3nodes/t/galera_evs_suspect_timeout.test
mysql-test/suite/galera_3nodes/t/galera_garbd.test
mysql-test/suite/galera_3nodes/t/galera_ist_gcache_rollover.cnf
mysql-test/suite/galera_3nodes/t/galera_ist_gcache_rollover.test
mysql-test/suite/galera_3nodes/t/galera_safe_to_bootstrap.test
mysql-test/suite/galera_3nodes/t/galera_var_dirty_reads2.test

Most of the mtr tests in the galera_3nodes suite fail
for a variety of reasons with a variety of errors.
Some tests simply need to add the missing "connection"
lines to the result files, but many of them fail due
to substantial errors that require reworking test files.
This patch adds the missing "connection" lines to
the result files and fixes several substantial flaws
in the galera_3nodes suite tests and in the mtr framework
service files, adapting the tests from galera_3nodes
for the current version of MariaDB.
https://jira.mariadb.org/browse/MDEV-18426

MDEV-18426: Most of the mtr tests in the galera_3nodes suite fail

---

mysql-test/suite/galera/t/galera_sst_mysqldump.cnf

Test galera_sst_mysqldump could fail occasionally due certification failure. Enforcing stricter causality checks by removing wsrep_sync_wait=0 from test configuration.

Fix for failures on galera.galera_sst_mysqldump

---

sql/wsrep_mysqld.cc

The if/else was a remnant from error voting code which was not
included in the release.

Fixed use of uninitialized value in wsrep_TOI_end()

---

mysql-test/suite/galera/disabled.def
mysql-test/suite/galera/r/galera_gcache_recover_manytrx.result
mysql-test/suite/galera/r/galera_sst_rsync2.result
mysql-test/suite/galera_3nodes/r/galera_evs_suspect_timeout.result
mysql-test/suite/galera_3nodes/t/galera_evs_suspect_timeout.test
scripts/wsrep_sst_mariabackup.sh
scripts/wsrep_sst_rsync.sh
sql/wsrep_sst.cc

* Donor node will now provide log-bin-index argument to wsrep_sst_rsync script
* Write correct path and log-bin file names into joiner log-bin-index file
* Extend archive timestamp in mariabackup script
* Re-recorded: galera.galera_gcache_recover_manytrx
* Fixed: galera_3nodes.galera_evs_suspect_timeout

MDEV-18178, mariabackup script timestamp change, galera suite fixed & re-recorded tests

---

cmake/submodules.cmake
cmake/wsrep.cmake

@janlindstrom, I suspect my PR yesterday was a result of not having `cmake.update-submodules` set (and not seeing the recursive submodule). This PR (and #1181) makes it more clear to the user (though these could be cleaned up a bit more once both are merged to the 10.4 branch).
Changed the  cmake/submodules.cmake message as this is the first time that we have recursive modules.
Without this commit the error message is:
$ cmake . -DWITH_WSREP=ON
-- Running cmake version 3.12.1
-- MariaDB 10.4.3
CMake Error at cmake/wsrep.cmake:36 (FILE):
FILE STRINGS file
".../mariadb-server-10.4/wsrep-lib/wsrep-API/v26/wsrep_api.h"
cannot be read.
Call Stack (most recent call first):
CMakeLists.txt:147 (INCLUDE)
Having 'git config cmake.update-submodules yes' nicely updates the
build without error.
$ …

cmake-wsrep: friendly error message about missing wsrep_api.h

---

mysql-test/suite/galera_sr/r/galera_sr_load_data.result
mysql-test/suite/galera_sr/r/galera_sr_load_data_splitting.result
mysql-test/suite/galera_sr/t/galera_sr_load_data.test
sql/sql_load.cc
sql/wsrep_mysqld.cc
sql/wsrep_mysqld.h

This patch makes wsrep_load_data_splitting to turn streaming replication on internally for the duration of load data. The SR parameters are chosen to match the original load data splitting behavior.
As a result, the load data splitting is now atomic, i.e. either all rows are committed or none.

10.4 make wsrep_load_data_splitting use streaming replication

---

mysys/my_open.c

According to close(2) "Retrying the close() after a failure return is
the wrong thing to do"

my_close: Don't retry on close

---

sql/sql_parse.cc
sql/wsrep_server_service.cc

This pull request consists of two fixes:
* The assertion reported in MDEV-18480 was fixed by skipping setting wsrep SE checkpoint if the provider didn't assign unique sequence number for a view event.
* The assertion reported in MDEV-18571 was due to missing calls to wsrep_after_statement() if the PS protocol was in use.

MDEV-18480, MDEV-18571 Rolling Galera upgrade from 10.3 to 10.4

---

sql/wsrep_sst.cc

When node is JOINER and bin-log is enabled but bin-log-index is not set in configuration, we would use NULL pointer which causes segfault. 
Fixed by checking for NULL pointer before using variable.

MDEV-18588 Galera: Rolling upgrade: segfault during node1 upgrade withh log-bin and log-slave-updates enabled

---

mysql-test/suite/galera_sr/r/MDEV-18585.result
mysql-test/suite/galera_sr/r/mysql-wsrep-features#136.result
mysql-test/suite/galera_sr/t/MDEV-18585.cnf
mysql-test/suite/galera_sr/t/MDEV-18585.test
sql/handler.cc
sql/wsrep_client_service.cc
sql/wsrep_trans_observer.h

Make sure that the Annotate_rows_log_events is written into
binlog only for the first fragment of the current statement.
Also avoid flusing pending rows event when calculating bytes
generated by the transaction.
Added and recorded a test which verifies that the binlog
contains only one Annotate_rows_log_event per statement
with various SR settings. Recrded mysql-wsrep-features#136
which produced different output with excession log events
suppressed.

MDEV-18585 Avoid excessive Annotate_rows_log_events in binlog

---

mysql-test/suite/galera_sr/r/galera_sr_create_drop.result
mysql-test/suite/galera_sr/t/galera_sr_create_drop.test
sql/sql_class.cc

The check for streaming replication logging format in
THD::decide_logging_format() did the check also for DDLs running
in TOI mode. This caused DROP DATABASE to fail if streaming
replication was enabled.
Added check for THD wsrep execution mode and perform the check
only if the THD is in local processing mode (i.e. not TOI).
Added galera_sr_create_drop test to verify that CREATE/DROP
statements pass even if streaming replication is on.

MDEV-18587 Don't reject DDLs if streaming replication is on

---

sql/wsrep_client_service.cc
sql/wsrep_high_priority_service.cc

The replayer did not signal replaying waiters. Added
mysql_cond_broadcast() after replaying is over.
Assertion on client error failed after replay attempt failed due
to certification failure. At this point the transaction does not
go through client state, so the client error cannot be overridden.
Assign ER_LOCK_DEADLOCK to thd directly instead.
Use timed cond wait when waiting for replayers to finish and
check if the transaction has been BF aborted during the wait.
This PR should also fix failure in galera_last_committed_id test when running test in repeat of after some other tests.

Fixed replaying bugs found with multimaster load

---

mysql-test/include/mtr_check.sql
mysql-test/suite/galera_3nodes/galera_2x3nodes.cnf
mysql-test/suite/galera_3nodes/galera_3nodes.cnf
mysql-test/suite/galera_3nodes/include/have_mariabackup.inc
mysql-test/suite/galera_3nodes/r/galera_garbd.result
mysql-test/suite/galera_3nodes/r/galera_pc_weight.result
mysql-test/suite/galera_3nodes/r/galera_var_dirty_reads2.result
mysql-test/suite/galera_3nodes/suite.pm
mysql-test/suite/galera_3nodes/t/galera_garbd.test
mysql-test/suite/galera_3nodes/t/galera_innobackupex_backup.test
mysql-test/suite/galera_3nodes/t/galera_ipv6_mariabackup.test
mysql-test/suite/galera_3nodes/t/galera_var_dirty_reads2.test
scripts/wsrep_sst_mariabackup.sh
scripts/wsrep_sst_rsync.sh

Current version of Galera does not support the wsrep_cluster_weight
status variable, which causes the galera_pc_weight test (from the
galera_3nodes suite) to fail.
This patch adds the missing variable to the wsrep status variables.
This patch also contains improvements for other tests, which taken
from the 10.2 branch. This changes synchronize the 10.3 branch with
the latest version of the previous MDEV-18426 fixes, which are also
related to the galera_3nodes suite (which originally were made for
the 10.2 branch, and has not yet been transferred to 10.3).
https://jira.mariadb.org/browse/MDEV-18515

MDEV-18515: The wsrep_cluster_weight status variable is not supported

---

mysql-test/suite/galera_sr/r/mysql-wsrep-features#165.result
mysql-test/suite/galera_sr/t/mysql-wsrep-features#165.inc
sql/service_wsrep.cc
sql/wsrep_client_service.cc
sql/wsrep_client_service.h
storage/innobase/lock/lock0lock.cc

This PR consists of two commits
* The first one adds missing call to `wsrep_handle_SR_rollback()` in InnoDB `DeadlockChecker::check_and_resolve()`. After this addition the test `mysql-wsrep-features#165` started to pass. Fixed the test to be deterministic and recorded.
* Cleaned up `Wsrep_client_service::interrupted()` call. With updated wsrep-lib the library part handles the wsrep transaction state checks and guarantees that the method will be called with LOCK_wsrep_thd locked.

Fixes to streaming replication BF aborts and rollbacks

---

mysql-test/suite/galera_sr/disabled.def
mysql-test/suite/galera_sr/r/galera_sr_rollback_statement.result
mysql-test/suite/galera_sr/t/galera_sr_rollback_statement.test
mysql-test/suite/galera_sr/t/mysql-wsrep#215.test

Disabled GCF-437 which relies on InnoDB redo log size limitation
which does not seem to exist or is increased in MariaDB 10.4.
Require debug sync for mysql-wsrep#215.

Fixed and recorded galera_sr.galera_sr_rollback_statement

---

mysql-test/suite/galera_3nodes/galera_2x3nodes.cnf
mysql-test/suite/galera_sr/r/mdev_18631.result
mysql-test/suite/galera_sr/t/galera_sr_mysqldump_sst.test
mysql-test/suite/galera_sr/t/mdev_18631.cnf
mysql-test/suite/galera_sr/t/mdev_18631.test
sql/handler.cc
sql/log.cc
sql/wsrep_high_priority_service.cc
sql/wsrep_high_priority_service.h
sql/wsrep_storage_service.cc
sql/wsrep_trans_observer.h

This PR reorganizes wsrep commit processing. Now commit hooks are entered from ha_commit_trans(), prepare_or_error() and write_transaction_to_binlog_events() in all wsrep execution modes (local, applying, replaying, storage access).
Additional commit includes stability improvement for galera_3nodes.galera_gtid_2_cluster test and fixes galera_sr.galera_sr_mysqldump_sst test.

MDEV-18631 Fixed streaming replication with wsrep_gtid_mode=ON

---

mysql-test/suite/galera_3nodes_sr/r/galera_sr_threeway_split_no_primary.result
mysql-test/suite/galera_3nodes_sr/t/galera_sr_threeway_split_no_primary.test
mysql-test/suite/galera_sr/r/galera_sr_cc_no_primary.result
mysql-test/suite/galera_sr/t/galera_sr_cc_no_primary.test

Added a couple of MTR tests which check that streaming transactions
get rolled back when their owners leave the primary component.
Specifically, the tests cover a case in which the cluster moves
between two primary views which have the same membership. This case is
currently not handled properly, the new version of the `wsrep-lib`
submodule addresses that.

MTR tests for clearing orphaned SR transactions in Galera

---

.travis.compiler.sh
.travis.yml

Fix travis galera tests on 10.4 branch by using galera-4 rather than 3.
success: https://travis-ci.org/grooverdan/mariadb-server/jobs/506052887 (in lieu of waiting)

travis: use galera-4 in 10.4 branch

---

mysql-test/suite/galera_sr/r/galera_sr_kill_all_norecovery.result
mysql-test/suite/galera_sr/t/galera_sr_kill_all_norecovery.test

* Disable `wsrep_sync_wait` before killing galera node which may be
non-primary (kill_galera.inc causes lock wait timeouts  due to
wsrep_sync_wait)
* Remove unnecessary `--sleep 1`
* Replace ```SELECT COUNT(*) = 0 ...``` with
```SELECT COUNT(*) `expect 0` ...```

MDEV-18666 Fix MTR test galera_sr_kill_all_norecovery

---

include/mysql/service_wsrep.h
mysql-test/suite/galera_3nodes/r/galera_load_data_ist.result
mysql-test/suite/galera_3nodes/t/galera_load_data_ist.cnf
mysql-test/suite/galera_3nodes/t/galera_load_data_ist.test
sql/log.cc
sql/sql_class.cc
sql/sql_class.h
sql/sql_load.cc
sql/sql_plugin_services.ic
sql/wsrep_dummy.cc
sql/wsrep_hton.cc
sql/wsrep_thd.cc
storage/innobase/handler/ha_innodb.cc

This patch contains a fix for the MDEV-17262/17243 issues and
new mtr test.
These issues (MDEV-17262/17243) have two reasons:
1) After an intermediate commit, a transaction loses its status
of "transaction that registered in the MySQL for 2pc coordinator"
(in the InnoDB) due to the fact that since version 10.2 the
write_row() function (which located in the ha_innodb.cc) does
not call trx_register_for_2pc(m_prebuilt->trx) during the processing
of split transactions. It is necessary to restore this call inside
the write_row() when an intermediate commit was made (for a split
transaction).
Similarly, we need to set the flag of the started transaction
(m_prebuilt->sql_stat_start) after intermediate commit.
The table->file->extra(HA_EXTRA_FAKE_START_STMT) called from the …

MDEV-17262: mysql crashed on galera while node rejoined cluster

---

storage/innobase/buf/buf0buf.cc
storage/innobase/include/ut0new.h

Fixed a bug I added in MDEV-10814 where a missing argument cased a later optional argument, true to be treated as the size.
While the first commit is the the minimal required fix, and the second commit cleans up the API so its harder to make the same mistake.
Mega culpa.

MDEV-18946: innodb: fix deallocation on innodb pages - during shutdown and resizing innodb_buffer_pool_size

---

mysql-test/suite/galera_sr/r/GCF-1018.result
mysql-test/suite/galera_sr/t/GCF-1018.test

Disabled autocommit retry (set wsrep_retry_autocommit to 0) so that BF
aborted autocommit statement always results in ER_LOCK_DEADLOCK.

Make test galera_sr.GCF-1018 deterministic

---

storage/mroonga/vendor/groonga/vendor/plugins/CMakeLists.txt

This error occurred when the path to the project contained regular expression characters.

Fix error failed to compile regex

---

storage/perfschema/pfs_events.h
storage/perfschema/pfs_events_waits.h

before:
(gdb) p sizeof(PFS_events_waits)
$1 = 184
after:
(gdb) p sizeof(PFS_events_waits)
$1 = 160
no functional changes
[Buildbot](http://buildbot.askmonty.org/buildbot/grid?category=main&branch=tt-10.1-MDEV-19172-pfs-member-reordering)

MDEV-19172 Reorder fields in PFS_events and PFS_events_waits to speed up memcpy()

---

mysql-test/suite/galera/r/galera_sp_bf_abort.result
mysql-test/suite/galera/r/galera_sp_insert_parallel.result
mysql-test/suite/galera/t/galera_sp_insert_parallel.test
sql/sp_head.cc
sql/sql_class.cc
sql/wsrep_client_service.cc
sql/wsrep_high_priority_service.cc
sql/wsrep_high_priority_service.h
sql/wsrep_trans_observer.h

- Changed replaying to always allocate a separate THD object
for applying log events. This is to avoid tampering original
THD state during replay process.
- Return success from sp_instr_stmt::exec_core() if replaying
succeeds.
- Do not push warnings/errors into diagnostics area if the
transaction must be replayed. This is to avoid reporting
transient errors to the client.
Added two tests galera_sp_bf_abort, galera_sp_insert_parallel.
Wsrep-lib position updated.

10.4: Fixed wsrep replaying for stored procedures

---

storage/innobase/ut/ut0timer.cc
storage/perfschema/pfs_timer.cc
storage/perfschema/pfs_timer.h
storage/perfschema/table_performance_timers.cc
storage/xtradb/ut/ut0timer.cc

[Buildbot](http://buildbot.askmonty.org/buildbot/grid?category=main&branch=tt-10.1-MDEV-19399-slow-times)

MDEV-19399 do not call slow my_timer_init() several times

---

mysql-test/suite/versioning/r/create.result
mysql-test/suite/versioning/t/create.test
sql/handler.cc
sql/table.cc

Disallow DATETIME for SYSTEM VERSIONING tables.
[Buildbot](http://buildbot.askmonty.org/buildbot/grid?category=main&branch=tt-10.3-MDEV-18512-versioning-datetime)

MDEV-18512 using DATETIME(6) as row_start/row_end crashes server

---

mysql-test/suite/innodb/r/instant_alter_charset.result
mysql-test/suite/innodb/t/instant_alter_charset.test
sql/sql_table.cc

innodb.instant_alter_charset: remove some garbage
Field_string::is_equal(): refactor and make this function strictier
supports_such_enlargement(): put non-obvious logic in a separate function
Field_varstring::is_equal(): fix crash with refactoring
and reordering of conditions
[Buildbot](http://buildbot.askmonty.org/buildbot/grid?category=main&branch=tt-10.4-MDEV-19524-is_equal-crash)

MDEV-19524 Server crashes in Bitmap<64u>::is_clear_all / Field_longstr::csinfo_change_allows_instant_alter

---

sql/slave.cc
storage/spider/mysql-test/spider/bugfix/include/slave_transaction_retry_errors_5digit_deinit.inc
storage/spider/mysql-test/spider/bugfix/include/slave_transaction_retry_errors_5digit_init.inc
storage/spider/mysql-test/spider/bugfix/r/slave_transaction_retry_errors_5digit.result
storage/spider/mysql-test/spider/bugfix/t/slave_transaction_retry_errors_5digit.cnf
storage/spider/mysql-test/spider/bugfix/t/slave_transaction_retry_errors_5digit.test

error code 12701 is already included in default value, but other plugin specific error codes are ignored because of checking with ER_ERROR_LAST. ER_ERROR_LAST does not include plugin specific error codes. So I just removed it for fixing this issue.

MDEV-17402 slave_transaction_retry_errors="12701" won't be enabled

---

mysql-test/t/repair_symlink-5543.test

On mips,  ELOOP is 90, instead of 40 or 20.
So we need to replace_regex 90 to 20, too.

MDEV-19883 [MIPS] repair_symlink-5543 fails: ELOOP is 90

---

mysql-test/suite/galera/r/galera_change_user.result
mysql-test/suite/galera/t/galera_change_user.test
sql/sql_parse.cc

COM_CHANGE_USER and COM_RESET_CONNECTION commands cause
THD::cleanup() to be called in the middle of command handling.
This causes wsrep client_state sanity checks to fail.
As a fix, temporarily close wsrep client_state before THD::change_user()
is called when handling COM_CHANGE_USER and COM_RESET_CONNECTION,
and restore the state after THD::change_user() returns.
This commit also updates wsrep-lib to version which removes
exception usage in wsrep client_state sanity checks.

Wsrep crash caused by COM_CHANGE_USER, COM_RESET_CONNECTION

---

storage/spider/ha_spider.cc
storage/spider/spd_conn.cc
storage/spider/spd_copy_tables.cc
storage/spider/spd_db_conn.cc
storage/spider/spd_db_handlersocket.cc
storage/spider/spd_db_mysql.cc
storage/spider/spd_db_oracle.cc
storage/spider/spd_direct_sql.cc
storage/spider/spd_group_by_handler.cc
storage/spider/spd_ping_table.cc
storage/spider/spd_table.cc
storage/spider/spd_trx.cc

This is an issue of memory alignment of variable argument when calling my_multi_malloc().
The fix is strictly casting allocating size to "uint".

MDEV-18737 Spider "Out of memory" on armv7hl

---

mysql-test/suite/galera/r/galera_performance_schema.result
sql/service_wsrep.cc
sql/sql_connect.cc
sql/threadpool_common.cc
sql/wsrep_client_service.cc
sql/wsrep_high_priority_service.cc
sql/wsrep_mysqld.cc
sql/wsrep_schema.cc
sql/wsrep_server_service.cc
sql/wsrep_server_service.h
sql/wsrep_sst.cc
sql/wsrep_storage_service.cc
sql/wsrep_thd.cc
sql/wsrep_thd.h
sql/wsrep_trans_observer.h
sql/wsrep_utils.cc

MariaDB 10.4 was crashing when thread-handling was set to
pool-of-threads and wsrep was enabled.
There were two apparent reasons for the crash:
- Connection handling in threadpool_common.cc was missing calls to
control wsrep client state.
- Thread specific storage which contains thread variables (THR_KEY_mysys)
was not handled appropriately by wsrep patch when pool-of-threads
was configured.
This patch addresses the above issues in the following way:
- Wsrep client state handling was added to pool-of-threads implementation.
- Thread local storage handling in wsrep patch was reworked by introducing
set of wsrep_xxx_threadvars() calls which replace calls to
THD store_globals()/reset_globals() and deal with thread handling
specifics internally.
Wsrep-lib was updated to version which relaxes …

MDEV-19826 10.4 seems to crash with "pool-of-threads"

---

mysql-test/main/brackets.result
mysql-test/main/except.result
mysql-test/main/except.test
mysql-test/main/except_all.result
mysql-test/main/except_all.test
mysql-test/main/intersect.test
mysql-test/main/intersect_all.result
mysql-test/main/intersect_all.test
mysql-test/main/set_operation.result
mysql-test/main/set_operation.test
mysql-test/main/set_operation_oracle.result
mysql-test/main/set_operation_oracle.test
sql/sql_class.h
sql/sql_lex.cc
sql/sql_lex.h
sql/sql_tvc.cc
sql/sql_union.cc
sql/sql_yacc.yy
storage/heap/hp_write.c

This patch contains the code developed within my project for GSoC2019.
The code includes an implementation of the set operations INTERSECT ALL and EXCEPT ALL still not supported in MariaDB.
This patch supports execution of query expressions containing any combinations all set operation, while the current MariaDB code can execute only query expressions containing DISTINCT set operations and UNION ALL. 
The main idea of execution query expression containing INTERSECT ALL and/or EXCEPT ALL is to store the results of squashing each group of duplicate rows in the temporary table used for the execution. When duplicate rows are squashed they are replaced with one replica supplied by the number of squashed duplicates stored in an additional hidden field of the temporary table. After the last …

MDEV-18844 Implement EXCEPT ALL and INTERSECT ALL operations

---

mysql-test/suite/galera/r/galera_bf_abort_at_after_statement.result
mysql-test/suite/galera/t/galera_bf_abort_at_after_statement.test
sql/sql_parse.cc
sql/wsrep_high_priority_service.cc

- Fixes a situation in which a thread gets BF aborted and does not send the reply back to
the client, even though the connection is still alive. That caused
both sides to hang waiting for the next message. Now we explicitly
check that the connection is still alive when deciding whether to reply.
- MTR test for the above.
- Replaced thd->killed assignments to thd->reset_kill_query where applicable.

MDEV-20172: Fix for thread and client getting stuck after a BF ABORT

---

debian/mariadb-server-10.1.postinst

Fixes bug introduced in commit https://github.com/MariaDB/server/commit/541500295abdba7fa619065069291ac9c1dd6e83.
Using script run-time filename does not always work. One cannot assume
that the filename is always the same as there might be temporary file
names used by dpkg in certain situations. See Debian #920415.
The same fix has been successfully in use in Debian official packages
since February 2019:
https://salsa.debian.org/mariadb-team/mariadb-10.3/commit/6440c0d6e75

MDEV-19694 - Deb: Implement proper version detection in maintainer scripts

---

support-files/mariadb.service.in
support-files/mariadb@.service.in
support-files/use_galera_new_cluster.conf

Include comment header that describes overrides.
Unit description now includes @VERSION@.
After=syslog.target removed - redunant
Add --basedir=@prefix to prevent /root/.my.cnf lookups
Additional changes to multi instance (support-files/mariadb@.service.in):
* added @SYSTEMD_EXECSTARTPRE@ / @SYSTEMD_EXECSTARTPOST@
* removed mariadb@bootstrap reference as galera_new_cluster as
its a little too proment.
* use_galera_new_cluster.conf updated to override pre/post steps

MDEV-12646: systemd service file changes from Fedora

---

cmake/readline.cmake

libedit changed it's interface a while ago. MariaDB's cmake file doesn't
recognize the new interface, the compile test fails:
/mariadb-10.2.19/CMakeFiles/CMakeTmp/src.cxx: In function 'int main(int, char**)':
/mariadb-10.2.19/CMakeFiles/CMakeTmp/src.cxx:6:47: error: invalid conversion from 'char*' to 'int' [-fpermissive]
int res= (*rl_completion_entry_function)(0,0);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
Fix this by adding a detection for the new interface as well.
In client/mysql.cc the ifdefs for the new readline interface are
extended to also check for the new libedit interface. They work the same
way.
Run-tested on a MIPS machine.
Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>

MDEV-19206: cmake: support new libedit interface

---

mysql-test/suite/galera/r/MDEV-20225.result
mysql-test/suite/galera/t/MDEV-20225.test
mysql-test/suite/galera/t/galera_sp_bf_abort.inc
mysql-test/suite/galera/t/galera_sp_bf_abort.test
sql/sp_head.cc
sql/sql_trigger.cc
sql/wsrep_mysqld.cc

When stored procedure execution was chosen as victim for a BF abort, the old implementation called for rollback immediately
when execution was inside SP instruction. Technically this happened in wsrep_after_statement() call, which identified the
need for a rollback.
The problem was that MariaDB does not accept rollback (nor commit) inside sub statement, there are several asserts about it,
checking for THD::in_sub_stmt.
This patch contains a fix, which skips calling wsrep_after_statement() for SP execution, which is marked as BF must abort. Instead,
we return error code to upper level, where rollback will eventually happen, outside of SP execution.
Also, appending the affected trigger table (dropped or created) in the populated key set for the write set,
which prevents parallel applying of …

MDEV-20225 BF aborting SP execution

---

include/my_global.h
sql/sql_cache.cc
storage/innobase/include/ut0new.h

This maps to the way Linux does it in MDEV-10814 except FreeBSD uses different constants.
Tested on FreeBSD-12.0 (x86_64)
Selected 10.3 as a target because that's when MDEV-10814 was added and because the concept is proved and the patch being FreeBSD has different constants.

MDEV-20684: innodb: use madvise CORE/NOCORE on FreeBSD for selective large allocations

---

client/mysql.cc

Fix for [MDEV-20767](https://jira.mariadb.org/browse/MDEV-20767) which causes broken builds on OSX with 10.4.8. This change is a copy/paste from 10.5, there was no specific commit could find in the 10.4 or 10.5 git history for this change but it showed up in the merge commit of https://github.com/MariaDB/server/commit/edef6a007428599fd249815f1dc59a02428090f4
I have previously signed the MCA.

MDEV-20767 writable-string error on OSX with 10.4.8

---

mysql-test/main/func_json.result
mysql-test/main/func_json.test
sql/item_jsonfunc.cc
sql/item_jsonfunc.h
sql/item_sum.cc
sql/item_sum.h
sql/lex.h
sql/sql_yacc.yy

The JSON_ARRAYAGG function extends the GROUP_CONCAT function and provides
a method of aggregating JSON results. The current implementation supports
DISTINCT and LIMIT but not ORDER BY (Oracle supports GROUP BY).
Adding GROUP BY support is possible but it requires some extra work as the
grouping appears to be done inside a temporary table that complicates
matters.
Added test cases that covert aggregation of all JSON types and JSON
validation for the generated results.

MDEV-16620: Add JSON_ARRAYAGG function

---

mysql-test/suite/galera/r/MDEV-6860.result
mysql-test/suite/galera/t/MDEV-6860.cnf
mysql-test/suite/galera/t/MDEV-6860.test
sql/rpl_parallel.cc

Instrumenting parallel slave worker thread with wsrep replication hooks.
Added mtr test for testing parallel slave support.
The test is based on the test attached in MDEV-6860 jira tracker.

MDEV-6860 Parallel async replication hangs

---

sql/log.cc
sql/wsrep_binlog.cc
sql/wsrep_client_service.cc
sql/wsrep_client_service.h
sql/wsrep_high_priority_service.cc
sql/wsrep_high_priority_service.h
sql/wsrep_storage_service.cc
sql/wsrep_storage_service.h

Redo changes reverted in commit
8f46e3833c7acb3ec3e4c7b389ae8cdd98eff1ce, this time without build
issues in wsrep-lib.

MDEV-17099 Preliminary changes for Galera XA support

---

storage/xtradb/include/ut0ut.h

Do the same that newer branches do and don't include glibc-related headers on non-glibc environment.

Fix build on !glibc/powerpc*

---

mysql-test/suite/galera/r/galera_as_slave_gtid_auto_engine.result
mysql-test/suite/galera/t/galera_as_slave_gtid.inc
mysql-test/suite/galera/t/galera_as_slave_gtid_auto_engine.cnf
mysql-test/suite/galera/t/galera_as_slave_gtid_auto_engine.test
sql/service_wsrep.cc
storage/innobase/handler/ha_innodb.cc

The original crash happened when async replication IO thread was updating mysql.gtid_slave_pos table. Operations on this table should remain node local, but it appears that protection (THD::wsrep_ignore_table flag) to prevent wsrep replication for this table was missing for innodb write_row() and update_row().
It was somewhat difficult to reproduce the issue, because mtr seems to create the affected table mysql.gtid_log_pos as of Aria engine type, and Aria engine operations will not be replicated anyhow. It looks, though, that in release installation, mysql.gtid_slave_pos table is of InnoDB engine.
It was possible to trigger somewhat related problem by running test galera.galera_as_slave_gtid with configuration: gtid_pos_auto_engines=InnoDB. However, this test mode, causes earlier crash …

MDEV-21096 async slave crash with gtid_slave_pos table access

---

mysql-test/suite/galera/r/galera_as_slave_gtid_myisam.result
mysql-test/suite/galera/t/galera_as_slave_gtid_myisam.cnf
mysql-test/suite/galera/t/galera_as_slave_gtid_myisam.test
sql/slave.cc
sql/wsrep_hton.cc

The problem happens when MariaDB master replicates writes for only non InnoDB
tables (e.g. writes to MyISAM table(s)). Async slave node, in Galera cluster,
can apply these writes successfully, but it will, in the end, write gtid position in
mysql.gtid_slave_pos table. mysql.gtid_slave_pos table is InnoDB engine, and
this write makes innodb handlerton part of the replicated "transaction".
Note that wsrep patch identifies that write to gtid_slave_pos should not be replicated
and skips appending wsrep keys for these writes. However, as InnoDB was present
in the transaction, and there are replication events (for MyISAM table) in transaction
cache, but there are no appended keys, wsrep raises an error, and this makes the söave
thread to stop.
The fix is simply to not treat it as an error if …

MDEV-19572 async slave node fails to apply MyISAM only writes

---

sql/sql_select.cc

Fix incorrect DBUG_ENTER message for join_read_last. I've based this on 10.1, I'm not sure how far back you'd like this patch to be applied and how far back are changes being merged upwards towards 10.5. I'm happy to base this on whatever branch you'd like.
I've signed the MCA previously.

MDEV-21116 Fix incorrect DBUG_ENTER message for join_read_last

---

mysql-test/suite/galera/r/galera_set_position_after_cert_failure.result
mysql-test/suite/galera/r/galera_set_position_after_dummy_writeset.result
mysql-test/suite/galera/t/galera_set_position_after_cert_failure.test
mysql-test/suite/galera/t/galera_set_position_after_dummy_writeset.test
sql/wsrep_high_priority_service.cc
sql/wsrep_server_service.cc
sql/wsrep_server_service.h

A certification failure followed by a clean shutdown would cause an
inconsistency between the sequence number stored in innodb and the
sequence number stored in provider.
This happened both in the case of local certification failure, and in
the case where dummy writeset is applied.
The fix consists of:
- updating wsrep position after dummy writeset is delivered in
`Wsrep_high_priority_service::log_dummy_write_set()`
- updating wsrep position while releasing commit order in wsrep-lib
side
Added two tests which stress the situation where a server is shutdown
after a certification failure.

Wsrep position not updated in InnoDB after certification failures

---

mysql-test/suite/galera/r/galera_sync_wait_upto.result
mysql-test/suite/galera/t/galera_sync_wait_upto.test
sql/item_strfunc.cc
sql/wsrep_mysqld.h

Function `signal_waiters` assigned `m_committed_seqno` variable outside of
mutex lock which caused incorrect behavior of WSREP_SYNC_WAIT_UPTO_GTID.
Fixed by moving assignment inside lock. Added handling of OOM and now
error is reported.
Remove hard-coded seqno value and read seqno directly from current node state.

Incorrect behaviour of WSREP_SYNC_WAIT_UPTO_GTID

---

sql/sql_parse.cc

When using LTO, one can see optimization of stack variables that
are passed to check_stack_overrun as argument buf. That prevents
proper stack overrun detection.

MDEV-21248: Prevent optimizing out buf argument in check_stack_overrun.

---

debian/autobake-deb.sh
debian/control
debian/libmariadb3.install
debian/libmariadbd-dev.install
debian/mariadb-plugin-rocksdb.install
debian/mariadb-server-10.3.install
debian/mariadb-test-data.install

No functional changes.
Apply this in 10.3 so eventually it is merged to 10.4 and 10.5, which
in turn will have separate wrap-and-sort runs but only for new lines,
and thus not affecting badly next merges from 10.3 to 10.4 to 10.5.

Deb: Run 'wrap-and-sort -a' so comparison across releases is easier

---

mysql-test/suite/galera/r/galera_slave_replay.result
mysql-test/suite/galera/t/galera_slave_replay.cnf
mysql-test/suite/galera/t/galera_slave_replay.test
sql/log_event.cc
sql/slave.cc
sql/wsrep_thd.cc

If async replication slave thread conflicts with cluster replication,
then the async slave transaction should be BF aborted, and depending on the
state of async slave transaction execution, potentially also replayed.
There were problems in such BF abort implementation and the replaying was not
started.
This pull request contains fixes which make sure that if async slave thread is
marked to abort and replay, it will complete carry out the rollback and
release all locks and resources before starting the replaying. After replaying,
async slave transactions is treated as successful, so the slave thread will
continue as usual, handling next replication event.
There is also new mtr test: galera.galera_slave_replay, which stresses both a
certification failure for async slave thread and a …

MDEV-21723 Async slave thread BF abort and replaying fixes

---

support-files/mariadb.service.in
support-files/mariadb@.service.in

mariadb{,@}.service comment typo open-file-limit -> open-files-limit

---

cmake/dtrace.cmake

cmake enabling -DENABLE_DTRACE=ON is particularly noisy with CMP0026
errors.
Fixed in the same way as 6b53f9d781cc19cbec96c3eb048e6407021685a2

MDEV-16662: cmake: CMP0026 compatible for dtrace

---

plugin/auth_socket/CMakeLists.txt
plugin/auth_socket/auth_socket.c

I have been packaging MariaDB 10.4 for the OmniOS operating system, which is a distribution of illumos (née OpenSolaris), and wanted to enable support for the `auth_socket` plugin.
illumos has `getpeerucred()` and so here's a patch to make auth_socket work on illumos platforms.
(It may also allow it to work on Solaris, which also has getpeerucred(), but I have not tested)
```
root@database:~# uname -a
SunOS sparse 5.11 omnios-r151032-702376803e i86pc i386 i86pc
root@database:~# mysql
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 8
Server version: 10.4.11-MariaDB OmniOS MariaDB Server
Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
MariaDB …
```

MDEV-21476: auth_socket: add support for illumos with getpeerucred()

---

storage/innobase/os/os0file.cc

Function `os_file_get_last_error_low` returns error number +
`OS_FILE_ERROR_MAX` (which is currently set to 200) for unknown numbers to
this program.

innodb: fix typo in function description

---

storage/innobase/ut/ut0crc32.cc

@dr-m in 1312b4ebb652 moved ut_crc32_byteorder to a x86_64 #ifdef area. As its only used in BIGENDIAN this wasn't useful and broke the travis builds on s390x added recently.
Corrected version builds and passes tests https://travis-ci.org/github/grooverdan/mariadb-server/builds/662994435.

fix ut_crc32_swap_byteorder

---

mysql-test/suite/galera/r/MDEV-19966.result
mysql-test/suite/galera/t/MDEV-19966.test
sql/service_wsrep.cc
storage/innobase/lock/lock0lock.cc
storage/innobase/trx/trx0roll.cc

When connections go to same node and deadlock happens, BF abort should
not happen for victim thread. Fixed by guarding
`wsrep_handle_SR_rollback()` so that is called only for SR transactions.
Co-authored-by: Seppo Jaakola <seppo.jaakola@iki.fi>
Co-authored-by: Daniele Sciascia <daniele.sciascia@galeracluster.com>

MDEV-20616: MariaDB-Galera 10.4.8 | Transaction aborted | Sig 6 Shutdown

---

mysql-test/suite/galera/r/galera_multirow_rollback.result
mysql-test/suite/galera/t/galera_multirow_rollback.combinations
mysql-test/suite/galera/t/galera_multirow_rollback.test
mysql-test/suite/galera_sr/r/galera_sr_multirow_rollback.result
mysql-test/suite/galera_sr/t/galera_sr_multirow_rollback.combinations
mysql-test/suite/galera_sr/t/galera_sr_multirow_rollback.test
sql/log.cc
sql/log.h
sql/wsrep_binlog.cc
sql/wsrep_binlog.h
sql/wsrep_mysqld.h
sql/wsrep_trans_observer.h

The pull request consists of two commits, which can be reviewed separately.
1) Simply removes some dead code
2) Fixes cluster wide data inconsistency, which may result on multirow inserts that are rolled back after an error.

MDEV-21675: Data inconsistency after multirow insert rollback

---

sql/slave.cc
sql/sql_class.cc
sql/sql_connect.cc
sql/sql_parse.cc
sql/wsrep_applier.cc
sql/wsrep_hton.cc
sql/wsrep_mysqld.cc

If async slave thread (slave SQL handler), becomes a BF victim, it may occasionally happen that rollbacker thread is used to carry out the rollback instead of the async slave thread.
This can happen, if async slave thread has flagged "idle" state when BF thread tries to figure out how to kill the victim.
The issue was possible to test by using a galera cluster as slave for external master, and issuing high load of conflicting writes through async replication and directly against galera cluster nodes.
However, a deterministic mtr test for the "conflict window" has not yet been worked on.
The fix, in this patch makes sure that async slave thread state is never set to IDLE. This prevents the rollbacker thread to intervene.
The wsrep_query_state change was refactored to happen by dedicated …

MDEV-21473 conflicts with async slave BF aborting

---

storage/maria/CMakeLists.txt

With OpenSSL < 1.1 there is a potential for a race condition to occur.
This can cause the S3 engine to crash. The workaround is to add locking
callbacks to OpenSSL so that this doesn't happen.
https://curl.haxx.se/libcurl/c/threadsafe.html
There is a fix in libMariaS3 for this which when a certain flag is set
(HAVE_CURL_OPENSSL_UNSAFE) will add the required locks.
This patch adds CMake support so that the flag is set if it is found
that Curl is compiled with an unsafe OpenSSL version. For example Ubuntu
16.04 with libcurl4-openssl-dev.

MDEV-20329 Fix S3 engine OpenSSL race

---

mysql-test/main/partition_alter.result
mysql-test/main/partition_alter.test
mysql-test/suite/versioning/r/partition.result
mysql-test/suite/versioning/t/partition.test
sql/sql_partition.cc

Assertion `old_part_id == m_last_part' failed in ha_partition::update_row or `part_id == m_last_part' in ha_partition::delete_row upon UPDATE/DELETE after dropping versioning
PRIMARY KEY change hadn't been treated as partition reorganization in case of partitioning by KEY() (without parameters).
* set `*partition_changed= true` in the described case.
* since add/drop system versioning does not affect alter_info->key_list, it required separate attention

MDEV-17091 - Assertion failed after dropping versioning

---

sql/signal_handler.cc

I didn't change the readlink /proc/self/cwd as there's no equivalent
FreeBSD-12.0
```
root@freebsd:/proc/58100 # ls -la /proc/curproc/
total 0
dr-xr-xr-x  1 root  wheel  0 Mar 27 03:46 .
dr-xr-xr-x  1 root  wheel  0 Mar 27 03:46 ..
-r--r--r--  1 root  wheel  0 Mar 27 03:46 cmdline
-rw-------  1 root  wheel  0 Mar 27 03:46 dbregs
-r--r--r--  1 root  wheel  0 Mar 27 03:46 etype
lr--r--r--  1 root  wheel  0 Mar 27 03:46 file -> /bin/ls
-rw-------  1 root  wheel  0 Mar 27 03:46 fpregs
-r--r--r--  1 root  wheel  0 Mar 27 03:46 map
-rw-------  1 root  wheel  0 Mar 27 03:46 mem
--w-------  1 root  wheel  0 Mar 27 03:46 note
--w-------  1 root  wheel  0 Mar 27 03:46 notepg
-rw-------  1 root  wheel  0 Mar 27 03:46 osrel
-rw-------  1 root  wheel  0 Mar 27 03:46 regs
-r--r--r--  1 root  wheel  0 …
```

output_core_info - freebsd rlimits in different proc entry

---

mysys/my_getncpus.c

Per https://www.unix.com/man-page/freebsd/3/pthread_affinity_np/, underscores matter.

Correct FreeBSD cpuset_t type

---

mysql-test/mysql-test-run.pl
mysql-test/suite/encryption/r/innodb-force-corrupt.result
mysql-test/suite/encryption/t/innodb-force-corrupt.test

Also executable can change for jemalloc.
Rather important one to correct bb errors like:
encryption.innodb-force-corrupt 'cbc,innodb' w1 [ fail ]  Found warnings/errors in server log file!
Test ended at 2020-04-06 15:44:39
line
2020-04-06 15:44:36 3 [ERROR] mariadbd: Index for table 't2' is corrupt; try to repair it
^ Found warnings in /dev/shm/var/1/log/mysqld.1.err

MDEV-22010: mtr, "mariadbd" exists in mysys error messages

---

appveyor.yml
mysql-test/mysql-test-run.pl

superseded version of #1488
windows doesn't require it:
https://ci.appveyor.com/project/grooverdan/mariadb-server/builds/32119201?fullLog=true
looked explicitly for tests:
<pre>
find mysql-test/ -name \*rdiff
mysql-test/r/subselect_sj2_jcl6,innodb_plugin.rdiff
mysql-test/r/innodb_bug878769,innodb_plugin.rdiff
mysql-test/r/mysqld--help,win.rdiff
mysql-test/r/innodb_mrr_cpk,innodb_plugin.rdiff
mysql-test/r/innodb_icp,innodb_plugin.rdiff
mysql-test/r/range_vs_index_merge_innodb,innodb_plugin.rdiff
mysql-test/suite/funcs_1/r/is_engines_innodb,innodb_plugin.rdiff
mysql-test/suite/rpl/r/rpl_insert_delayed,stmt.rdiff
</pre>
Took appveyor config from 10.2 to test, too many type conversion warnings so hence /W0

mtr no patch --binary

---

extra/crc32-vpmsum/clang_workaround.h

Clang 7 changed the behavior of vec_xxpermdi in order to match GCC's
behavior.  After this change, code that used to work on Clang 6 stopped
to work on Clang >= 7.
Tested on Clang 6, 7, 8 and 9.
Reference: https://bugs.llvm.org/show_bug.cgi?id=38192
Upstream fix: https://github.com/antonblanchard/crc32-vpmsum/commit/361aaf77a599995e23acd50c9c50d48d30c69241
Thanks @ottok  for the bug report.
I submit this under the MCA

MDEV-21984: POWER crc32 acceleration - fix clang's behavior on versions >= 7

---

scripts/mysql_system_tables_fix.sql

This fixes bugs where upgrading MariaDB failed to start after an upgrade
from MySQL 5.7 in Ubuntu, where auth_socket has been the default for MySQL
as well for some time now.
This was adopted from Debian where this change has been since Apr 18, 2019:
https://salsa.debian.org/mariadb-team/mariadb-10.4/-/commit/3919860b6a4ef98c098fef35fb34601adbb132b2

MDEV-18768: Rename auth_socket to unix_socket on upgrades from MySQL

---

mysql-test/mysql-test-run.pl

Windows is always MSWin32 according to https://perldoc.perl.org/perlvar.html#%24OSNAME
Windows GNU patch 2.7.6 per the appveyor version;
patch --version
GNU patch 2.7.6
Copyright (C) 2003, 2009-2012 Free Software Foundation, Inc.
Copyright (C) 1988 Larry Wall
This might be https://packages.msys2.org/package/patch per https://www.appveyor.com/docs/windows-images-software/#mingw-msys-cygwin
So sorry @vuvova, back to an OS version.

mtr: Only old windows patch-2.5.9 needs --binary

---

mysql-test/suite/galera/r/mdev_21025.result
mysql-test/suite/galera/t/mdev_21025.test
sql/handler.cc

If a transaction had no effect due to INSERT IGNORE and a new
transaction was started with START TRANSACTION without committing
the previous one, the server crashed on assertion when starting
a new wsrep transaction.
As a fix, refined the condition to do wsrep_commit_empty() at the end
of the ha_commit_trans().

MDEV-21025 Server crashes on START TRANSACTION after INSERT IGNORE

---

vio/viosocket.c

vio: typo on sock{et}_errno in comment

---

mysql-test/mysql-test-run.pl

Fix mtr error:
Bareword "HAVE_WIN32_CONSOLE" not allowed while "strict subs" in use at mysql-test-run.pl line 387.
Execution of mysql-test-run.pl aborted due to compilation errors.
Added in e3f5789ac0b23a16bb71e06b05dec9cfec3161f0
@vaintroub  quick fix of non-win builds - e.g. http://buildbot.askmonty.org/buildbot/builders/bld-p9-rhel7/builds/3261/steps/mtr/logs/stdio

mysql-test-run.pl - fix strict subs in HAVE_WIN32_CONSOLE

---

storage/innobase/log/log0log.cc

I noticed a small typo in logs
```
2020-04-30  9:37:35 0 [Note] InnoDB: Waiting for master threadto exit
^^^^^^^^
```
I started the branch from the commit where the typo first time appeared. "Merge 10.1 to 10.2"

innodb: add space between thread name and "to exit" text

---

storage/innobase/sync/sync0rw.cc

- There are multiple inconsistency and incorrect way in which rw-lock
stats are calculated.
- shared rw-lock stats:
"rounds" counter is incremented only once for N rounds done
in spin-cycle.
- all rw-lock stats:
If the spin-cycle is short-circuited then attempts are re-counted.
[If spin-cycle is interrupted, before it completes
srv_n_spin_wait_rounds (default 30) rounds, spin_count is incremented
to consider this. If thread resumes spin-cycle (due to unavailability
of the locks) and is again interrupted or completed, spin_count
is again incremented with the total count, failing to adjust the
previous attempt increment].
- s/x rw-lock stats:
spin_loop counter is not incremented at-all instead it is projected
as 0 (in show engine output) and division to calculate spin-round per
spin-loop is …

MDEV-22544: Inconsistent and Incorrect rw-lock stats

---

debian/additions/debian-start
debian/mariadb-server-10.5.install
debian/mariadb-server-10.5.logcheck.ignore.paranoid
debian/mariadb-server-10.5.logcheck.ignore.server
debian/mariadb-server-10.5.logcheck.ignore.workstation
debian/mariadb-server-10.5.mariadb.init
debian/mariadb-server-10.5.postinst
debian/mariadb-server-10.5.postrm
debian/mariadb-server-10.5.preinst
debian/mariadb-server-10.5.prerm
debian/rules
debian/salsa-ci.yml
debian/tests/smoke
mysql-test/unstable-tests

While all current versions of Linux have systemd, support for traditional
init.d is still needed e.g. on Linux subsystem on Windows, kFreeBSD and
special variants of Debian/Ubuntu that for other reasons don't have
systemd.
Supporting traditional init.d is easy, since Debian has facilities for it.
Partially reverts commit a4cc6fb91f3855e0ed803a6e1762440cfcf8cb5c.
Depends on https://salsa.debian.org/mariadb-team/mariadb-10.4/-/merge_requests/2 and https://github.com/MariaDB/server/pull/1172 being merged first.

Deb: Add support for legacy init systems

---

mysql-test/r/udf.result
mysql-test/t/udf.test

Localhost, depending on the platform can return any
127.0.0.1/8 address.
backport, for @ottok.

MDEV-21976: mtr main.udf - broaden localhost

---

mysys/my_largepage.c

my_is_2pow is only used on linux.
fixes compile warning:
mysys/my_largepage.c:48:23: warning: unused function 'my_is_2pow' [-Wunused-function]
static inline my_bool my_is_2pow(size_t n) { return !((n) & ((n) - 1)); }
^
1 warning generated.

MDEV-22408: largepages: osx compile warning fix

---

storage/innobase/fts/fts0fts.cc
storage/innobase/fts/fts0opt.cc
storage/innobase/fts/fts0que.cc
storage/innobase/include/fts0priv.h
storage/innobase/include/fts0types.h
storage/innobase/include/fts0types.ic

I noticed that `fts_indexes` field in `fts_update_t` was not used at all.

MDEV-22629: Remove fts_indexes field from struct fts_update_t

---

mysql-test/suite/galera_sr/r/MDEV-22616.result
mysql-test/suite/galera_sr/t/MDEV-22616.test
sql/sql_class.cc

Executing CHECK TABLE  with streaming replication enabled reports
error "Streaming replication not supported with
binlog_format=STATEMENT".
Administrative commands such as CHECK TABLE, are not replicated and
temporarily set binlog format to statement.
To avoid the problem, report the error only for active transactions
for which streaming replication is enabled.

MDEV-22616 CHECK TABLE fails with wsrep_trx_fragment_size > 0

---

mysql-test/suite/galera/r/galera_bf_kill.result
mysql-test/suite/galera/t/galera_bf_kill.test
sql/service_wsrep.cc
storage/innobase/trx/trx0trx.cc

The hang can happen between a lock connection issuing KILL CONNECTION for a victim,
which is in committing phase.
There happens two resource deadlock where  killer is holding victim's
LOCK_thd_data and requires trx mutex for the victim.
The victim, otoh, holds his own trx mutex, but requires LOCK_thd_data
in wsrep_commit_ordered(). Hence a classic two thread deadlock happens.
The fix in this commit changes innodb commit so that wsrep_commit_ordered()
is not called while holding trx mutex. With this, wsrep patch commit time mutex
locking does not violate the locking protocol of KILL command
(i.e. LOCK_thd_data -> trx mutex)
Also, a new test case has been added in galera.galera_bf_kill.test for scenario
where a client connection is killed in committing phase.

MDEV-22666 galera.MW-328A hang

---

.gitignore
cmake/libutils.cmake
cmake/merge_archives_unix.cmake

This corrects build failures on ppc64{,le} with the EMBEDDED_SERVER
option enabled.
MDEV-22641 added an unusual case in which the same object
file in different directories contained a different function
defination. The original cmake/merge_archives_unix.cmake
did not tolerate such eventualities.
So we move to the highest voted answer on Stack Overflow
for the merging of static libraries.
https://stackoverflow.com/questions/3821916/how-to-merge-two-ar-static-libraries-into-one
Thin archives generated compile failures and the libtool
mechanism would of been another dependency and using .la
files that isn't part of a normal cmake output. The straight
Apple mechanism of libtool with static archives also failed
on Linux.
This leaves the MRI script mechansim which was implemented
in this …

cmake: merge_static_libs - correct duplicate assumptions

---

mysql-test/main/cte_recursive.result
mysql-test/main/subselect_no_opts.result
mysql-test/main/subselect_no_scache.result
mysql-test/main/subselect_partial_match.result
sql/item_cmpfunc.h

when Item::print() is called with the QT_PARSABLE flag, WHERE i NOT IN
(SELECT ...) gets printed as WHERE !i IN (SELECT ...) instead of WHERE
!(i in (SELECT ...)) because Item_in_optimizer returns DEFAULT_PRECEDENCE.
it should return the precedence of the inner operation.

when printing Item_in_optimizer, use precedence of wrapped Item

---

mysql-test/suite/galera/r/galera_parallel_autoinc_manytrx.result
mysql-test/suite/galera/t/galera_parallel_autoinc_manytrx.test

The galera.galera_parallel_autoinc_manytrx mtr test opens and runs test
scenario through 3 connections to node 1 and one connection to node 2.
In the test initialization phase, the test creates two tables 't1' and 'ten'
and then creates a stored procedure 'p1' to operate on these tables.
These 3 create DDL statements are issued through same connection to node 1.
In the next test phase, the mtr script uses send command to launch the call
for the p1 stored procedure through all 3 connections to node 1 and through
one connection to node 2. As the mtr send command is asynchronous,
this test phase is non blocking and fast operation.
Now, if the replication between nodes is slow, it may happen that the
initialization phase DDL statements have not been received or have not been
fully applied in …

MDEV-21759 galera.galera_parallel_autoinc_manytrx sporadic failures.

---

debian/additions/source_mariadb-10.5.py
debian/mariadb-server-10.5.install
debian/mariadb-server-10.5.logcheck.ignore.paranoid
debian/mariadb-server-10.5.logcheck.ignore.server
debian/mariadb-server-10.5.logcheck.ignore.workstation
debian/mariadb-server-10.5.mariadb.init
debian/mariadb-server-10.5.mysql-server.logrotate
debian/mariadb-server-10.5.postinst
debian/mariadb-server-10.5.postrm
debian/mariadb-server-10.5.preinst
debian/rules
mysql-test/lib/v1/mysql-test-run.pl
scripts/mysqld_safe.sh
support-files/MacOSX/ReadMe.txt
support-files/binary-configure.sh
support-files/mariadb.service.in
support-files/mariadb@.service.in
support-files/mysql-log-rotate.sh
support-files/mysql-multi.server.sh
support-files/mysql.server-sys5.sh
support-files/mysql.server.sh
support-files/policy/apparmor/usr.sbin.mysqld

Replace all references to /usr/sbin/mysqld (and bin and libexec) with
mariadbd, so that the binary server will always be 'mariadbd'.
Also update all places that reference the server binary in other ways,
such as AppArmor profiles and scripts that previously expected to find
a 'mysqld' in process lists.

MDEV-22569: Run bin/mariadbd instead of bin/mysqld

---

storage/innobase/trx/trx0trx.cc

Rollback segments are allocated to transactions in round-robin fashion.
This is controlled by incrementing a static-scope counter named rseg_slot.
Said logic is not protected by any mutex or use of atomic for the counter.
This potentially can cause the same rollback segment to get allocated to
N different transactions (requesting allocation at the same time).
While this is not an issue as a rollback segment can host multiple
transactions from contention (performance) perspective it is better to
allocate these rollback segments in round-robin fashion.
Fix for the said issue ports use of atomic for the said counter that would
ensure the original design semantic (even distribution through round-robin)
is retained.

MDEV-22794: Avoid potential rollback segment contention with increased scalability through even distribution

---

cmake/libutils.cmake

Because of common dependencies between the
static libraries list can contain duplicates.
We reduce these down to the single last one in
the list.
This reduces the relative time of a rebuild from:
$ (cd builddir/; time make -j)
...
real	0m30.789s
user	1m33.477s
sys	0m19.678s
and the LIB entries
$ grep ADDLIB builddir/libmysqld/mysqlserver-\$\<CONFIG\>.mri.tpl  | wc -l
179
$ du -h builddir/libmysqld/libmariadbd.a
4.1G	builddir/libmysqld/libmariadbd.a
To:
$ (cd builddir/; time make -j)
...
real	0m20.139s
user	1m32.423s
sys	0m12.208s
$ grep ADDLIB builddir/libmysqld/mysqlserver-\$\<CONFIG\>.mri.tpl  | wc -l
25
$ du -h builddir/libmysqld/libmariadbd.a
688M	builddir/libmysqld/libmariadbd.a

libutils: merge static libraries only once

---

cmake/install_layout.cmake

to match #1504
This will propagate to all the defaults of libmariadb so they default to the same socket path too.

INSTALL_UNIX_ADDRDIR for debian to /run/mysqld/mysqld.sock

---

mysql-test/suite/galera/r/MDEV-20225.result
mysql-test/suite/galera/r/galera_sp_bf_abort.result
mysql-test/suite/galera/t/MDEV-20225.test
mysql-test/suite/galera/t/galera_sp_bf_abort.inc
mysql-test/suite/galera/t/galera_sp_bf_abort.test
sql/sp_head.cc
sql/sql_trigger.cc
sql/wsrep_hton.cc
sql/wsrep_mysqld.cc
sql/wsrep_thd.cc
sql/wsrep_thd.h

Backported the support for aborting and replaying stored procedure execution and fix for trigger
key assignments from 10.4 version.
Backported also two mtr tests: wsrep_sp_bf_abort.test and MDEV-20225.test

MDEV-22763 backporting MDEV-20225 fix into 10.1

---

include/mysql/psi/mysql_socket.h

accept might return an error, including SOCKET_EAGAIN/
SOCKET_EINTR. The caller, usually handle_connections_sockets
can these however and invalid file descriptor isn't something
to call fcntl on.
Thanks to Etienne Guesnet (ATOS) for diagnosis, sample patch description and testing.

MDEV-22173: socket accept - test for failure

---

debian/mariadb-plugin-s3.install
man/CMakeLists.txt
man/aria_s3_copy.1
storage/maria/aria_s3_copy.cc

Based on output of 'aria_s3_copy --help'.
Also fix a typo in command help.

Add man page for new command aria_s3_copy

---

mysql-test/suite/galera/r/galera_toi_truncate.result
mysql-test/suite/galera/t/galera_toi_truncate.test

galera_toi_truncate test launches a long term INSERT statement in node 2,
and then submits an offending TRUNCATE through node 1. The idea is that
the replicated TRUNCATE will conflict with INSERT in node 2, and force
the INSERT to abort.
The test first issues --send INSERT in node 2, and then switches to node 1
to launch --send TRUNCATE. As the INSERT is launched asynchronously by --send,
it may happen that INSERT has not yet started to process, before the TRUNCATE
is replicated. The net effect may be that TRUCATE processes to completion in node 2,
and only after that INSERT starts to execute. As the INSERT is very long query,
it will last longer than mtr test suite max test time, the test will fail for timeout.
The fix in this commit uses another connection in node 2, to wait until the …

MDEV-22966- Hang on galera_toi_truncate test case

---

CMakeLists.txt
cmake/check_linker_flag.cmake

Fixes noisy clang output like #1524
Treats "-Wl,-z,relro,-z,now" as an actual linker flags rather than compile flags.
Slightly WIP due to being a purely linker check rather than testing module and shared library builds separately, however it does have an advantage over #1524  in that the linker flags are still used in clang.

check_linker_flag: use for linker flags

---

storage/innobase/handler/ha_innodb.cc
storage/xtradb/handler/ha_innodb.cc

THD proc info was assigned from stack allocated temporary buffer
which went out of scope immediately after assignment.
Fixed by removing the use of temp buffer and assign proc info
from string literal.

MDEV-23272 Galera stack-use-after-scope error with ASAN build

---

scripts/mysql_install_db.sh

Removed duplicate.
Also move the --no-defaults option close to the other "default*"
options.

mysql_install_db: help lists --defaults-file twice

---

support-files/mariadb.service.in
support-files/mariadb@.service.in

Correct to a true 2^14 rather than some different number that
was actually just a number typo.
Bug report thanks to Hartmut Holzgraefe.

MDEV-23088: Change LimitNOFILE default from 16364 to 16384

---

storage/rocksdb/mysql-test/rocksdb/t/concurrent_alter.test

FreeBSD doesn't have bash installed by default and sh
has sufficient job control for this test.
Test on 10.5 but the test hasn't changed since 10.2
$  mysql-test/mtr --mem --max-test-fail=30 --force --parallel=1 rocksdb.concurrent_alter
Logging: /home/dan/mariadb-server-10.5/mysql-test/mysql-test-run.pl  --mem --max-test-fail=30 --force --parallel=1 rocksdb.concurrent_alter
vardir: /usr/home/dan/build-mariadb-server-10.5/mysql-test/var
Creating var directory '/usr/home/dan/build-mariadb-server-10.5/mysql-test/var'...
- symlinking 'var' to '/tmp/var_auto_P81m'
MariaDB Version 10.5.4-MariaDB
- binaries built with wsrep patch
Collecting tests...
Installing system …

rocksdb: mtr - rocksdb.concurrent_alter use sh

---

mysql-test/mysql-test-run.pl

There was no ability to set the mtr arguments of:
* --max-test-fail;
* --max-save-core; and
* --max-save-datadir
to 0. This is desirable in an automated scenario where space is limited hence targeting 10.1 branch.
We take aware the 0 means unlimited aspect consistently for these  however, perl can handle some big numbers so they may as well be close enough to unlimited for all meaningful purposes
closes #854

MDEV-17076: mtr make 0 mean 0 for --max-save-{core,datadir}

---

mysql-test/main/mysqld--help-aria.test

The remaining test failure on OSX (travis at least) after #1518 cleans up the major OSX test failures.
https://travis-ci.org/github/grooverdan/mariadb-server/jobs/680842564
sneakily use lower-case-table-names=1 that unix and OSX won't emit warnings about. Its a `mysqld--help` test after all so its importance doesn't matter that much (expect for the warning output)
Here's it working (on test rebased after the #1518 fix):
https://travis-ci.org/github/grooverdan/mariadb-server/jobs/680907510#L5954

MDEV-22407: mtr: mysqld--help-aria test on OSX fail

---

mysql-test/r/win_ntile.result
mysql-test/t/win_ntile.test
sql/item_windowfunc.h

We save NTILE argument(N) and compare it to the following N.
If N not a constant for the partition - we stop with an error.
Currently used an old error:Argument of NTILE must be greater than 0

MDEV-9911: NTILE must return an error when parameter is not stable

---

include/my_sys.h
mysys/CMakeLists.txt
mysys/crc32/crc32_arm64.c
storage/innobase/ut/ut0crc32.cc

MariaDB adopted a hardware optimized crc32c approach on ARM64 starting 10.5.
Said implementation of crc32c needs support from target hardware for crc32
and pmull instructions. Existing logic is checking only for crc32 support
from target hardware through a runtime check and so if target hardware
doesn't support pmull it would cause things to fail/crash.
Expanded runtime check to ensure pmull support is also checked on the target
hardware along with existing crc32.
Thanks to Marko and Daniel for review.

MDEV-23030: ARM crash on Raspberry Pi 4

---

.travis.yml

Passes this test case.
https://travis-ci.org/github/grooverdan/mariadb-server/jobs/723046285
pushing as a pr to do a second test.

travis: osx build time out storing cache. Ensure not Cellar

---

storage/innobase/os/os0file.cc
storage/xtradb/os/os0file.cc

On some libc (like musl[1]), posix_fallocate() is a fallocate() syscall
wrapper, and does not include fallback code like glibc does. In that
case, EOPNOTSUPP is returned if underlying filesystem does not
support fallocate() with mode = 0.
This patch enables falling back to writing zeros when EOPNOTSUPP, fixes
some cases like running on filesystem without proper fallocate support
on Alpine.
[1]: https://git.musl-libc.org/cgit/musl/tree/src/fcntl/posix_fallocate.c?h=v1.2.1
This is 10.1 version of #1658.

InnoDB, XtraDB: handle EOPNOTSUPP from posix_fallocate()

---

plugin/aws_key_management/aws_key_management_plugin.cc

Define new `aws_key_management_endpoint_url` plugin variable to use a different endpoint url for KMS operations.

Define variable to override endpoint url

---

support-files/use_galera_new_cluster.conf

This is just to make sure no ExecStartPre/Post actions from the multi-instance MariaDB service definition are executed when a user attempts to start mariadb@bootstrap.
Fixes consequence of 3723c70a3045
was originally part of #510 however is highly suitable for backport.

systemd: mariadb@bootstrap - clear ExecStartPre and ExecStartPost

---

sql/mysqld.cc

…
When process is aborted WSREP deinitialization and memory cleanup is not properly handled.  Other reported leaks are in Galera library and should be fixed there.

MDEV-23559: Galera LeakSanitizer: detected memory leaks in galera.GAL-419

---

mysql-test/suite/wsrep/r/variables.result
mysql-test/suite/wsrep/t/variables.test

Require galera_have_debug_sync.inc and re-record to include new
variables exposed by latest galera library.

Fix MTR test wsrep.variables

---

.travis.yml

Upgrade to using Ubuntu 20.04 (Focal) as the baseline distro version
now that Travis-CI has made it available. Drop Xenial and all the
excess repositories Xenial needed. Now we only Focal and one Bionic
build to keep things simple and streamlined.
Keep GCC-7/Clang-7 as the older compiler, and start using GCC-10
and Clang-10 as the newer compiler. Assume that if both of them
build OK, than the intermediate versions would be OK as well.
Print 'apt-cache policy' to make it transparent in build logs what
repositories was used for build dependencies.
Remove temporary workaround from homebrew install step as Travis-CI has
fixed the original issue.
Revert ignoring results form build that previously failed on the test
main.thread_pool_info as MDEV-20372 is not fixed.
Keep arm64 failures ignored …

Travis-CI: Use new Ubuntu 20.04 as base, streamline and document

---

mysql-test/suite/period/r/delete.result
mysql-test/suite/period/t/delete.test
sql/sql_delete.cc

DELETE...FOR PORTION OF... statement accepted non-constant FROM...TO clause. This contradicts the documentation and is inconsistent with the behavior of UPDATE statement. 
I add a validation that checks if a given deletion period is specified by constant.

MDEV-22596: Check if deletion period is specified by constant

---

storage/maria/ma_ft_parser.c

Jira issue number：MDEV-24031
summary： Aria storage engine uses sizeof(ft_boolean_syntax) as a replacement for strlen() but "ft_boolean_syntax" has "const char *" type.
problem description：The sizeof(ft_boolean_syntax) in maria_ft_boolean_check_syntax_string() may be intended to compute its length, but the ft_boolean_syntax's type is const char *. 
solution:  remove the maria_ft_boolean_check_syntax_string function since it's never used.
The modification will not hurt any other areas since this function isn't called at ay place. And the server can still be compiled successfully.

MDEV-24031: remove maria_ft_boolean_check_syntax_string()

---

debian/autobake-deb.sh
debian/rules

ColumnStore seems to build by default, so it must be explicitly disabled with a build flag, so that it does not build at all and thus build machine disk space and CPU will be spared.
This reverts commit 113f18686d004788f13e3a5bb60ea1c77847c963 and adds to it.

Fix commit 113f18686d0 and d1809097966: PLUGIN_COLUMNSTORE=NO by default

---

.travis.yml

The base distro version was changed from bionic to focal and GCC/Clang to 10, and I expect there will be some regressions/bugs that will need fine tuning and a follow-up commit.
I reviewed status of Travis-CI. Most jobs timeout/are skipped due too much traffic on Travis. Of the jobs that actually run, the majority pass OK. Examples:
- https://travis-ci.org/github/MariaDB/server/builds/747444463
- https://travis-ci.org/github/MariaDB/server/builds/748092290
- https://travis-ci.org/github/MariaDB/server/builds/749059547
I looked at the couple of failures e.g.
- https://travis-ci.org/github/MariaDB/server/jobs/750378268
- https://travis-ci.org/github/MariaDB/server/jobs/749049920
The end result is an optimization of the .travis-ci.yml file that should serve us well into the future.

Travis-CI: Optimize rate of false negatives vs true failures

---

man/mysqlcheck.1

Possible bug in `mysqlcheck` man page.
```
•   --skip-database=db_name -s
Don't process the database (case-sensitive) specified as argument.
```

-s stands for silent, copy-paste mistake?

---

sql/wsrep_binlog.cc

The implementation for MDEV-17048 apperas to be direct copy from mysql version.
The group commit works differently in mariadb and the assert in wsrep_unregister_from_group_commit() is too strict.
The reason is that in: Wsrep_high_priority_service::log_dummy_write_set(), the transaction will undergo full rollback:
{
cs.before_rollback();
cs.after_rollback();
}
After that, the client's transaction state is set to be:  wsrep::transaction::s_aborted.
The execution then continues execution by:
...
wsrep_register_for_group_commit(m_thd);
...
wsrep_unregister_from_group_commit(m_thd);
The bogus assert in wsrep_unregister_from_group_commit() allows only transactions states of :s_ordered_commit or s_aborting.
As the fix, I brought back the same assert as is present in MariaDB 10.4 version.

MDEV-24721 galera.mysql-wsrep-bugs-607 test failure

---

storage/innobase/dict/dict0dict.cc
storage/innobase/dict/dict0stats.cc
storage/innobase/handler/ha_innodb.cc
storage/innobase/handler/i_s.cc
storage/innobase/include/dict0mem.h
storage/innobase/include/dict0stats.ic

In theory, read-only workload shouldn't have anything to do with
dict_sys mutex. dict_sys mutex is meant to protect database metadata.
But then why does dict_sys mutex shows up as part of a read-only workload?
This workload needs to fetch stats for query processing and while reading
these stats dict_sys mutex is taken.
Is this really needed?
No. For the traditional reasons, it was the default global mutex used.
Based on 10.6 changes, flow can now use table->lock_mutex to protect
update/access of these stats. table mutexes being table specific
global contention arising out of dict_sys is reduced.
Thanks to Marko Makela for his early suggestion around proposed alternative
and review of the draft patch.

MDEV-25029: Reduce dict_sys mutex contention for read-only workload

---

sql/sql_table.cc

Hello. I just found that a header file "sql_parse.h" is included twice in "sql_table.cc".
I think that's a sort of typo, but to be honest I'm not so used to handle source code written in c++, I can't assure.
Would anyone check this one? thank you.

Delete duplicated #include "sql_parse.h"

---

man/mysqladmin.1

Relates to #1749 
Closes [MDEV-24963](https://jira.mariadb.org/browse/MDEV-24963)

MDEV-24963: Document `flush-ssl` in the mysqladmin manpage.

---

include/my_global.h

1. Add FORMAT_MESSAGE_MAX_WIDTH_MASK flag to remove trailing \r\n from
the error message returned by FormatMessageA().
2. Also, add FORMAT_MESSAGE_IGNORE_INSERTS to avoid potential problems
with system messages that have argument placeholders.
Quote from FormatMessage docs on MSDN:
If this function is called without FORMAT_MESSAGE_IGNORE_INSERTS, the
Arguments parameter must contain enough parameters to satisfy all insertion
sequences in the message string, and they must be of the correct type.
Therefore, do not use untrusted or unknown message strings with inserts
enabled because they can contain more insertion sequences than Arguments
provides, or those that may be of the wrong type. In particular, it is
unsafe to take an arbitrary system error code returned from an API and use …

Remove trailing newline from error message in dlerror() on Windows

---

storage/innobase/buf/buf0buf.cc
storage/innobase/buf/buf0flu.cc
storage/innobase/include/buf0buf.h

- Currently page cleaner thread will stop flushing if
dirty_pct < srv_max_dirty_pages_pct_lwm.
- If the server is not performing any activity then said resources/time
could be used to flush the pending dirty pages and keep buffer pool
clean for the next burst of the cycle. This flushing is called idle flushing.
- flushing logic underwent a complete revamp in 10.5.7/8
and as part of the revamp idle flushing logic got removed.
- New proposed logic of idle flushing is based on updated logic of the
page cleaner that will enable idle flushing if
- buf page cleaner is idle
- there are dirty pages (< srv_max_dirty_pages_pct_lwm)
- server is not performing any activity
Logic will kickstart the idle flushing bounded by srv_io_capacity.
(Thanks to Marko Makela for reviewing the patch and idea
right …

MDEV-24949: Enabling idle flushing (possible regression from MDEV-23855)

---

extra/mariabackup/xtrabackup.cc

In this platform, it s better not to rely on optional proc filesystem presence.
Using native API to retrieve binary absolute path instead.

mariabackup little FreeBSD update support.

---

include/my_atomic_wrapper.h
storage/innobase/include/buf0buf.h
storage/innobase/include/ut0counter.h

track page-access counter
As part of MDEV-21212, n_page_gets that is meant to track page access,
is ported to use distributed counter that default uses atomic sub-counters.
n_page_gets originally was a non-atomic counter that represented an approximate
value of pages tracked. Using the said analogy it doesn't need to be
an atomic distributed counter.
This patch introduces an interface that allows distributed counter to be
used with atomic and non-atomic sub-counter (through template) and also
port n_page_gets to use non-atomic distributed counter using the said
updated interface.

MDEV-25281: Switch to use non-atomic (vs atomic) distributed counter to

---

include/my_cpu.h

            memory barrier on ARM
As suggested in the said JIRA ticket based on the contribution done by
the community (in an attempt to optimize the spin-loop) the said approach
was evaluated against MariaDB Server 10.5 and found to help improve
throughput in the range of 2-5%.
Note: 10.6 timing graph and model are different as home-brew
mutexes are replaced with pthread mutexes. Said patch has mixed
impact on 10.6 so not recommended for 10.6.

MDEV-24630: MY_RELAX_CPU assembly instruction upgrade/research for

---

extra/mariabackup/innobackupex.cc
extra/mariabackup/xtrabackup.cc
extra/mariabackup/xtrabackup.h
mysql-test/suite/mariabackup/innodb_force_recovery.result
mysql-test/suite/mariabackup/innodb_force_recovery.test
storage/innobase/srv/srv0start.cc

During the prepare phase of restoring backups, `mariabackup` does not seem to allow (or recognize) the option `innodb_force_recovery` for the embedded InnoDB server instance that it starts.
If page corruption observed during page recovery, the prepare step fails. While this is indeed the correct behavior ideally, allowing this option to be set in case of emergencies might be useful when the current backup is the only copy available. Some error messages during `--prepare` suggest to set `innodb_force_recovery` to `1`:
```
[ERROR] InnoDB: Set innodb_force_recovery=1 to ignore corruption.
```
For backwards compatibility, `--innobackupex --apply-log` should also have this option.

MDEV-24197: Add option "innodb_force_recovery" for "mariabackup"

---

debian/autobake-deb.sh
debian/control

MariaDB Server still supports Ubuntu 16.04 "Xenial" until it goes EOL
in April 30, 2021. Thus we need to include a customization for backwards
compatibility.

Deb: Stop depending on empty transitional package dh-systemd

---

debian/autobake-deb.sh
debian/salsa-ci.yml

The commit https://github.com/mariadb-corporation/mariadb-columnstore-engine/commit/d9fa408ecee1e92b9724117aff65ffc2b00a0dee for ColumnStore 5.5.1.2 is now on 10.5 and 10.6, so this issue is completely solved and workaround can be cleaned away.

MCOL-4535: Clean up libreadline as ColumnStore no longer needs it

---

sql/threadpool_generic.cc

In NetBSD 9.x and prior, udata is an intptr_t, but in 10.x (current
development branch) it was changed to be a void * for compatibility
with other BSDs a year or so ago.
Unfortunately, this does not simplify the code, as NetBSD 8.x and 9.x
are still supported and will be for a few more years.
All of my contributions are freely available under the new BSD license.

Support future NetBSD kqueue versions

---

.github/pull_request_template.md

I would love for this to be a starting point for a discussion on whether or not we should add a PR template file for the server repository, whether there is a particular format that we should follow if a PR template file is desired, etc.
Basically, I would love to hear your opinions on this.
I made a case in this [comment](https://github.com/MariaDB/server/pull/1776#issuecomment-796783537) for why I believe we definitely need something like this in our daily workflow.

Add Pull Request template file to the MariaDB/server repository

---

debian/additions/innotop/innotop
debian/additions/innotop/innotop.1

Synced from downstream Debian:
https://salsa.debian.org/mariadb-team/mariadb-10.5/-/commit/7015e8e4b5ed3a7727a8e442039fceb2c5b1a6b9
Also fix two spelling errors.

Deb: Innotop: Add support for MariaDB 10.5+

---

debian/autobake-deb.sh
debian/mariadb-server-10.5.README.Debian
debian/mariadb-server-10.5.mysql.default
debian/mariadb-server-10.5.postinst
debian/rules
debian/salsa-ci.yml
debian/tests/control
debian/tests/smoke

* Clean up autobake-deb.sh
- No need to define any TokuDB rules, there is no such package
- No need to define RocksDB arch, it already has "Architecture:" line
- No need to dh-systemd backwards compat stanza, neither Debian Jessie
nor Ubuntu Xenial has any new MariaDB 10.5 releases anymore
- Minor spelling fixes
* Ensure dch runs non-interactively so builds pass with new dch version
A recent version of dch (available in Ubuntu Hirsute and Debian Bullseye)
had a change in behaviour that it started prompting if the DEBEMAIL or
EMAIL variable as unset, asking for confirmation. We can't have anything
interactive in our build scripts, so prevent this prompt by giving
--controlmaint to the command, so it always uses the name and email from
the debian/control file and does not prompt anything. …

Deb: Misc cleanup and autobake-deb.sh and Salsa-CI fixes

---

debian/mariadb-plugin-connect.install

This partially reverts commit d7321893d8c50071632a102e17a7869da9cb03a5.
The *.jar files are not being built and all Debian builds are failing
as dh_install stops on missing files. To build them we would need to also
add new Java build dependencies.
In a stable release (10.2->10.5) we shouldn't add new files and certainly
not any new build dependencies, so reverting commit.
Also, the files are located in a different path, and already included
in the mariadb-test-data package:
/usr/share/mysql/mysql-test/plugin/connect/connect/std_data/JavaWrappers.jar
/usr/share/mysql/mysql-test/plugin/connect/connect/std_data/JdbcMariaDB.jar
/usr/share/mysql/mysql-test/plugin/connect/connect/std_data/Mongo2.jar
/usr/share/mysql/mysql-test/plugin/connect/connect/std_data/Mongo3.jar
This change needs to be …

Revert "CONNECT: move jar files to /usr/share and include them in DEBs"

---

cmake/os/OpenBSD.cmake

In the past I have disabled the libexecinfo support for our port / package, but -current has now imported libexecinfo into base. The header is found. Need to fix finding the libexecinfo library.

Link with libexecinfo on OpenBSD for stacktrace functionality.

---

.gitlab-ci.yml

As Travis-CI has stopped offering free testing for open source projects,
and they don't seem to have any plans to revert their new restrictions,
MariaDB no longer has a good CI system outside contributors could run
independently for basic validation before submitting Pull Requests.
Implement a simple Gitlab-CI pipeline that runs basic RPM builds on
one old, one less old and one very new distro release and then do some
basic tests on the RPM packages to validate they installed and the
server actually runs.
See it in action at https://gitlab.com/ottok/mariadb/-/pipelines/313059780
- Makes use of standard CMake and `make package` commands and thus simulates as closely as possible a "normal" MariaDB build.
- Runs the build on a recent Fedora, Centos 8 and Centos 7 in parallel to ensure that …

Implement simple Gitlab-CI pipeline for MariaDB with RPM builds

---

debian/salsa-ci.yml

SHOW PLUGINS has a more complete view of the installed
plugins into the server.
The mysql.user is a compatibility view that doesn't
show the complete authentication picture. Use global_priv.
Add `show create user` for default users to more clearly
represent its contents.
No JIRA Issue.
As mentioned previously the mysql.user view isn't predicatable. This adds the right extraction of system users/ plugins so that it can be more accurately read.
Pushing through salsa when it ends up there.
This is the first branch with a salsa file.
no considerations necessary.

debian/salsa: Show complete auth and plugin situtation

---

include/mysql/service_json.h

Signed-off-by: Michael Okoko <okokomichaels@outlook.com>
I had to work with some of the JSON parser functions while working on MDEV-21130. They were helpful but also, the comments could be improved. This tries to make it clearer e.g., 
- by describing how to get desired values after calling `json_get_array_item`

Improve documentation of json parser functions

---

storage/spider/mysql-test/spider/bugfix/include/mdev_24517_deinit.inc
storage/spider/mysql-test/spider/bugfix/include/mdev_24517_init.inc
storage/spider/mysql-test/spider/bugfix/r/mdev_24517.result
storage/spider/mysql-test/spider/bugfix/t/mdev_24517.cnf
storage/spider/mysql-test/spider/bugfix/t/mdev_24517.test
storage/spider/spd_db_mysql.cc

how to repeat:
CREATE TABLE t1(i INT PRIMARY KEY, j JSON)ENGINE=spider...
INSERT INTO t1 VALUES(1, '{"Name":"Tom", "Age":18}'), (2, '{"Name":"Jerry", "Age":20}');
SELECT * FROM t1 WHERE json_extract(jdoc, '$.Age')=20; -- ERROR 1064 (42000): You have an error in your SQL syntax;
how to solve:
Let Spider process Item_func::JSON_EXTRACT_FUNC as Item_func::UNKNOWN_FUNC does

MDEV-24517: JSON_EXTRACT as select conditions syntax error on Spider

---

plugin/auth_socket/CMakeLists.txt
plugin/auth_socket/auth_socket.c

Documentation for LOCAL_PEEREID: https://man.netbsd.org/unix.4
License: 2 clause BSD

auth_socket: Add SO_PEERCRED definitions for NetBSD

---

scripts/mysql_setpermission.sh

Hi,
It seems that there is some kind of logic confusion in mysql set_permission perl script. By default all connections parameters are read from configuration file of mariadb:
https://github.com/MariaDB/server/blob/10.7/scripts/mysql_setpermission.sh#L61
Fresh installation of mariadb on Fedora does not contain any connection information in configuration file. It falls back automatically to localhost DB. Nothing wrong with that.
Trying to execute mysql_setpermission with this configuration will fail:
```
mysql_setpermission fails to connect to local mariadb, claiming that 
DBI connect(';host=localhost;port=3306','newuser',...) failed: Connection error: port cannot be specified when host is localhost or embedded at /usr/bin/mysql_setpermission line 116.
```
I don't think that's correct …

MDEV-26474: Fix mysql_setpermission hostname logic

---

client/mysql_plugin.c

`$ echo -e "auth_socket\nunix_socket">>auth-ini.ini`
`$ echo -e "ha_rocksdb\nrocksdb">>rock.ini`
Use configuration file (all groups - related to PR #1262 ):
`./client/mysql_plugin -v -f ./extra --plugin_ini=./client/auth-ini.ini unix_socket ENABLE`
or:
`./client/mysql_plugin -v -f ./extra --basedir=. --datadir=../datadir-10.2 --plugin_dir=./storage/rocksdb/ --plugin_ini=./client/rock.ini -l ./sql/share rocksdb ENABLE`

MDEV-19227: mysql_plugin doesn't run bootstrap from source

---

debian/autobake-deb.sh
debian/rules
debian/salsa-ci.yml
debian/source/lintian-overrides

The debian/salsa-ci.yml used to work also on upstream MariaDB.org branches,
but has recently regressed and several jobs stopped working. These fixes
are necessary to get it working again.
* Partially revert 8642f592 that never worked, as MariaDB 10.2 does not
have a mysql.global table nor a mariadb.sys user. Those features weren't
introduced until MariaDB 10.4.
* Partially revert 0268b871 as we don't want ColumnStore as part of the
native Debian build. It should build only when the build is triggered
via autobake-deb.sh (MariaDB.org builds).
* Add Lintian overrides for systemd service file location error that is
most likely a bug in Lintian or incompatibility with dh_systemd.
* Adjust salsa-ci.yml to cope with various Stretch to Sid upgrade issues
and remove the legacy mariadb-connector-c …

Deb: Fix Gitlab-CI/Salsa-CI builds failures

---

.gitlab-ci.yml
cmake/cpack_rpm.cmake

- Add new Ninja and Clang build jobs. This helps to ensure those
toolchains also work in addition to default CMake/gcc.
- Generate dependencies.dot/png to illustrate the CMake/Make/Ninja
build dependencies. Viewing this image and identifying bottle necks
in parallelism can help make the build run faster.
- Enable CUnit tests now as they are fixed on 10.6 (MDEV-25820).
- Limit parallel builds to 2 CPUs (full parallelism needs MDEV-25968) on
CMake/Make. Now only the Ninja builds run full parallel builds as only
Ninja is smart enough to prevent builds failing on resource
over-consumption.
- Enable Gitlab-CI cache for job 'centos8' for ccache so that it builds
faster. Don't use Gitlab-CI cache for other jobs, as it would too easily
use up all free tier storage on Gitlab.com and force users to …

Misc improvements to the Gitlab-CI pipeline for MariaDB

---

include/my_global.h

Xcode on latest Apple silicone for development
Build using Xcode with Apple M1 CPU

10.2 MDEV-19129 buildfix

---

debian/control

**NOTE!** This was split off #1734 to have a part of the changes on 10.7 branch instead of 10.5.

Deb: Sync build and runtime dependencies from downstream to upstream

---

mysql-test/r/parser.result
mysql-test/t/parser.test
sql/sql_lex.cc

There is a scientific notation bug that uses the e notation which was discovered many years ago and was used to bypass some Web Application Firewall.
With more research, I found out more use case to this bug and that it is possible to bypass modern WAF as the query seems to be invalid but is valid.
So the following query that seems to be invalid:
```
mysql> select id 1.e, char 10.e(id 2.e), concat 3.e('a'12356.e,'b'1.e,'c'1.1234e)1.e, 12 1.e*2 1.e, 12 1.e/2 1.e, 12 1.e|2 1.e, 12 1.e^2 1.e, 12 1.e%2 1.e, 12 1.e&2 from test;
+------+--------------------------------------+------------------------------------------+----------+----------+----------+----------+----------+----------+
| id   | char 10.e(id 2.e)                    | concat 3.e('a'12356.e,'b'1.e,'c'1.1234e) | 12 1.e*2 | 12 1.e/2 | …
```

MDEV-27066 Fixed scientific notation parsing bug

---

debian/additions/mariadb.conf.d/50-server.cnf

There's no need for Debian to set config items to their
default. Left commented socket, user, datadir and tmpdir as
these may want to be changed. lc-messages and skip-external-locks
are so infrequently set even listing them looks overly verbose.

Debian: comment default config

---

mysql-test/main/upgrade_geometrycolumn_procedure_definer.result
mysql-test/main/upgrade_geometrycolumn_procedure_definer.test
scripts/mysql_system_tables_fix.sql

From 10.4.13, the `mariadb.sys` user was created to replace `root` definers.
- In commit 0253ea7f2208354b187ffcfa2f3128878597cc11, definer of
Add/DropGeometryColumn procedures was changed to `mariadb.sys`, in
`scripts/maria_add_gis_sp.sql.in`.
However, maria_add_gis_sp.sql only applies to new databases created by
installation script. Databases upgraded from old versions will miss this
change.
- In addition, according to commit
0d6d801e5886208b2632247d88da106a543e1032(MDEV-23102), in some scenarios
when root user is replaced it will skip creating `mariadb.sys` user.
This commit is to update the definer from `root` to `mariadb.sys` during
upgrade. It only makes the change if the original definers are root.
Doesn't choose to execute `maria_add_gis_sp.sql` in upgrade script to
recreate the …

Update definer of Add/DropGeometryColumn procedures from 'root' to 'mariadb.sys' 

---

mysys/lf_alloc-pin.c
mysys/lf_hash.c
unittest/mysys/thr_template.c

MariaDB server crashes on ARM (weak memory model architecture) while
concurrently executing l_find to load node->key and add_to_purgatory
to store node->key = NULL. l_find then uses key (which is NULL), to
pass it to a comparison function.
The specific problem is the out-of-order execution that happens on a
weak memory model architecture. Two essential reorderings are possible,
which need to be prevented.
a) As l_find has no barriers in place between the optimistic read of
the key field lf_hash.cc#L117 and the verification of link lf_hash.cc#L124,
the processor can reorder the load to happen after the while-loop.
In that case, a concurrent thread executing add_to_purgatory on the same
node can be scheduled to store NULL at the key field lf_alloc-pin.c#L253
before key is loaded in l_find. …

MDEV-27088: Server crash on ARM (WMM architecture) due to missing barriers in lf-hash (10.2)

---

mysys/lf_alloc-pin.c
mysys/lf_hash.cc

MariaDB server crashes on ARM (weak memory model architecture) while
concurrently executing l_find to load node->key and add_to_purgatory
to store node->key = NULL. l_find then uses key (which is NULL), to
pass it to a comparison function.
The specific problem is the out-of-order execution that happens on a
weak memory model architecture. Two essential reorderings are possible,
which need to be prevented.
a) As l_find has no barriers in place between the optimistic read of
the key field lf_hash.cc#L117 and the verification of link lf_hash.cc#L124,
the processor can reorder the load to happen after the while-loop.
In that case, a concurrent thread executing add_to_purgatory on the same
node can be scheduled to store NULL at the key field lf_alloc-pin.c#L253
before key is loaded in l_find. …

MDEV-27088: Server crash on ARM (WMM architecture) due to missing barriers in lf-hash (10.5)

---

mysql-test/suite/galera/r/galera_UK_conflict.result
mysql-test/suite/galera/t/galera_UK_conflict.test

- [] *The Jira issue number for this PR is: MDEV-_____*
mtr test galera.galera_UK_conflict, has rather distorted logic in test scenario 2.
The test would fail always with:
CURRENT_TEST: galera.galera_UK_conflict
mysqltest: In included file "./include/galera_wait_sync_point.inc":
included from /home/seppo/work/wsrep/mariadb-server/mysql-test/suite/galera/t/galera_UK_conflict.test at line 216:
At line 3: query 'SET SESSION wsrep_on = 0' failed: 1179: You are not allowed to execute this command in a transaction
This happens because wait_condition is called in wrong connection (node_1, which is executing MST transaction)
This test is fixed by using control connection for wait condition checking, and new result is recorded as well

Fix for the test galera.galera_UK_conflict

---

debian/salsa-ci.yml

Upstream Salsa-CI refactored the build process in
https://salsa.debian.org/salsa-ci-team/pipeline/-/commit/58880fcef5b742cb9c661121a8c8707bf392b3b5
This broke our custom direct invocation of install-build-deps.sh as the
Salsa-CI images no longer contain them. Adapt the .build-script
equivalent to follow new Salsa-CI method so builds work again.
Only affects Salsa-CI.

Deb: Adapt custom build steps to be compatible with latest Salsa-CI

---

include/my_rdtsc.h
mysys/my_rdtsc.c

This pr adds cycle clock implementation for riscv. It is modified from https://reviews.llvm.org/D78084 and https://github.com/google/benchmark/blob/3b3de69400164013199ea448f051d94d7fc7d81f/src/cycleclock.h#L190. 
I have tested on sifive unmatched board (riscv64) running gentoo. Unfortunately, I am not familiar with freebsd etc, so not sure if ```__GNUC__``` can be removed.

MDEV-27429: Support riscv cycle timer

---

man/mysql_install_db.1
scripts/mysql_install_db.sh

The mysql_install_db script is used to initialize the data directory.
However, if the user needs to apply some customized init commands (for
example to change user or password) they have to start the database
with `--skip-grant-tables` after the install script, and then restart
the database with normal mode.
To make it easier to include customization in the mysql_install_db
script, in this commit, a new parameter `extra-init-file` is added in
mysql_install_db script to support some extra customized init commands.
With this option we can support applying extra init file for
mysql_install_db command line at runtime, which reduces the complexity
of customized initialization process.
This script is only used for install and is not included in the mtr
bootstrap file. Commit also updates the …

MDEV-21252: Support extra initialization file for mysql_install_db

---

cmake/systemd.cmake
support-files/mariadb.service.in
support-files/mariadb@.service.in

Add SYSTEMD_READWRITEPATH-variable to mariadb.service.in to make sure that
if one is not building RPM or DEB packages then make sure there is ReadWritePaths
directive is defined in systemd service file.
This ensures that tar-ball installation has right to write database default
installation path (default: /usr/local/mysql/data) even if it's located
under /usr. Writing to that location is prevented by 'ProtectSystem=full'
systemd directive by default.
Merge PR and make cpack tar ball. Then in support-files/mariadb.service file there should be ReadWritePaths-directive pointing to /usr/local/mysql/data.
This is upward compatible

MDEV-26317: Make sure that tar-ball has write permissions to default database path

---

mysql-test/main/mysql_tzinfo_to_sql_symlink.result
mysql-test/main/mysql_tzinfo_to_sql_symlink.test
mysql-test/suite/wsrep/r/mysql_tzinfo_to_sql_symlink.result
sql/tztime.cc

The --skip-write-binary-log added to mysql_tzinfo_to_sql in
MDEV-18778 was only effective if galera was enabled on the server.
This is because it tied together three concepts under one option:
1. binary logging
2. wsrep replication, and
3. using innodb as a transitional table type.
Change 1: small change in help option to reflect this.
To solve the performance problem with Aria tables, LOCK TABLES WRITE
is used to eliminate the need to fdatasync until the UNLOCK TABLES.
If galera isn't enabled, then we also want to use the LOCK TABLE WRITE
mechanism.
The START TRANSACTION added in MDEV-23440 needed to be moved to
before LOCK TABLES otherwise it would cancel their effect.
TRUNCATE TABLE statements also need to be before the LOCK TABLES.
When changing back from InnoDB to Aria, include the …

MDEV-23326: Aria significantly slow on timezone intialisation

---

mysql-test/r/func_system.result
mysql-test/t/func_system.test
sql/item_strfunc.h

Database names are 64 utf8 characters per the system tables
that refer to them.
The current database() function is returning 34 characters.
The result of limiting this function results to max length of 34
became apparent when used in a UNION ALL where the results are
truncated to 34 characters.
For (uninvestigated) reasons, SELECT DATABASE() on its own
would always return the right number of characters.
Thanks Alexander Barkov for the review.
Thanks dave for noticing the bug in the stackexchange post
https://dba.stackexchange.com/questions/306183/why-is-my-database-name-truncated
mtr test case include
Previous tables auto created from `database()` might be 34 characters (like the …

MDEV-27544 database() function should return 64 characters

---

.gitlab-ci.yml
debian/mariadb-server-10.8.install
support-files/CMakeLists.txt
support-files/mini-benchmark.sh

Running a small 10 minute benchmark on every commit will help to catch if
there are severe performance regressions introduced.
Also bump MARIADB_MAJOR_VERSION to 10.7 which is needed on the 10.7 branch.

Extend the Gitlab-CI pipeline to run mini benchmark

---

storage/innobase/os/os0file.cc

Ran into this while compiling on FreeBSD 13.0-RELEASE
After this one change, it compiles and runs just fine on my FreeBSD Aarch64 server.

MDEV-27790: Fix mis-matched braces for compiling on non-Linux targets

---

storage/perfschema/my_thread.h

This uses uintptr_t, so needs including cstdint
While building on GNU/Hurd, I got a build error in perfschema, because uintptr_t is used in my_thread.h but cstdint is not included.
This would need to introduce in the CI a profile that exercices the  HAVE_INTEGER_PTHREAD_SELF case.

MDEV-27804 Fails to build - perf schema - thread id of type uintptr_t requires header

---

storage/innobase/dict/dict0stats_bg.cc

- regression got revealed while running tpcc workload.
- as part of MDEV-25919 changes logic for statistics computation was revamped.
- if the table has changed to certain threshold then table is added to
statistics recomputation queue (dict_stats_recalc_pool_add)
- after the table is added to queue the background statistics thread is
notified
- during revamp the condition to notify background statistics threads was
wrongly updated to check if the queue/vector is empty when it should
check if there is queue/vector has entries to process.
- vec.begin() == vec.end() : only when vector is empty
- also accessing these iterator outside the parallely changing vector is not
safe
- fix now tend to notify background statistics thread if the logic adds
an entry to the queue/vector.
TODO: fill …

MDEV-27805: tpcc workload shows regression with MDB-10.6

---

sql/wsrep_mysqld.cc
sql/wsrep_utils.h

This PR removes some dead code clutter.

Removed dead code.

---

scripts/wsrep_sst_mariabackup.sh
sql/wsrep_notify.cc
sql/wsrep_utils.cc
sql/wsrep_utils.h

This PR removes some dead code clutter.

Preview 10.9 mdev 26971 json status

---

mysys/crc32/crc32c.cc

Remove C++ `<string>` from `crc32c.cc` since it is not used by  `crc32c.cc`

Remove unused header from crc32c.cc

---

mysql-test/suite/perfschema/r/sxlock_func.result
mysql-test/suite/perfschema/t/sxlock_func.test
storage/innobase/handler/ha_innodb.cc
storage/innobase/include/srw_lock.h
storage/innobase/include/trx0rseg.h
storage/innobase/include/univ.i
storage/innobase/trx/trx0purge.cc
storage/innobase/trx/trx0rec.cc
storage/innobase/trx/trx0rseg.cc
storage/innobase/trx/trx0sys.cc
storage/innobase/trx/trx0trx.cc
storage/innobase/trx/trx0undo.cc

- In 10.6, trx_rseg_t mutex was ported to use latch. As part of this porting
profiling of the patch was removed. This patch reenables it given that
the said latch continues to occupy the top slots in the contention list.
- Run any write-workload with performance schema enabled and try to track trx_rseg latch-based contention.
- [X ] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*
N.A.

MDEV-27935: Enable performance_schema profiling for trx_rseg_t latch

---

extra/mariabackup/xtrabackup.cc
mysql-test/main/dyncol.result
mysql-test/main/dyncol.test
mysql-test/suite/archive/discover.result
mysql-test/suite/archive/discover.test
mysql-test/suite/mariabackup/log_page_corruption.result
mysql-test/suite/mariabackup/log_page_corruption.test
scripts/sys_schema/README.md
scripts/sys_schema/procedures/table_exists.sql
sql/semisync_master_ack_receiver.h
sql/sql_table.cc
storage/maria/ha_s3.cc

Fix various spelling errors
Among others:
existance -> existence
reinitialze -> reinitialize
successfuly -> successfully

Fix various spelling errors

---

mysql-test/suite/innodb/r/innodb_buffer_pool_resize_bigtest.result
mysql-test/suite/innodb/t/innodb_buffer_pool_resize_bigtest.opt
mysql-test/suite/innodb/t/innodb_buffer_pool_resize_bigtest.test
storage/innobase/buf/buf0buddy.cc
storage/innobase/buf/buf0buf.cc
storage/innobase/buf/buf0flu.cc
storage/innobase/buf/buf0lru.cc
storage/innobase/include/buf0buf.h

During an increase in resize, the new curr_size got a value
less than old_size.
As n_chunks_new and n_chunks have a strong correlation to the
resizing operation in progress, we can use them and remove the
need for old_size.
n_chunks_new and n_chunks are always read and altered under
the pool mutex, the running_out function does the same. Also
the volatile compiler optimization is removed.
Added test case of a smaller size than the Marko/Roel original
in JIRA reducing the size to 200M. SEGV hits roughly 1/10 times
but its better than a 21G memory size.
----
Existing innodb buffer pool resize tests included sizes/options that where incompatible with triggering this bug hence the new test file.
Original cause of old_size error unidentified. gdb and rr on the test case failed to trigger the …

MDEV-27891: SIGSEGV in InnoDB buffer pool resize

---

mysql-test/r/error_simulation.result
mysql-test/r/truncate_notembedded.result
mysql-test/t/error_simulation.test
sql/mysqld.cc
sql/sys_vars.cc

When `max_session_mem_used` is set and exceeded, the server responds with an error, but call the option name as `max-thread-mem-used`. This is due to a type in `my_malloc_size_cb_func` inside `sql/mysqld.cc`. There is no `max-thread-mem-used` option in MariaDB, only `max-session-mem-used`.
Test case and result is included in `error_simulation.test` and `error_simulation.result`. It was tested successfully in my local branch.

MDEV-27978 fix wrong name in error when max_session_mem_used exceeded

---

.gitlab-ci.yml

The commits a73acf6c068a39d0bb9437e05b0b60a87e46bba8 and
4d74bac8bc8c14c2b217391b3b8860f3dc701202 updated the PCRE library to a new
version, which in turn requires CMake 3.0. That does not exist in CentOS 7
nor 8, so builds started failing.
Actually the build should not be downloading anything at all. The root
cause was that pcre2-devel was missing from the dependencies. This was
originally not detected, as the download fallback had masked the issue.

Fix failing Gitlab-CI by adding pcre2-devel as a build dependency

---

debian/autobake-deb.sh

zstd-1.1.3 is needed however stretch has only 1.1.2.
Move to distro version based checks as checks against the
apt-cache are unreliable if there is no cache.
See if it builds on stretch
No issues identified.

MDEV-28022: Debian stretch has zstd too old

---

mysql-test/suite/binlog/r/binlog_xa_recover_using_new_server_id.result
mysql-test/suite/binlog/t/binlog_xa_recover_using_new_server_id.test
sql/handler.cc
sql/handler.h

Commit 6c39eaeb1 made the crash recovery dependent on server_id.
The crash recovery could fail when restoring a new instance from
original crashed data directory USING A NEW SERVER ID.
The issue doesn't exist in previous major versions before 10.6.
Root cause is when generating the input XID to be searched in the hash,
server id is populated with the current server id.
So if the server id changed when recovering, the XID couldn't be found
in the hash due to server id doesn't match.
This fix is to use original server id when creating the input XID
object in function `xarecover_do_commit_or_rollback`.
I've verified manually the issue was fixed with the commit.
Also a new MTR test binlog.binlog_xa_recover_using_new_server_id is added to verify the scenario.
All new code of the whole pull …

MDEV-27342: Fix issue of recovery failure using new server id

---

debian/salsa-ci.yml
debian/source/lintian-overrides

Since Debian Sid now has MariaDB 10.6, we can't do upgrade tests on the
10.5 branch in Sid anymore, it just fails with downgrade errors.
Also, since MariaDB 10.5 is no longer in Sid, we can't even test 10.5.x
to 10.5.y upgrades in Sid.
Instead the 10.5 branch salsa-ci.yml should run all builds and tests based
on Debian Bullseye, which has MariaDB 10.5 (only).
To achieve this, essentially sync most the the salsa-ci.yml contents from
https://salsa.debian.org/mariadb-team/mariadb-10.5/-/tree/bullseye
Also add a couple Lintian overrides to make Salsa-CI pass.
**NOTE TO MERGERS: This commit is intended for the 10.5 branch only, do not
merge anything from it on 10.6 or any other branch.**
See CI result at https://salsa.debian.org/mariadb-team/mariadb-server/-/pipelines/354230 (failure in …

Deb: Sync Salsa-CI from Debian MariaDB 10.5 repository

---

debian/control

There is not Extended description available for compression provider package which are requires in `Debian Policy Manual section 3.4` 
PR fixes Lintian errors:
```
E: mariadb-plugin-provider-bzip2: extended-description-is-empty
E: mariadb-plugin-provider-lz4: extended-description-is-empty
E: mariadb-plugin-provider-lzma: extended-description-is-empty
E: mariadb-plugin-provider-lzo: extended-description-is-empty
E: mariadb-plugin-provider-snappy: extended-description-is-empty
```
Which is cause missing Debian Policy Manual section 3.4 (The description
of a package) extended descriptions in mariadb-plugin-provide-*
packages
Salsa-CI has CI run located https://salsa.debian.org/illuusio/mariadb-server/-/jobs/2581906/raw that does not contain errors. Manually:
```
apt install lintian
cd …
```

MDEV-28120: Clean lintian 'extended-description-is-empty' errors

---

debian/mariadb-plugin-provider-bzip2.lintian-overrides
debian/mariadb-plugin-provider-lz4.lintian-overrides
debian/mariadb-plugin-provider-lzma.lintian-overrides
debian/mariadb-plugin-provider-lzo.lintian-overrides
debian/mariadb-plugin-provider-snappy.lintian-overrides

Provider Plugins throws Lintian False-Positive Errors. This because these shared objects does not share any symbols from Glibc and Lintian uses command `objdump -X` to check exactly which symbols are required by shared object. As Lintian error itself if correct it's not error and it's false-positive which should be overrided with `.lintian-overrides`-files
PR fixes Lintian errors:
```
E: mariadb-plugin-provider-bzip2: library-not-linked-against-libc usr/lib/mysql/plugin/provider_bzip2.so
E: mariadb-plugin-provider-lz4: library-not-linked-against-libc usr/lib/mysql/plugin/provider_lz4.so
E: mariadb-plugin-provider-lzma: library-not-linked-against-libc usr/lib/mysql/plugin/provider_lzma.so
E: mariadb-plugin-provider-lzo: library-not-linked-against-libc usr/lib/mysql/plugin/provider_lzo.so …
```

MDEV-28120: Remove false-positive Lintian linking error

---

debian/autobake-deb.sh

The autopkgtest was failing due to missing *.changes file. This is part
of source build, so revert autobake-deb.sh back to NOT using -b for
Gitlab-CI/Salsa-CI runs.
Before, failing autopkgtestin CI: https://salsa.debian.org/mariadb-team/mariadb-server/-/pipelines/362475
After, successful CI: https://salsa.debian.org/mariadb-team/mariadb-server/-/pipelines/362464

Deb: Fix Salsa-CI autopkgtest failure

---

plugin/server_audit/server_audit.c

On the aarch64 platform, MySQL 5.7.33 cannot install the audit plugin of Mariadb-10.2.43 version, but it can run normally on the X86_64 platform.
Install the audit plugin of version 10.2.43 on MySQL 5.7.33 on aarch64 platform.

MDEV-28177: Update the offset of dbName on the aarch64 platform.

---

storage/innobase/CMakeLists.txt

CMAKE_SYSTEM_PROCESSOR on AIX is "powerpc". To
de-conflict with the Linux 32bit arch of the same
name, CMAKE_SYSTEM_NAME was used in the CMakeLists.txt
test to enable -mhtm in the same way that was required
for Linux ppc64{,le} compilers in MDEV-27936

MDBF-348: innodb aix htm support

---

debian/salsa-ci.yml
debian/source/lintian-overrides

As MariaDB 10.5 has been removed from Debian Sid and MariaDB 10.6 has
entered it, the Salsa-CI testing needs to adapt.
To achieve this, essentially sync most the the salsa-ci.yml contents from
https://salsa.debian.org/mariadb-team/mariadb-server/-/tree/debian/latest
Also add a couple Lintian overrides to make Salsa-CI pass.
NOTE TO MERGERS: This commit is made on 10.6 branch and can be merged to
all later branches (10.7, 10.8, 10.9..) for now, but later somebody needs
to go in and update all the testing stages to do the upgrade testing
correctly for 10.6->10.7->10.8->10.9 etc.
Before, broken: https://salsa.debian.org/mariadb-team/mariadb-server/-/pipelines/363479
After, fixed: https://salsa.debian.org/mariadb-team/mariadb-server/-/pipelines/363480

Deb: Sync Salsa-CI from Debian MariaDB 10.6

---

debian/tests/control
debian/tests/smoke

Add compression plugins:
* bzip2
* lz4
* lzma
* lzo
* snappy
To Autopkg's basic smoke-test dependencies.
Also make sure that MariaDB service is reloaded
when smoke-test is executed.
Salsa-CI has CI run located https://salsa.debian.org/illuusio/mariadb-server/-/jobs/2582162/raw that does not contain errors. Manually:
```
apt install debci
cd mariadb-server
debian/autobake-deb.sh
..wait..
cd ..
debci -c "debci localtest $WORKING_DIR/*.changes"
```
Smoke test should pass
This should no affect backward compatibility

MDEV-28121: Add new compression plugins as autopkg dependencies

---

debian/salsa-ci.yml

As as discussed with @dbart we decided to move https://deb.mariadb.org/repo to https://deb.mariadb.org so that a
request on https://deb.mariadb.org will end up directly in https://mirror.mariadb.org/repo.
The same behavior was configured for rpms (https://rpm.mariadb.org --> https://mirror.mariadb.org/yum) this also makes the old yum.mariadb.org service transparently compatible with this new service (after DNS change to point to rpm.mariadb.org).
See also: https://jira.mariadb.org/browse/MDBF-297

Change MDBF mirror URL

---

extra/innochecksum.cc
mysql-test/main/thread_pool_info.test

Aix now that its enabled again, has a few mtr failures.
First AIX has no threadpool, so disable the test.
The second innochecksum has different behaviour in the OS fseeko function as described in the commit message.
innodb_zip.innochecksum_3,4k,crc32,innodb covers the innochecksum test.
AIX supported from 10.5

aix mtr fixes MDEV-28250 + disable threadpool test

---

debian/autobake-deb.sh
debian/rules
debian/salsa-ci.yml

With autobake-deb.sh no doing explicit dependencies, we need to run this
explicitly as a prep step in salsa-ci so the dependencies can be pulled
before the real compilation begins.
Resolves 10.5 part of salsa in #2039.
Currently running on https://salsa.debian.org/grooverdan/mariadb-server/-/pipelines/361865)
(10.8 test timed out)

MDEV-28153: Debian autobake- use absolute dependencies

---

mysql-test/mysql-test-run.pl

This issue is caused by a function `usage()` in mariadb-test-run.pl.
When we try to run `perl ./mtr` with the wrong option (in the example, `perl ./mtr --ps--protocol`), a function `usage()` in mariadb-test-run.pl is called with the wrong option as its argument. In this case, because the function call `exit;` in a first if statement, we get exit status `0`. However, the expected status is `1`.
Call these commands on a terminal
```bash
$ perl ./mtr --ps--protocol
$ echo $?
```
The expected output is as follows:
```bash
$ perl ./mtr --ps--protocol
Logging: ./mtr  --ps--protocol
VS config: 
Invalid option "--ps--protocol"
For full list of options, use ./mtr --help
$ echo $?
1
```

MDEV-27448: MTR returns success (zero) upon invalid option

---

storage/spider/mysql-test/spider/r/variable_deprecation.result
storage/spider/mysql-test/spider/t/variable_deprecation.test
storage/spider/spd_param.cc
storage/spider/spd_table.cc

There is not much use of the variable ```spider_internal_limit```.
The variable ```spider_internal_limit``` and the corresponding table option are deprecated.
Test case is included in the pull request.

MDEV-27981 Deprecate spider_internal_limit

---

mysql-test/lib/My/CoreDump.pm

GDB has supported -frame-arguments and full for a while.
Let's make our bb logs give a little bit more detail on those
hard to reproduce bugs.
Tested with:
```
$ while [ 1 ]; do sleep 2; killall -SEGV mysqld ; done
```
and
```
mysql-test/mtr innodb_fts.innodb_fts_stopword_charset
...
Thread 27 (Thread 0x7f4d0a8a9640 (LWP 332030)):
#0  0x00007f4d1010823b in fsync () from /lib64/libc.so.6
No symbol table info available.
#1  0x000000000092eb4f in os_file_fsync_posix (file=72) at /home/dan/repos/mariadb-server-10.2/storage/innobase/os/os0file.cc:2526
ret = <optimized out>
failures = 0
#2  os_file_flush_func (file=file@entry=72) at /home/dan/repos/mariadb-server-10.2/storage/innobase/os/os0file.cc:2619
ret = <optimized out>
#3  0x0000000000a6825f in pfs_os_file_flush_func (file={m_file = 72, …
```

mtr: extend gdb backtace to -frame-arguments all full

---

storage/spider/mysql-test/spider/r/variable_deprecation.result
storage/spider/mysql-test/spider/t/variable_deprecation.test
storage/spider/spd_param.cc
storage/spider/spd_table.cc

Deprecate the server variable spider_internal_offset and the corresponding
table parameters "ios" and "internal_offset".
We believe this variable is not much use to users, therefore decided to
deprecate it.
Deprecate the server variable spider_internal_offset and the corresponding
table parameters "ios" and "internal_offset".
All existing tests should pass.
Test cases are added in `spider.variable_deprecation`
It just deprecates the variable, therefore backward compatibility is kept. We may delete the variable in a future release.

MDEV-28297 Deprecate spider_internal_offset

---

mysql-test/suite/gcol/r/innodb_virtual_fk.result
mysql-test/suite/innodb/r/innodb-index-online-fk.result
mysql-test/suite/innodb/r/innodb-index.result
mysql-test/suite/innodb/r/stored_fk.result
sql/share/errmsg-utf8.txt

- Simplified Chinese translation added
- Character encoding is gdk
-- gdk covers more characters
-- gdk includes both Simplified and Traditional
-- best option I think, may need to work along with other locale
settings
- Other cleanup
-- Within each error, messages are sorted according to language code
-- More consistent formatting (8 spaces proceeding each translation)
-- The formatting consistency change makes merging difficult initially. I think we can suffer through the pain now, and subsequent change will be much easier.
This PR is for error message translation. It shouldn't affection any functions of MariaDB. Visual verification and subsequent refinement will be needed after release.
The translation is based on MariaDB 10.4's error messages in English.

MDEV-28227 Error message Chinese translation

---

storage/innobase/row/row0vers.cc

aarch64 RHEL7 and Centos7 internal compiler error here, so we carry
another pragma enchantment like buf0lru.cc and row0ins.cc.
TODO: fill details here, …

MDEV-28313 InnoDB transactions are not aligned at cache lines (postfix)

---

debian/mariadb-server-10.2.postrm
debian/mariadb-server-10.2.preinst

==============
By testing `pgrep` with `--ns` option,
introduced with MDEV-21331, commit https://github.com/MariaDB/server/commit/fb7c1b9415c9a8b0dc2e86ae44f0e7a2634e5d7e,
I noted that:
a) `--ns`  cannot use more than single PID.
b) `--ns` is returning the processes of the namespace to which supplied PID belongs to.
So by that sense command `pgrep -x --ns $$ mysqld` will always return an error and skip
checking of the existing PID of the server.
==============
Suggested solution is to add `--nslist pid`, since `--ns` needs to know in which namespace type it should look for.
See `pgrep --help` for different namespace types.
Note also that this works *only* if script is run as a `root` (we have that case here).
Current PR is a part of:
1. MDEV-21331: sync preinst and postrm script
2. …

Use proper pid namespace

---

support-files/rpm/server.cnf

Update server.cnf to adjust major version to 10.8 group.
For example, adding some options for enabling SSL (ssl_key, ssl_cert, ssl_ca, ssl_cipher)

server.cnf: adjust major version to 10.8

---

sql/table.h

remove some invalid function declaration
N/A. Just compile
You might consider answering some questions like:
1. Does this affect the on-disk format used by MariaDB?
No
2. Does this change any behavior experienced by a user
who upgrades from a version prior to this patch?
No
3. Would a user be able to start MariaDB on a datadir
created prior to your fix?
Yes

remove some invalid function declaration

---

mysql-test/suite/innodb/t/innodb_buffer_pool_resize.test
mysql-test/suite/innodb/t/innodb_buffer_pool_resize_temporary.test
mysql-test/suite/innodb/t/innodb_buffer_pool_resize_with_chunks.test
mysql-test/suite/innodb/t/restart.test
mysql-test/suite/sys_vars/t/innodb_buffer_pool_size_basic.test
storage/innobase/buf/buf0buf.cc
storage/innobase/handler/ha_innodb.cc

InnoDB buffer pool resize messages are more succinct from this change:
Before:
```
2022-05-07 17:10:33 0 [Note] InnoDB: Completed resizing buffer pool from 14745600 to 19660800 bytes.
2022-05-07 17:10:33 0 [Note] InnoDB: Completed resizing buffer pool.
2022-05-07 17:10:33 8 [Note] InnoDB: Completed resizing buffer pool. (New size: 19660800 bytes).
```
After:
```
2022-05-07 17:10:33 0 [Note] InnoDB: Completed resizing buffer pool from 14745600 to 19660800 bytes.
```
This PR just cleans up the output/log messages. Test case may not be necessary.
I have verified the correct, more condensed messages are written to the error log. Reviewers and engineer who wrote the issue originally should be able to manually verify the output change also.

MDEV-27314 Condense innodb buffer pool resize message

---

storage/spider/spd_db_conn.cc
storage/spider/spd_db_mysql.cc
storage/spider/spd_include.h

https://jira.mariadb.org/browse/MDEV-28360
This PR removes `#ifdef SPIDER_use_LEX_CSTRING_for_KEY_FField_name`, since `SPIDER_use_LEX_CSTRING_for_KEY_FField_name` is always defined [here](https://github.com/MariaDB/server/blob/10.9/storage/spider/spd_include.h#L113).
This PR does not change behavior, so no test case is added or modified.
We can test this PR by just compiling.

MDEV-28360 Spider: remove #ifdef SPIDER_use_LEX_CSTRING_for_KEY_FField_name

---

mysys/my_gethwaddr.c
storage/spider/mysql-test/spider/t/partition_mrr.test

With some small datatype changes to the Linux/Solaris my_gethwaddr implementation
the hardware address of AIX can be returned. This is an important aspect
in Spider (and UUID).
Spider test suite used this hwaddr implementation.
```
spider.spider3_fixes                     w3 [ pass ]    506
spider.spider3_fixes_part                w1 [ pass ]    607
spider.spider_fixes_part                 w4 [ pass ]    708
spider.spider_fixes                      w2 [ pass ]    951
spider.auto_increment                    w3 [ pass ]   1229
spider.pushdown_not_like                 w2 [ pass ]    716
spider.direct_left_right_left_join_nullable w1 [ pass ]    752
spider.direct_right_join                 w1 [ pass ]    448
spider.quick_mode_0                      w2 [ pass ]    465
spider.basic_sql …
```

MDEV-28243: AIX missing my_gethwaddr implementation

---

support-files/mysql.server.sh

Fix mysql startup script error in mac os.
/usr/local/bin/mysql.server  
log_success_msg: command not found
Run the command in mac os.
```shell
mysql.server start 
```
or 
```
mysql.server stop
```

fix: fix a syntax error

---

debian/control

File '/usr/bin/mariadb_config' has been moved from Debian package libmariadbd-dev to libmariadb-dev since MariaDB version 10.2 this leads to situation where upgrade will no succeed but fail with this kind of error message: `trying to overwrite '/usr/bin/mariadb_config', which is also in package libmariadbd-dev 1:10.2.44+maria~bionic`
Add libmariadbd-dev to libmariadb-dev Debian control files 'Breaks' solve situation and upgrading won't error anymore
For example Ubuntu 18.04 (Bionic) this can be testes manually (sorry no other way). Preassume is that one is in correct Git branch. It's convenient to test this on Podman or Docker container. 
```
sudo apt update
sudo apt-get install -y git-buildpackage apt-transport-https curl
sudo mk-build-deps -r -i debian/control -t "apt-get -y -o …
```

MDEV-28666: Add correct 'Breaks' to make sure upgrade from 10.2 succeeds

---

plugin/hashicorp_key_management/hashicorp_key_management_plugin.cc

OpenBSD / NetBSD and DragonFlyBSD do not have the alloca.h header just as FreeBSD.

Fix building the Hashicorp plugin on OpenBSD / NetBSD and DragonFlyBSD

---

mysql-test/mariadb-test-run.pl

1. What problem is the patch trying to solve?
When running `mtr` for the test that is not completed we get the output that is not properly formatted
- status of the test is not inline with test name
- path to the log file is showed that is not needed at all.
Reported by @dr-m.
3. If some output changed, what was it looking like before
the change and how it's looking with this patch applied
Example for the test
```sql
CREATE TABLE `#mysql50#T#` (a INT);
```
Output is
```bash
worker[1] Using MTR_BUILD_THREAD 300, with reserved ports 16000..16019
CREATE TABLE `#mysql50#T#` (a INT);
***Warnings generated in error logs during shutdown after running tests: innodb.f
2022-06-28 17:04:26 6 [ERROR] Invalid (old?) table or database name 'T#'
2022-06-28 17:04:26 6 [ERROR] Invalid (old?) table or …
```

Format properly mtr report for the test case that is not completed

---

mysql-test/include/ensure_binlog_row_event_columns.inc
mysql-test/suite/rpl/include/rpl_row_img_sequence.inc
mysql-test/suite/rpl/r/rpl_row_img_sequence.result
mysql-test/suite/rpl/t/rpl_row_img_sequence.cnf
mysql-test/suite/rpl/t/rpl_row_img_sequence.test
sql/sql_sequence.cc

MDEV-28487: sequences not respect value of binlog_row_image with select nextval(seq_gen)
Problem:
========
When using sequences, the function
sequence_definition::write(TABLE *table, bool all_fields)
is used to save DML/DDL updates to sequence tables (e.g. nextval,
setval, and alter). Prior to this patch, the value all_fields was
always false when invoked via nextval and setval, which forced the
bitmap to only include changed columns.
Solution:
========
Change all_fields when invoked via nextval and setval to be reliant
on binlog_row_image, such that it is false when binlog_row_image is
MINIMAL, and true otherwise.

MDEV-28487: sequences not respect value of binlog_row_image with select nextval(seq_gen)

---

.gitlab-ci.yml

All but the Ninja builds were restricted to 2 parallel builds due to compiler
otherwise crashing (MDEV-25968). The 'fedora-ninja' job was not failing on
Gitlab.com default runners, but on runners with more processors the crash was
repeatable for Ninja too. Thus also the Ninja build should be limited
with "-j 2".
Using more parallelism might speed up the build, but when testing the build
with '-j' values 2, 4, 8, 16 and 32, the improvement in build times was less
than 10%, indicating that the typical bottleneck is I/O and not CPU cores.
Therefore, "-j 2" is not a big drawback and it was chosen in order to remain
consistent with the other builds affected by MDEV-25968.
Run Gitlab-CI on a custom runner that has a high amount of CPU cores and observe that `fedora-ninja` job fails. With this …

Fix Ninja builds on Gitlab-CI by limiting parallelism

---

sql/sql_class.cc

DBUG_ENTER incorrect function name printed in function entry

fix DBUG_ENTER awake_no_mutex

---

storage/spider/mysql-test/spider/r/variable_deprecation.result
storage/spider/mysql-test/spider/t/variable_deprecation.test
storage/spider/spd_param.cc
storage/spider/spd_table.cc

Deprecate spider_param_bka_table_name_type
Testcases of this PR.
`./mysql-test/mtr spider.variable_deprecation`

MDEV-28795 Deprecate spider_bka_table_name_type

---

storage/connect/ioapi.c
storage/connect/ioapi.h

off_t is 64-bit on OpenBSD / NetBSD and DragonFly as well.

Fix building Connect storage engine ioapi code on OpenBSD / NetBSD / DragonFly

---

mysql-test/suite/binlog/include/binlog_write_error.inc
mysql-test/suite/binlog/r/binlog_bug23533.result
mysql-test/suite/binlog/r/binlog_write_error.result
mysql-test/suite/binlog/t/binlog_bug23533.test
mysql-test/suite/binlog_encryption/binlog_write_error.result
mysql-test/suite/binlog_encryption/rpl_mixed_binlog_max_cache_size.result
mysql-test/suite/rpl/include/rpl_binlog_max_cache_size.test
mysql-test/suite/rpl/r/rpl_mdev-11092.result
mysql-test/suite/rpl/r/rpl_mixed_binlog_max_cache_size.result
mysql-test/suite/rpl/r/rpl_stm_binlog_max_cache_size.result
mysql-test/suite/rpl/t/rpl_mdev-11092.test
sql/handler.cc
sql/log.cc

This PR has two commits. The first commit is Sujatha's original
patch cherry-picked on top of 10.3. The second contains my
additions on top of the original commit.

MDEV-21087: ER_SLAVE_INCIDENT arrives at slave without failure specifics

---

storage/innobase/lock/lock0lock.cc
storage/innobase/srv/srv0mon.cc
storage/innobase/srv/srv0srv.cc

SHOW ENGINE INNODB STATUS doesn't need a locked accurate history_size.
So we used the relaxed version of the function. 10.6 is the first version that adds history_size_approx.
SHOW ENGINE INNODB STATUS still shows the same answer.
- [ X ] *This is a minor optimization*
None relevant.

MDEV-29166: reduce locking on SHOW ENGINE INNODB STATUS (and friends that access innodb_history_size)

---

mysql-test/main/mysql_tzinfo_to_sql_symlink.result
mysql-test/main/mysql_tzinfo_to_sql_symlink.test
sql/tztime.cc

In 3b662c6ebd26b54ce534d9e7451cdc31e6c0046c, @dr-m appears to have discovered that the values of the `wsrep_is_on` and `wsrep_cannot_replicate_tz` variables need to be overridden for embedded builds.
However, there are other build configurations where these variables also
have NULL values.  The mariadb-tzinfo-to-sql script (implemented in
sql/tztime.cc) can be slightly modified to set its 'wsrep_is_on' and
'wsrep_cannot_replicate_tz' variables more predictably in all such cases,
thus allowing the mysql_tzinfo_to_sql_symlink.test test to pass without
any special-casing for particular build types.
See comments:
- https://github.com/MariaDB/server/commit/3b662c6ebd26b54ce534d9e7451cdc31e6c0046c#r78994411
- https://jira.mariadb.org/browse/MDEV-28782?focusedCommentId=230038&page=com.atlassian.j …

MDEV-28782: modify mariadb-tzinfo-to-sql to set 'wsrep*' variables appropriately in cases where Galera is not compiled in

---

mysql-test/suite/period/r/alter.result
mysql-test/suite/period/t/alter.test
sql/sql_lex.h
sql/table.cc
sql/table.h
sql/vers_string.h

https://jira.mariadb.org/browse/MDEV-18873
The crash was due to period names being empty, which was causing unexpected errors in other places.
To eliminate those errors, this patch adds a validation logic for period names in a query.  Because We execute the validation when parsing a query, any queries with invalid period names won't go further, preventing errors on the later stage. As far as I've read the code, this strategy is commonly used also for column names or table names.
Note that currently we use the same validation logic as column names, assuming the requirement for period names is the same as column names. 
Added a test case to check if the crash won't reproduce.
In this patch, we introduced a validation for period names. It rejects some period names that has been accepted …

MDEV-18873 Server crashes in Compare_identifiers::operator or in my_strcasecmp_utf8 upon ADD PERIOD IF NOT EXISTS with empty name

---

strings/ctype-simple.c

****
Hi, guys! I'm a 2022 GSoC Contributor and working on MCS.These days I am trying to optimize the string compared in MCS .Today I find a redundant variable in function my_strnncollsp_simple in ctype-simple.c of MDB
****
This change will not change existing test results. 
Basing the PR against the correct MariaDB version

Remove redundant variable  in my_strnncollsp_simple function in ctype-simple.c 

---

mysys/my_gethwaddr.c

Because of a define error the wrong value was being returned.
Regression in MDEV-28243
Fixes: 607f9874679c3e4ef7edcd2c9d80120051af73cc

MDEV-29418 linux uuid implementation returning non-hwaddr based suffix

---

debian/autobake-deb.sh

To build on kinetic (Ubuntu 22.10) we need to know about it so we can adjust dependencies accordingly.
Needed for https://github.com/MariaDB/buildbot/pull/52
Technically we'll only package 10.6+ for kinetic, but it will build on 10.5 as a minium (due to openssl-3.0).
Its manual at the moment, however chicken/egg - its needed for bb to get its kinetic (not yet released) builder.

Deb: add kinetic to autobake

---

debian/salsa-ci.yml

Currently Salsa-CI upgrade topic are bit misleading and incorrect. This PR correct them and adds upgrade test from 10.8
Check upgrading topics on Salsa-CI run:
https://salsa.debian.org/illuusio/mariadb-server/-/pipelines/384409
Nothing this more linting than anything. Does not change behavior or adds more as 10.8 upgrading is tested.

MDEV-28645: Reword MariaDB 10.9 Salsa-CI file and add upgrade test from 10.8

---

debian/mariadb-plugin-gssapi-server.install
debian/mariadb-plugin-oqgraph.install
debian/mariadb-plugin-rocksdb.install
debian/mariadb-plugin-tokudb.install

Preset include directory for configuration files below MariaDB 10.5 is `/etc/mysql/conf.d` not `/etc/mysql/mariadb.d`
Change installation location wrong plugin installation location from `/etc/mysql/mariadb.d` to default include directory `/etc/mysql/conf.d`. Change makes _gssapi-server_, _oqgraph_, _rocksdb_ and _tokudb_ plugins loading work after installation
This can be tested manually (for example Ubuntu 20.04. Please remove old version before testing):
To compile you need to have correct branch
```
sudo apt update
sudo apt-get install -y git-buildpackage apt-transport-https curl
sudo mk-build-deps -r -i debian/control -t "apt-get -y -o Debug::pkgProblemResolver=yes --no-install-recommends"
debian/autobake-deb.sh
cd ..
sudo dpkg -i mariadb-common_10.3.36+maria~ubu1804_all.deb …
```

MDEV-28605: Change wrong plugin config installation location

---

mysql-test/suite/binlog/r/binlog_checkpoint.result
mysql-test/suite/binlog/t/binlog_checkpoint.test
sql/log.cc
sql/mysqld.cc

The shutdown time assert was caused by untimely deactivation of
the binlog background thread and related structs destruction.
It could specifically occur when a transaction is replication unsafe
and has to be completed with a ROLLBACK event in binlog.
This gets fixed with the binlog background thread stop relocation
to a point when user transactions have been completed.
A test case is added to binlog.binlog_checkpoint
also receives as a bonus a minor correction to reactivate a MDEV-4322 test
case that also required a shutdown phase.
["Writing good test cases"](https://mariadb.org/get-involved/getting-started-for-developers/writing-good-t …

MDEV-24660 MYSQL_BIN_LOG::cleanup(): Assertion `b->xid_count == 0' 

---

storage/innobase/buf/buf0buf.cc
storage/innobase/buf/buf0lru.cc
storage/innobase/include/buf0buf.h

When InnoDB isn't using memory its polite to other system
processes to allow that memory to be used.
Use madvise(MADV_FREE) to keep virtual mapping but allow kernel
to reclaim memory.
buf_page_t::set_state(buf_page_t::NOT_USED) will call madvise(MADV_FREE)
as will the initialization of the same state.
buf_LRU_block_free_non_file_page is restructured to do this call
after it has overwritten the table space id and page id so that
it is not immediately marked as reused by the kernel.
<pre>
sql/mariadbd --no-defaults --skip-networking --datadir=/tmp/${PWD##*/}-datadir --socket=/tmp/${PWD##*/}.sock --plugin-dir=${PWD}/mysql-test/var/plugins/ --verbose  --innodb-buffer-pool-size=10G
$ ps  -C mariadbd -o drs,trs,vsz,rss,pid
DRS  TRS    VSZ   RSS     PID
12963911 8592 12972504 293792 123320
$ …

MDEV-25341: innodb buffer pool soft decommit of memory

---

mysql-test/suite/roles/recursive_dbug.result
mysql-test/suite/roles/role_grant_propagate-29458.result
mysql-test/suite/roles/role_grant_propagate-29458.test
mysql-test/suite/roles/roles_tables_priv-29465.result
mysql-test/suite/roles/roles_tables_priv-29465.test
sql/sql_acl.cc

These bugs were encountered while working on the reverse grants project. They are straightforward errors. Their reasoning is well documented within the test cases as well as the commit messages and the MDEVs themselves.
Test cases in the commits.

MDEV-29458 & MDEV-29465 Role bugs blocking negative grants testing

---

sql/sql_show.cc
sql/sys_vars.cc

Add missing comment and remove unnecessary initialization
- Commit c8948b0d0db4 introduced `get_one_variable()` - updating missing argument.
- Remove caller setting of empty string in `rpl_filter`, since underlying functions will do the same
(commit 9584cbe7fcc4 introduced the change).

Add missing comment and remove unnecessary initialization

---

storage/connect/ha_connect.cc
storage/connect/mysql-test/connect/r/mysql.result
storage/connect/mysql-test/connect/t/mysql.test

- Spaced column names are note quoted properly
Reviewer: <>
Note: failing ` connect.misc` is not related to this bug.

MDEV-28533: CONNECT engine does not quote columns involved in WHERE clause

---

client/mysql_upgrade.c
mysql-test/main/mysql_upgrade.result
mysql-test/main/mysql_upgrade.test

rather than mariadb/mariadb-check. 10.5 was the version when real mariadb names became the default, so use the mariadb names in the mariadb-upgrade.
- [ X ] *This is a bug fix and …

MDEV-29614 mariadb-upgrade calls mysql and mysql-check

---

client/mysqlshow.c
sql/sql_analyse.cc
sql/sql_repl.cc
storage/connect/bsonudf.cpp
storage/connect/global.h
storage/connect/jdbconn.cpp
storage/connect/json.cpp
storage/connect/jsonudf.cpp
storage/connect/plugutil.cpp
storage/connect/tabbson.cpp
storage/connect/tabwmi.cpp
storage/connect/valblk.cpp
storage/federatedx/ha_federatedx.cc

Continue with similar changes as done in 19af1890 to replace sprintf(buf, ...) with
snprintf(buf, sizeof(buf), ...),
specifically in the "easy" cases where buf is allocated with a size
known at compile time. Also commit taking care of several less obvious scenarios with sprintf()
The changes make sure we are not write outside array/string bounds which
will lead to undefined behaviour. In case the code is trying to write
outside bounds - safe version of functions simply cut the string
messages so we process this gracefully.
All build stages pass for these commits. For the commit without the intentional bug, mysql-test-run is properly passing. The changes are not change the functionality itself they just replace unsafe C methods with the safe ones.
The changes fully backward compatible.
All …

Use memory safe snprintf() in Connect Engine and elsewhere

---

config.h.cmake

Looking into the build directory:
<details> <summary> Without patch </summary> 
<pre>
$ grep -R "USE_MB" ./include
./include/config.h:#define USE_MB 1
./include/config.h:#define USE_MB_IDENT 1
./include/config.h:#define USE_MB 1
./include/config.h:#define USE_MB_IDENT 1
./include/my_config.h:#define USE_MB 1
./include/my_config.h:#define USE_MB_IDENT 1
./include/my_config.h:#define USE_MB 1
./include/my_config.h:#define USE_MB_IDENT 1
</pre>
</details>
<details> <summary> With patch </summary> 
<pre>
$ grep -R "USE_MB" ./include
./include/config.h:#define USE_MB 1
./include/config.h:#define USE_MB_IDENT 1
./include/my_config.h:#define USE_MB 1
./include/my_config.h:#define USE_MB_IDENT 1
</pre>
</details>
Patch introducing the change: bc76ad8f6be7

Remove redudant defines USE_MB and USE_MB_IDENT

---

client/mysqlbinlog.cc

The statement 'Verify checksum binlog events.' is confusing. Fix word order to make it clear.
This is a word order change for a text description as a part of UI design, so automatic unit testing is not suitable here. It should be tested by being read by human beings.

MDEV-29183: Clarify mysqlbinlog command description

---

scripts/mysqld_multi.sh

The mysqld_multi script template used @datadir@ as default log destination, this is not the MariaDB datadir in this context though but rather the -- typically write-only -- /share dir.
The correct placeholder to use here is @localstatedir@ which gets replaced with the actual MariaDB datadir
This request replaces the earlier https://github.com/MariaDB/server/pull/2109 and includes the requested changes (based on 10.11 now, and also changed the comment above the changed code)

MDEV-6655: mysqld_multi default log location in wrong directory

---

mysql-test/main/grant2.result
mysql-test/main/grant5.result
mysql-test/main/grant5.test
sql/sql_acl.h
sql/sql_parse.cc
sql/sql_show.cc

=========== Problem =============
- `show columns` is not working for temporary tables, even though there
is enough privilege `create temporary tables`.
=========== Solution =============
- Append `TMP_TABLE_ACLS` privilege when running `show columns` for temp
tables.
- Additionally `check_access()` for database only once, not for each
field
=========== Additionally =============
- Update comments for function `check_table_access` arguments
Problem is visible in MySQL 5.7 - 8.0 too (see JIRA comment)

MDEV-28455: CREATE TEMPORARY TABLES privilege is insufficient for SHOW COLUMNS

---

mysql-test/suite/sql_sequence/default.result
mysql-test/suite/sql_sequence/default.test
sql/sql_class.h
sql/sql_insert.cc

The population of default values in INSERT SELECT was being performed twice. With sequences, this resulted in every second sequence value being used.
With SELECT INSERT we remove the second invokation of table->update_default_fields(). This was already performed in store_values() invoking fill_record_n_invoke_before_triggers() which invoked update_default_fields() previously.
We do need to return an error on duplicate values, so the ::store_values is extended to take the ignore option.
mtr test included
Users won't be hopefully depending on skipped values in sequences in INSERT SELECT.

MDEV-29540 Incorrect sequence values in INSERT SELECT

---

client/mysqldump.c

If mariadb cnf set log error to some file which mysql user  doesn't has permission to write, mariadb dump will generate an empty file because of executing flush logs  failed at the begin part. 
So I add an error message , and set the exit code to EX_MYSQLERR.
CI test is ok.
No

MDEV-28720 add error message if flush log failure

---

storage/maria/CMakeLists.txt

FreeBSD 13 has libcurl in /usr/local/lib so linking failed just trying
to link curl by name. CMake finds curl's true place so let's use that.
Fixes one of the two compiling issues in FreeBSD 13 (the other is in RocksDB which I have upstreamed a fix for)
Compile in FreeBSD 13 with the S3 engine enabled. A linking error will occur with `lcurl` prior to the patch.
Should improve compatibility in general.

MDEV-27680 Fix Aria S3 building in FreeBSD

---

mysql-test/main/ps_missed_cmds_bin_prot.result
mysql-test/main/ps_missed_cmds_bin_prot.test

We'd like to update our HELP contents independently of the test cases.
Like 5e270ca28d05acb72c6aec9f1d37f9610fc11a0e, the same concept is applied to make the MTR output of a dummy help topic is done to prove the HELP can works as a prepared statement.

MDEV-16708: mtr ps_missed_cmds_bin_prot allow for updated HELP

---

client/mysqldump.c
man/mysqldump.1
mysql-test/main/mysqldump-header.result
mysql-test/main/mysqldump-header.test

This PR improves *mysqldump* tool with a *--header* flag for the *--tab* option, so that a row of column headers is included in the exported txt files, providing further compliance to the standard CSV format. Invoking *mysqldump database --tab \<path\> --header* adds a header row with column names to the text files generated by *--tab*. The options *--fields-terminated-by*, *--fields-enclosed-by*, *--fields-optionally-enclosed-by* and *--lines-terminated-by* also apply to the header row. If the *--header* option is used without a leading *--tab* option, an error occurs.
It can be tested by running *test_issue_22200.sh* and checking its output against *test_issue_22200.output*.
The bash script file *test_issue_22200.sh* creates a small database with a single table from the file …

MDEV-22200: Include header row in txt files exported by mysqldump

---

mysys/my_gethwaddr.c

This now builds. But I am not certain how to test this to ensure it matches actual MAC addresses of any HW interfaces. I can see that the suffix changes before and after when using ```select UUID();```.
Also when merging forward to 10.5 and newer OpenBSD needs to be added to the list of OS's for ```memcpy_and_test()```.

Fix building my_gethwaddr() on OpenBSD

---

sql/mysqld.cc

Per the code my_set_max_open_files 3 lines earlier, we attempt to set the nofile (number of open files), rlimit to max_open_files.
We should use this in the warning because wanted_files may not be the number.

MDEV-29847: Wrong warning on rlimit capping of max_open_files

---

include/my_alarm.h

```
/usr/ports/pobj/mariadb-10.9.3/mariadb-10.9.3/mysys/my_lock.c:183:7: warning: incompatible function pointer types assigning to 'sig_return' (aka 'void (*)(void)') from 'void (*)(int)' [-Wincompatible-function-pointer-types]
ALARM_INIT;
^~~~~~~~~~
/usr/ports/pobj/mariadb-10.9.3/mariadb-10.9.3/include/my_alarm.h:43:16: note: expanded from macro 'ALARM_INIT'
alarm_signal=signal(SIGALRM,my_set_alarm_variable);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/pobj/mariadb-10.9.3/mariadb-10.9.3/mysys/my_lock.c:189:7: warning: incompatible function pointer types passing 'sig_return' (aka 'void (*)(void)') to parameter of type 'void (*)(int)' [-Wincompatible-function-pointer-types]
ALARM_END;
^~~~~~~~~
/usr/ports/pobj/mariadb-10.9.3/mariadb-10.9.3/include/my_alarm.h:44:41: note: expanded …
```

Fix warning with signal typedef for *BSD

---

storage/connect/mysql-test/connect/r/odbc_postgresql.result
storage/connect/mysql-test/connect/t/odbc_postgresql.test
storage/connect/odbconn.cpp
storage/connect/tabext.cpp

ODBC Rewind triggered an error with no SQL, but this is sometimes a valid condition (as can be seen with other classes). Setting this to a 0 return stops errors firing when they shouldn't.
Also fixes ASAN hits from in MDEV-29687 tabext.cpp.
Additional MTR test added, to test the additional MDEV-29687 fix, run the CONNECT PostgreSQL ODBC test under ASAN.

MDEV-29397 CONNECT engine: Fix note turning into error

---

debian/autobake-deb.sh
debian/mariadb-server-10.6.mariadb.init
debian/rules
debian/salsa-ci.yml
debian/source/lintian-overrides
debian/tests/upstream

See commit messages for details of changes.
Anybody can sign up for a free account at salsa.debian.org, the Gitlab instance for Debian development.
The Salsa-CI status for current 10.6 head (ab0190101b0587e0e03b2d75a967050b9a85fd1b) is visible at https://salsa.debian.org/otto/mariadb-server/-/pipelines/443617
CI status after these commits is visible at https://salsa.debian.org/otto/mariadb-server/-/pipelines/444495
Once #2294 is merged up from branch 10.5 to 10.6 and once @illuusio completes the Lintian fixes in #2275 the CI status will be even more green as visible in the mockup at https://salsa.debian.org/otto/mariadb-server/-/pipelines/444496
The last failure will be fixed if/when I finalize #2300. It is a hard one, so I wasn't able to crack it this weekend.
These changes only affect …

Misc Debian/Salsa-CI fixes

---

mysys/my_gethwaddr.c

OS detection logic in my_gethwaddr.c is backwards. `#if !defined(_AIX) || !defined(__linux__)` evaluates to true on any platform.
Building mariadb on an illumos (OpenSolaris based) operating system works; w/o this patch it fails.

OS detection logic in my_gethwaddr.c is backwards

---

sql/sql_connect.cc

(and linked messages like MDEV-24850, MDEV-21456, MDEV-4160(sort of))
Because of the default warning level, aborted unauthenticated
connections are in the error log. These errors frequently occur
in production environments because cancelled connectiosn occur
all the time when web pages are shutdown.
Rather than flood our user's errors log with these ordinary
messages, lets push them down to the warning level at log-warnings=4
level.
Concept approved by Monty.
`nc -U /tmp/build-mariadb-server-10.3.sock < /dev/null` no longer outputs error log, unless started with `log_warnings=4` (or more).
Those using fail2ban or something on these non-authentication attempts to reduce error messages get these warnings removed at no CPU cost.

MDEV-12274: Too many connections warning in error log

---

mysql-test/main/query_cache_notembedded.result
mysql-test/main/query_cache_notembedded.test
sql/sql_cache.cc
sql/sql_cache.h
sql/sql_table.cc

Drop database was hanging the server by accessing invalid query cache data. The invalidation of table data dropping the tables wasn't called due to an error in dfb41fddf69ccbca89fd322901f2809bc3bcc0e9.
Also clean up the interface just a little bit.
mtr cases included in commit.

MDEV-29760 query cache - drop db hangs database

---

mysql-test/main/mysql_upgrade.result
mysql-test/main/mysql_upgrade.test
scripts/mysql_system_tables_fix.sql

MDEV-16735 describes how mysql_upgrade fails when alter_algorithm
is set to a value different than DEFAULT/COPY. It was marked as
fixed by 0ee08683, but there was a typo in it. This commit
fix the typo and add MTRs to ensure the fix is working properly.
```
MariaDB [(none)]> set alter_algorithm=DEFAULT;
Query OK, 0 rows affected (0.000 sec)
MariaDB [(none)]> show variables like 'alter_algorithm';
+-----------------+---------+
| Variable_name   | Value   |
+-----------------+---------+
| alter_algorithm | INPLACE |
+-----------------+---------+
1 row in set (0.001 sec)
MariaDB [(none)]> set alter_algorithm='DEFAULT';
Query OK, 0 rows affected (0.000 sec)
MariaDB [(none)]> show variables like 'alter_algorithm';
+-----------------+---------+
| Variable_name   | Value   | …
```

[MDEV-16735] Ensure mysql_upgrade works when changing alter_algorithm

---

.gitlab-ci.yml

Add additional build job that is very similar to the existing `fedora-clang` job except that ASAN, TSAN, MSAN, and UBSAN flags are enabled. The sanitizers are enabled atop the `fedora-clang` job because MSAN is not available for the GCC compiler in the `fedora` build. Additionally, extract the original MTR test out as a template and create separate MTR test jobs to invoke sanitizer errors separate from functional test failures.
Currently there is no way to run the same job (`mysql-test-run`) for different dependencies (once for each sanitizer). Therefore, 4 new separate test jobs are needed.
`eatmydata` was not used in this job as it would consistently fail at 24% with the ASAN flags enabled. Furthermore the difference in build/compile time between the `fedora` job and the `fedora-asan` …

Extend GitLab CI with Sanitizer build and test

---

mysql-test/main/bad_startup_options.test

Commit 32158be added a new test `bad_startup_options`. This test fails
if run as root, which is common on many CI systems.
This test should include `not_as_root.inc` so it is skipped, just
like all other similar tests in MariaDB.
All existing test cases should still be passing in Buildbot as well as GitLab-CI.
`bad_startup_options` is labelled as `[ skipped ]` in CI but when run locally (as non-root user, e.g., mysql) is marked as `[ pass ]`.
This bug fix should be fully backward-compatible

[MDEV-30002] Skip bad_startup_options test when running as root

---

.gitlab-ci.yml

The version was fixed to be Fedora 36 due to previous issues on Gitlab-CI,
but those seem to be solved now.
Use 'mariadb' name in scripts and server binary as Fedora switched name in
https://src.fedoraproject.org/rpms/mariadb/c/df76620f9e8a9b3f14da8a615050feeac2c62e26
Switch to using the `default:` section supported by newer Gitlab-CI,
see https://docs.gitlab.com/ee/ci/yaml/#default.
Also define an explicit timeout of 3 hours to ensure builds don't time out
if the default timeout is too short.
NOTE TO MERGERS: These changes are version independent and should be
merged up on all MariaDB branches 10.6 -> 10.11.
Gitlab-CI passing at:
* https://salsa.debian.org/otto/mariadb-server/-/pipelines/458208
* https://gitlab.com/ottok/mariadb/-/pipelines/700286605
(test failure on …

Gitlab-CI: Upgrade Fedora build to always use latest (now 37) version

---

mysql-test/dgcov.pl

- Patch introduced 7baf24a0f8e9491a55 for multidigit gcc dump.
There is no dot in `dumpversion`.
```
$ gcc -dumpversion
10
```
Otherwise it will fail and not produce the output
```
Running dgcov
Name "IO::Uncompress::Gunzip::GunzipError" used only once: possible typo at ./dgcov.pl line 197.
Cannot parse gcc -dumpversion: 9
```
- The warning `once` is always generated:
```
Running dgcov
Name "IO::Uncompress::Gunzip::GunzipError" used only once: possible typo at ./dgcov.pl line 197.
<number>
```
Suppresing the line `Name "IO::Uncompress::Gunzip::GunzipError" used only once: possible typo at ./dgcov.pl line 197.`
with the patch.
- Reviewed by: <>

dgcov: parsing without dot to get specific version

---

debian/mariadb-test-data.lintian-overrides
debian/mariadb-test.lintian-overrides
debian/source/lintian-overrides

This supersedes PR #2257 which is against 10.6
* Lintian 2.115 introduced new syntax for overrides. Add minimal set of rules to remove errors and have clean tests. Minimal set of rules can be merge up-to 10.8
* MariaDB 10.2 is not build for Debian Sid so it can't be used for testing anymore. It should be removed upstream `debian/salsa-ci.yml`
* Make small change to `debian/rules' to remove one external tab
* Make sure that there is not versions in external dependency `Conflicts` in `debian/control`
Most of these changes are beyond manual testing. Building branch and running lintian against it should work as in Salsa-CI:
https://salsa.debian.org/illuusio/mariadb-server/-/jobs/3590792/raw
Current situation with Lintian is:
https://salsa.debian.org/illuusio/mariadb-server/-/jobs/3586829/raw …

MDEV-28834: Make minimal Lintian changes and some cleanup

---

mysql-test/main/gis-json.result
mysql-test/main/gis-json.test
sql/spatial.cc

The geometry type requires Type:"Feature" but the feature need not be first in the JSON structure.
Adjust code to return an error if geometry isn't a JSON object, but continue parsing searching for Type: "Feature" to trigger the geometry parsing.
Thanks Derick Magnusen for the bug report.

MDEV-30150 ST_GeomFromGeoJSON, 'geometry' before 'type: feature' error

---

storage/innobase/dict/dict0dict.cc
storage/innobase/dict/dict0stats.cc

Hide the errors related to missing innodb stats tables in bootstrap mode on the assumption that because we are in bootstrap mode they are going to be created.
```
$ mkdir -p /tmp/${PWD##*/}-datadir && scripts/mysql_install_db --no-defaults --srcdir=$OLDPWD --builddir=$PWD --datadir=/tmp/${PWD##*/}-datadir --verbose --enforce-storage-engine=InnoDB
Installing MariaDB/MySQL system tables in '/tmp/build-mariadb-server-10.4-datadir' ...
2022-11-22 13:55:55 0 [Note] /home/dan/repos/build-mariadb-server-10.4/sql/mysqld (mysqld 10.4.28-MariaDB) starting as process 194910 ...
2022-11-22 13:55:55 0 [Note] InnoDB: Using Linux native AIO
2022-11-22 13:55:55 0 [Note] InnoDB: The first innodb_system data file 'ibdata1' did not exist. A new tablespace will be created!
2022-11-22 13:55:55 0 [Note] …
```

MDEV-30065: mariadb-install-db allow for --enforce-storage-engine=InnoDB

---

scripts/mysql_install_db.sh

Previously we parsed it out in mysql_install_db for use in the error message, but failed to pass it to mysqld in the bootstrap.
Thanks Michal Schorm for the test case.
Successful case (rather silent)
```
$ mkdir -p /tmp/${PWD##*/}-datadir && scripts/mysql_install_db --no-defaults --srcdir=$OLDPWD --builddir=$PWD --datadir=/tmp/${PWD##*/}-datadir --verbose --log-error=/tmp/mysql.err
Installing MariaDB/MySQL system tables in '/tmp/build-mariadb-server-10.3-datadir' ...
2022-12-08 10:24:40 0 [Note] /home/dan/repos/build-mariadb-server-10.3/sql/mysqld (mysqld 10.3.38-MariaDB) starting as process 306909 ...
OK
~/repos/build-mariadb-server-10.3 
$ cat /tmp/mysql.err
2022-12-08 10:24:40 0 [Note] InnoDB: Using Linux native AIO
2022-12-08 10:24:40 0 [Note] InnoDB: The first innodb_system data file …
```

MDEV-18591: mysql_install_db - pass --log-error to mysqld in install

---

mysql-test/main/log_slow.result
mysql-test/main/log_slow.test
sql/sql_parse.cc

Consistent with MDEV-4206 and empty log_slow_filter still means no explict filtering. Since 21518ab2e453 however the log_queries_not_using_indexes became stored in the same variable.
As we need to test for the absense of log_queries_not_using_indexes the SERVER_QUERY_NO_INDEX USED part of log_slow_statement, the empty criteria resulted in an always true to log queries not using indexes if log_slow_filter was set to empty.
Adjusted the log_slow.test for MDEV-4206 as slow_log_query has been global and session for a while and it was relying on the MDEV-21187 buggy behavior to detect a slow query.
mtr test included.
- [X ] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

MDEV-21187: log_slow_filter="" logs queries not using indexes

---

debian/additions/debian-start
debian/additions/debian-start.inc.sh
debian/mariadb-server-10.5.postinst
mysql-test/README
scripts/mysql_install_db.sh
support-files/rpm/server-postin.sh

And a small bit of shell escaping.
Also include the ftp.mariadb.org script rather than old name.

Deb: MariaDB names as default for deb scripts

---

include/heap.h
include/json_lib.h
include/m_ctype.h
include/ma_dyncol.h
include/my_base.h
include/my_decimal_limits.h
include/my_dir.h
include/my_global.h
include/my_sys.h
include/myisam.h
include/myisammrg.h
include/mysql.h
include/mysql/plugin_ftparser.h
include/mysql/psi/mysql_thread.h
include/mysql/service_base64.h
include/mysql/service_my_snprintf.h
include/mysql/service_thd_timezone.h
include/queues.h
include/waiting_threads.h

10.3 version
https://github.com/MariaDB/server/pull/2348
<s>sed -i "s/extendible/extendable/g" server/include/lf.h</s>
extendible is an alternate spelling of extendable
some header typos appeared in newer versions than 10.3
include/heap.h
include/json_lib.h
include/m_ctype.h
include/ma_dyncol.h
include/my_base.h
include/my_decimal_limits.h
include/my_dir.h
include/my_global.h
include/my_sys.h
include/myisam.h
include/myisammrg.h
include/mysql.h
include/mysql/plugin_ftparser.h
include/mysql/psi/mysql_thread.h
include/mysql/service_base64.h
include/mysql/service_my_snprintf.h
include/mysql/service_thd_timezone.h
include/queues.h
include/waiting_threads.h

header typos

---

mysql-test/suite/innodb_fts/t/innodb-fts-stopword.test
mysql-test/suite/innodb_fts/t/stopword.test
mysql-test/suite/parts/t/partition_repair_myisam.test
storage/connect/value.cpp
storage/innobase/row/row0row.cc
storage/maria/ma_locking.c
storage/maria/ma_loghandler.c
storage/myisam/mi_locking.c
storage/rocksdb/ha_rocksdb.cc

10.3 version
untranslated strings (from Swedish)
mysql-test/suite/parts/t/partition_repair_myisam.test
storage/maria/ma_locking.c
storage/myisam/mi_locking.c
typos
mysql-test/suite/innodb_fts/t/innodb-fts-stopword.test
mysql-test/suite/innodb_fts/t/stopword.test
storage/connect/value.cpp
storage/innobase/row/row0row.cc
storage/maria/ma_loghandler.c
storage/rocksdb/ha_rocksdb.cc

miscellaneous typos

---

CMakeLists.txt

There is a small typo in the root cmake file - s/profilingg/profiling.
---

Fix a typo in CmakeLists.txt

---

debian/mariadb-server-10.5.mariadb.init
debian/tests/smoke
mysql-test/suite/wsrep/common.pm
scripts/galera_recovery.sh
scripts/mariadb-service-convert

Fix bug in mariadb-service-convert
If mariadb-service-convert is run and the user variable is unset then this sets `User=` in `[Service]`, which then tries to run mariadb as root, which in-turn fails. This only happens when mysqld_safe is missing which is all the time now. So...
1. Don't set `User=` if there is no user variable.
2. User mariadbd-safe instead.
Also
* galera_recovery to use mariadbd
* mtr - wsrep use mariadb executables
* debian/mariadb-server.mariadb.init use mariadbd-safe

MDEV-30275: mariadb names rather than mysql names should be used

---

sql/sql_acl.cc

Using clang generates the unused-function warning on embedded like:
```
FAILED: libmysqld/CMakeFiles/sql_embedded.dir/__/sql/sql_acl.cc.o /usr/lib64/ccache/clang++ .... libmysqld/CMakeFiles/sql_embedded.dir/__/sql/sql_acl.cc.o -MF libmysqld/CMakeFiles/sql_embedded.dir/__/sql/sql_acl.cc.o.d -o libmysqld/CMakeFiles/sql_embedded.dir/__/sql/sql_acl.cc.o -c /home/dan/repos/mariadb-server-10.11/sql/sql_acl.cc
sql_acl.cc:113:20: error: unused function 'is_public' [-Werror,-Wunused-function] static inline bool is_public(const LEX_USER *l) { return is_public(&l->user); }
```
```
$ clang++ --version
clang version 15.0.6 (Fedora 15.0.6-2.fc37)
```
fix for 0537ce4e9fab

acl - is_public - avoid embedded warning

---

mysql-test/suite/innodb/r/insert_into_empty.result
mysql-test/suite/innodb/t/insert_into_empty.test
storage/innobase/row/row0merge.cc

Fixes wrong file write offset calculation in row_merge_write_blob_to_tmp_file()
Test "innodb-mdev-30321" is included in this PR

MDEV-30321: blob data corrupted by row_merge_write_blob_to_tmp_file()

---

cmake/install_macros.cmake

When building with -DWITH_WSREP=OFF, files required for MTR tests are excluded and several tests fail. This is cause by a recent commit 7b44d0ba which attempted to resolve MDEV-23230.
Even when building without WSREP/Galera support some of the MTR include files named *wsrep* are required by other tests.
Removing the following from the CMake install macros will avoid excluding the MTR test .inc files:
`|include/((w.*)?wsrep.*|.*galera.*)\\.inc`
The succesful MTR tests can be seen in this [public pipeline](https://salsa.debian.org/robinnewhouse/mariadb-server-mirror/-/jobs/3743831).
BSD-new license. I am contributing on behalf of my employer
Amazon Web …

MDEV-30344 MTR tests fail when built without WSREP

---

mysys/array.c
mysys/hash.c
mysys/my_alloc.c
mysys/my_malloc.c

Since 7c58e97bf6f80a251046c5b3e7bce826fe058bd6 the PSI_memory_key was added to some routines in the
mysys/. This commit fixes synopses of functions that were updated with
the PSI_memory_key parameter.
---

Fix synopses in mysys APIs

---

mysql-test/main/func_json.result
mysql-test/main/func_json.test
mysql-test/main/opt_trace.result
mysql-test/main/opt_trace_index_merge.result
mysql-test/main/opt_trace_ucs2.result
mysql-test/main/range_notembedded.result
mysql-test/suite/plugins/r/multiauth.result
sql/item_jsonfunc.cc

Represents JSON in the most understandable way emphasizing nested structures.
The test files are appended to `func_json.test`

MDEV-19160 JSON_DETAILED output unnecessarily verbose

---

sql/mysqld.cc

Don't display the source revision in the mysqld --help output.

MDEV-17093: SOURCE_REVISION in log (postfix - not in help)

---

mysql-test/main/create.result
mysql-test/main/create.test
mysql-test/main/insert_select.result
mysql-test/main/insert_select.test
sql/sql_class.h
sql/sql_insert.cc

regression from MDEV-29540 / 8c389393695.
Insert ignore errors needed to be unconditionally ignored.
Test included.

MDEV-30342 Wrong "Truncated incorrect DECIMAL value" warning/error

---

storage/archive/azio.c
storage/connect/connect.cc
storage/connect/ioapi.c
storage/connect/tabtbl.cpp
storage/connect/zip.c
storage/rocksdb/ha_rocksdb.cc
storage/rocksdb/ha_rocksdb.h
storage/tokudb/PerconaFT/ft/loader/loader.cc
storage/tokudb/PerconaFT/ft/txn/txn_manager.cc

clang15 finally errors on old prototype definations.
Its also a lot fussier about variables that aren't used
as is the case a number of time with loop counters that
aren't examined.
RocksDB was complaining that its get_range function was
declared without the array length in ha_rocksdb.h. While
a constant is used rather than trying to import the
Rdb_key_def::INDEX_NUMBER_SIZE header (was causing a lot of
errors on the defination of other orders). If the constant
does change can be assured that the same compile warnings will
tell us of the error.
The ha_rocksdb::index_read_map_impl DBUG_EXECUTE_IF was similar
to the existing endless functions used in replication tests.
Its rather moot point as the rocksdb.force_shutdown test that
uses myrocks_busy_loop_on_row_read is currently disabled.

clang15 warnings - unused vars and old prototypes

---

mysql-test/main/func_json.result
mysql-test/main/func_json.test
sql/item_create.cc

In MySQL, the function is called JSON_PRETTY. We should add ability to use this name as an alias of `JSON_DETAILED`.
The test files locate at `func_json.test`

MDEV-19160 json_pretty() alias for json_detailed()

---

client/mysql.cc

I noticed an early return after a call to `my_alloca` which did not have call to `my_afree`
I suppose one could build on a system without alloca, force the early return case, and observe the leak with `valgrind`.
I have not done this.
This should not impact compatibility

missing my_afree after my_alloca

---

sql/wsrep_mysqld.cc
sql/wsrep_sst.cc

Updated wsrep-lib to version in which server_state wait_until_state() and sst_received() were changed to report errors via return codes instead of throwing exceptions. Added error handling accordingly.
Tested manually that failure in sst_received() which was caused by server misconfiguration (unknown configuration variable in server configuration) does not cause crash due to uncaught exception.

MDEV-30419 Fix unhandled exception thrown from wsrep-lib

---

.github/pull_request_template.md

We do not want people to try to rebase their patch on anything prior to the earliest *maintained* version.
If one finds a bug which has existed since before the earliest maintianed version, the template should make it clear what the earliest version to check is.
N/A
N/A

Update the PR template to reflect 10.3 is the earliest maintained

---

mysql-test/main/log_slow_debug.result
mysql-test/main/mysqld--help.result
mysql-test/suite/sys_vars/r/log_slow_admin_statements_func.result
mysql-test/suite/sys_vars/r/sysvars_server_embedded.result
mysql-test/suite/sys_vars/r/sysvars_server_notembedded.result
sql/sys_vars.cc

log_slow_filter=admin as been available for a long time.
Uses can migrate from log_slow_statements_statements=OFF by removing 'admin' from the default log_slow_filter variable setting.
Deprecation warning at the moment. …

MDEV-6339 deprecate log_slow_admin_statements

---

client/mysql.cc
man/mysql.1

Also replace the use of MYSQL_HISTFILE as an environment variable with MARIADB_HISTFILE.
With the triviality of this I've ignored the backwards compatibility aspects here and was just planning on putting this into the release notes.

MDEV-26548: replace .mysql_history with .mariadb_history

---

cmake/cpack_rpm.cmake

During testing of RPM packages in MDEV-30203:
file /usr/share/man/man3 from install of
MariaDB-devel-11.0.1-1.el7_9.x86_64 conflicts with file from
package filesystem-3.2-25.el7.x86_64
MariaDB is the first libmariadb to include man3 man pages so make the changes here like what is done for man1 and man8.
Install MariaDB-devel. For as yet unexplained reasons it can happen in buildbot without error.

rpm: ignore man3

---

mysql-test/suite/rpl/r/rpl_delayed_parallel_slave_sbm.result
mysql-test/suite/rpl/t/rpl_delayed_parallel_slave_sbm-slave.opt
mysql-test/suite/rpl/t/rpl_delayed_parallel_slave_sbm.test
sql/rpl_parallel.cc
sql/slave.cc
sql/slave.h

The first commit on this PR is the regression with an MTR test showing the issue.
The second commit is the code fix.
Problem:
========
On a parallel, delayed replica, Seconds_Behind_Master will not be
calculated until after MASTER_DELAY seconds have passed and the
event has finished executing, resulting in potentially very large
values of Seconds_Behind_Master for the entire duration of
MASTER_DELAY. This is especially prevalent for workloads with
infrequent transactions.
Solution:
========
Treat replicas using both parallelization and master_delay as an
edge case to force the serial method of updating
Seconds_Behind_Master. Effectively, this means the value will seem
more recent than the true state of the replica for both long running
transactions and workers with long queues. This will …

MDEV-29639 Seconds_Behind_Master is incorrect for Delayed, Parallel Replicas

---

tpool/aio_liburing.cc

Fixes the following error when building with gcc 13:
"tpool/aio_liburing.cc:64:18: error: 'runtime_error' is not a member of 'std'
64 |       throw std::runtime_error("aio_uring()");"
Built locally with gcc-13.0.1_pre20230122

Add missing include for std::runtime_error

---

tpool/aio_linux.cc

This is needed with GCC 13 and newer [1]
[1] https://www.gnu.org/software/gcc/gcc-13/porting_to.html
Signed-off-by: Khem Raj <raj.khem@gmail.com>
TODO: …

Add missing include <cstdio>

---

debian/control

in order to be able to retrieve files using REST queries. Otherwise,
`ERROR 1105 (HY000): Curl not installed.` will be thrown.
This is upstreaming: [Debian Salsa MariaDB team MR 25](https://salsa.debian.org/mariadb-team/mariadb-server/-/merge_requests/25)
Use plugin connect without curl and it will fail. Then install curl and it works
Does not provide backward compatibility problems but solves user problem.

MDEV-30509: mariadb-plugin-connect: introduce curl as recommends

---

dbug/dbug.c
mysys/stacktrace.c

__gcov_flush was never an external symbol in the documentation.
It was removed in gcc-11. The correct function to use is __gcov_dump which is defined in the gcov.h header.
Compile with ENABLE_GCOV=YES on any version. …

MDEV-30573 Server doesn't build with GCOV by GCC 11+

---

man/mysql_fix_extensions.1
scripts/mysql_fix_extensions.sh

This is a myisam script and we encourage the use of Aria. So we deprecate it.
Its useful to deprecate it as carrying large amount of low utility scripts makes it hard to determine what is useful and what isn't in the packaging.
Run it.

MDEV-30448 No deprecation message shown for mysql_fix_extensions

---

mysql-test/suite/plugins/r/locales.result
mysql-test/suite/plugins/t/locales.test
sql/sql_locale.cc

As requested to the UN the country formerly known as Turkey is to be refered to as Türkiye.
Reviewer: Alexander Barkov
TODO: fill details here, if applicable, or remove the …

MDEV-30621: Türkiye is the correct current country naming

---

mysql-test/main/func_json.result
mysql-test/main/func_json.test
sql/item_jsonfunc.cc

JSON_OBJECTAGG doesn't escape double quote in key
Append the tests to `func_json.test`

MDEV-30412: JSON_OBJECTAGG doesn't escape double quote in key

---

mysql-test/main/func_json.result
mysql-test/main/func_json.test
sql/item_jsonfunc.h

JSON_LENGTH does not return error upon wrong number of parameters
The test is 'json_length.test'.

MDEV-24538: JSON_LENGTH does not return error upon wrong number of parameters

---

storage/maria/ha_s3.cc
storage/maria/s3_func.c

Very minor hits found by Coverity for the S3 engine.

Fix S3 engine Coverity hits

---

.gitlab-ci.yml

**This is _NOT_ intended to be merged to >=10.5 as GitLab CI 
is already implemented without using bundled SSL (planned for 10.5).**
Add .gitlab-ci.yml file to earliest supported branch to enable
automated building and testing for all MariaDB major branches.
For 10.3/4 we use the bundled SSL to build MariaDB when the platform
does not have OpenSSL 1.1 available. This requires the installation of
gnutls-devel as a dependency of MariaDB Connector/C.
OpenSSL 3.0 support was backported to MariaDB 10.5
(see https://github.com/MariaDB/server/pull/2036, f0fa40ef, 8a9c1e9c)
The pipeline for these changes successfully complete and a [public pipeline](https://salsa.debian.org/robinnewhouse/mariadb-server-mirror/-/commits/10.3-backport-CI) is available.
Note: The CI currently has a build failure in …

Backport GitLab CI to earlier branches

---

mysql-test/main/locale.result
mysql-test/main/locale.test
mysql-test/suite/plugins/r/locales.result
sql/sql_locale.cc

MDEV-28227 added the error messages in simplified characters. Lets use these for those running a zh_CN profile.
From Haidong Ji in the MDEV, Taiwan/Hong Kong (zh_TW/zh_HK) would expect traditional characters so this is left for when we have these.
plugin.locales tests.
```
mariadbd  --lc-messages=ZH_CN --lc-messages-dir=$PWD/sql/share/chinese
2023-02-15 10:44:32 0 [Note] sql/mysqld：已经准备好接受连接
Version：'10.4.29-MariaDB'套接字：'/tmp/build-mariadb-server-10.4.sock'端口：0 Source distribution
```
```
MariaDB [(none)]> select none;
ERROR 1054 (42S22): 未知列'none'在'field list'
MariaDB [(none)]> is this an error?;
ERROR 1064 (42000): 您的 SQL 语法有错误；请查看相关文档 附近'is this an error?'在第1行
MariaDB [(none)]> select version();
+-----------------+
| version()       |
+-----------------+
| 10.4.29-MariaDB | …
```

MDEV-30630 locale: Chinese error messages for ZH_CN

---

mysql-test/suite/perfschema/r/events_waits_current_MDEV-29091.result
mysql-test/suite/perfschema/r/table_aggregate_hist_2u_2t.result
mysql-test/suite/perfschema/r/table_aggregate_hist_2u_3t.result
mysql-test/suite/perfschema/r/table_aggregate_hist_4u_2t.result
mysql-test/suite/perfschema/r/table_aggregate_hist_4u_3t.result
mysql-test/suite/perfschema/t/events_waits_current_MDEV-29091.test
storage/perfschema/pfs.cc

When one session SELECT rows FOR UPDATE and holds the lock, subsequent
sessions that SELECT ... FOR UPDATE will wait to get the lock.
Currently, that event is labeled as `wait/io/table/sql/handler`, which
is incorrect. Because it is NOT waiting for IO. Instead, it should have
been `wait/lock/table/sql/handler`.
All existing test cases should still be passing in Buildbot as well as
GitLab-CI. In addition, new test case added for this PR should also pass.
This bug fix should be fully backward-compatible
BSD-new license. I am contributing on behalf of my employer Amazon Web
Services, Inc.

MDEV-29091: Correct event_name in PFS for wait caused by FOR UPDATE

---

include/ssl_compat.h

Fix the following build failure with libressl >= 3.5.0:
```
In file included from /tmp/instance-10/output-1/build/mariadb-10.3.36/vio/viosslfactories.c:18: /tmp/instance-10/output-1/build/mariadb-10.3.36/vio/viosslfactories.c: In function 'get_dh2048': /tmp/instance-10/output-1/build/mariadb-10.3.36/include/ssl_compat.h:68:45: error: invalid use of incomplete typedef 'DH' {aka 'struct dh_st'}
68 | #define DH_set0_pqg(D,P,Q,G)            ((D)->p= (P), (D)->g= (G))
|                                             ^~
```
Fixes:
- http://autobuild.buildroot.org/results/524198344aafca58d214537af64c5961c407b0f8
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

include/ssl_compat.h: fix build with libressl >= 3.5.0

---

client/mysql.cc
client/mysql_upgrade.c
client/mysqladmin.cc
client/mysqlbinlog.cc
client/mysqlcheck.c
client/mysqldump.c
client/mysqlslap.c
client/mysqltest.cc
sql/sql_string.cc

The purpose of this patch is to address scan by coverity on MariaDB client folder.
There are couple of commits for one or more files in client folder.
Each commit is addressing specific coverity status on found defect in specific file or files.
Check commit message and check coverity scan.

MDBF-534: Coverity scan: fix client folder

---

storage/connect/mysql-test/connect/r/mysql.result
storage/connect/mysql-test/connect/t/mysql.test
storage/connect/myutil.cpp

When using the MySQL table type the CONNECT engine converted the YEAR datatype to DATETIME for INSERT queries. This is incorrect, causing an error on the INSERT. It should be SHORT instead.
Extra regression suite test added.
N/A

MDEV-29782 CONNECT YEAR type conversion fix

---

scripts/mysql_install_db.sh

If you are running mariadb-install-db from a source tree instead of installation it was executing `mysqld` instead of `mariadb` which showed the deprecation warning. This patch fixes that as well as fixing messages and links to other things that have been renamed.

Fix warning in mariadb-install-db

---

plugin/aws_key_management/aws_key_management_plugin.cc

AWS KMS plugin saves all key files under the root folder of data
directory. Increasing of the key IDs and key rotations will generate a
lot of key files under the root folder, looks messy and hard to
maintain the folder permission etc.
Now introduce a new plugin parameter `aws_key_management_keyfile_dir` to
define the directory for saving the key files for better maintenance.
Detailed parameter information as following:
```
VARIABLE_NAME: AWS_KEY_MANAGEMENT_KEYFILE_DIR
SESSION_VALUE: NULL
GLOBAL_VALUE: <Directory path>
GLOBAL_VALUE_ORIGIN: COMMAND-LINE
DEFAULT_VALUE:
VARIABLE_SCOPE: GLOBAL
VARIABLE_TYPE: VARCHAR
VARIABLE_COMMENT: Define the directory in which to save key files for the AWS key management plugin.
If not set, the root datadir will be used
READ_ONLY: YES …
```

Add parameter of key file path for AWS KMS plugin

---

mysql-test/main/locale.result
mysql-test/main/locale.test
mysql-test/main/variables.result
mysql-test/main/variables.test
mysql-test/suite/plugins/r/locales.result
mysql-test/suite/sys_vars/r/lc_time_names_basic.result
mysql-test/suite/sys_vars/t/lc_time_names_basic.test
sql/sql_locale.cc

Adding support of Georgian in sql_locale.cc
- [x ] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/11.0/CODING_STANDARDS.md) file and my PR conforms to …

MDEV-30789 Adding full support for Georgian language

---

libmysqld/libmysql.c
mysys/my_atomic_writes.c
mysys/my_conio.c
mysys/my_likely.c
mysys/my_thr_init.c
sql-common/client.c
strings/conf_to_src.c
strings/uctypedump.c
strings/xml.c

Replace calls to `sprintf` and `strcpy` by the safer options `snprintf` and `safe_strcpy` in the following directories:
- libmysqld
- mysys
- sql-common
- strings
All build stages pass for these commits. For the commit without the intentional bug, mysql-test-run is properly passing. The changes are not change the functionality itself they just replace unsafe C methods with the safe ones.
The changes fully backward compatible.

 Minimize unsafe C functions usage - replace sprintf() and strcpy()

---

sql/signal_handler.cc

and my_getwd(). The cause is my_errno define which depends on my_thread_var being a not null pointer
otherwise it will be de-referenced and cause
a SEGV already in the signal handler.
Replace uses of these functions in the output_core_info using posix read/getcwd functions instead.
The getwd fallback in my_getcwd isn't needed as
its been obsolute for a very long time.
Thanks Vladislav Vaintroub for diagnosis and posix recommendation.\
```
information that should help you find out what is causing the crash.
Writing a core file...
Working directory at /tmp/build-mariadb-server-10.4-datadir
Resource Limits:
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size …
```

MDEV-30613 output_core_info crashes in my_read()

---

.gitlab-ci.yml
support-files/mini-benchmark.sh

The mini-benchmark.sh script failed to run in the latest Fedora
distributions in GitLab CI. It requires `lscpu` resolved by installing
util-linux.
Additionally, executing the benchmark inside a Docker container had
failed because of increased Docker security in recent updates. In
particular the `renice` and `taskset` operations are not permitted.
Neither are the required `perf` operations.
https://docs.docker.com/engine/security/seccomp/
Allow these operations to fail gracefully, and test then skip `perf`,
allowing the remaining benchmark activities to proceed.
Other minor changes to the CI are included such as allowing sanitizer
jobs to fail and using "needs" in the mini-benchmark pipeline.
The pipeline for these changes successfully complete and a [public …

Fix mini-benchmark

---

sql/sql_class.h
sql/temporary_tables.cc

MDEV-23000: Ensure we get a warning from THD::drop_temporary_table() in case of disk errors 

---

extra/comp_err.c
sql/derror.cc
sql/share/errmsg-utf8.txt

Charset names in the 'languages' line are not used any more.
Removing to avoid confusion.
All messages in errmsg-utf8.txt are in utf8 now.
Charset names should have been removed in MySQL-5.5 during: https://dev.mysql.com/worklog/task/?id=751
Bump version number.
Sufficient mtr tests cases around error messages /locales as updated in previous 10.11 commit.
Its on 10.11 for ease of review (lack of merge conflicts with previous commit). Might need to go to 11.0 / 11.1.
Bumping version number means errmsg.sys cannot be used on older versions.

MDEV-30810 errmsg-utf8.txt no longer uses charsets

---

sql/sql_class.h

This Was failing to compile with AppleClang 14.0.0.14000029.
Thanks to Arunesh Choudhary for noticing.
Compile with latest AppleClang

sql_class: sprintf -> snprintf

---

sql/rpl_reporting.h

This was failing to compile with AppleClang 14.0.0.14000029.
Thanks to Arunesh Choudhary for noticing.
- [ X ] *This is a bug fix and the PR is based against the earliest …

rpl_reporting: sprintf -> snprintf

---

debian/autobake-deb.sh
debian/mariadb-server.mariadb.init
debian/mariadb-server.preinst

Reasoning behind this is that AWK is under used to be hard dependency for building or  installating MariaDB with Debian. This PR removed most part of (G)AWK need.
Debian installation needs/uses AWK for checking for is there enough space for new database. As this is neat and cute way to do it is this reasoning to have AWK installed for example in container image if it's not needed afterwards?
AWK is also used with SysV-init script same purpose with one line which can be rewritten easily (as postint script) to use GNU `coreutils`  and pure BASH which are used and installed.
Same goes with `autobake-debs.sh` where AWK is used just for printing out packages after build. It can be rewritten using Bash only.
This can be tested to build packages and install them and have not enough installation …

MDEV-30837: Remove awk from Debian scripts
