MariaDB/server

mysql-test/r/alter_table_online.result, mysql-test/t/alter_table_online.test, sql/sql_table.cc
This no-op of an operations should be able to occur without locks and
occur online.
=> Alter online table x (no options) possible

storage/xtradb/include/os0file.h, storage/xtradb/os/os0file.cc, storage/xtradb/row/row0mysql.cc, storage/xtradb/srv/srv0start.cc
* This fix for XtraDB should be applied to both MariaDB 10.0 and 10.1
* This was fixed for InnoDB in MariaDB 10.0 and 10.1 here..
* https://github.com/MariaDB/server/commit/a65162a396b1c298687992dd62ece924978b4c29
* This was originally fixed for InnoDB in MySQL 5.6 here..
* https://github.com/mysql/mysql-server/commit/aee6bc8ed15e14fb2a532cd0ebffa0ec161c0e77 & https://github.com/mysql/mysql-server/commit/8c486f2bc2fdb1a75214d4061de76f4718cf0a65
* This has not yet been fixed for InnoDB in MySQL 5.7 (I'm not sure why?)
####
Bug report can be found here https://mariadb.atlassian.net/browse/MDEV-7480
=> Apply fixes for raw devices to XtraDB in MariaDB 10.0

extra/innochecksum.cc
fclose the file and free memory. Mainly to remove errors in static analysis of code
=> innodbchecksum: add fclose and handle errors

plugin/auth_gssapi/gssapi_client.cc
As noted during review, my last name is spelled "Harwood".  Thanks, and glad to see the rest of this land!
=> Fix spelling of my name

sql/rpl_reporting.cc
I submit this under MCA..
I'll group a number of pull requests into a MDEV related to minor things that remove static analysis warnings.
=> MDEV-9433: Add va_end to sql/rpl_reporting.cc to make cppcheck happy

storage/innobase/include/log0log.h, storage/xtradb/include/log0log.h
This code of the whole pull request, including one or several files that are contributed, either new files or modified ones, under the BSD-new license.
=> Fix spelling: shhould -> should

storage/innobase/btr/btr0sea.cc, storage/innobase/include/btr0sea.h, storage/xtradb/btr/btr0sea.cc, storage/xtradb/include/btr0sea.h
From https://github.com/MariaDB/server/pull/169#discussion_r65465588
=> MDEV-10168 - Remove  btr_search_n_succ and btr_search_n_hash_fail counters

storage/tokudb/mysql-test/tokudb_parts/r/partition_alter1_1_2_tokudb.result, storage/tokudb/mysql-test/tokudb_parts/r/partition_alter1_1_tokudb.result, storage/tokudb/mysql-test/tokudb_parts/r/partition_alter1_2_tokudb.result, storage/tokudb/mysql-test/tokudb_parts/r/partition_alter2_1_1_tokudb.result, storage/tokudb/mysql-test/tokudb_parts/r/partition_alter2_2_1_tokudb.result, storage/tokudb/mysql-test/tokudb_parts/r/partition_alter4_tokudb.result, storage/tokudb/mysql-test/tokudb_parts/r/partition_basic_tokudb.result
=> MDEV-10707 Tokudb tokudb_parts test suites failing

mysql-test/r/derived_cond_pushdown.result, mysql-test/t/derived_cond_pushdown.test, sql/item.cc, sql/item.h, sql/item_cmpfunc.cc, sql/item_cmpfunc.h, sql/item_func.cc, sql/item_func.h, sql/item_geofunc.h, sql/item_inetfunc.h, sql/item_row.cc, sql/item_row.h, sql/item_strfunc.h, sql/item_subselect.h, sql/item_sum.h, sql/item_timefunc.h, sql/item_windowfunc.h, sql/item_xmlfunc.cc, sql/item_xmlfunc.h, sql/procedure.h, sql/sql_derived.cc, sql/sql_derived.h, sql/sql_lex.cc, sql/sql_lex.h, sql/sql_priv.h, sql/sql_select.cc, sql/sql_select.h, sql/sys_vars.cc, sql/table.cc, sql/table.h
The consolidated patch for mdev-9197.
=> MDEV-9197 - Pushdown conditions into non-mergeable views/derived tables

storage/innobase/handler/ha_innodb.cc, storage/xtradb/buf/buf0flu.cc, storage/xtradb/handler/ha_innodb.cc
This code of the whole pull request, including one or several files that are contributed, either new files or modified ones, under the BSD-new license.
=> Remove unnecessary semicolons

debian/control, debian/libmariadbclient-dev.install, debian/libmariadbd-dev.install, debian/libmariadbd18.install, debian/libmariadbd19.install
Small fixes on the MDEV-6284 merge.
=> MDEV-5725: debian packaging

storage/innobase/lock/lock0lock.cc
Remove the victim preference since VATS is not enabled in replication.
Consider lock wit mode first.
=> Bug fix for has_higher_priority

sql/hostname.cc
Let me know if I am missing anything
=> fixes MDEV-11354 twin include

mysql-test/mysql-test-run.pl
=> MDEV-11619: mtr --mem and $MTR_MEM support in sane and consistent manner (10.0)

mysql-test/suite/compat/oracle/r/sp-goto.result, mysql-test/suite/compat/oracle/t/sp-goto.test, sql/lex.h, sql/sp_head.cc, sql/sp_head.h, sql/sp_pcontext.cc, sql/sp_pcontext.h, sql/sql_lex.cc, sql/sql_lex.h, sql/sql_yacc.yy, sql/sql_yacc_ora.yy
Hi Alexander,
This is the pull request with only one commit.
Regards
=> MDEV-10697 GOTO statement

scripts/galera_new_cluster.sh
From: https://github.com/devexp-db/mariadb/blob/f27/mariadb-galera-new-cluster-help.patch
=> MDEV-12646: wsrep_new_cluster: Add -h and --help options

mysql-test/r/func_str.result, mysql-test/t/func_str.test, sql/item_create.cc, sql/item_strfunc.cc, sql/item_strfunc.h
I shared this patch under term of MCA.
Regards.
=> MDEV-12658 Make the third parameter to LPAD and RPAD optional

.travis.yml
Since OSX tests are so make them as allowed_failures.
=> travis: allow_failures os: osx

sql/threadpool_unix.cc
Found by Coverity scan - id 92087
=> thread_group_close: release mutex in all branches

sql/ha_partition.cc, sql/ha_partition.h
=> remove unneeded allocation

sql/sql_lex.cc, sql/sql_lex.h
=> remove a dead code

sql/sql_lex.cc, sql/sql_lex.h, sql/sql_parse.cc
=> remove dead code

README.md
Made a few links in README.md secure (https).
=> README.md - Secure (HTTPS) Links

mysql-test/suite/compat/oracle/r/func_substr.result, mysql-test/suite/compat/oracle/t/func_substr.test, sql/item_create.cc, sql/item_strfunc.cc, sql/item_strfunc.h, sql/sql_lex.cc, sql/sql_lex.h, sql/sql_yacc.yy, sql/sql_yacc_ora.yy
I share this code under term of MCA.
=> MDEV-14012 - sql_mode=Oracle: substr(): treat position 0 as position 1

sql/table.h
=> unused class member

.travis.yml
=> travis: no percona tests in 10.3

debian/patches/33_scripts__mysql_create_system_tables__no_test.dpatch, debian/patches/38_scripts__mysqld_safe.sh__signals.dpatch, debian/patches/41_scripts__mysql_install_db.sh__no_test.dpatch, debian/patches/50_mysql-test__db_test.dpatch, sql/sql_derived.cc, sql/sql_lex.cc, sql/sql_view.cc
=> SQL: optimized build fix on view/derived

mysql-test/suite/sql_sequence/gtid.result, mysql-test/suite/sql_sequence/gtid.test, mysql-test/suite/sql_sequence/replication.result, mysql-test/suite/sql_sequence/replication.test
=> Tests: some sql_sequence tests require wsrep plugin

storage/innobase/include/log0recv.h
Hi, I found a misspelling in log0recv.h and fixed it.
Thank you.
=> Spelling fix

.travis.yml, debian/autobake-deb.sh, debian/rules
For details see the git commits.
=> Fix Travis-CI issues and most notably make the deb build job pass

.gitignore
=> Misc: updated .gitignore

support-files/mariadb.service.in, support-files/mariadb@.service.in
=> MDEV-12128: systemd: add Documentation= directives

include/my_dbug.h, sql/item_func.cc, sql/item_sum.cc, sql/key.cc, sql/log.cc, sql/log_event.cc, sql/mdl.h, storage/perfschema/pfs.cc, storage/perfschema/table_threads.cc
Old PR https://github.com/MariaDB/server/pull/543
=> Compilation speed

scripts/mysql_install_db.sh
correct some information in the mysql_install_db script.
=> mysql_install_db info

scripts/wsrep_sst_xtrabackup-v2.sh
Based off #451
@angeloudy,@arj can you please check this.
Targeted xtrabackup-v2 as it seems the wsrep_sst_xtrabackup-v2 is going to be used for mariabackup too (MDEV-14030)
sh compatibility maintained. Note there is one other find here though the binlogs didn't seem to be using extended expressions.
=> MDEV-13789: FreeBSD wsrep_sst_xtrabackup-v2 - find compatibilty +lsof

debian/autobake-deb.sh, debian/control, debian/mariadb-plugin-rocksdb.install, storage/rocksdb/CMakeLists.txt
Hi Otto!
Can you double check the changes to debian/control for adding myrocks_hotbackup script?
Vicentiu
=> Add myrocks hotbackup

sql/mysqld.cc
=> remove duplicated inclusion of derror.h

mysql-test/suite/sys_vars/r/innodb_buffer_pool_dump_abort_loads.result, mysql-test/suite/sys_vars/r/sysvars_innodb.result, mysql-test/suite/sys_vars/t/innodb_buffer_pool_dump_abort_loads.opt, mysql-test/suite/sys_vars/t/innodb_buffer_pool_dump_abort_loads.test, mysql-test/suite/sys_vars/t/sysvars_innodb.test, storage/innobase/buf/buf0dump.cc, storage/innobase/handler/ha_innodb.cc, storage/innobase/include/srv0srv.h, storage/innobase/srv/srv0srv.cc
Rebase work from #265 (against 10.3) and completed test case with debug system variable.
Sorry for late resubmit. Missed the debug variable option in the review to make this work. Had battled with debug_sync unsuccessfully for far too long last time.
FYI @dr-m , @janlindstrom , address your previous review comments.
=> MDEV-11455: innodb buffer pool dump incomplete load

debian/dist/Debian/control, debian/dist/Ubuntu/control
=> debian: VCS is on github

mysys/my_fopen.c
=> my_fdopen: list all args in comment

mysql-test/suite/compat/oracle/r/func_substr.result, mysql-test/suite/compat/oracle/t/func_substr.test, sql/item_strfunc.h
I share this code under terms of MCA.
=> MDEV-10574 / SUBSTR - sql_mode=Oracle: return null instead of empty string

include/my_global.h, mysys/my_symlink.c, sql/log.cc, storage/innobase/handler/ha_innodb.cc, storage/innobase/os/os0file.c, storage/maria/ma_control_file.c, storage/maria/ma_loghandler.c, storage/maria/ma_open.c, storage/myisam/mi_open.c, storage/xtradb/handler/ha_innodb.cc, storage/xtradb/os/os0file.c
FD 2,3 need to be open by subprocesses for SST to report error. Rest of files are CLOEXEC (todo fd 5, datadir).
<pre>
$ cd /proc/20448
$ ls -la --sort=none fd                          
total 0
dr-x------. 2 dan dan  0 Mar  2 12:03 .
dr-xr-xr-x. 9 dan dan  0 Mar  2 12:03 ..
lrwx------. 1 dan dan 64 Mar  2 12:03 0 -> /dev/pts/8
l-wx------. 1 dan dan 64 Mar  2 12:03 1 -> /tmp/error.log
l-wx------. 1 dan dan 64 Mar  2 12:03 2 -> /tmp/error.log
lrwx------. 1 dan dan 64 Mar  2 12:03 3 -> /tmp/datadir/mysqlbin.index
lrwx------. 1 dan dan 64 Mar  2 12:03 4 -> /tmp/datadir/aria_log_control
lr-x------. 1 dan dan 64 Mar  2 12:03 5 -> /tmp/datadir
lrwx------. 1 dan dan 64 Mar  2 12:03 6 -> /tmp/datadir/aria_log.00000001
lrwx------. 1 dan dan 64 Mar  2 12:03 7 -> /tmp/datadir/ibdata1
lrwx------. 1 dan …
=> MDEV-8743: use CLOEXEC to protect mariadb files from sst script touching

storage/innobase/dict/dict0dict.cc, storage/innobase/include/os0file.h, storage/innobase/lock/lock0lock.cc, storage/innobase/os/os0file.cc, storage/innobase/srv/srv0start.cc
=> innodb: os_file_create_tmpfile always called with NULL -> simplify

mysql-test/suite/galera/disabled.def, mysql-test/suite/galera/r/galera_as_master.result, mysql-test/suite/galera/t/galera_as_master.test
Was failing due to missing RESET MASTER
=> MDEV-13549 Fix and re-enable MTR test galera.galera_as_master

mysql-test/suite/galera/disabled.def, mysql-test/suite/galera/r/galera_ist_mysqldump.result, mysql-test/suite/galera/t/galera_ist_mysqldump.test
Test works after fixes for galera_sst_mysqldump.
=> MDEV-13549 Record and re-enable galera_ist_mysqldump

mysql-test/suite/versioning/r/sysvars.result, mysql-test/suite/versioning/t/sysvars.test, sql/mysqld.cc, sql/sql_class.h, sql/table.cc
This code is submitted under the BSD-new license.
=> MDEV-15978 Add Feature_system_versioning status variable

sql/sql_insert.cc, sql/table.cc, sql/table.h
=> cleanup TABLE_LIST

scripts/wsrep_sst_rsync.sh
(cherry picked from commit 1adc382c2fb4300059d130521a24a1dab141531e)
=> Use stunnel during rsync SST if available

man/CMakeLists.txt, man/mysql_ldb.1
Separate commit, as mysql_ldb is available only in 10.2
=> MDEV-14927: Missing man pages

debian/dist/Ubuntu/mariadb-galera-server-5.5.py
=> MDEV-13129: apport - sanitize wsrep_sst_auth from report

storage/innobase/handler/handler0alter.cc
cleanup
change_fields_versioning_try(): use innodb_col_no() instead of a manual loop
change_fields_versioning_cache(): use innodb_col_no() instead of a manual loop
=> MDEV-16330 Allow instant change of WITH SYSTEM VERSIONING column attribute

README.md
Update Travis CI badge to active branch and break off long line.
=> Small updates for README.md

storage/innobase/include/ut0counter.h
=> MDEV-17313 Data race in ib_counter_t

.travis.yml
update xcode version.
Overall its not worse.
I submit this under the MCA.,
=> travis: xcode10.1

mysql-test/mysql-test-run.pl, mysql-test/suite/wsrep/t/binlog_format.test, sql/wsrep_server_service.cc
Pull request 50 contained fix for mysql-test-run.pl
=> bb-10.4-galera4-PR50 Merge from 10.4-wsrep_API-26, PR 50

mysql-test/lib/My/ConfigFactory.pm, mysql-test/suite/galera/galera_2nodes.cnf, mysql-test/suite/galera/galera_2nodes_as_master.cnf, mysql-test/suite/galera/galera_2nodes_as_slave.cnf, mysql-test/suite/galera/galera_3nodes_as_slave.cnf, mysql-test/suite/galera/galera_4nodes.cnf, mysql-test/suite/galera/r/galera_pc_recovery.result, mysql-test/suite/galera_3nodes/galera_2x3nodes.cnf, mysql-test/suite/galera_3nodes/galera_3nodes.cnf, mysql-test/suite/galera_3nodes/r/galera_garbd.result
* Fixed galera.galera_pc_recovery
* Fixed galera_3nodes.galera_garbd
* Fixed initialization of ENV variables in config file
=> Pull request codership/mariadb-wsrep#64

sql/wsrep_client_service.cc
Some tests fail for seeing ER_QUERY_INTERRUPTED when ER_DEADLOCK_ERROR was expected.
e.g. MW-328B can fail for this sporadically.
The fix here allows interrupted state for client, only if THD is not aborted by wsrep.
ER_QUERY_INTERRUPTED is still possible, if connection is killed manually.
=> ER_QUERY_INTERRUPTED returned for cluster conflicts

storage/innobase/dict/dict0mem.cc, storage/innobase/handler/handler0alter.cc, storage/innobase/include/dict0mem.h
@dr-m Please, merge.
This code is submitted under the BSD-new license.
=> non_pk_col_map code readability

mysql-test/suite/galera_sr/r/galera_sr_shutdown_master.result, mysql-test/suite/galera_sr/t/galera_sr_shutdown_master.test
* Test needed auto increment save / restore
* Fixed suppression of warning, warning text changed
=> Fix MTR test galera_sr.galera_shutdown_master

mysql-test/suite/galera_sr/r/galera_sr_ws_size2.result
Records the test and updates to wsrep-lib revision that contains a
fix to make it pass.
=> Record MTR test galera_sr.galera_sr_ws_size2

mysql-test/suite/galera/galera_2nodes.cnf, mysql-test/suite/galera/galera_2nodes_as_master.cnf, mysql-test/suite/galera/galera_2nodes_as_slave.cnf, mysql-test/suite/galera/galera_3nodes_as_slave.cnf, mysql-test/suite/galera/galera_4nodes.cnf, mysql-test/suite/galera/include/galera_base_port.inc, mysql-test/suite/galera/r/galera_pc_recovery.result, mysql-test/suite/galera/t/galera_pc_recovery.test, mysql-test/suite/galera_3nodes/galera_2x3nodes.cnf, mysql-test/suite/galera_3nodes/galera_3nodes.cnf, mysql-test/suite/galera_3nodes/r/galera_garbd.result, mysql-test/suite/galera_3nodes/t/galera_garbd.test
* Extract base_port from wsrep_provider_options
* galera_pc_recovery and galera_garbd modified and re-recorded
* Removed unsed ENV variables in .cnf files
=> Extract base_port directly from galera node

scripts/wsrep_sst_mariabackup.sh
The mariabackup SST script was incorrectly processes
innodb_data_home_dir parameter if it is specified in
the configuration file for one of the cluster nodes.
Therefore, a corresponding revision of the mariabackup
SST script was made, which provides reading of the
corresponding parameter from the configuration file
or from the command line.
https://jira.mariadb.org/browse/MDEV-17848
=> MDEV-17848: Galera test failure on galera_sst_xtrabackup-v2[_data_dir]

mysql-test/suite/galera_3nodes_sr/r/GCF-606.result, mysql-test/suite/galera_3nodes_sr/r/GCF-817.result, mysql-test/suite/galera_3nodes_sr/r/GCF-832.result, mysql-test/suite/galera_3nodes_sr/r/galera_sr_isolate_master.result, mysql-test/suite/galera_3nodes_sr/r/galera_sr_join_slave.result, mysql-test/suite/galera_3nodes_sr/r/galera_sr_kill_master.result, mysql-test/suite/galera_3nodes_sr/r/galera_sr_kill_slave_after_apply.result, mysql-test/suite/galera_3nodes_sr/r/galera_sr_kill_slave_after_apply_rollback.result, mysql-test/suite/galera_3nodes_sr/r/galera_sr_kill_slave_before_apply.result, mysql-test/suite/galera_3nodes_sr/r/galera_sr_threeway_split.result, mysql-test/suite/galera_3nodes_sr/t/GCF-817.test, mysql-test/suite/galera_3nodes_sr/t/GCF-832.test, mysql-test/suite/galera_3nodes_sr/t/disabled.def, mysql-test/suite/galera_3nodes_sr/t/galera_sr_join_slave.test, mysql-test/suite/galera_3nodes_sr/t/galera_sr_kill_master.test, mysql-test/suite/galera_3nodes_sr/t/galera_sr_kill_slave_after_apply.test, mysql-test/suite/galera_3nodes_sr/t/galera_sr_kill_slave_after_apply_rollback.test, mysql-test/suite/galera_3nodes_sr/t/galera_sr_kill_slave_before_apply.test, mysql-test/suite/galera_3nodes_sr/t/galera_sr_threeway_split.test
Recorded all tests that pass, disabled the rest.
=> Record tests in galera_3node_sr suite

mysql-test/suite/galera/r/galera_as_slave_nonprim.result, mysql-test/suite/galera/t/galera_as_slave_nonprim.test, sql/wsrep_mysqld.cc
* Only call sync_wait for wsrep_client_threads
* Removed wsrep_on=ON/OFF for non wsrep server
=> Fix for galera.galera_as_slave_nonprim

scripts/wsrep_sst_mariabackup.sh
resubmitting pull request for  #718
=> Make mariabackup.sh compatible on FreeBSD

mysql-test/suite/galera/r/galera_concurrent_ctas.result, sql/service_wsrep.cc, sql/sql_insert.cc, sql/wsrep_thd.cc, storage/innobase/include/trx0trx.h
This pull request has fixes for MW-286 test and create table as select processing. 
A separate fix for MW-286 has been merged in earlier, but this pul request does not conflict with it.
=> bb-10.4-galera4-mw-286-ctas,  Fix for create table as select

.travis.yml
passed in https://travis-ci.org/grooverdan/mariadb-server/jobs/330273292
=> MDEV-15022 - travis: add versioning to test suite

mysql-test/suite/wsrep/t/mdev_10186.cnf, mysql-test/suite/wsrep/t/mdev_10186.opt, mysql-test/suite/wsrep/t/mdev_10186.test, sql/mysqld.cc, sql/wsrep_var.cc
* Don't initialize wsrep if WSREP_ON is false.
* Check if provider is loaded before changing address
=> Fix for wsrep.mdev_10186

scripts/mysql_install_db.sh
=> remove duplicated paragraph from mysql_install_db.sh

mysql-test/suite/galera/r/galera_sst_mysqldump,release.rdiff
Created galera_sst_mysqldump,release.diff
=> Added release result diff for galera.galera_sst_mysqldump

include/mysql/service_wsrep.h, sql/wsrep_schema.cc, sql/wsrep_schema.h, storage/innobase/row/row0ins.cc, storage/innobase/row/row0sel.cc
Changed type of variable `sr_table_name_full_str` to `const char*` and
renamed it `wsrep_sr_table_name_full`.
=> Make sr_table_name_full_str `const char*`

mysql-test/suite/galera/r/galera_FK_duplicate_client_insert.result
Recorded new test result, old result file missed debug run "connection node_1" tags
=> Fix for galera_FK_duplicate_client_insert

mysql-test/mysql-test-run.pl
* Moved waiting for wsrep to be ready in mysql_server_start and
mysql_server_wait.
* Fixed function wait_wsrep_ready() to work also when MTR runs with
option --verbose.
* Fixed wsrep_is_bootstrap_server() so that it checks both
`wsrep_cluster_address` and `wsrep-cluster-address`.
Also, the function was returning `undef` when `false` was expected.
=> Fixes to mysql-test-run.pl according to Svoj's review

mysql-test/suite/innodb/r/alter_varchar_change.result, mysql-test/suite/innodb/r/instant_varchar_enlarge.result, mysql-test/suite/innodb/t/alter_varchar_change.test, mysql-test/suite/innodb/t/instant_varchar_enlarge.test
[Buildbot](http://buildbot.askmonty.org/buildbot/grid?category=main&branch=tt-10.2-MDEV-18468-merge-tests)
=> MDEV-18468 merge instant_varchar_enlarge.test and alter_varchar_change.test

mysql-test/suite/innodb/r/alter_varchar_change.result, mysql-test/suite/innodb/t/alter_varchar_change.test
Make ALGORITHM=INSTANT explicit.
[Buildbot](http://buildbot.askmonty.org/buildbot/grid?category=main&branch=tt-10.3-MDEV-18470-improve-test)
=> MDEV-18470 improve alter_varchar_change.test

cmake/submodules.cmake
Tell developers about the git config `cmake.update-submodules`
=> cmake/submodules: notify user about gitconfig for automatic update

sql/lock.cc
Call desync_and_pause() and resync_and_resume() only if state is s_synced.
=> Fix for galera_3nodes.galera_var_dirty_reads2

mysql-test/suite/galera/disabled.def, mysql-test/suite/galera/r/MW-388.result, mysql-test/suite/galera/t/MW-388.test, sql/sp_head.cc
Fixed sync points in MW-388 and fixed SP wsrep error handling to
avoid propagating wsrep errors via client-server protocol response.
=> MDEV-18837 Fixed stored procedure wsrep error handling and MW-388

.gitignore
Let me know if this PR would be better suited for lower branch.
=> Ignore Visual Studio Code workspace 

mysql-test/suite/storage_engine/vcol.result, mysql-test/suite/vcol/r/vcol_ins_upd_innodb.result, mysql-test/suite/vcol/r/vcol_ins_upd_myisam.result, mysql-test/suite/vcol/r/vcol_misc.result, mysql-test/suite/vcol/r/vcol_select_myisam.result, sql/share/errmsg-utf8.txt, storage/innobase/mysql-test/storage_engine/vcol.rdiff, storage/myisammrg/mysql-test/storage_engine/vcol.rdiff
Fix for MDEV-17449, typo in error message.
=> Mdev 17449

mysql-test/main/mysqld--help.result, mysql-test/suite/sys_vars/r/sysvars_server_notembedded.result
=> MDEV-16543 Replicating to spider is fragile without retries

README.md, appveyor.yml
=> Appveyor configuration and addition of badge

BUILD/check-cpu
add Hygon CPU vendorID checking in check-cpu and use k8 as initial support
=> add Hygon Dhyana support in check-cpu

.clang-format, storage/innobase/.clang-format
Add .clang-format files to a root directory and to storage/innobase
[Buildbot](http://buildbot.askmonty.org/buildbot/grid?category=main&branch=tt-5.5-MDEV-13631-clang-format)
=> MDEV-13631 Make use of clang-format

mysql-test/suite/binlog/r/flashback-largebinlog.result, mysql-test/suite/binlog/t/flashback-largebinlog.test, mysys/mf_iocache.c
fix the problem that Failed to get the result using mysqlbinlog flashback option on big binlog file.(MDEV-18750)
=> MDEV-18750: Failed to get the result using mysqlbinlog flashback option on big binlog file

mysql-test/suite/sys_vars/r/slave_transaction_retry_errors.result
fix test result of sys_vars.slave_transaction_retry_errors
=> MDEV-17402 slave_transaction_retry_errors="12701" won't be enabled

support-files/mariadb@.service.in
=> MDEV-19884 systemd multiinstance - doc fix - version number

sql/log_event.cc, sql/sql_class.cc, sql/sql_class.h, sql/wsrep_high_priority_service.cc, sql/wsrep_high_priority_service.h, sql/wsrep_mysqld.cc, sql/wsrep_schema.cc
- TOI error ignoring fix (wsrep_ignore_apply_errors)
=>  - wsrep-lib update (SR cleanups and voting support)

sql/log.cc, sql/wsrep_binlog.cc, sql/wsrep_client_service.cc, sql/wsrep_client_service.h, sql/wsrep_high_priority_service.cc, sql/wsrep_high_priority_service.h, sql/wsrep_storage_service.cc, sql/wsrep_storage_service.h
Update wsrep-lib, and adapt to wsrep-lib interface changes.
=> MDEV-17099 Preliminary changes for Galera XA support

mysql-test/main/mysqld--help-aria.result, mysql-test/main/mysqld--help-aria.test, mysql-test/main/shutdown.result, mysql-test/main/shutdown.test, mysql-test/mysql-test-run.pl
=> MDEV-22010: mtr search for mariadbd first

mysql-test/suite/galera_3nodes/t/galera_ipv6_mariabackup.test, mysql-test/suite/galera_3nodes/t/galera_ipv6_mariabackup_section.test
and galera_ipv6_mariabackup MTR tests
=> Fix include statements in galera_ipv6_mariabackup_section

scripts/wsrep_sst_rsync.sh
Fix for Galera rsync SST with the specific conditions listed in MDEV-21709
=> MDEV-21709 ZFS snapdir=visible breaks Galera rsync SST replication 

debian/additions/mariadb.cnf, debian/additions/mariadb.conf.d/50-client.cnf, debian/additions/mariadb.conf.d/50-mysqld_safe.cnf, debian/additions/mariadb.conf.d/60-galera.cnf, storage/maria/s3.cnf, storage/spider/spider.cnf
=> MDEV-22980: Document plugin-maturity=alpha so users can more easily enable it; Unify config file style and links to KB

.github/CODEOWNERS
As the first entry, define user 'ottok' (Otto Kekäläinen) as the person
who by default gets assigned all PRs that modify the debian/ contents.
=> Add a Github CODEOWNERS file to project

client/mysqladmin.cc, mysql-test/main/mysqladmin.result, mysql-test/main/mysqladmin.test
Re-opens #1555 
Closes #MDEV-19168
Includes tests.
=> MDEV-19168: Add ssl-flush command.

sql/item_jsonfunc.cc
insencitive -> insensitive
excapint -> excipient
Jost -> Just
belive -> believe
=> Fix several typos in sql/item_jsonfunc.cc

storage/innobase/buf/buf0flu.cc
innodb_adaptive_flushing_lwm is hit. (possible regression)
adaptive flushing should kick in if
a. dirty_pct (dirty pages in buffer pool) > innodb_max_dirty_pages_pct_lwm
OR
b. innodb_adaptive_flushing_lwm limit is reached (default to 10%)
both conditions are mutually exclusive and whichever is first to evaluate
true should kick-start the adaptive flushing.
After recent changes to simplify the flushing algorithm logic, (b) got ignored
that introduced the said regression.
=> MDEV-25093: Adaptive flushing fails to kick in even if

CONTRIBUTING.md, README.md
Remove mention of Freenode/IRC
=> Remove mention of Freenode/IRC

.gitignore, include/my_context.h, mysys/my_context.c, storage/connect/bsonudf.cpp, storage/connect/inihandl.cpp, storage/connect/tabbson.cpp, storage/innobase/row/row0upd.cc
Xcode compatibility update
Compile with Xcode
=> Xcode compatibility update

sql/CMakeLists.txt
Fixing build for Xcode
Use CMake generator for Xcode. This patch fixes this problem:
```CMake Error in wsrep-lib/CMakeLists.txt:
The custom command generating
/Users/name/build/mariadb-server/sql/lex_token.h
is attached to multiple targets:
GenServerSource
sql
but none of these is a common dependency of the other(s).  This is not
allowed by the Xcode "new build system".
```
Compatible
=> MDEV-19129: Fixed configure for Xcode, CMake generate

support-files/policy/selinux/mariadb-server.te
This change is fixing SELinux issue after upgrading to MariaDB 10.4.24
=> fix: Fix 'unknown type usermodehelper_t' issue after upgrading to MariaDB 10.4.24

mysql-test/suite/perfschema/r/dml_file_instances.result, mysql-test/suite/perfschema/t/dml_file_instances.test
Order by results in MTR test to make it predictable.
=> MDEV-27932: perfschema.dml_file_instances mtr failure

mysql-test/suite/galera/t/galera_bf_abort_ps_bind.test
Test expects to be run with regular protocol (uses ps-protocol manually).
=> Disable galera_bf_abort_ps_bind under --ps-protocol

storage/spider/spd_db_conn.cc, storage/spider/spd_include.h
Hi team this is my first contribution to MariaDB! It'd be great if you could check this PR when you get a chance 🙏 
https://jira.mariadb.org/browse/MDEV-28359
Now that `SPIDER_HAS_MY_CHARLEN` is always defined at the below line, we can safely remove the `#ifdef SPIDER_HAS_MY_CHARLEN #else` condition branch permanently.
https://github.com/MariaDB/server/blob/441c26da22eb0af31e5de330eb9a426a2caab7ad/storage/spider/spd_include.h#L102
Since this does not change any existing behavior, we do not have to add any tests.
=> MDEV-28359 Spider: remove #ifdef SPIDER_HAS_MY_CHARLEN

sql/share/errmsg-utf8.txt
=> MDEV-25273 Typo in error message for ER_JSON_DEPTH: "strucures"

client/mysqldump.c, mysql-test/main/lock_view.result, mysql-test/main/mysqldump-nl.result, mysql-test/main/mysqldump.result, mysql-test/suite/roles/definer.result
This is particularly important for Azure where there is no
MyISAM support in their MariaDB cloud product.
Like mysqldumper does, a view can satisfy the requirement
like a table, without constraints. The views in frm files are
text form and don't have column limits.
Thanks @Hipska for the suggestion.
MTR tests
The temporary table, and now view, only existing within the time-frame of the import. While is possible something is manipulating these files directly, I don't think this is a common case, or one that can't be easily resolved.
=> MDEV-26447: mysqldump to use temporary view instead of tables.

sql/item_jsonfunc.cc
Please Refer PR [#2205](https://github.com/MariaDB/server/pull/2205)
=> Refactor: remove redundant assignments of JSON_MERGE_PATCH 

mysql-test/main/public_basic.result, mysql-test/main/public_basic.test, sql/sql_delete.h, sql/sql_update.h
Typo in PUBLIC roles test.
Missing override causing clang compile errors.
=> Preview 10.11 preview fixes

debian/additions/innotop/innotop, debian/additions/mariadb-report, debian/mariadb-server-10.5.postinst, debian/salsa-ci.yml
10.5 version
debian/additions/innotop/innotop
debian/additions/mariadb-report
debian/mariadb-server-10.5.postinst
debian/salsa-ci.yml
=> debian typos

include/mysql/psi/psi.h
10.5 version
include/mysql/psi/psi.h
=> header typo

include/my_compare.h, include/my_rdtsc.h
10.4 version
include/my_compare.h
include/my_rdtsc.h
=> header typos

debian/additions/innotop/innotop
Pull request created in: https://jira.mariadb.org/browse/MDEV-30353
=> MDEV-30353 Debian/additions version detection fix (trivial)

mysql-test/main/win_orderby.result, mysql-test/main/win_orderby.test, sql/sql_lex.cc, sql/sql_lex.h, sql/sql_list.h, sql/sql_parse.cc
Pull request created in: https://jira.mariadb.org/browse/MDEV-30052
=> MDEV-30052 SIGSEGV in subquery_types_allow_materialization, AddressSanitizer: use-after-poison in base_list_iterator::next

mysql-test/mariadb-test-run.pl
- Output as expected for 10.3+
```
$ ./mtr --suite=mroonga
worker[1] Using MTR_BUILD_THREAD 300, with reserved ports 16000..16019
mysql-test-run: *** ERROR: Test suite aborted
```
=> MDEV-30186: Use of uninitialized value  in substitution

debian/additions/mariadb.conf.d/50-mariadb-clients.cnf, debian/additions/mariadb.conf.d/50-mariadb_safe.cnf, debian/additions/mariadb.conf.d/50-server.cnf, debian/mariadb-client.install, debian/mariadb-server.README.Debian, debian/mariadb-server.install
May as well get some remaining bits of the naming right.
=> Deb: MariaDB naming

THIRDPARTY
Update UCA license based on:
https://www.unicode.org/license.txt and
https://www.unicode.org/copyright.html.
urls above.
=> MDEV-27009: Add UCA-14.0.0 collations - License

debian/autobake-deb.sh
=> deb: autobake - add lunar/mantic

.gitignore
Adding .ccls-cache/ to .gitignore, which is generated by the language server ccls
.ccls-cache/ is not considered for staging etc.
There's no need to write mtr tests for this.
No issues with backward compatibility
=> Adding .ccls-cache/ to .gitignore

cmake/cpack_rpm.cmake, debian/control, plugin/cracklib_password_check/CMakeLists.txt, storage/cassandra/CMakeLists.txt, storage/connect/CMakeLists.txt, storage/oqgraph/CMakeLists.txt, storage/rocksdb/CMakeLists.txt, storage/tokudb/CMakeLists.txt
Update package description, consistent about use of MariaDB server, and "package"
no tests required.
- [  X ] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced*
=> MDEV-31358: Update description for MariaDB debian/rpm packages

client/mysqladmin.cc
The `--verical` option does not appear to behave as documented and research shows it never appears to have behaved as intended.
As this appears to be a completely unused feature, let's remove it.
=> MDEV-15736 Remove mariadb-admin --vertical

sql/share/README.md, sql/share/insert_translations_into_errmsg.py
Instructions and a script to help speed up language translations for MariaDB are provided. The README.md provides instructions of a recommended workflow that involves:
- Extracting the English language entries in the file errmsg-utf8.txt
- Using online tools to do automatic translation.
- Proof-reading the automatic translations.
- Running the script insert_translations_into_errmsg.py that will take the original errmsg-utf8.txt file, the extracted english translations file and the new language translations file and generate a new file errmsg-utf8-with-new-language.txt that is a copy of errmsg-utf8.txt but with the new language entries inserted into it at the correct positions.
This procedure and script was used to generate the Swahili language translations in …
=> Facilitate translation of MariaDB error messages to new languages

storage/innobase/sync/srw_lock.cc
Fix debug mode build failure on s390x. 
Replaced builtin_ttest by __builtin_tx_nesting_depth() > 0 as a s390x equivalent version of the expression.
cmake -DCMAKE_BUILD_TYPE=Debug
make 
make install
mysql-test
./mtr --suite=unit --force --max-test-fail=0
=> MDEV-23924 s390x patch  srw_lock.cc

include/byte_order_generic_x86_64.h
=> typo fixed. HAVE_mi_uint8korr

storage/innobase/fsp/fsp0fsp.cc, storage/innobase/trx/trx0purge.cc
During undo log truncation, `trx_purge_truncate_history()` was prematurely removing dirty pages from the `buf_pool.flush_list`. This is not safe to do before `mtr_t::commit_shrink()`, where it is actually being done. If dirty pages are marked as clean before the size change of the undo tablespace has been durably written, the `buf_flush_page_cleaner()` thread could advance the InnoDB log checkpoint. On crash recovery, this would cause previously committed transactions within the undo tablespace to appear as incomplete, requiring a rollback.
```bash
./mtr --parallel=auto --repeat=100 innodb.undo_truncate_recover{,,,,,,,,,,,,,,,,,,}
```
Thanks to the 10.5 specific bug [MDEV-32681](https://jira.mariadb.org/browse/MDEV-32681), InnoDB can be forcibly killed before `mtr_t::commit_shrink()` …
=> 10.5 MDEV-32757 innodb_undo_log_truncate=ON is not crash safe

storage/innobase/buf/buf0buf.cc
After discovering eventfds for #2807 it simplifies the current implementation a little here too.
Like #2807 we don't get to read from the eventfd in the quit case as the m_abort flag is set.
Eventfds have a simpler interface and are one file descriptor rather than two.
Reuse the patten of the accepting socket connections by testing for abort after a poll returns. This way the same event descriptor can be used for Quit
and debugging trigger.
Also correct the registration of mem pressure file descriptors.
mem_pressure test already.
=> MDEV-24670 memory pressure - eventfd rather than pipe

storage/innobase/btr/btr0btr.cc
A stress test that makes use of `ROW_FORMAT=COMPRESSED` tables caused a crash in `btr_attach_half_pages()` due to a null pointer that had been returned by `btr_page_get_father_block()`, signifying that something is corrupted. The root cause of that corruption is unknown at the moment, but in the spirit of 0b47c126e31cddda1e94588799599e138400bcf8 we should avoid crashes when the database is corrupted.
`btr_attach_half_pages()`, `btr_lift_page_up()`, `btr_compress()`: Return `DB_CORRUPTION` if `btr_page_get_father_block()` returns `nullptr`.
Rerun the stress test that was described in [MDEV-31817](https://jira.mariadb.org/browse/MDEV-31817), preferrably in the same environment. The added error handling code is unreachable in the regression test suite.
It is not feasible to fix this in older …
=> MDEV-31817 SIGSEGV after btr_page_get_father_block() returns nullptr on corrupted data

storage/innobase/trx/trx0purge.cc
`trx_purge_truncate_history()`: If a fast shutdown has been initiated, disregard `innodb_undo_log_truncate=ON` and return.
@hgxl64 tested this by running a write heavy Sysbench workload and then initiating a shutdown.
While this bug does affect 10.4 as well, the code there is quite different and there are other problems with `innodb_undo_log_truncate=ON` in the 10.4 branch.
=> MDEV-33062 innodb_undo_log_truncate=ON prevents fast shutdown

storage/innobase/buf/buf0buf.cc
Errors outputted as notes are weird, and when a user cannot do anything about them, why output them at all.
Point taken, removed these, and left positive message on initialization (from Marko).
Thanks Elena Stepanova.
=> MDEV-24670 memory pressure - warnings/notes

support-files/mini-benchmark.sh
[MDEV-30839](https://jira.mariadb.org/browse/MDEV-30839)
[`mini-benchmark.sh`](https://github.com/MariaDB/server/blob/10.8/support-files/mini-benchmark.sh) has been useful for locally-run benchmarks, recently it has been used to provide benchmarks for [MDEV-30628](https://jira.mariadb.org/browse/MDEV-30628). However, using the script can be tedious since it requires manually modifying the code to change the benchmark configuration. Also, the current implementation doesn't save standard output of the script (`lscpu` and other output is lost).
This PR adds command line options that address the above issues and improve usage of the script.
- _`--log`_: If set, logs `mini-benchmark.sh` output (`lscpu`, etc.) to a file within the benchmarks folder.
- _`--duration`_: Sets the duration in …
=> MDEV-30839: Improvements to mini-benchmark (add CLI options and fixes)

.github/pull_request_template.md
Help documention people work out what to write in release notes.
See if contributor enter information in this field.
- [*] *This is a PR template change against what is soon to the default branch where GH reads it *
- [*] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.
=> pr template: ask about release notes

mysys/lf_alloc-pin.c
When testing MariaDB on Arm64, a stall issue will occur, jira link:
https://jira.mariadb.org/browse/MDEV-28430.
The stall occurs because of an unexpected circular reference in the
LF_PINS->purgatory list which is traversed in lf_pinbox_real_free().
We found that on Arm64, ABA problem in LF_ALLOCATOR->top list was not
solved, and various undefined problems will occur, including circular
reference in LF_PINS->purgatory list.
When testing MariaDB on Arm64, a stall issue will occur, jira link: https://jira.mariadb.org/browse/MDEV-28430.
Run unit.lf.
=> MDEV-28430: Fix memory barrier missing of lf_alloc on Arm64

debian/libmariadb-dev.install
During the build process this is wrapped into plugin_auth.h.
=> MDEV-32546: debian files - erronus install of plugin_auth_common.h

README.md
When navigating through the existing links in the README, it is not immediately obvious where to go to find instructions in building and testing the source code. Since the README is often the first thing people see when looking at a repository, this information should be front and centre so that newcomers to the project can get setup as quickly as possible.
N/A
N/A
=> Link beginner instructions in README.md

storage/innobase/os/os0file.cc
SyncFileIO should do multiple read/write call when length is greater than os_file_request_size_max value.
Tested the patch with os_file_request_size_max as 65536. InnoDB does multiple read/write in case of read/write.
This is done in the commit b1fa0f59a635f6333a8a0889c53f663746860e55
=> MDEV-33809 Bulk insert or DDL fails if a BLOB is too long

storage/innobase/handler/ha_innodb.cc, storage/innobase/include/row0sel.h
We have quite a few assertions
```c++
ut_a(m_prebuilt->trx == thd_to_trx(ha_thd()));
```
in low-level functions.
These had better be debug assertions for performance reasons. It should suffice to check that condition in the less frequently invoked `ha_innobase::change_active_index()`.
`convert_search_mode_to_innobase()`: Return whether the mode is unsupported, and optionally update `ha_innobase::m_last_match_mode`.
`ha_innobase::index_read()`: Only branch on `find_flag` once, and simplify the error handling after invoking `row_search_mvcc()`.
`ha_innobase::rnd_pos()`: Remove an assertion that is duplicating one in `ha_innobase::index_read()`, which we are calling unconditionally.
`ha_innobase::records_in_range()`: Check only once whether `min_key`, `max_key` are null pointers. …
=> MDEV-33779 InnoDB row operations could be faster

tpool/tpool_generic.cc
This is a server hang and not an issue with backup. While concurrent DDLs in server gets in hanged state, mariabackup waits for DDLs to finish trying to acquire MDL_BACKUP_BLOCK_DDL.
The server hang is serious in nature and caused by thread pool state being incorrectly set to thread creation pending state while no creation is actually pending. Once a thread pool reaches such state no new thread gets created in the pool.
While it could possibly affect all thread pools in server, the innodb thread pool is the victim in current bug where IO job gets blocked when the pool is stuck with much less number of threads than intended. Available workers are blocked in purge waiting for page lock to be released by IO write (SX lock) causing a complete deadlock.
The issue is caused by the state …
=> MDEV-33669 mariabackup --backup hangs

client/mysqladmin.cc, client/mysqldump.c, client/mysqlimport.c, sql-common/client.c, sql-common/my_time.c
Fix various typos in comments and DEBUG statements. Code changes are non-functional.
The tool [codespell](https://github.com/codespell-project/codespell) was used to find these typos.
N/A
Code changes are non-functional and `./mtr --suite=main` passes successfully.
All new code of the whole pull request, including one or several files that are
either new files or modified ones, are contributed under the BSD-new license. I
am contributing on behalf of my employer Amazon Web Services, Inc.
=> Fix Various Typos

README.md
This commit updates the README to indicate that the "Get the code, build it, test it" link will help decide the correct branch to work in.
Also fixes a grammar issue and cleans-up the Markdown a little bit.
=> Update README for branch choice

storage/perfschema/unittest/pfs_noop-t.cc
Invoke cleanup routine at the end of pfs_noop.
=> MDEV-33616 Fix memleak in pfs_noop

mysys/lf_alloc-pin.c, mysys/thr_mutex.c, mysys/waiting_threads.c, sql/mdl.cc, sql/sql_base.cc, sql/sql_servers.cc, sql/sql_test.cc, sql/table_cache.cc, sql/xa.cc, storage/innobase/include/trx0sys.h, storage/innobase/lock/lock0lock.cc, storage/innobase/trx/trx0trx.cc
In `cmake -DWITH_UBSAN=ON` builds with `clang` but not with GCC, `-fsanitize=undefined` will flag several runtime errors on function pointer mismatch related to the lock-free hash table `LF_HASH`.
Let us use matching function signatures and remove function pointer casts in order to avoid potential bugs due to undefined behaviour.
This is probably not worth mentioning, because no actual bugs related to this are known.
I ran the following after both `cmake -DCMAKE_BUILD_TYPE=Debug` and with `cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo` using `clang` 18.1.6 and `-DWITH_UBSAN=ON`:
```sh
UBSAN_OPTIONS=halt_on_error=0 ./mtr --parallel=auto --max-test-fail=0 --force --big-test
grep -li lf_ mysql-test/var/*/log/mysqld*err*
```
The `mtr` driver would appear to hang due to the sheer amount of test …
=> MDEV-33161 Function pointer signature mismatch in LF_HASH

storage/innobase/log/log0recv.cc
- There is a possibility that InnoDB fails to truncate the undo tablespace when there are no pages to recover while applying the redo log. trx_lists_init_at_db_start() could've applied the redo logs for undo tablespace page0.
Need to write solid mtr test case.
=> MDEV-34381 InnoDB fails to truncate during recovery

.github/pull_request_template.md
Make it clear that refactoring code goes into the latest version.
=> Update pull request template for refactoring

storage/oqgraph/graphcore.cc, storage/oqgraph/ha_oqgraph.h
A follow up of #3331
Add suggested overrides in oqgraph
Not for release notes.
Valgrind build passes compilation again.
=> MDEV-33746 [fixup] Add suggested overrides in oqgraph

mysql-test/main/win.result, mysql-test/main/win.test, mysql-test/suite/encryption/r/tempfiles_encrypted.result
Correct compatibility with view-protocol.
N/A
```
$ mysql-test/mtr  --view-protocol  main.win
Logging: /home/dan/repos/mariadb-server-rebase/mysql-test/mysql-test-run.pl  --view-protocol main.win
...
==============================================================================
TEST                                      RESULT   TIME (ms) or COMMENT
--------------------------------------------------------------------------
worker[01] Using MTR_BUILD_THREAD 300, with reserved ports 19000..19029
main.win                                 [ pass ]   4180
```
=> MDEV-19052 main.win postfix --view-protocol compat

storage/innobase/mtr/mtr0mtr.cc
Issue: During mtr_t:commit, if there is not enough space available in redo log buffer, we flush the buffer. During flush, the log system latch is released allowing other concurrent mtr to commit. After flush we reacquire the latch but use the old LSN obtained before check. It could lead to redo log corruption. As the LSN moves backwards with the possibility of data loss and unrecoverable server if the server aborts for any reason or if server is shutdown with innodb_fast_shutdown=2. With normal shutdown, recovery fails to map the checkpoint LSN to correct offset.
In debug mode it hits log0log.cc:863: lsn_t log_t::write_buf() Assertion `new_buf_free == ((lsn - first_lsn) & write_size_1)' failed.
In release mode, after normal shutdown, restart fails. [ERROR] InnoDB: Missing …
=> MDEV-34689 Redo log corruption at high load

plugin/type_geom/plugin.cc
Fix a typo in a comment. No functional changes.
There  are no functional changes.
=> Fix typo spatial_ref_sys

storage/innobase/mtr/mtr0mtr.cc
`log_t::resize_write()`: Advance `log_sys.resize_lsn` and reset the `resize_log` offset to `START_OFFSET` whenever the memory-mapped buffer would wrap around.
Previously, in case the initial target offset would be beyond the requested `innodb_log_file_size`, we only adjusted the offset but not the LSN. An incorrect LSN would cause `log_sys.buf_free` to be out of bounds when the log resizing completes.
The `log_sys.lsn_lock` will cover the entire duration of replicating memory-mapped log for resizing. We just need any mutex that is compatible with the caller holding `log_sys.latch`. While the choice of `mtr_t::finisher` (for normal log writes) depends on `mtr_t::spin_wait_delay`, replicating the log during resizing is a rare operation where we can afford possible additional context …
=> MDEV-34446 SIGSEGV on SET GLOBAL innodb_log_file_size with memory-mapped log file

cmake/os/FreeBSD.cmake, storage/innobase/os/os0file.cc
FreeBSD on merge to 10.11 got warnings and merge errors:
https://buildbot.mariadb.org/#/builders/619/builds/6641/steps/5/logs/stdio
merge fix - nothing required.
FreeBSD BB worker will build without InnoDB warnings. Other Linux/Windows builder will also build.
=>  MDEV-33894 / 34825 FreeBSD - few InnoDB things are innodb, cmake/os/FreeBSD lost in merge

mysql-test/main/derived.result, mysql-test/main/derived.test, sql/share/errmsg-utf8.txt, sql/sql_base.cc, sql/sql_cte.cc, sql/sql_cte.h, sql/sql_derived.cc, sql/sql_lex.cc, sql/sql_lex.h, sql/sql_select.cc, sql/sql_union.cc, sql/sql_view.cc, sql/sql_yacc.yy, sql/table.cc, sql/table.h
Pull request created in: https://jira.mariadb.org/browse/MDEV-31466
=> MDEV-31466 Add optional correlation column list for derived tables

scripts/mysql_install_db.sh
We don't use launchpad any more.
Not noteworthy.
Informational only.
=> Fix URL in mariadb-install (no longer on launchpad)

storage/innobase/log/log0log.cc
In commit 6acada713a95a605b3aa65bd519fbd4532ad23e5 the logic for treating the file system of `/dev/shm`
as if it were persistent memory was broken.
This is a minor change that should only affect internal testing. Probably not worth mentioning.
```sh
./mtr --rr innodb.innodb
rr replay var/log/mysqld.1.rr/latest-trace
```
Set a breakpoint on `log_mmap` and a hardware watchpoint on `log_sys.buf` and `log_sys.flush_buf`. If the logic works as intended, `log_sys.flush_buf` will remain `nullptr`. Also the InnoDB start-up message should mention the memory-mapped interface:
```
[Note] InnoDB: log sequence number 56351 (memory-mapped); transaction id 16
```
=> MDEV-35608 Fake PMEM on /dev/shm no longer works

mysql-test/suite/galera/disabled.def, mysql-test/suite/galera/r/galera_sequences.result, mysql-test/suite/galera/t/galera_sequences.test, sql/sql_yacc.yy
Its a crash, because the create_info isn't cleared on ALTER TABLE.
Correct crash in galera on issuing ALTER SEQUENCE after a table manipulation failure.
test case included.
=> MDEV-33245 SIGSEGV in wsrep_check_sequence

mysql-test/lib/My/SafeProcess/safe_process_win.cc
This backports https://github.com/mysql/mysql-server/commit/e2f685972985, which works around perl issue https://github.com/Perl/perl5/issues/17570
MySQL fix  ensures that FILE_APPEND_DATA is used in redirected stdout/stderr open flags, rather than FILE_GENERIC_WRITE. Only this gives lossless append behavior, if multiple processes use the same file.
See commit comments. This is a workaround for perl bug, which affects mysql-test-run.pl, which uses undocumented system(1,..) call.
Release notes should not say anything , it only affects testing framework.
This is a fix in test infrastructure. It is enough if MTR passes on Windows on CI.
=> MDEV-35891 mtr, Windows - fix multi-process append for stdout and stderr

mysql-test/main/multidelete_engine.result
Record the required result file and make the test more interesting, too
=> MDEV-36074 main.multidelete_engine missing result file

.github/workflows/backup.yml
No MariaDB server code is touched here, this is only about GitHub actions CI.
=> MDBF-1000: implement an export for the server repository

.github/workflows/backup.yml
No MariaDB server code is touched here, this is only about GitHub actions CI.
=> MDBF-1000: wrong urls

.github/workflows/backup.yml
No MariaDB server code is touched here, this is only about GitHub actions CI.
=> Add a sanity check for backups

mysql-test/suite/archive/archive-big.test, mysql-test/suite/federated/federatedx_create_handlers.test, plugin/auth_examples/auth_0x0100.c, storage/federatedx/ha_federatedx.cc, storage/mroonga/vendor/groonga/lib/db.c, storage/mroonga/vendor/groonga/lib/hash.c, storage/mroonga/vendor/groonga/lib/ii.c
Fixes a UBSAN error. 
Create full consistent plugin API for the 0x0100 type authentication in sql_plugin_compat.h and make the auth_0x0100 plugin test and the server use the consistent definition.
As the plugin is a .c file the downgrade/upgrade functions moved to sql/sql_acl.cc, the only used location.
nothing - internal test change on a old deprecated protocol.
plugins.auth_v0100 unit test under a -DWITH_UBSAN=ON environment.
=> MDEV-36341/MDEV-36347 UBSAN fixes - FederatedX/Mroonga/auth_v0100

mysql-test/main/analyze_format_json.result, mysql-test/main/explain_json.result, mysql-test/main/order_by.result, mysql-test/main/show_analyze_json.result, mysql-test/main/show_explain_json.result, mysql-test/main/subselect4.result, mysql-test/main/subselect_cache.result, sql/sql_explain.cc
Pull request created in: https://jira.mariadb.org/browse/MDEV-36463
=> MDEV-36463 Rename expression_cache to subquery_cache

storage/innobase/log/log0recv.cc
Reason:
======
During --prepare of partial backup, if InnoDB encounters the redo log for the excluded tablespace then InnoDB stores the space id in dirty tablespace list during recovery, anticipates that it may encounter FILE_* redo log records in the future. Even though we encounter FILE_* record for the partial excluded tablespace then we fail to replace the name in dirty tablespace list. This lead to missing of FILE_* redo log records error.
Solution:
========
fil_name_process(): Rename the file name from "" to name encountered during FILE_* record
[backup.zip](https://jira.mariadb.org/secure/attachment/74824/backup.zip) of [MDEV-36304](https://jira.mariadb.org/browse/MDEV-36304) is helpful to test this scenario. Please prepare the
backup against backup directory.
Please open 10.11 …
=> MDEV-36304  InnoDB: Missing FILE_CREATE, FILE_DELETE or FILE_MODIFY error during mariabackup --prepare

cmake/3rdparty_info.cmake, cmake/generate_sbom.cmake, cmake/sbom.json.in
Some users want additional properties in SBOM.  This PR adds them.
The properties (license and copyright statement) are maintained per third party dependency in machine-readable file (which is also human readable).
Also other relevant properties are maintained
Nothing needs to be in the notes. SBOMs are only product metadata
cmake . -DWITH_SBOM=1
examine sbom.json in build directory.
=> MDEV-36398 Extend SBOM with 'license' and 'copyright'

debian/autobake-deb.sh
Plucky Puffin as Ubuntu 25.04 released.
Also prepare, ahead of time, Ubuntu Questing Quokka for 25.10
Also prepare for Debian 14 - Forky.
Run autobake.sh on these platforms.
=> packaging prep for Ubuntu Plucky

mysys/crc32/crc32_arm64.c
MDEV-36864 Makes Windows on ARM64 compile again (MSVC)
Followup for [4052 pull request](https://github.com/MariaDB/server/pull/4052#issuecomment-2902729240), rebased on 11.4,
as requested in review.
=> MDEV-36864 crc32 compatibility on Windows on ARM64

mysql-test/main/table_elim.result, mysql-test/main/table_elim.test, sql/opt_table_elimination.cc
Pull request created in: https://jira.mariadb.org/browse/MDEV-36215
=> MDEV-36215 Fix Wrong query result due to Table Elimination

support-files/rpm/server.cnf
10.11 is included in the configuration file however the current version is 11.8.
Barely noteworthy. Per JIRA entry.
See installed file.
=> MDEV-36697: Wrong server.cnf group for version

mysql-test/main/derived_split_innodb.result, mysql-test/main/derived_split_innodb.test, sql/opt_split.cc
Pull request created in: https://jira.mariadb.org/browse/MDEV-37407
=> MDEV-37407 Wrong result with LATERAL DERIVED, for 10.11

storage/innobase/handler/handler0alter.cc
Errors updating the InnoDB internal table SYS_COLUMNS during ALTER TABLE ALGORITHM=INSTANT result in a memory leak of a block of memory allocated for partition information.
Corrected by freeing the partition information when this internal error occurred.
Unsure if worthy as unlikely condition?
innodb.instant_alter_debug under LeakSantiizer
=> MDEV-37724: Memory leak with InnoDB ALTER TABLE ALGORITHM=INSTANT
